### ISSUE TITLE
Watched items

### ISSUE THREAD

**Issue by pcs333** [Taxel/PlexTraktSync#1]
Hi
I am getting random missed watched seasons and episodes on Plex.
For example, The 100, I have watched all seasons which shows in trakt but in Plex the last season is marked unwatched.
There are also some shows with episodes not marked watched on Plex.
I have ran the script a few times but not seeing any errors.

**Comment by pcs333** [comment]
I'm very sorry 
My mistake. I set it up logged into the wrong trakt account 😂

**Comment by Taxel** [comment]
Looks resolved -> Closing this issue.
