### ISSUE TITLE
Sqlite3: Sleeping for 200ms to retry busy DB.

### ISSUE THREAD

**Issue by samcro1967** [Taxel/PlexTraktSync#1004]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I have been running this for several days and have been experiencing Plex connectivity issues.  I am running this via the docker container.  It is working and I am seeing movies appear in my traktlist, but after several hours and a few runs, I am no longer able to connect to Plex.  I removed the container and let Plex run for a day and experienced no issues.  I added this container back and the issue started again.  I do not see any errors or gaps in time in `Plex Media Server.log` when I am not able to connect, so Plex still seems to be running in the container.  A restart of the Plex container makes Plex available again.  I am running Plex version `1.28.1.6092`.

Googling of the Plex issue seems to indicate it is an issue with resources for Plex.  Quite certain this is not the case.  The Docker host has 8 cores and 32 GB of RAM.  The storage is being hosted by a commercial NAS with 8 Enterprise class SSD's, 32 GB of RAM, and a quad core Intel i9 processor.  Performance for both the host and NAS show no memory, CPU, or disk bottlenecks.

Thinking maybe I should try limiting CPU and memory plextraktsync is able to use to try and slow down what it is sending to Plex.  Seems like the Plex IP stack is being overwhelmed and is crashing?  Thought I would ask here and get some other thoughts.  Worst case I think I automate running this once a day and restart Plex after completion.

### Error trace / logs

```text
Processing TV Shows 100% ━━━━━━━━━━━━━━━━━━━ 9/9  [ 0:00:02 < 0:00:00 , 5 it/s ]                                        INFO     TV Shows processed in 2.1 seconds
Syncing show ratings   0%                    0/9  [ 0:00:00 < -:--:-- , ? it/s ]
INFO     Updated plex watchlist in 0.0 seconds
INFO     Completed full sync in 12.9 seconds
INFO     PlexTraktSync [0.20.10]
ERROR    Plex connection error:
         HTTPSConnectionPool(host='172-18-0-<redacted>.p
         lex.direct', port=32400): Read timed out. (read timeout=30), local url
         http://172.18.0.1:32400 didn't respond either. Check PLEX_LOCALURL in
         .env file.
Plex connection error: HTTPSConnectionPool(host='172-18-0-1.<redacted>.plex.direct', port=32400): Read timed out. (read timeout=30), local url http://172.18.0.1:32400 didn't respond either. Check PLEX_LOCALURL in .env file.                                                                                                                   INFO     PlexTraktSync [0.20.10]
ERROR    Plex connection error: ('Connection aborted.',
         RemoteDisconnected('Remote end closed connection without response')),
         local url http://172.18.0.1:32400 didn't respond either. Check
         PLEX_LOCALURL in .env file.
Plex connection error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), local url http://172.18.0.1:32400 didn't respond either. Check PLEX_LOCALURL in .env file.
```

### Expected behavior

Able to run the script every 8 hours and able to connect to Plex without having to restart Plex.

### Steps to reproduce the behavior

1. Run container.
2. Connect to plex after 2 or 3 runs

### Workarounds

Restart Plex

### Install method

docker-compose

### Version

0.20.10

### Python Version

3.10.6

### Operating System and Version

Ubuntu 20.04

**Comment by twolaw** [comment]
You use `172.18.0.x` which is the Plex **container ip address** and it can possibly change when container upgrades or restarts.
You should use the **static address of the host** instead.

Check your address in Plex server settings > Remote access :

![image](https://user-images.githubusercontent.com/10365746/185189501-7f5f7abe-c585-4444-8a25-c374de55d26f.png)

or at `https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=<your plex token>`

As an exemple corresponding `.env` file has :
```
PLEX_TOKEN=123456789ABCDEFGHIJKLM
PLEX_BASEURL=https://192-168-0-12.b35b5xxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400
PLEX_LOCALURL=http://192.168.0.12:32400
```
192.168.0.12 being the static address of the host computer.

**Comment by samcro1967** [comment]
@twolaw Plex Remote access is showing my private IP address is `192.168.1.104` which is the IP address of the docker host.

**Comment by twolaw** [comment]
Then change the .env line to :
`PLEX_LOCALURL=http://192.168.1.104:32400`
(leave the PLEX_BASEURL as it is for now)

**Comment by samcro1967** [comment]
Change made and container started.  Will monitor over the next day and report back.

**Comment by twolaw** [comment]
Ok, the login process should have selected this address. I don't know what happened.

As I said, you can see all addresses of your Plex server at `https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=<your plex token>`  :

```
<Connection protocol="https" address="192.168.0.12" port="32400" uri="https://192-168-0-12.b35b53d5e9xxxxxxxxxxxxxxxxxxxxxxx.plex.direct:32400" local="1"/>
<Connection protocol="https" address="176.160.xxx.xxx" port="16422" uri="https://176-160-xxx-xxx.b35b53d5e9xxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct:16422" local="0"/>
```
You can use one of those addresses too.

**Comment by samcro1967** [comment]
This seems to have resolved the issue.  Have not had a reoccurrence in Plex in over 24 hours.  Prior to this I was having an issues 2 or 3 times in a 24 hour period.  Thanks for your help and work on this project!
