### ISSUE TITLE
HTTPS error 

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Taxel/PlexTraktSync#1009]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I have HTTPS enabled and the script is trying to connect via http.

### Error trace / logs

```text
Attempting to connect to xxxxxxx. This may take time and print some errors.
Server connections:

ERROR   

http://plex.domain.com:443: (400) bad_request; http://plex.domain.com:443/ <html> <head><title>400 The plain HTTP request was sent
         to HTTPS port</title></head> <body> <center><h1>400 Bad Request</h1></center> <center>The plain HTTP request was sent to HTTPS port</center>
         <hr><center>cloudflare</center> </body> </html>
ERROR    https://plex.domain.com:443: 'NoneType' object is not subscriptable
Unable to connect to resource: Infinityflix, Try another server, <class 'plexapi.exceptions.NotFound'>

```

### Expected behavior

Connect via HTTPS

### Steps to reproduce the behavior

Have HTTPS via cloudflare
Try to connect

### Install method

docker-compose

### Version

0.20.10

### Python Version

3.10.6 (main, Aug 10 2022, 00:31:49) [GCC 10.3.1 20211027]

### Operating System and Version

Ubuntu 20.04 lts

**Comment by Cookie-Monster-Coder** [comment]
Signed in with the admin account and it works and shows the second account under it. So apparently you need to sign into the script via the admin account.

**Comment by glensc** [comment]
The steps to reproduce are invalid. However, the issue is already closed.
