### ISSUE TITLE
Sync watch status from watchlist

### ISSUE THREAD

**Issue by navycrow** [Taxel/PlexTraktSync#1023]
hello
I just discovered this app few hours ago and i find it very useful.
But a lot of series seems not to be synced (series that i watch on streaming services).
Can you confirm that watch status sync also work from watchlit (new plex function implemented a few month ago).
If not do you plan to integrate it ?
thx

**Comment by twolaw** [comment]
It's a Plex feature by design.

Read Plex FAQ about it [here](https://support.plex.tv/articles/universal-watchlist/#toc-4)

>Why did something I played from a Plex Media Server or other streaming service not get removed from the Watchlist?
>
>Currently, the Universal Watchlist and Discover source do not sync the view state of content from a Plex Media Server or external streaming service content. It will only automatically track content from Plex’s own Movies & Shows streaming or when you manually mark something as watched in the Discover source.

**Comment by navycrow** [comment]
So thre is no sync between universal watchlist and servers watchlist.
By the way, I don't know if it is possible to sync from Trakt to Universal watchlist but i'm pretty sure it is at least possible to sync from Universal watchlist to Trakt and then from trakt to server watchlist.

**Comment by twolaw** [comment]
I don't know what you mean by **server watchlist** versus **universal watchlist**.
The Plex watchlist is not on your local Plex server, it's on the internet Plex server (https://metadata.provider.plex.tv).
