### ISSUE TITLE
Cannot submit credentials

### ISSUE THREAD

**Issue by marshie250** [Taxel/PlexTraktSync#1039]
After installing using the pip command, I cannot set up plextraktsync for use. After running via cmd, I can input my username, but when asked for my password, I can no longer type into the cmd shell. The only key that sends is Enter, which obviously submits an empty password and doesn't work. Is there a file where I could just paste my password into to bypass this part of the setup?

**Comment by glensc** [comment]
password typing prompt obviously doesn't print your password you type.

**Comment by marshie250** [comment]
Yes, the problem was that I was not able to type-- I could put in the username no problem, but nothing happened when I tried to type the password. I figured it out though; I located the .env file and just put my info in there.

**Comment by glensc** [comment]
that "nothing happen" is unix design: nothing is printed anywhere while you type password. press enter and then password is sent and terminal printing is restored. use google!

**Comment by glensc** [comment]
alternatively `--password` commandline option exists, but it's not recommended to do that because passwords aren't supposed to be visible

**Comment by glensc** [comment]
https://unix.stackexchange.com/questions/268006/why-is-the-password-i-entered-not-visible

**Comment by marshie250** [comment]
Thanks for the info. I did come here as a last resort after I couldn't find anything on Google--perhaps I did not know the correct terminology. Even typing the password did not work, but again, I was able to figure out an alternative route.
