### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by sirloinofbeef** [Taxel/PlexTraktSync#105]
The script works perfectly on a remote server, but my local PMS (which uses the credentials) throws up the following error, whether I use the loopback, local or public IP:

WARNING:BadRequest (401) unauthorized http://127.0.0.1:32400/; <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>

**Comment by twolaw** [comment]
You should not "USE AN IP", you should let the script connect to the PMS address found during setup.
I suggest you do the setup from scratch, then enable debug in config.json, then run the script and show here the content of last_update.log.

**Comment by sirloinofbeef** [comment]
After a re-download of the script and starting from scratch it now works :)
Not sure why it wasn't working before.
Thanks for the help.
