### ISSUE TITLE
Feature request: Add rewatched episode as new play to trakt.tv

### ISSUE THREAD

**Issue by douggutaby** [Taxel/PlexTraktSync#1057]
### Use case

I couldn't find this feature or request.

Add tv show episode and movie as new play in trakt.tv. Now if I rewatch an episode it won't be added as new play.
It can be driven by a boolean variable in config, for example add_new_play
I don't know the solution, because it shouldn't add everything again just the new plays after this setup.

**Comment by douggutaby** [comment]
No, readme said: "It does NOT run a sync between Plex and Trakt" So I thought it is only for scrobbling.
BUT I tried now and it is working :) When I finished with an episode it is marked as new play in trakt.tv.
Thanks, I will set up the watch to run as a deamon.

**Comment by p3t3r** [comment]
Is this now a feature? I have this same problem, when plextraktsync isn't running with the watch command a rewatch is not added to Trakt. There does not seem to be a command to this afterwards with the sync command (or watch command)

**Comment by glensc** [comment]
removed the sentence: https://github.com/Taxel/PlexTraktSync/commit/f1f4c889757b6b4404abd5fb63c4f069bad6f5ba

I wonder why people never bother to submit the changes themselves, only complain. there are several sentences in readme inviting people to contribute.
