### ISSUE TITLE
lastViewedAt and lastRatedAt not properly set

### ISSUE THREAD

**Issue by tadly** [Taxel/PlexTraktSync#107]
Couldn't find an existing issue for this so here goes.

Fresh Plex setup with all my media scanned.
Installed the Plugin and did a sync (configured to only pull from trakt)

## What I expect
*lastViewedAt* and *lastRatedAt* should have the same date and time as they are on trakt.

## What happens
Both mentioned field got assigned a datetime from when the sync was run (today in my case)

Is this expected behavior because plex is limiting in its API or maybe just an oversight in the plugin?

**Comment by twolaw** [comment]
Yes, it is a limitation of Plex API.

**Comment by tadly** [comment]
I feel like crying now...
Sorry for not reading the README properly. I should have seen that :/

So, I'm did write myself a script some time ago to update "addedAt" and "updatedAt" based on the files mtime (unix specific).
I do that by updating the database myself (I know... I know...)

Question is, could the plugin do the same and would you guys be willing to add such hacky functionality if possible?

**Comment by twolaw** [comment]
No because the script have no access to plex host filesystem (shared library, remote host,...), only api access.

**Comment by tadly** [comment]
Properly sandboxed huh. Makes sense but in this instance is rather annoying.

Looks like I have to find a different solution then :/
Thanks for getting me up to speed though :)
