### ISSUE TITLE
Feature request: Add support for replacing $PTS_LOG_FILENAME env var in config

### ISSUE THREAD

**Issue by AndreiArdelean1** [Taxel/PlexTraktSync#1078]
### Feature description

I would like one or more of the 3 features below:

1.  Replace `'$PTS_LOG_FILENAME'` string from `config.yml`->`logging`->`filename` with the respective env var. Similar to how `$PTS_CACHE_DIR` is handled [here](https://github.com/Taxel/PlexTraktSync/blob/7e72e9b487d26479fee63bfccb4c2c5e31efedd9/plextraktsync/config.py#L199)
2. Replace all `${SOME_ENV_VAR}` from the config with the corresponding env var. Similar to [Docker compose](https://docs.docker.com/compose/environment-variables/). Or just the values that start with `!ENV` (`!ENV '/var/${LOG_PATH}'`). Here are some references ([1](https://dev.to/mkaranasou/python-yaml-configuration-with-environment-variables-parsing-2ha6), [2](https://stackoverflow.com/questions/52412297/how-to-replace-environment-variable-value-in-yaml-file-to-be-parsed-using-python))
3. Specify the config file name at runtime from the run command (`python3 -m plextraktsync --config '/config/config_1.yml'`)

### Use case

I'm running 2 instances of PlexTraktSync, one for monitoring plex, and one for syncing on demand and I'd like for them to log to different files

### Workarounds
\-
### Plan to implement

My preference is to go with option 2, and from a quick search, it shouldn't be too hard to implement. I can have a look myself if you'd like.

**Comment by glensc** [comment]
You can already now override log dir with `$PTS_LOG_DIR`:
- https://github.com/Taxel/PlexTraktSync/blob/033737bc5b85f7dd19a00e34fa92a2ca0c17a734/Dockerfile#L32

**Comment by glensc** [comment]
The same goes for config dir, `$PTS_CONFIG_DIR`:
- https://github.com/Taxel/PlexTraktSync/blob/033737bc5b85f7dd19a00e34fa92a2ca0c17a734/Dockerfile#L30

adding docs needed label so you can contribute to docs

**Comment by glensc** [comment]
reminder, that readme says:

> Looking for a way to contribute? Please find issues with the [help-wanted](https://github.com/Taxel/PlexTraktSync/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+sort%3Aupdated-desc) label or to improve documentation [docs-needed](https://github.com/Taxel/PlexTraktSync/issues?q=label%3A%22docs+needed%22+sort%3Aupdated-desc), thank you.
