### ISSUE TITLE
Installing requirements.txt fails on Python 3.9

### ISSUE THREAD

**Issue by flammable** [Taxel/PlexTraktSync#108]
I'm using Python 3.9 on the Mac that I'm running this script (it's running macOS 10.15.7). Both pip and pip3 are pointed to `/Library/Frameworks/Python.framework/Versions/Current/bin/python3`, which at the moment is `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`.

Running `pip3 install -r requirements.txt` failed at the part where it's trying to install typed_ast, version 1.4.0. I found [this GitHub issue](https://github.com/python/typed_ast/issues/126) where it appears this was resolved in version 1.4.2. I modified requirements.txt to include `typed-ast==1.4.2` instead, and was able to install successfully. The Trakt/Plex sync works OK now.

I don't know the greater implications of this, so I figured I'd submit an issue before a pull request. If you'd like a pull request for this, just let me know.

**Comment by glensc** [comment]
@flammable send PR, please. Also, you can use pipenv to run the app in isolation of system library versions.

**Comment by glensc** [comment]
@flammable, @Taxel, @twolaw: do you know what for the `typed-ast` package is needed? git history is not useful here. it was added in 6831818311cc4c09b98a9c7b9886f41ecf1a1fe8 commit. when developing I removed the line from requirements, installed dependencies, and the app seems to work without errors.

**Comment by flammable** [comment]
Thanks! I don't actually know what it does, just that using the newer version resolves the installation errors with Python 3.9.

I'll send a PR in a bit, but if `typed-ast` isn't needed at all, it's even better to not include it in the first place. :)

**Comment by flammable** [comment]
Actually, looking at the [readme](https://github.com/python/typed_ast/blob/master/README.md)...it appears they don't plan to support `typed-ast` on Python 3.8 and greater. It doesn't look like it's necessary anymore. Maybe it should just be removed from requirements.txt instead?

**Comment by glensc** [comment]
perhaps write the dependency with version range. I've seen it being done, but don't know-how.

to my knowledge, the current code in this repo does not use Python typings (but I thought of using typings), but dependencies might, and I'm not sure, do the dependencies need or use the typings. I'm just a fly-by Python coder.

**Comment by glensc** [comment]
@flammable so, as all that is unknown, please send PR of you changing the requirement that worked for py3.9.

**Comment by glensc** [comment]
I think what happened was that @Taxel tried to save dependencies used in the project, and used `pip freeze`:
- https://pip.pypa.io/en/stable/reference/pip_freeze/

however that records down all packages installed in system, not just for current project.

**Comment by flammable** [comment]
Nice find. If that's the case, it sounds like requirements.txt could probably be trimmed down.

**Comment by glensc** [comment]
@flammable it's also possible that the dependencies at that time included the packages as sub-dependencies. and requirements.txt is flattened packages, not only top level.

**Comment by twolaw** [comment]
I think it's a good idea.
Using [pipdeptree](https://github.com/naiquevin/pipdeptree#using-pipdeptree-to-write-requirementstxt-file) ?

**Comment by glensc** [comment]
@twolaw: I already composed the list manually (plex, requests, trakt), don't have the exact list here as it's on other computer now.

the `pipdeptree` can give some confidence and verification.

**Comment by twolaw** [comment]
I made some tests.
In my opinion, `requirements.txt` should contain :
```
PlexAPI==4.4.1
python-dotenv==0.15.0
requests-cache==0.5.2
trakt==3.0.0
```

and PR #128 be closed (typed-ast not needed).

**Comment by glensc** [comment]
Here's my version:
- https://github.com/Taxel/PlexTraktSync/pull/132

**Comment by flammable** [comment]
Thank you both!
