### ISSUE TITLE
hide the disruptive comments. I remind you [again](https://github.com/Taxel/PlexTraktSync/discussions/1067#discussioncomment-3768834), you are showing off offense towards developers/maintainers who offer this software for free, you should be thankful not throw insulting comments in **their** discussions. next action is to ban user permanently.

### ISSUE THREAD

**Issue by MrBamse** [Taxel/PlexTraktSync#1101]
It seems like glensc has gone of the rails and ban ppl for contributing. You can't even answer questions with glensc getting offended and banning you.

He's Probably high or something so it could be worth taking a look at, because currently, the only one I've seen behave badly is glensc.

     hide the disruptive comments. I remind you [again](https://github.com/Taxel/PlexTraktSync/discussions/1067#discussioncomment-3768834), you are showing off offense towards developers/maintainers who offer this software for free, you should be thankful not throw insulting comments in **their** discussions. next action is to ban user permanently.

_Originally posted by @glensc in https://github.com/Taxel/PlexTraktSync/discussions/1067#discussioncomment-3850399_

**Comment by twolaw** [comment]
This issue is useless. Please contribute in a constructive way.
