### ISSUE TITLE
Scrobling not working and early completion of media than the actual one

### ISSUE THREAD

**Issue by dspdhckr** [Taxel/PlexTraktSync#1103]
I have been using following configuration and I am new to all the settings. But with this configuration I am facing several issues,

1. The completion time for media is almost lagging to averaging 3 minutes meaning that actual media ends after 2 to 5 minutes after the time synced with Trakt.
2. Scroble not showing anything on Trakt while I have set it to run in the background through Linux screen function
3. Watched status from Trakt is not synced with Plex but the watch status from Plex is synced.
4. If I change the rating for a particular media then only the first version of it gets synced and changes in settings after sync never takes place.
5. Removal from watchlist on Trakt never reflects on the Plex.

`cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 15

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false

watch:
  add_collection: false
  remove_collection: true
  scrobble_threshold: 30
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et

`

**Comment by glensc** [comment]
Use issue templates to report issues or request features. they are created for the purpose that you fill all required fields.
