### ISSUE TITLE
Please download and install Python, then restart this project.

### ISSUE THREAD

**Issue by karadoulis** [Taxel/PlexTraktSync#1128]
Hello,
new here i am trying to install PlexTraktSync-0.23.3 but when i type y it says "Please download and install Python, then restart this project." I already have installed latest version of python [Python 3.10.8].
Any help would be really appreciated it.
Thanks in advance.

**Comment by karadoulis** [comment]
found the solution.

**Comment by twolaw** [comment]
Then, write it down here

**Comment by karadoulis** [comment]
> Then, write it down here

Tried uninstalling and installing python (the third time worked). I don't know if this helps!
