### ISSUE TITLE
twolaw/plextraktsync Docker container is restarting after every run of the script

### ISSUE THREAD

**Issue by Hebusing** [Taxel/PlexTraktSync#113]
Apologies in advance if I should have posted my issue somewhere else but I can see that Towlaw is active on this forum.

I've installed successfully the twolaw/plextraktsync docker image and the first run goes well (I'm able to sync, after the setup, my Plex to Trakt). However if I stop the container and start it again, then the script will run until the end (I can see the completion message in the logs like "Completed full sync in 5 min 41.1 seconds"), but the container will stop immediately after this.

I'm running the last version on a Synology NAS. I deleted the containers and recreated it 2 times but it is still the same issue.

I would be happy to share with you some logs and do whatever test is needed.

Many thanks!

**Comment by Hebusing** [comment]
If I replace the content of main.py by just "print("Completed test!")" and start the container, I'll have the same issue. In the logs I'll see "Completed test!" but then immediately the container will stop.

**Comment by twolaw** [comment]
Hi, this is not an issue.
My plextraktsync container works like that. It has to be triggered every x hours by the host through a cronjob.
Container exit with code 0 means success, exit with code 1 means error.


Note : The [official docker version](https://github.com/Taxel/PlexTraktSync/discussions/88) will not work like that, the container will be running forever with the cronjob **inside** the container. But this version is not ready yet.

**Comment by Hebusing** [comment]
Oh! Apologies Twolaw. Now I get it, and that's why Cron is not working as well (I had to start it myself). Thanks for your answer! Hope to get the official docker version soon then  ;-)
