### ISSUE TITLE
Mark_Watched: Unsupported media type: episodes error on sync

### ISSUE THREAD

**Issue by cjsage52** [Taxel/PlexTraktSync#1144]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I get the following error when syncing: "Error: Error running sync command: mark_watched: Unsupported media type: episodes"

### Error trace / logs

```text
INFO     Adding to collection: <tmdb:770610:Episode:1154067:Cinderella-Man-s01e01>
INFO     Adding to collection: <tmdb:770611:Episode:1154068:Cinderella-Man-s01e02>
INFO     Adding to collection: <tmdb:770612:Episode:1154069:Cinderella-Man-s01e03>
INFO     Adding to collection: <tmdb:770613:Episode:1154070:Cinderella-Man-s01e04>
INFO     Adding to collection: <tmdb:770614:Episode:1154071:Cinderella-Man-s01e05>
INFO     Adding to collection: <tmdb:770615:Episode:1154072:Cinderella-Man-s01e06>
INFO     Adding to collection: <tmdb:770616:Episode:1154073:Cinderella-Man-s01e07>
INFO     Adding to collection: <tmdb:770617:Episode:1154074:Cinderella-Man-s01e08>
INFO     Adding to collection: <tmdb:770618:Episode:1154075:Cinderella-Man-s01e09>
INFO     Adding to collection: <tmdb:770619:Episode:1154076:Cinderella-Man-s01e10>
INFO     Adding to collection: <tmdb:770620:Episode:1154077:Cinderella-Man-s01e11>
INFO     Adding to collection: <tmdb:770621:Episode:1154078:Cinderella-Man-s01e12>
INFO     Adding to collection: <tmdb:770622:Episode:1154079:Cinderella-Man-s01e13>
INFO     Adding to collection: <tmdb:770623:Episode:1154080:Cinderella-Man-s01e14>
INFO     Adding to collection: <tmdb:770624:Episode:1154081:Cinderella-Man-s01e15>
INFO     Adding to collection: <tmdb:770625:Episode:1154082:Cinderella-Man-s01e16>
INFO     Adding to collection: <tmdb:1338967:Episode:1127207:Love-Sick:-The-Serie-s01e01>
INFO     Marking as watched in Trakt: <tmdb:1338967:Episode:1127207:Love-Sick:-The-Serie-s01e01>
Processing shows   1% ----------------------------------------------------------- 1/157  [ 0:00:28 < -:--:-- , ? it/s ]
Error: Error running sync command: mark_watched: Unsupported media type: episodes
```

### Expected behavior

Mark episode as watched.

### Steps to reproduce the behavior

Run sync on library with items to be marked as watched

### Install method

git clone

### Version

0.23.0dev0

### Python Version

3.10.1

### Operating System and Version

Windows 10

**Comment by glensc** [comment]
> Version
> 0.23.0dev0

development versions are not supported unless explicitly asked to test by a developer. in such case link to such request.

**Comment by cjsage52** [comment]
Okay, I'll try to downgrade to the version from 3 days ago. The update about 20 hours ago introduced this issue.

**Comment by twolaw** [comment]
`Error running sync command: mark_watched: Unsupported media type: episodes`

bug introduced with 1eaf57410f11f09028c82f9bd93ac681b91cc739

**Comment by glensc** [comment]
apparently, dependencies were not updated. that's why we support only pipx and docker images.

**Comment by twolaw** [comment]
Maybe we could check few modules version at PTS launch and throw a warning if not up-to-date.
Eg. check minimum version for `plexapi` and `pytrakt` modules.

**Comment by glensc** [comment]
nah. would need to keep that list updated again and again. I propose just making docs clearer that only pipx and docker images are supported.

that means moving setup.bat and unraid to unsupported -> use discussions for support, not issues. while unraid uses docker image, it doesn't have this dependency issues, but everything else is unknown to me and I will not install unraid for that purpose to understand what it is.

maybe add third checkbox, "I have installed dependencies"?

maybe print "you are running in unsupported node" if not running at pipx or docker image?

you may want to add this specific check if show_id is missing then throw "need pytrakt 3.4.9".

**Comment by twolaw** [comment]
> maybe add third checkbox, "I have installed dependencies"?

too complicated for pipx and docker users IMHO

> I propose just making docs clearer that only pipx and docker images are supported.

Agree

> maybe print "you are running in unsupported node" if not running at pipx or docker image?

no, too much

> you may want to add this specific check if show_id is missing then throw "need pytrakt 3.4.9".

no

**Comment by glensc** [comment]
closing. problem was that the user hasn't installed the expected dependencies.
