### ISSUE TITLE
websocket connected

### ISSUE THREAD

**Issue by Rezcow** [Taxel/PlexTraktSync#1155]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

When running the script for the second time it does not progress and I get the error "websocket connected"

### Error trace / logs

```text
2022-10-30 15:31:56,899 INFO[PlexTraktSync]:Completed full sync in 97 min 15.5 seconds
2022-10-30 15:36:29,896 INFO[PlexTraktSync.WebSocketListener]:Listening for events!
2022-10-30 15:36:29,918 INFO[plexapi]:Starting AlertListener: wss://172-18-0-1.41f258f810f148ff954ff53bd007b5ad.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<hidden>
2022-10-30 15:36:34,027 WARNING[websocket]:websocket connected
```

### Expected behavior

I hope the script does a scan again

### Steps to reproduce the behavior

After running the script for the first time, the program performed a perfect scan between Trakt and Plex.

later I modified the docker-compose.yml adding the Sheduler service to it.

then I ran: docker-compose run --rm plextraktsync and it gives me a "websocket connected error" and does nothing else.

### Install method

docker-compose

### Version

0.23.7

### Python Version

Python 3.9.2

### Operating System and Version

Debian GNU/Linux 11

**Comment by glensc** [comment]
websocket connected is not an error but a warning. your app is working fine, it's in watch mode, not sync mode.

**Comment by Rezcow** [comment]
> websocket connected is not an error but a warning telling connection to plex server established successfully. your app is working fine, it's in watch mode, not sync mode.

Thank you! Can I leave it like this and it will work correctly?
