### ISSUE TITLE
Trakt official lists raise : 'TraktList' object has no attribute 'trakt_items'

### ISSUE THREAD

**Issue by bulletproof2k** [Taxel/PlexTraktSync#1161]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

```
Traceback (most recent call last):
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\cli.py", line 53, in cli
    sync()
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\commands\sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\sync.py", line 90, in sync
    listutil.addPlexItemToLists(movie)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\trakt_list_util.py", line 97, in addPlexItemToLists
    tl.addPlexItem(m.trakt, m.plex.item)
  File "D:\IDE\.py\PlexTraktSync-0.23.4\plextraktsync\trakt_list_util.py", line 61, in addPlexItem
    rank = self.trakt_items.get((trakt_item.media_type, trakt_item.trakt))
AttributeError: 'TraktList' object has no attribute 'trakt_items'

D:\IDE\.py\PlexTraktSync-0.23.8>
```

### Error trace / logs

```text
2022-11-01 11:49:48,271 WARNING[gitinfo.gitinfo]:No git dir found]
2022-11-01 11:50:23,519 ERROR[plexapi]:http://139.162.130.28:8443: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-11-01 11:50:44,443 ERROR[plexapi]:http://46.164.221.196:33400: HTTPConnectionPool(host='46.164.221.196', port=33400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FAEB4D0DC0>, 'Connection to 46.164.221.196 timed out. (connect timeout=30)'))
2022-11-01 11:50:44,443 ERROR[plexapi]:https://46-164-221-196.e2111fcb49ed4b5c9070f0b62df6213e.plex.direct:33400: HTTPSConnectionPool(host='46-164-221-196.e2111fcb49ed4b5c9070f0b62df6213e.plex.direct', port=33400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001FAEB4D1240>, 'Connection to 46-164-221-196.e2111fcb49ed4b5c9070f0b62df6213e.plex.direct timed out. (connect timeout=30)'))
2022-11-01 11:51:40,546 INFO[PlexTraktSync]:Sync Movie sections: [<PlexLibrarySection:movie:Документальное>, <PlexLibrarySection:movie:Короткометражки>, <PlexLibrarySection:movie:Фильмы>]
2022-11-01 11:51:40,553 INFO[PlexTraktSync]:Sync Show sections: [<PlexLibrarySection:show:Аниме>, <PlexLibrarySection:show:Сериалы>]
2022-11-01 11:51:43,020 INFO[PlexTraktSync]:Downloaded List Alien 40th Anniversary Short Films
2022-11-01 11:51:43,611 INFO[PlexTraktSync]:Downloaded List Alien
2022-11-01 11:51:44,762 INFO[PlexTraktSync]:Downloaded List Scary-Movies
2022-11-01 11:51:45,426 INFO[PlexTraktSync]:Downloaded List Popular Horror
2022-11-01 11:52:16,421 WARNING[gitinfo.gitinfo]:No git dir found
2022-11-01 11:52:16,427 INFO[PlexTraktSync]:PlexTraktSync [0.23.0dev0]
2022-11-01 11:52:16,522 INFO[PlexTraktSync]:Sync Movie sections: [<PlexLibrarySection:movie:Документальное>, <PlexLibrarySection:movie:Короткометражки>, <PlexLibrarySection:movie:Фильмы>]
2022-11-01 11:52:16,527 INFO[PlexTraktSync]:Sync Show sections: [<PlexLibrarySection:show:Аниме>, <PlexLibrarySection:show:Сериалы>]
2022-11-01 11:52:19,369 INFO[PlexTraktSync]:Downloaded List Alien 40th Anniversary Short Films
2022-11-01 11:52:19,380 INFO[PlexTraktSync]:Downloaded List Alien
2022-11-01 11:52:19,402 INFO[PlexTraktSync]:Downloaded List Scary-Movies
2022-11-01 11:52:19,415 INFO[PlexTraktSync]:Downloaded List Popular Horror
```

### Expected behavior

Synchronization of views and ratings.

### Steps to reproduce the behavior

Installation with [pipx]:
1. pipx install PlexTraktSync
to run:
2. plextraktsync

### Install method

pipx

### Version

0.23.8

### Python Version

3.7.10

### Operating System and Version

Windows 11 Pro

**Comment by glensc** [comment]
Your error trace comes from PlexTraktSync-0.23.4, which is not installed with pipx, and besides that, it's some older version (0.23.4).

**Comment by glensc** [comment]
The other error comes from `TraktList` being initialized with no username
- https://github.com/Taxel/PlexTraktSync/blob/9bdd0d1dea000dd3b53189c8c4a7d55348b9178e/plextraktsync/trakt_list_util.py#L40-L50
- https://github.com/Taxel/PlexTraktSync/blob/9bdd0d1dea000dd3b53189c8c4a7d55348b9178e/plextraktsync/trakt_list_util.py#L60-L61

what's your config? what lists have you watching, they have no name? I'm actually not familiar with the watchlist code.

the error will likely go away if you disable watchlist related sync items from config.

**Comment by glensc** [comment]
> Workarounds
>
> No response

you said it worked before, so find an older version where it worked, that would help nail the bug if it's in this project code.

**Comment by bulletproof2k** [comment]
Where can I find this configuration file?

p.s. Packages trakt and trakt.py were removed using pip. How do I delete the rest?
Please give me instructions 🙏🏻
After installation using the pipix, there is no request for synchronization in the services, perhaps this is important. For some reason I'm already logged in.

**Comment by bulletproof2k** [comment]
How do I remove everything related to your package and perform a clean install?

**Comment by bulletproof2k** [comment]
1. Yes
2. How do I delete them?
3. There were two installations and pipix and for Windows. I can tell you one thing, it's the same error in all versions and installation methods.

**Comment by bulletproof2k** [comment]
This is a new installation using pipx and it still remembers my data. Maybe you need to delete some folders?

Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Установите последнюю версию PowerShell для новых функций и улучшения! https://aka.ms/PSWindows

PS C:\Users\victo> pipx install PlexTraktSync
  installed package plextraktsync 0.23.8, installed using Python 3.10.7
  These apps are now globally available
    - plextraktsync.exe
done! ✨ 🌟 ✨
PS C:\Users\victo> plextraktsync
INFO     PlexTraktSync [0.23.8]
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Документальное>, <PlexLibrarySection:movie:Короткометражки>,
         <PlexLibrarySection:movie:Фильмы>]
INFO     Sync Show sections: [<PlexLibrarySection:show:Аниме>, <PlexLibrarySection:show:Сериалы>]
INFO     Downloaded List Alien 40th Anniversary Short Films
INFO     Downloaded List Alien
INFO     Downloaded List Scary-Movies
INFO     Downloaded List Popular Horror
Processing Документальное   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/5  [ 0:00:00 < -:--:-- , ? it/s ]
Traceback (most recent call last):
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\victo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\victo\.local\bin\plextraktsync.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\cli.py", line 53, in cli
    sync()
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\commands\sync.py", line 57, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\sync.py", line 90, in sync
    listutil.addPlexItemToLists(movie)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\trakt_list_util.py", line 97, in addPlexItemToLists
    tl.addPlexItem(m.trakt, m.plex.item)
  File "C:\Users\victo\.local\pipx\venvs\plextraktsync\lib\site-packages\plextraktsync\trakt_list_util.py", line 61, in addPlexItem
    rank = self.trakt_items.get((trakt_item.media_type, trakt_item.trakt))
AttributeError: 'TraktList' object has no attribute 'trakt_items'
PS C:\Users\victo>

**Comment by bulletproof2k** [comment]
These are the settings after installation.

cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter:
#    # Filter out all messages with level WARNING
#    - level: WARNING
#    # Filter out message with level WARNING and containing a text
#    - level: WARNING
#      message: "not found on Trakt"
#    - message: "because provider local has no external Id"
#    - message: "because provider none has no external Id"
#    - message: "Retry using search for specific Plex Episode"

sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false

watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et

**Comment by glensc** [comment]
why do you want to delete data? 

if you want the reported error go away:
1. find oldest version that still works, so could find buggy code. i already told this
2. disable the watchlist syncing. i already told this.

also, edit your posts and put the pastes to code block for better formatting:
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by glensc** [comment]
also, all your errors end with "Popular Horror" being the last before crash. can you explain what you know about it? did you added it recently? what is it anyway? a link? have you trying removing it, unsubscribing it? repeat: I don't know how the watchlist feature works, so I'm just suggesting things.

**Comment by bulletproof2k** [comment]
This is a list in the Trakt that I liked, just put a like.

**Comment by glensc** [comment]
> This is a list in the Trakt that I liked, just put a like.

you don't want to get helped or what is it? i asked for list link, I asked you to remove (unlike then) and try it again. also how's it going with a downgrade to a version that doesn't crash?

**Comment by bulletproof2k** [comment]
Downgrading the version didn't work, I'll do all of the above a little later, I'm busy with work right now. Sorry @glensc

**Comment by bulletproof2k** [comment]
> also, all your errors end with "Popular Horror" being the last before crash. can you explain what you know about it? did you added it recently? what is it anyway? a link? have you trying removing it, unsubscribing it? repeat: I don't know how the watchlist feature works, so I'm just suggesting things.

https://trakt.tv/users/lish408/lists/popular-horror?sort=rank,asc
https://trakt.tv/lists/official/alien-40th-anniversary-short-films-da668a6d-5378-4e32-a8a9-af3366c27805?sort=rank,asc
https://trakt.tv/users/gersomuzziel/lists/alien

**These are the lists in the Trakt.**

**Comment by bulletproof2k** [comment]
I completely followed your instructions and removed the likes from these sheets, now everything works, thank you so much for your help

PS C:\Users\victo> plextraktsync
INFO     PlexTraktSync [0.23.8]
INFO     Sync Movie sections: [<PlexLibrarySection:movie:Документальное>, <PlexLibrarySection:movie:Короткометражки>,
         <PlexLibrarySection:movie:Фильмы>]
INFO     Sync Show sections: [<PlexLibrarySection:show:Аниме>, <PlexLibrarySection:show:Сериалы>]
ERROR    <Movie:1587:Третий-рейх:-Операци>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://392039?lang=ru>
Processing Документальное  80% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━ 4/5  [ 0:00:01 < 0:00:01 , 2 it/s ]INFO     Документальное processed in 2.0 seconds
INFO     Adding to collection: <tmdb:682810:Movie:1597:096>
INFO     Adding to collection: <tmdb:495362:Movie:1595:Изгнанник>
INFO     Rating <tmdb:495362:Movie:1595:Изгнанник> with 8 on Trakt
INFO     Marking as watched in Trakt: <tmdb:495362:Movie:1595:Изгнанник>
INFO     Adding to collection: <tmdb:438597:Movie:1450:Майор-Гром>
INFO     Rating <tmdb:438597:Movie:1450:Майор-Гром> with 8 on Trakt
INFO     Rating <tmdb:464111:Movie:1484:Зигота> with 8 on Trakt
ERROR    <Movie:1586:Последний-норвежский>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://596327?lang=ru>
INFO     Rating <tmdb:418087:Movie:1601:Пыльца> with 8 on Trakt
INFO     Rating <tmdb:295627:Movie:1188:Спаун:-Призыв> with 6 on Trakt
INFO     Rating <tmdb:341870:Movie:1585:Хищник:-Тёмные-века> with 6 on Trakt
INFO     Adding to collection: <tmdb:588207:Movie:1594:Чужой:-Сдерживание>
INFO     Adding to collection: <tmdb:588216:Movie:1593:Чужой:-Экземпляр>
Processing Короткометражки 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/11  [ 0:00:10 < 0:00:00 , 1 it/s ]INFO     Короткометражки processed in 10.2 seconds
INFO     Rating <tmdb:760104:Movie:1187:X> with 6 on Trakt
ERROR    <Movie:1845:Алита:-Боевой-ангел>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://88173?lang=ru>
INFO     Rating <tmdb:55931:Movie:1485:Аниматрица> with 10 on Trakt
INFO     Rating <tmdb:503736:Movie:1465:Армия-мертвецов> with 8 on Trakt
INFO     Adding to collection: <tmdb:16873:Movie:1486:Битва-за-планету-Тер>
ERROR    <Movie:1838:Весна>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://817556?lang=ru>
INFO     Adding to collection: <tmdb:985939:Movie:1238:Вышка>
INFO     Rating <tmdb:985939:Movie:1238:Вышка> with 10 on Trakt
INFO     Adding to collection: <tmdb:12244:Movie:1473:Девять>
INFO     Rating <tmdb:12244:Movie:1473:Девять> with 10 on Trakt
ERROR    <Movie:1826:Ку!-Кин-дза-дза>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://420070?lang=ru>
INFO     Adding to collection: <tmdb:603:Movie:1318:Матрица>
INFO     Adding to collection: <tmdb:604:Movie:1322:Матрица:-Перезагрузк>
INFO     Adding to collection: <tmdb:605:Movie:1314:Матрица:-Революция>
INFO     Rating <tmdb:514847:Movie:1662:Охота> with 10 on Trakt
INFO     Adding to collection: <tmdb:647:Movie:1383:Последняя-фантазия-7>
Processing Фильмы 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31/31  [ 0:00:27 < 0:00:00 , 1 it/s ]INFO     Фильмы processed in 27.0 seconds
WARNING  <Show:1165:Аниматрица>: Skipping guid <PlexGuid:com.plexapp.agents.thetvdb://80468?lang=ru> not found on Trakt
INFO     Rating <tmdb:2320905:Episode:590:Киберпанк:-Бегущие-п-s01e01> with 8 on Plex
INFO     Rating <tmdb:3894660:Episode:591:Киберпанк:-Бегущие-п-s01e02> with 10 on Plex
INFO     Rating <tmdb:3894661:Episode:592:Киберпанк:-Бегущие-п-s01e03> with 8 on Plex
INFO     Rating <tmdb:3894662:Episode:593:Киберпанк:-Бегущие-п-s01e04> with 10 on Plex
INFO     Rating <tmdb:3894664:Episode:595:Киберпанк:-Бегущие-п-s01e06> with 7 on Plex
INFO     Rating <tmdb:3894665:Episode:596:Киберпанк:-Бегущие-п-s01e07> with 8 on Plex
ERROR    <Show:1274:Легенды-Halo>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://470148?lang=ru>
INFO     Rating <tvdb:357888/1/3:Episode:1434:Любовь,-смерть-и-роб-s01e03> with 6 on Plex
INFO     Rating <tvdb:357888/1/10:Episode:1408:Любовь,-смерть-и-роб-s01e10> with 8 on Plex
INFO     Rating <tvdb:357888/1/11:Episode:1409:Любовь,-смерть-и-роб-s01e11> with 8 on Plex
ERROR    <Show:1213:Спаун>: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://409197?lang=ru>
INFO     Adding to collection: <tvdb:397934/1/1:Episode:1841:Человек-бензопила-s01e01>
INFO     Adding to collection: <tvdb:397934/1/2:Episode:1842:Человек-бензопила-s01e02>
INFO     Adding to collection: <tvdb:397934/1/3:Episode:1843:Человек-бензопила-s01e03>
Processing Аниме 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7  [ 0:00:06 < 0:00:00 , 1 it/s ]INFO     Аниме processed in 6.5 seconds
ERROR    <Show:1305:Halo-4-Forward-Unto->: Unable to parse a valid provider from guid
         <PlexGuid:com.plexapp.agents.kinopoisk2://692309?lang=ru>
INFO     Adding to collection: <tvdb:372700/1/1:Episode:1829:Викинги:-Вальхалла-s01e01>
INFO     Adding to collection: <tvdb:372700/1/2:Episode:1830:Викинги:-Вальхалла-s01e02>
INFO     Adding to collection: <tvdb:372700/1/3:Episode:1831:Викинги:-Вальхалла-s01e03>
INFO     Adding to collection: <tvdb:372700/1/4:Episode:1836:Викинги:-Вальхалла-s01e04>
INFO     Adding to collection: <tvdb:372700/1/5:Episode:1832:Викинги:-Вальхалла-s01e05>
INFO     Adding to collection: <tvdb:372700/1/6:Episode:1833:Викинги:-Вальхалла-s01e06>
INFO     Adding to collection: <tvdb:372700/1/7:Episode:1834:Викинги:-Вальхалла-s01e07>
INFO     Adding to collection: <tvdb:372700/1/8:Episode:1835:Викинги:-Вальхалла-s01e08>
INFO     Rating <tvdb:409559/1/1:Episode:1471:Кабинет-редкостей-Ги-s01e01> with 6 on Plex
INFO     Rating <tvdb:409559/1/3:Episode:1489:Кабинет-редкостей-Ги-s01e03> with 7 on Plex
INFO     Rating <tvdb:409559/1/4:Episode:1490:Кабинет-редкостей-Ги-s01e04> with 6 on Plex
INFO     Adding to collection: <tvdb:409559/1/7:Episode:1608:Кабинет-редкостей-Ги-s01e07>
INFO     Adding to collection: <tvdb:409559/1/8:Episode:1609:Кабинет-редкостей-Ги-s01e08>
INFO     Rating <tvdb:409559/1/8:Episode:1609:Кабинет-редкостей-Ги-s01e08> with 8 on Plex
INFO     Rating <tmdb:1481339:Episode:690:Касл-Рок-s01e01> with 7 on Plex
INFO     Rating <tmdb:1535091:Episode:703:Касл-Рок-s01e09> with 7 on Plex
INFO     Rating <tmdb:1535092:Episode:701:Касл-Рок-s01e10> with 6 on Plex
INFO     Rating <tmdb:1906742:Episode:681:Касл-Рок-s02e01> with 7 on Plex
WARNING  <Show:1366:Космос:-Возможные-ми>: Skipping <PlexGuid:com.plexapp.agents.none://1366?lang=xn> because provider
         none has no external Id
INFO     Adding to collection: <tvdb:387525/1/1:Episode:1654:Обитель-зла-s01e01>
INFO     Adding to collection: <tvdb:387525/1/2:Episode:1655:Обитель-зла-s01e02>
INFO     Adding to collection: <tvdb:387525/1/3:Episode:1656:Обитель-зла-s01e03>
INFO     Adding to collection: <tvdb:387525/1/4:Episode:1657:Обитель-зла-s01e04>
INFO     Adding to collection: <tvdb:387525/1/5:Episode:1658:Обитель-зла-s01e05>
INFO     Adding to collection: <tvdb:387525/1/6:Episode:1659:Обитель-зла-s01e06>
INFO     Adding to collection: <tvdb:387525/1/7:Episode:1660:Обитель-зла-s01e07>
INFO     Adding to collection: <tvdb:387525/1/8:Episode:1661:Обитель-зла-s01e08>
INFO     Rating <tmdb:3042860:Episode:943:Ходячие-мертвецы-s11e02> with 7 on Plex
WARNING  <Episode:1349:Ходячие-мертвецы-s11e19>: Skipping <PlexGuid:local://1349> because provider local has no external         Id
WARNING  <Episode:1350:Ходячие-мертвецы-s11e20>: Skipping <PlexGuid:local://1350> because provider local has no external         Id
Processing Сериалы 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13  [ 0:00:12 < 0:00:00 , 1 it/s ]INFO     Сериалы processed in 12.6 seconds
INFO     Rating <tvdb:409559:Show:1469:Кабинет-редкостей-Ги> with 8 on Trakt
INFO     Rating <tvdb:79066:Show:1610:Мастера-ужасов> with 8 on Trakt
INFO     Rating <tmdb:105248:Show:585:Киберпанк:-Бегущие-п> with 8 on Trakt
INFO     Rating <tvdb:357888:Show:1398:Любовь,-смерть-и-роб> with 10 on Trakt
Syncing show ratings  93% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━ 14/15  [ 0:00:04 < 0:00:01 , 4 it/s ]INFO     Adding Love, Death & Robots to Trakt watchlist
INFO     Adding Evil Dead Rise to Trakt watchlist
Processing Plex watchlist 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6  [ 0:00:05 < 0:00:00 , 1 it/s ]INFO     Adding What the Bleep! Down the Rabbit Hole to Plex watchlist
INFO     Skipping Cyberpunk 2077: Phoenix Program from Trakt watchlist because not found in Plex Discover
INFO     Skipping Cosmos: Possible Worlds from Trakt watchlist because not found in Plex Discover
Processing Trakt watchlist 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3  [ 0:00:15 < 0:00:00 , 0 it/s ]INFO     Updated watchlist in 20.6 seconds
INFO     Completed full sync in 1 min 36.5 seconds
PS C:\Users\victo>``

**Comment by glensc** [comment]
@bulletproof2k, so which exact list was problematic? any of the four?

but you said it worked before, so how far did you downgrade, at least tell to what version attempted?

and what's the way to reproduce? please provide **exact** steps including what links or buttons to click, as I'm not familiar with this feature.

**Comment by glensc** [comment]
1. @bulletproof2k also you didn't edit your comments for code blocks
2. also I don't see you tried changing config

**Comment by bulletproof2k** [comment]
Some one, or even all four.
Now I have the installation using pipx latest version.
Also, some time ago, the versions for installing Windows were 0.22.4 and 0.23.4.

**Comment by bulletproof2k** [comment]
> 1. @bulletproof2k also you didn't edit your comments for code blocks
> 2. also I don't see you tried changing config

I didn't edit anything, I just removed my likes from the problem lists.

**Comment by glensc** [comment]
> Some one, or even all four.

unable to decrypt. be specific.

> I didn't edit anything, I just removed my likes from the problem lists.

but I asked you to edit your comments to fix the formatting:
- https://github.com/Taxel/PlexTraktSync/issues/1161#issuecomment-1298437467
i.e this comment:
- https://github.com/Taxel/PlexTraktSync/issues/1161#issuecomment-1298392595
- and this one https://github.com/Taxel/PlexTraktSync/issues/1161#issuecomment-1298390525

**Comment by bulletproof2k** [comment]
You don't have to worry because all versions work, the problem was in these lists and that's it.

**Comment by glensc** [comment]
@bulletproof2k so, waiting reproducer exact steps then.

**Comment by bulletproof2k** [comment]
**On Windows, install via pip**
Step 1. Installing pipx: `python -m pip install --user pipx`
Step 2. Installing the package: [pipx install PlexTraktSync](url)
Step 3. Run the command: `plextraktsync`
Step 4. Removing likes from problem lists on the Trakt website.

**Comment by glensc** [comment]
> Step 4. Removing likes from problem lists on the Trakt website.

Please details on that!

I repeat 4th time already: I don't know how the liked lists feature works, so give exact steps:
- https://github.com/Taxel/PlexTraktSync/issues/1161#issuecomment-1300356070

I tried to click some subscribe on https://trakt.tv/users/lish408/lists/popular-horror?sort=rank,asc but it gave me VIP subscription required error. so, give me exact steps to reproduce the error you reported in this issue.

**Comment by bulletproof2k** [comment]
> @bulletproof2k, so which exact list was problematic? any of the four?
> 
> but you said it worked before, so how far did you downgrade, at least tell to what version attempted?
> 
> and what's the way to reproduce? please provide **exact** steps including what links or buttons to click, as I'm not familiar with this feature.

Step 1. Go to the list that you have recently liked and which causes an error in the command: `plextraktsync` on the Tract website.
Step 2. Unlike this list.
Step 3. Wait some time for the cache on the Tract website to be updated.
Step 4. Run the command again: `plextraktsync`

**Comment by bulletproof2k** [comment]
> @bulletproof2k, so which exact list was problematic? any of the four?
> 
> but you said it worked before, so how far did you downgrade, at least tell to what version attempted?
> 
> and what's the way to reproduce? please provide **exact** steps including what links or buttons to click, as I'm not familiar with this feature.

I downgraded the version to 0.22.4 and to 0.23.4 they worked for a while (Installing the package in an unsupported way for Windows)

**Comment by bulletproof2k** [comment]
At the moment I am using the latest version of the package 0.23.8 installed in a supported way using pipX.

**Comment by glensc** [comment]
I'm unable to reproduce using these instructions

1. visit https://trakt.tv/users/lish408/lists/popular-horror?sort=rank,asc
2. click like: <img width="185" alt="image" src="https://user-images.githubusercontent.com/199095/199531751-217cc57d-589a-40e7-8f41-40bdc0fa8042.png">
1. run

**Comment by glensc** [comment]
@bulletproof2k that's what U did, I gave the link of the list to like, is the list you refer to with a different URL? if so, then tell me. r reproducible steps include URLs (links).

**Comment by bulletproof2k** [comment]
@glensc 
Step 1. Find the problem list by searching through the lists. (you can go to this list and remove the like there)
Step 2. Remove your like
Step 3. Wait some time for the cache on the Tract website to be updated.
Step. 4. Run the command: `plextraktsync` again

**Comment by bulletproof2k** [comment]
**Lists**
https://trakt.tv/search/lists?query=Popular+Horror
https://trakt.tv/users/lish408/lists/popular-horror

**Comment by glensc** [comment]
@bulletproof2k will you confirm @twolaw fix solves your issue?
- https://github.com/Taxel/PlexTraktSync/issues/1161#issuecomment-1300814866

**Comment by bulletproof2k** [comment]
@glensc yes, the problem is solved.

**Comment by glensc** [comment]
@bulletproof2k let me be **super clear**: I ask does the pull request solve the problem? I'm not asking if removing "like" from some lists solved YOUR PERSONAL problem you were having.

to confirm this, you need to:
1. go back to state the problem was happening
2. try with the code from the pull request
3. report results to the pull request

**Comment by glensc** [comment]
so far I have not seen anywhere you have tested the mentioned pull request and confirmed it resolved the problem.

**Comment by bulletproof2k** [comment]
Unfortunately, I do not know how to do this, I'm new here.
