### ISSUE TITLE
Upload collection metadata

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#117]
It would be nice if metadata support for collections were added.

| Current  | With metadata support |
| ------------- | ------------- |
| <img width="161" alt="image" src="https://user-images.githubusercontent.com/19761269/110007884-27dbe200-7d41-11eb-9d31-32a33093afd4.png">  | <img width="161" alt="image" src="https://user-images.githubusercontent.com/19761269/110007877-25798800-7d41-11eb-8b37-3054d8ddc763.png">  |

**Comment by glensc** [comment]
@agneevX please explain what do you mean. scrobble in my dictionary means to use "user is watching x"

movie play scrobbling is possible with `watch` subcommand since:
- https://github.com/Taxel/PlexTraktSync/pull/192

tv episode scrobbling does not work yet

**Comment by twolaw** [comment]
metadata = picture definition (720p, 1080p,...), audio channels and codec, etc...

**Comment by glensc** [comment]
ok, seems it's about this feature:
- https://blog.trakt.tv/how-to-build-your-collection-146e6e80bcd7

but can't find any method from trakt library we are using to support this. is there public api for this?

**Comment by glensc** [comment]
found the api doc:
- https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection

**Comment by agneevX** [comment]
Sorry, I misunderstood the definition of "scrobble" 😅

**Comment by agneevX** [comment]
Worth noting is that the Plex-trakt-scrobbler doesn't support `Format` and `HDR` parameters; it defaults to `Digital` and `No` respectively. 

This info can perhaps be retrieved from the file name and analyzed metadata perhaps.

**Comment by glensc** [comment]
adding missing link:
- https://github.com/trakt/Plex-Trakt-Scrobbler

@agneevX please link to resources you are talking about!

**Comment by glensc** [comment]
support from trakt library we are using is missing:
- https://github.com/moogar0880/PyTrakt/issues/143

**Comment by glensc** [comment]
I was able to make up these fields:

```python
    def to_json(self):
        return {
            "collected_at": timestamp(self.collected_at),
            "media_type": "digital",
            "resolution": self.resolution,
            # "hdr": "dolby_vision",
            # "audio": "dts_ma",
            "audio_channels": self.audio_channels,
        }
```

**Comment by glensc** [comment]
for audio channels, need exact values from plex side for these:
> Set to 1.0, 2.0, 2.1, 3.0, 3.1, 4.0, 4.1, 5.0, 5.1, 5.1.2, 5.1.4, 6.1, 7.1, 7.1.2, 7.1.4, 9.1, or 10.1

trakt was so picky, that it gave 500 error if for audio channels was submitted `2`, not `"2.0"`

the same for videos, need plex side values for:
> Set to uhd_4k, hd_1080p, hd_1080i, hd_720p, sd_480p, sd_480i, sd_576p, or sd_576i.

dirty code is here now: https://github.com/Taxel/PlexTraktSync/pull/211, maybe moved out soon, as that pr is for `collected_at` field only. and the PR is for movies only right now.

**Comment by glensc** [comment]
so, @agneevX (and others), if you want to progress this faster, you can help by finding values to use for re-mapping.

**Comment by glensc** [comment]
Changes for only this issue are here now:
- https://github.com/Taxel/PlexTraktSync/pull/214/files

**Comment by agneevX** [comment]
@glensc I'm not exactly sure what it is you want me to do... do you want me to provide stream metadata info for media in my library?

**Comment by agneevX** [comment]
If so, I hope these help.

1. `Dolby Vision` `4K` w/ `E-AC3/DDP+` audio

`<Stream id="471182" streamType="1" default="1" codec="hevc" index="0" bitrate="21842" DOVIBLCompatID="0" DOVIBLPresent="1" DOVIELPresent="0" DOVILevel="6" DOVIPresent="1" DOVIProfile="5" DOVIRPUPresent="1" DOVIVersion="1.0" bitDepth="10" chromaSubsampling="4:2:0" codecID="dvhe" codedHeight="2160" codedWidth="3840" colorRange="pc" frameRate="23.976" height="2160" level="156" profile="main 10" refFrames="1" streamIdentifier="1" width="3840" displayTitle="4K (HEVC Main 10)" extendedDisplayTitle="4K (HEVC Main 10)"></Stream>`

`<Stream id="471183" streamType="2" selected="1" default="1" codec="eac3" index="1" channels="6" bitrate="768" language="English" languageCode="eng" audioChannelLayout="5.1(side)" samplingRate="48000" streamIdentifier="2" displayTitle="English (EAC3 5.1)" extendedDisplayTitle="English (EAC3 5.1)"></Stream>`

2. `HDR`/`HDR10` 4K Blu-ray w/ `DTS-HD MA` (7.1) audio, `TrueHD` (7.1) + `Atmos`

These are ordered according to the XML sheet. 

`<Stream id="483655" streamType="1" codec="hevc" index="0" bitrate="64783" language="English" languageCode="eng" bitDepth="10" chromaSubsampling="4:2:0" codedHeight="2160" codedWidth="3840" colorPrimaries="bt2020" colorRange="tv" colorSpace="bt2020nc" colorTrc="smpte2084" frameRate="23.976" height="2160" level="153" profile="main 10" refFrames="1" width="3840" displayTitle="4K (HEVC Main 10 HDR)"></Stream>`

`<Stream id="483656" streamType="2" selected="1" default="1" codec="truehd" index="1" channels="8" language="English" languageCode="eng" audioChannelLayout="7.1" bitDepth="24" samplingRate="48000" displayTitle="English (TRUEHD 7.1)"></Stream>`

`<Stream id="483657" streamType="2" codec="dca" index="2" channels="8" bitrate="1536" language="English" languageCode="eng" audioChannelLayout="7.1" bitDepth="24" profile="ma" samplingRate="48000" displayTitle="English (DTS-HD MA 7.1)"></Stream>`

3. `1080p` Blu-ray with `TrueHD` (5.1)

`<Stream id="475191" streamType="1" default="1" codec="h264" index="0" bitrate="31695" language="English" languageCode="eng" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" codedHeight="1088" codedWidth="1920" frameRate="23.976" hasScalingMatrix="0" height="1080" level="41" profile="high" refFrames="4" scanType="progressive" title="MPEG-4 AVC Video / 30733 kbps / 1080p / 23.976 fps / 16:9 / High Profile 4.1" width="1920" displayTitle="1080p (H.264)" extendedDisplayTitle="MPEG-4 AVC Video / 30733 kbps / 1080p / 23.976 fps / 16:9 / High Profile 4.1"></Stream>`

`<Stream id="475192" streamType="2" selected="1" default="1" codec="truehd" index="1" channels="6" language="English" languageCode="eng" audioChannelLayout="5.1(side)" bitDepth="24" samplingRate="48000" title="Dolby TrueHD Audio / 5.1 / 48 kHz / 1221 kbps / 16-bit" displayTitle="English (TRUEHD 5.1)" extendedDisplayTitle="Dolby TrueHD Audio / 5.1 / 48 kHz / 1221 kbps / 16-bit (English)"></Stream>`

**Comment by agneevX** [comment]
I see that Trakt allows Atmos metadata for `TrueHD` or `DDP+`...

<img src="https://user-images.githubusercontent.com/19761269/114266763-9e8d8e80-9a15-11eb-8c50-558e5d23c931.png" width="190">

However, if you look at the XML data for either of those above, you'll notice that there's no mention of `Atmos` or `Dynamic objects`, so I guess you have to default to uploading metadata to the non Atmos version.

**Comment by glensc** [comment]
@agneevX is there info on how you obtained those XML's? for me and for posterity.

I grepped through mine, they all were channels=2, which is weird.

**Comment by agneevX** [comment]
Oh! Overflow menu → Get Info → View XML in bottom-left corner of the modal

<img src="https://user-images.githubusercontent.com/19761269/114267878-f0d1ae00-9a1b-11eb-8f3b-90110316ed11.png" width="180">

**Comment by glensc** [comment]
@agneevX this is very confusing to me, can you put up a table or logic on how to map these together for trakt? 

- trakt needs these keywords: https://github.com/Taxel/PlexTraktSync/issues/117#issuecomment-817009672

for audio it seems simple, take `audioChannelLayout` from media.parts.audiostream:
- https://python-plexapi.readthedocs.io/en/latest/modules/media.html#plexapi.media.AudioStream

but video, it has tons of attributes:
- https://python-plexapi.readthedocs.io/en/latest/modules/media.html#plexapi.media.VideoStream

this area is very foreign here, I'm just trying to map available data, so help is appreachiated. 

for example are `uhd_4k` (what trakt wants), `4K HLG` (what you showed), `4K (HEVC Main 10)` (what plex has in the stream field) the same thing or not, I have no idea!

I've added `inspect` command, to help printing the data (in https://github.com/Taxel/PlexTraktSync/pull/214):

```
$ ./plex_trakt_sync.sh inspect /library/metadata/9725
Audio: 'stereo', 'English (AAC Stereo)'
Video: h264
```

**Comment by glensc** [comment]
I've now added a test case, so could mock the objects and see if the expected result is built:

```
$ ./test_collection_metadata.py
test_collection_metadata.py  [100%]
== 1 passed in 0.20s ===================
```

**Comment by agneevX** [comment]
> for example are `uhd_4k` (what trakt wants), `4K HLG` (what you showed), `4K (HEVC Main 10)` (what plex has in the stream field) the same thing or not, I have no idea!

Ok, so these are different.

`uhd_4k` is just 2160p 4K video, not a HDR format. 

HLG is a HDR format. You'd find this if `colorTrc` is `arib-std-b67`.

The other one is the text metadata, that the encoder has put in (I think!), so this label should be ignored.

For example to determine Dolby Vision, which is a HDR format, you can check if `DOVIPresent="1"` is present or not.

**Comment by glensc** [comment]
Since there's no interest from anyone to write code for this, I'm going to merge existing PR as it is:
- https://github.com/Taxel/PlexTraktSync/pull/214

**Comment by agneevX** [comment]
Maybe add a `help-wanted` tag??

**Comment by glensc** [comment]
added label. would you update readme to add a section so people actually find such issues?

**Comment by mcdallas** [comment]
hey @glensc the Plex-Trakt-Scrobbler plugin supports this functionality nicely. I checked the source code and found the mapping logic [here](https://github.com/trakt/Plex-Trakt-Scrobbler/blob/aeb0bfbe62fad4b06c164f1b95581da7f35dce0b/Trakttv.bundle/Contents/Libraries/Shared/plugin/sync/handlers/collection/push.py#L10-L115)

**Comment by glensc** [comment]
Added doc how to share xml:
- https://github.com/Taxel/PlexTraktSync/pull/372

**Comment by glensc** [comment]
re-opening, as the current code submits typical 720p movies as 576p:
- https://github.com/Taxel/PlexTraktSync/pull/366#issuecomment-878592575

the thread there discusses a possible solution.
