### ISSUE TITLE
Playlists not created from Liked Lists

### ISSUE THREAD

**Issue by NGDM** [Taxel/PlexTraktSync#1177]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Ever since the #941 bug the sync of Trakt liked lists to Plex playlists has stopped working.

In the logs they still seem to be downloaded, but I can't find them in my Plex Playlists.
Nothing in the logs seem to show an issue/warning/error, not even in debug logs.

I tried unliking, syncing, liking and syncing again to trigger a redownload, but still no cigar.

Also tried with a new setup from scratch, still no sync. 

### Error trace / logs

```text
INFO     Downloaded List 1001 Greatest Movies of All Time                       
INFO     Downloaded List Lord of the Rings                                      
INFO     Downloaded List All of these Films are Worth Seeing (1400 Titles)      
INFO     Downloaded List Movies from the last decade [couchmoney.tv]            
INFO     Downloaded List Recommended Movies                                     
INFO     Downloaded List The Best Movie You Never Saw                           
INFO     Added to list 1001 Greatest Movies of All Time:                        
         <Movie:9643:Princess-Mononoke>                                         
Processing Anime Movies  77% ━━━━━━━━╺━━ 23/30  [ 0:00:00 < 0:00:01 , 214 it/s ]
INFO     Anime Movies processed in 0.6 seconds                                  
INFO     Added to list All of these Films are Worth Seeing (1400 Titles):       
         <Movie:22780:Accepted>                                                 
INFO     Added to list 1001 Greatest Movies of All Time:                        
         <Movie:19096:The-Aviator>                                              
INFO     Added to list All of these Films are Worth Seeing (1400 Titles):       
         <Movie:19096:The-Aviator>       
…
```

### Expected behavior

I would expect my liked lists being present in Plex as playlists.

### Steps to reproduce the behavior

1. docker-compose run --rm plextraktsync2
2. follow setup steps (Plex login, Trakt login)
3. let script finish
4. check playlists in Plex

### Install method

docker-compose

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Family
  - HDD Movies
  - HDD TV Shows

config:
  dotenv_override: true

logging:
  append: false
  debug: false
  filename: plextraktsync.log

sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true

watch:
  add_collection: true
  remove_collection: true
  scrobble_threshold: 80
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et
```

### Version

0.23.8-19-gcfad5c9_main

### Python Version

3.10.8

### Operating System and Version

Docker (Ubuntu)

**Comment by glensc** [comment]
> Workarounds
>
> No response

Downgrade? and please specify what version downgrade helped!

**Comment by glensc** [comment]
> Version
>
> 0.23.8-19-gcfad5c9_main

(While it probably is not broken in this case) We don't do support for development versions. (unless a developer particularly asked to test some development version).

**Comment by NGDM** [comment]
> > Workarounds
> > No response
> 
> Downgrade? and please specify what version downgrade helped!

Tried going back to 0.23.0 since everything before that fails on #941 
Still the same thing.


> > Version
> > 0.23.8-19-gcfad5c9_main
> 
> (While it probably is not broken in this case) We don't do support for development versions. (unless a developer particularly asked to test some development version).

I guess this is because I've been using `image: 'ghcr.io/taxel/plextraktsync:main'` for my docker container. 
I switched to `:latest` instead, but as you said it didn't fix this issue. 


I've now also tried on a different Plex server and get the same results. 
Am I really the only one with this issue?

Not sure what else I could try?

**Comment by glensc** [comment]
> Not sure what else I could try?

since you said it worked before, find the version where it worked.

**Comment by NGDM** [comment]
That would be somewhere before the bug I already mentioned (#941) which broke this script for a while until the PyTrakt project was forked…
I believe it was caused because of an update to the Trakt Lists API? 

So I can't really go back further without mocking the Trakt API or smth (wouldn't even know where to begin though).

Could you check if this functionality works for you @glensc?

**Comment by NGDM** [comment]
I'm wondering if the [python-plexapi](https://github.com/pkkid/python-plexapi) is the issue here.
Is it possible to output the plex-api logs in DEBUG/TRACE level within the PTS container?

**Comment by glensc** [comment]
> Could you check if this functionality works for you @glensc?

I don't use the feature, so first need to understand how it's supposed to work. If you describe step by step, it could help. maybe even submit a change to README?

> I believe it was caused because of an update to the Trakt Lists API?

for https://github.com/Taxel/PlexTraktSync/issues/941 You will need this change:
- https://github.com/moogar0880/PyTrakt/commit/2613efbe0136cc6e61f8d361892ae03273883926
It's from this PR:
- https://github.com/moogar0880/PyTrakt/pull/206/files#diff-bf5a3e77fd5033ce082c7a260d30782c5cafa5b35ade48268e147129dfd5e2ac

you can mock it with making a copy from the image and bind mounting it to container, or just modify the file inside the container before running the app.

**Comment by glensc** [comment]
> Is it possible to output the plex-api logs in DEBUG/TRACE level within the PTS container?

yes. it's documented in readme how to enable debug logging.

**Comment by glensc** [comment]
you could also bind mount `~/.config/plexapi/config.ini` to container, I believe `/root/.config/plexapi/config.ini` is the path, but enabling debug in pts worked so far:
- https://github.com/Taxel/PlexTraktSync/blob/ff6e108b0110abc3a55828265233cb13f656b020/plextraktsync/logging.py#L30-L36

**Comment by glensc** [comment]
but, have you tried this PR:
- https://github.com/Taxel/PlexTraktSync/pull/1162

does it change anything for you?

**Comment by glensc** [comment]
From https://github.com/Taxel/PlexTraktSync/issues/1177#issuecomment-1308401247

> I don't use the feature, so first need to understand how it's supposed to work. If you describe step by step, it could help.

**Comment by NGDM** [comment]
> but, have you tried this PR:
> 
>     * [Add trakt official lists support #1162](https://github.com/Taxel/PlexTraktSync/pull/1162)
> 
> 
> does it change anything for you?

Tried this but didn't fix it.




> From [#1177 (comment)](https://github.com/Taxel/PlexTraktSync/issues/1177#issuecomment-1308401247)
> 
> > I don't use the feature, so first need to understand how it's supposed to work. If you describe step by step, it could help.
> 
> don't forget to describe what config keys must be enabled.


1. Like a public (non-official) list on Trakt. [For example](https://trakt.tv/users/captainnapalm/lists/1001-greatest-movies-of-all-time) (make sure you have some movies from the list on your Plex server as well)
2. Set the `liked_lists` config under `trakt_to_plex` to `true`
3. Run a regular PTS `sync`, wait for finish.
4. Check on your Plex server's "Playlists" library if the liked playlist has been added to it.
Inside should be the movies from the Trakt list which are present on your server.

**Comment by NGDM** [comment]
Found the issue!

I believe the issue is caused by [this commit:](https://github.com/Taxel/PlexTraktSync/commit/827309e699b7dbfc2c137728ac8b0ef7e36cd5c7)

Here a new config was implemented for `watchlist_as_playlist` and some logic was changed.
More precise: [This method](https://github.com/Taxel/PlexTraktSync/blob/f7bdae025fafad1870673bc666a1e5aee79b818a/plextraktsync/sync.py#L111) is only ran when watchlists are synced (one of `watchlist` configs set to true) and `trakt_to_plex["watchlist_as_playlist"]` is true, which is wrong, since it should also be called when only `liked_lists` is true. 

Another strange occurrence is the liked list sync only happens when the `trakt_to_plex["watchlist"]` config is true. 
[This line](https://github.com/Taxel/PlexTraktSync/blob/f7bdae025fafad1870673bc666a1e5aee79b818a/plextraktsync/sync.py#L107) seems to indicate it should run as well if `plex_to_trakt["watchlist"]` is true I believe?

Could you try to rework this to also allow when only liked lists are synced?

**Comment by glensc** [comment]
marking as "docs needed label" you're welcome to send documentation update. the other you can send feature request.
