### ISSUE TITLE
Feature request: Allow syncing of Liked Lists without needing Watchlist sync

### ISSUE THREAD

**Issue by NGDM** [Taxel/PlexTraktSync#1182]
### Feature description
For the moment the Liked List sync feature (`trakt_to_plax["liked_lists"]`) is broken because it only runs if you enable the `trakt_to_plex["watchlist"]` and `trakt_to_plex["watchlist_as_playlist"]` configs.
[See here ](https://github.com/Taxel/PlexTraktSync/issues/1177#issuecomment-1309335976) for more elaborate explanation.

Syncing Liked Lists should be possible even if the `watchlist` and `watchlist_as_playlist` configs are false. 

### Use case

I don't want to sync my Trakt Watchlist as a separate Plex Playlist, but as the Plex Watchlist, yet also want to sync my Trakt Liked Lists as Plex Playlists.
For the moment this is not possible. 

### Workarounds

Leave `trakt_to_plex["watchlist"]` and  `trakt_to_plex["watchlist_as_playlist"]` on `true`

### Plan to implement

N/A

**Comment by glensc** [comment]
Can you propose new config keys to support all variations? or just different variations of config and I can see how to tweak the code?

My first thought would have been to just separate `watchlist` and `watchlist_as_playlist`, but here seems more variations are possible. and for compatibility turn `watchlist_as_playlist` off by default.
