### ISSUE TITLE
Issue Getting PlexTraktSync Working with Unraid 6.11

### ISSUE THREAD

**Issue by jeff15110168** [Taxel/PlexTraktSync#1198]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I can't seem to get this program up and running again after previously setting it up 6+ months ago (I believe back then I was able to launch a manual refresh which showed progress bar when run from the container console). I was trying to force a manually sync to Trakt again today but it's not working. Everytime I go try "start" the PlexTraktSync container on the dashboard, it never actually starts. See below for log file. I tried running the script too which does nothing (currently running background).

Container setup:
![image](https://user-images.githubusercontent.com/9892738/202092578-7e239777-b656-4b43-9684-6aa1fc6b1b77.png)

User Script (running in background):
![image](https://user-images.githubusercontent.com/9892738/202092642-e0bb1403-0e13-4425-8fca-430c79d056d8.png)

### Error trace / logs

```text
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x149562a0a990>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/watch.py", line 223, in watch
    server = factory.plex_server()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/factory.py", line 39, in plex_server
    return PlexServerConnection(factory).connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/decorators/nocache.py", line 12, in inner
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/plex_server.py", line 68, in connect
    if url[:5] == "https":
       ~~~^^^^
TypeError: 'NoneType' object is not subscriptable

** Press ANY KEY to close this window **
```

### Expected behavior

Trying to force update my Trakt account using a manual refresh.

### Steps to reproduce the behavior

1. try to start docker container "PlexTraktSync", since container won't start i can't access the container's own console
2. try to run a command using Unraid's command line; doesn't work
3. Not sure how to get a manual sync completed

### Install method

Unraid installation method

### Version

Not Sure (don't know how to get command)

### Python Version

Not Sure

### Operating System and Version

Unraid 6.11.3

**Comment by zeroquinc** [comment]
Remove the watch command, it should start after that.

**Comment by glensc** [comment]
The error trace happens if `PLEX_BASEURL` or `PLEX_LOCALURL` are empty.

**Comment by glensc** [comment]
> Workarounds
>
> No response

There's always way to downgrade.

> Version
>
> Not Sure (don't know how to get command)

`plextraktsync --version` prints the version. the bug report form informed about this too.

**Comment by glensc** [comment]
This omits the exception:
- https://github.com/Taxel/PlexTraktSync/pull/1203

but the underlying problem is that plex url is missing

**Comment by jeff15110168** [comment]
> > Remove the watch command, it should start after that.
> 
> "command: watch" has nothing to do with the exception:
> 
> * https://github.com/Taxel/PlexTraktSync/blob/980bd83b655dbef4531dc8c2610602e8d5c17e39/plextraktsync/plex_server.py#L68

Hi sorry - apologies for my ignorance, but what is the solution for my problem if it isn't removing watch command?

**Comment by glensc** [comment]
plex url is missing:
- https://github.com/Taxel/PlexTraktSync/issues/1198#issuecomment-1318796539
- https://github.com/Taxel/PlexTraktSync/issues/1198#issuecomment-1318785978

**Comment by jeff15110168** [comment]
ah okay, thank you, Do i need to do anything or is this an update that is being pushed to fix it? Not too familiar with how to fix the PLEX URL myself or how to make sure my container is updated if it needs an update

**Comment by jeff15110168** [comment]
> ah okay, thank you, Do i need to do anything or is this an update that is being pushed to fix it? Not too familiar with how to fix the PLEX URL myself or how to make sure my container is updated if it needs an update (my container repository is set to "ghcr.io/taxel/plextraktsync:latest" if that pushes the latest)

apologies again but was this ever fixed via an update? I guess for an idiot like me, what do i need to do as I wasn't fully following the conversation above in terms of what i can do to fix this vs. if this was something needed to fixed by the devs.

Thank you so much for all the help!
