### ISSUE TITLE
Show with all-numeric title can't be collected

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#1244]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

syncing keeps printing:

```
INFO     Adding to collection: <tvdb:xxx/1/1:Episode:xxx:<show_title>-s01e01>
INFO     Adding to collection: <tvdb:xxx/1/2:Episode:xxx:<show_title>-s01e02>
```

I have deleted the cache and the problem is recurring.

### Expected behavior

add proper show to collection. currently seems some irrelevant show is matched and that is seen in trakt as collected:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/199095/204667014-4d054112-e563-46f5-8303-4e06a685d4f9.png">

### Steps to reproduce the behavior

1. add some show to plex whose title is all numeric
2. enable collection sync in config
3. run sync first time
4. run sync second time

### Install method

pipx

### Version

0.24.3

### Python Version

3.10.8

### Operating System and Version

macOS-10.15.7

**Comment by glensc** [comment]
show details request is correct:
- `https://api-v2launch.trakt.tv/search/tvdb/<tvdb_id>?type=show`

but getting episodes detail goes nuts:
- `https://api-v2launch.trakt.tv/shows/<show_title>/seasons?extended=episodes`

it uses `show_title` not `id` there. the code is from here:
>             data = yield self.ext + '/seasons?extended=episodes'
- https://github.com/glensc/python-pytrakt/blob/3a6ab7050da258a00da9fcc03ac14bdd69f55092/trakt/tv.py#L434

That `ext` definition is here:

>     @property
>     def ext(self):
>         return 'shows/{slug}'.format(slug=self.slug)

- https://github.com/glensc/python-pytrakt/blob/3a6ab7050da258a00da9fcc03ac14bdd69f55092/trakt/tv.py#L254-L256

**Comment by glensc** [comment]
Problem would be fixed if `<trakt_id>` is used:
- `'https://api-v2launch.trakt.tv/shows/<trakt_id>/seasons?extended=episodes`

**Comment by glensc** [comment]
Possible fix:
- https://github.com/glensc/python-pytrakt/pull/9

**Comment by glensc** [comment]
Well, seems that is also problematic.

1. in pytrakt saved shows.json game of thrones id is  353: https://github.com/glensc/python-pytrakt/blob/3.4.13/tests/mock_data/shows.json#L95-L97
2. in https://api-v2launch.trakt.tv/shows/353/seasons?extended=episodes trakt id is `1170`, that's something else

let's try with slug:
- https://api-v2launch.trakt.tv/shows/game-of-thrones/seasons?extended=episodes this has trakt id 3962
- https://api-v2launch.trakt.tv/shows/3962/seasons?extended=episodes this is again something very different, trakt id is 12281, title search gave me this show: https://trakt.tv/shows/dekh-bhai-dekh, but for that one at least https://api-v2launch.trakt.tv/shows/dekh-bhai-dekh/seasons?extended=episodes is consistent and gives 12281 as  trakt id as well

**Comment by glensc** [comment]
none of the ids for game-of-thrones make sense:

```
➜ ./curl.sh -s https://api-v2launch.trakt.tv/shows/game-of-thrones/seasons?extended=episodes|jq |head
[
  {
    "number": 0,
    "ids": {
      "trakt": 3962,
      "tvdb": 137481,
      "tmdb": 3627,
      "tvrage": null
    },
```

- https://trakt.tv/search/trakt?query=3962
- https://trakt.tv/search/tvdb?query=137481
- https://trakt.tv/search/tmdb?query=3627

**Comment by glensc** [comment]
`$ ./curl.sh https://api.trakt.tv/shows/game-of-thrones`

```json
{"title":"Game of Thrones","year":2011,"ids":{"trakt":1390,"slug":"game-of-thrones","tvdb":121361,"imdb":"tt0944947","tmdb":1399,"tvrage":24493}}PlexTraktSync (refactor-ratings-for-shows) ➜ 
```

`$ ./curl.sh https://api.trakt.tv/shows/1390`

```json
{"title":"Game of Thrones","year":2011,"ids":{"trakt":1390,"slug":"game-of-thrones","tvdb":121361,"imdb":"tt0944947","tmdb":1399,"tvrage":24493}}
```

so, game of thrones trakt id is 1390?

**Comment by twolaw** [comment]
Game of Thrones is not a show with all-numeric title. Which show with all-numeric title do you talk about ?

**Comment by glensc** [comment]
Yes, game of thrones is not all-numeric-title. But it still had wrong id in test data of pytrakt. also `/shows/game-of-thrones/seasons?extended=episodes` endpoint seems to return garbage. probably need to report it to trakt.tv support. I'll try to find show with all-numeric-title.

**Comment by glensc** [comment]
Found one:
- https://trakt.tv/shows/1945

will check the data later.

**Comment by twolaw** [comment]
> `/shows/game-of-thrones/seasons?extended=episodes` endpoint seems to return garbage

Doesn't look garbage to me. Explain your point.

**Comment by glensc** [comment]
read the previous posts, especially:
- https://github.com/Taxel/PlexTraktSync/issues/1244#issuecomment-1331505296

what is this id? `"trakt": 3962`

**Comment by twolaw** [comment]
You asked seasons ids, you get seasons ids. This one is the season 0 id.

**Comment by glensc** [comment]
Ah. oops, indeed. thanks. so all fine with trakt data.

**Comment by twolaw** [comment]
Another one for tests : https://trakt.tv/shows/24
