### ISSUE TITLE
docker compose file error

### ISSUE THREAD

**Issue by joelkeasley** [Taxel/PlexTraktSync#1246]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Docker compose will not run with current instructions

On your instructions can you add version: "3" to the very top line of the compose file like shown below confirmed works with this

version: "3"
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn

### Expected behavior

will not run with out version 

### Steps to reproduce the behavior

follow your docker compose guide

### Workarounds

just added version: "3" to first line of docker compose file

### Install method

docker-compose

### Version

latest

### Python Version

3.7

### Operating System and Version

ubuntu 22.04

**Comment by glensc** [comment]
Incomplete bug report.

What is the error? What is your docker-compose version?

> Version: latest

don't cheat. fill the version!

**Comment by joelkeasley** [comment]
I was just trying to help you I could care less works  on my system

latest version is not cheating but what evs

**Comment by twolaw** [comment]
Thanks @joelkeasley 👍 

@glensc don't close without a good reason.
