### ISSUE TITLE
TypeError: UserList.new() got an unexpected keyword argument 'trakt'

### ISSUE THREAD

**Issue by jmirodrigues** [Taxel/PlexTraktSync#1314]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Hi,
I've reinstalled plextraktsync on a docker after trakt.tv outage. Now i'm not hable to do the library sync. Authentication on trakt is ok but the sync process guives me these errors:

```python
You are now logged into Trakt. Your Trakt credentials have been added in .env and .pytrakt.json files.
INFO Sync Movie sections: [PlexLibrarySection:movie:Filmes]
INFO Sync Show sections: [<PlexLibrarySection:show:Séries de TV>]
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in _run_code
File "/app/plextraktsync/main.py", line 18, in
cli()
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1635, in invoke
rv = super().invoke(ctx)
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/plextraktsync/cli.py", line 73, in cli
sync()
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in call
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/plextraktsync/cli.py", line 28, in wrap
cmd(*args, **kwargs)
File "/app/plextraktsync/commands/sync.py", line 70, in sync
runner.sync(walker=w, dry_run=config.dry_run)
File "/app/plextraktsync/sync.py", line 142, in sync
listutil.addList(lst["listid"], lst["listname"])
File "/app/plextraktsync/trakt_list_util.py", line 97, in addList
self.lists.append(TraktList(listid, listname))
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/plextraktsync/trakt_list_util.py", line 42, in init
userlist = LazyUserList._get(listname, listid)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/trakt/core.py", line 557, in inner
return generator.send(json_data)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/plextraktsync/trakt_list_util.py", line 31, in _get
ulist = LazyUserList(creator=data['user']['username'], **data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserList.new() got an unexpected keyword argument 'trakt'
[~] #
```

Please advice

### Expected behavior

Sync was working ok before trakt.tv outage they had. After trakt.tv was back online I run plextraktsync and it gave me an login error. I reinstalled it on a newer version of docker, cleared the config files and run the authentication process again. Everything is ok except when it tries to sync the library.

### Steps to reproduce the behavior

just can't run the docker after login process

### Install method

docker-compose

### Version

0.25.2

### Python Version

not shure

### Operating System and Version

docker

**Comment by twolaw** [comment]
> I have tried downgrading to find version that can be used as a workaround

Which version did you try ?
Did `0.24.7` output the same error ?

Maybe linked to Pytrakt 3.4.15 update :
- https://github.com/glensc/python-pytrakt/pull/14

**Comment by glensc** [comment]
Did you try removing cache?

**Comment by jmirodrigues** [comment]
> Did you try removing cache?

It's a new fresh installation

**Comment by jmirodrigues** [comment]
Just made a reboot on the server ando got this "extra" logs:

INFO     Sync Movie sections: [<PlexLibrarySection:movie:Filmes>]               
INFO     Sync Show sections: [<PlexLibrarySection:show:Séries de TV>]           
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max       
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73cb8030>: Failed to establish a new connection: [Errno -3] Try      
         again')) for plextraktsync.trakt.TraktApi.me(), retrying after 1       
         seconds (try: 1/5)                                                     
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max       
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73b92ab0>: Failed to establish a new connection: [Errno -3] Try      
         again')) for plextraktsync.trakt.TraktApi.me(), retrying after 2       
         seconds (try: 2/5)                                                     
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max       
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73b92ab0>: Failed to establish a new connection: [Errno -3] Try      
         again')) for plextraktsync.trakt.TraktApi.me(), retrying after 3       
         seconds (try: 3/5)                                                     
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max       
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73b92cd0>: Failed to establish a new connection: [Errno -3] Try      
         again')) for plextraktsync.trakt.TraktApi.me(), retrying after 4       
         seconds (try: 4/5)                                                     
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max       
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73b92cd0>: Failed to establish a new connection: [Errno -3] Try      
         again')) for plextraktsync.trakt.TraktApi.me(), retrying after 5       
         seconds (try: 5/5)                                                     
ERROR    Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max
         retries exceeded with url: /users/me (Caused by                        
         NewConnectionError('<urllib3.connection.HTTPSConnection object at      
         0x73b92cd0>: Failed to establish a new connection: [Errno -3] Try      
         again'))                                                               
ERROR    API didn't respond properly, script will abort now. Please try again   
         later.                                                                 
ERROR    Last call: plextraktsync.trakt.TraktApi.me((), {})

**Comment by glensc** [comment]
> > Did you try removing cache?
> 
> It's a new fresh installation

That does not always guarantee removed cache. Config and cache are preserved if you used the same config path.

**Comment by twolaw** [comment]
Answer questions about downgrading you tried, please.

**Comment by glensc** [comment]
paste logs in code blocks:
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by glensc** [comment]
> Maybe linked to Pytrakt 3.4.15 update :
> 
> * [Refactor: Add IdsMixin to replace extract_ids() utility method glensc/python-pytrakt#14](https://github.com/glensc/python-pytrakt/pull/14)

If that's the case, then `extract_ids` should be removed:
- https://github.com/Taxel/PlexTraktSync/blob/71a1e3a4932c657bbb30c03201739f50b39a8f7b/plextraktsync/trakt_list_util.py#L22
- https://github.com/Taxel/PlexTraktSync/blob/71a1e3a4932c657bbb30c03201739f50b39a8f7b/plextraktsync/trakt_list_util.py#L30

but I recall I tested it:
- https://github.com/glensc/python-pytrakt/pull/14#issuecomment-1345581598

i.e without removing them and left them in as the code worked

**Comment by jmirodrigues** [comment]
> 0.24.7

I'm gone try and give you feedback soon

**Comment by jmirodrigues** [comment]
> > > Did you try removing cache?
> > 
> > 
> > It's a new fresh installation
> 
> That does not always guarantee removed cache. Config and cache are preserved if you used the same config path.

I've removed the config folder for a new install

**Comment by twolaw** [comment]
> I'm gone try to downgrade and give you feedback soon

You said in 1st post that you tried downgrading to find version that can be used as a workaround 🤦‍♂️

**Comment by jmirodrigues** [comment]
No i did not....

**Comment by jmirodrigues** [comment]
I've got this on the yml file: image: ghcr.io/taxel/plextraktsync:latest
Should this work:  image: ghcr.io/taxel/plextraktsync:0.24.7
?? Whats the correct tag for downgrade?

**Comment by twolaw** [comment]
> No i did not....

You confirmed by checking the box. That's the purpose of confirmation section, to ensure users do test before opening new issue.

**Comment by jmirodrigues** [comment]
Sorry I'm not used to GitHub.... How can I TAG the version i want in docker?

I Have this: image: ghcr.io/taxel/plextraktsync:**latest** 

I tried replacing the **_latest_** TAG by 0.24.7 but it didn't work....

**Comment by glensc** [comment]
> I've got this on the yml file: image: ghcr.io/taxel/plextraktsync:latest Should this work: image: ghcr.io/taxel/plextraktsync:0.24.7 ?? Whats the correct tag for downgrade?


> Sorry I'm not used to GitHub.... How can I TAG the version i want in docker?
> 
> I Have this: image: ghcr.io/taxel/plextraktsync:**latest**
> 
> I tried replacing the **_latest_** TAG by 0.24.7 but it didn't work....

why so vague bug report "didn't work"? where's the actual error you got?

both images pull fine here:

```
~ ➜ docker pull ghcr.io/taxel/plextraktsync:latest
latest: Pulling from taxel/plextraktsync
Digest: sha256:8ffe4962d5d78184d8d0185ed6a0e1702a4262ddde9686ccaea3e69058c8d73d
Status: Image is up to date for ghcr.io/taxel/plextraktsync:latest
ghcr.io/taxel/plextraktsync:latest

~ ➜ docker pull ghcr.io/taxel/plextraktsync:0.24.7
0.24.7: Pulling from taxel/plextraktsync
Digest: sha256:40e96e1b51ebefa6a4e033cec792dd929d66f67259f20419fe7dc4c0434e1bac
Status: Image is up to date for ghcr.io/taxel/plextraktsync:0.24.7
ghcr.io/taxel/plextraktsync:0.24.7
~ ➜
```

**Comment by glensc** [comment]
You could try this PR:
- https://github.com/Taxel/PlexTraktSync/pull/1315

**Comment by glensc** [comment]
> The image simply didn't download by docker. I tried it again now and it just worked this time...
> 

still should have shared the error detail.

seems your container sometimes has network issues:
- https://github.com/Taxel/PlexTraktSync/issues/1314#issuecomment-1362939618

**Comment by jmirodrigues** [comment]
> > The image simply didn't download by docker. I tried it again now and it just worked this time...
> 
> still should have shared the error detail.
> 
> seems your container sometimes has network issues:
> 
> * [TypeError: UserList.new() got an unexpected keyword argument 'trakt' #1314 (comment)](https://github.com/Taxel/PlexTraktSync/issues/1314#issuecomment-1362939618)

My mistake, I should have seen the error log. Indeed it's not the first time an image is not downloaded and I need to install it again, using docker-compose....

**Comment by bulletproof2k** [comment]
The same problem if you upgrade further than 0.24.7
