### ISSUE TITLE
Feature request: Resume broken sync

### ISSUE THREAD

**Issue by jwm-evans** [Taxel/PlexTraktSync#1325]
### Feature description
When the application exits before it has fully synced a library it should leave a record of how far it had progressed. When the application is next run, it sees this record, removes it, and resumes from that point. If there is another failure, it again leaves a record of its progress. If there is no record present, it syncs from the beginning again.

### Use case
This feature would be useful for large collections where syncing might fail due to connection issues or rate limiting. e.g. when something like this occurs:

```
WARNING  Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 5 seconds (try: 5/5)
ERROR    Error: Internal Server Error
ERROR    Error message: Internal server error. Please open a support issue and include your full API request and response, 
         including all headers.
ERROR    API didn't respond properly, script will abort now. Please try again later.
ERROR    Last call: plextraktsync.trakt.TraktApi.search_by_id(('2987341',), {'id_type': 'tmdb', 'media_type': 'episode'})
```

Syncing a large collection takes a very long time and it is frustrating to have to start from scratch whenever it fails.

### Workarounds

There only option is to restart the sync from the beginning

### Plan to implement

I don't have the necessary knowledge to provide an implementation, but given the information present in the log the information needed to create the checkpoint should be available

**Comment by glensc** [comment]
This isn't going to be implemented any time soon (too complex, low benefit, too specific).

As for the problem, I suggest figuring out the problematic id's and try to do something about them. Very likely is that if trakt is failing the id now, it will fail on retry as well not matter how many times you retry.

ps: separate bug reports for the errors, if it's PlexTraktSync related
