### ISSUE TITLE
Feature request: Sync plays for a 2nd and 3rd time

### ISSUE THREAD

**Issue by jmirodrigues** [Taxel/PlexTraktSync#1336]
### Feature description

When we play something on plex that has already been marked as seen on trakt, that 2nd (and others) play is not counted on trakt. I was wondering if the script could sync all plays to trakt, even on the already played media.

### Use case

Just keep track of all played media from my library.

### Workarounds

Maybe just check-in or mark as seen on trakt site

### Plan to implement

??

**Comment by glensc** [comment]
Duplicate. The `sync` command doesn't do rewatches. The `watch` command is able to.
