### ISSUE TITLE
Existing Shows not syncing to Trakt. Error shows "Skipping guid <PlexGuid:tvdb://...> not found on Trakt". 

### ISSUE THREAD

**Issue by m4urer** [Taxel/PlexTraktSync#1350]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Hi, I'm having issues with some shows that are not syncing to Trakt. 
I've checked the logs and they all show the same: **Skipping guid <PlexGuid:tvdb://...> not found on Trakt**

At first I thought that it was an issue with some shows that have both Spanish and English titles (The Boss and Stolen Cup) but as you can see I'm also having issues with NCIS, This Is Us or Murdoch Mysteries.

I've also checked Trakt and the shows are there (and I can sync their status with other platforms like Kodi/Trakt):
[https://trakt.tv/shows/the-boss-2022](https://trakt.tv/shows/the-boss-2022)
[https://trakt.tv/shows/the-stolen-cup](https://trakt.tv/shows/the-stolen-cup)

Is this an issue with my configuration or a bug?

Thanks in advance.

### Error trace / logs

```text
> 2023-01-10 09:01:02,591 WARNING[PlexTraktSync]:<Episode:35100:The-Boss-s01e01>: Skipping guid <PlexGuid:tvdb://9371037> not found on Trakt
> 2023-01-10 09:01:02,614 WARNING[PlexTraktSync]:<Episode:35101:The-Boss-s01e02>: Skipping guid <PlexGuid:tvdb://9371039> not found on Trakt
> 2023-01-10 09:01:11,351 WARNING[PlexTraktSync]:<Episode:35211:Murdoch-Mysteries-s16e11>: Skipping guid <PlexGuid:tvdb://9431209> not found on Trakt
> 2023-01-10 09:01:11,359 WARNING[PlexTraktSync]:<Episode:35211:Murdoch-Mysteries-s16e11>: Skipping guid <PlexGuid:imdb://tt23396926> not found on Trakt
> 2023-01-10 09:01:13,501 WARNING[PlexTraktSync]:<Episode:34815:NCIS-s20e01>: Skipping guid <PlexGuid:tvdb://9229801> not found on Trakt
> 2023-01-10 09:01:13,509 WARNING[PlexTraktSync]:<Episode:34815:NCIS-s20e01>: Skipping guid <PlexGuid:imdb://tt19310068> not found on Trakt
> 2023-01-10 09:01:13,659 WARNING[PlexTraktSync]:<Episode:35453:NCIS-s20e10>: Skipping guid <PlexGuid:tvdb://9445795> not found on Trakt
> 2023-01-10 09:01:16,692 WARNING[PlexTraktSync]:<Episode:35158:The-Stolen-Cup-s01e01>: Skipping guid <PlexGuid:tvdb://9371081> not found on Trakt
> 2023-01-10 09:01:16,729 WARNING[PlexTraktSync]:<Episode:35160:The-Stolen-Cup-s01e03>: Skipping guid <PlexGuid:tvdb://9371083> not found on Trakt
> 2023-01-10 09:01:16,784 WARNING[PlexTraktSync]:<Episode:35163:The-Stolen-Cup-s01e06>: Skipping guid <PlexGuid:tvdb://9371086> not found on Trakt
> 2023-01-10 09:01:17,539 WARNING[PlexTraktSync]:<Episode:30200:This-Is-Us-s05e02>: Skipping guid <PlexGuid:tvdb://7905559> not found on Trakt
> 2023-01-10 09:01:17,547 WARNING[PlexTraktSync]:<Episode:30200:This-Is-Us-s05e02>: Skipping guid <PlexGuid:imdb://tt13275494> not found on Trakt
```

### Expected behavior

all existing shows should sync to trakt

### Steps to reproduce the behavior

watched shows not syncing

### Install method

docker-compose

### Version

0.25.3

### Python Version

3.7

### Operating System and Version

Windows 10

**Comment by glensc** [comment]
Have you checked good practices section?
- https://github.com/Taxel/PlexTraktSync#good-practices

**Comment by twolaw** [comment]
+1

You need to populate external ids of not fund episodes on [tmdb](https://www.themoviedb.org/tv/128306-el-encargado/season/1/episode/1/edit?active_nav_item=external_ids) as explained in readme.

Or the easy way : change your Plex agent to `Plex TV Series` 😎

**Comment by m4urer** [comment]
I was already using Plex TV and Movies Agent but after I prioritized the TMBD over the TVDB Agent and scanned again those shows, it started syncing correctly.
Thanks for the quick reply!  It's now solved.
