### ISSUE TITLE
Can't connect to plex

### ISSUE THREAD

**Issue by PyroFD3S** [Taxel/PlexTraktSync#1386]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

fresh install of dockered plextraktsync
INFO     PlexTraktSync Version: 0.25.11                                                                                                                                
INFO     Python Version: 3.11.1 (main, Jan 18 2023, 00:49:22) [GCC 11.2.1 20220219]                                                                                    
INFO     Plex API Version: 4.13.2                                                                                                                                      
INFO     Trakt API Version: 3.4.19                                                                                                                                     
INFO     Cache Dir: /app/config                                                                                                                                        
INFO     Config Dir: /app/config                                                                                                                                       
INFO     Log Dir: /app/config                                                                                                                                          
INFO     Log File: /app/config/plextraktsync.log                                                                                                                       
INFO     Cache File: /app/config/trakt_cache.sqlite                                                                                                                    
INFO     Config File: /app/config/config.yml                                                                                                                           
INFO     Servers Config File: /app/config/servers.yml                                                                                                                  
INFO     Plex username: pyrofd3s@gmail.com                                                                                                                             
INFO     Trakt username: PyroFD3S                                                                                                                                      
INFO     Plex Server Name: default  

trying to get plex connected with plex-login command but get python errors:

### Error trace / logs

```text
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 18, in <module>
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/cli.py", line 25, in wrap
    cmd(*args, **kwargs)
  File "/app/plextraktsync/commands/plex_login.py", line 196, in plex_login
    login(username, password)
  File "/app/plextraktsync/commands/plex_login.py", line 200, in login
    if factory.has_plex_token():
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
```

### Expected behavior

connect to plex 

### Steps to reproduce the behavior

 docker-compose run --rm plextraktsync plex-login

### Install method

docker-compose

### Config file contents

```yaml
# Config File: /app/config/config.yml
cache:
  path: /app/config/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.25.11

### Python Version

3.11.1

### Operating System and Version

Ubuntu 18.04.6 LTS

**Comment by PyroFD3S** [comment]
rolling back to an older version seems to have fixed it

**Comment by glensc** [comment]
always include info what version you rolled back to. help other users as well not just yourself!
