### ISSUE TITLE
Unraid docker broken

### ISSUE THREAD

**Issue by steve1977** [Taxel/PlexTraktSync#1394]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

I am aware that Unraid is docker is not supported, but stil hoping to get some support here by the community?

Unfortunately, the docker for Unraid has stopped working. More details on the Unraid forum:

https://forums.unraid.net/topic/125763-help-me-get-plextraktsync-working-again/#comment-1218278

### Expected behavior

Should start up and work. It does not.

### Steps to reproduce the behavior

1. Install docker
2. Start it (then it fails)

### Install method

Unraid installation (not supported)

### Version

Don't know

### Python Version

Don't know

### Operating System and Version

Don't know

**Comment by glensc** [comment]
Fill in details of your error here rather than "Don't know", "No response". or use discussions.

**Comment by steve1977** [comment]
See below log when starting the docker. Afterwards, it just shuts down again, so I cannot start anything manually:

WARNING  plextraktsync without command is deprecated. Executing "plextraktsync  
         sync"                                                                  
INFO     PlexTraktSync [0.25.14]                                                
ERROR    (401) unauthorized; http://192.168.11.120:32400/                       
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    (401) unauthorized; http://172.17.0.1:32400/                           
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    No more methods to connect. Giving up.                                 
WARNING  plextraktsync without command is deprecated. Executing "plextraktsync  
         sync"                                                                  
INFO     PlexTraktSync [0.25.14]                                                
ERROR    (401) unauthorized; http://192.168.11.120:32400/                       
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    (401) unauthorized; http://172.17.0.1:32400/                           
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    No more methods to connect. Giving up.                                 
WARNING  plextraktsync without command is deprecated. Executing "plextraktsync  
         sync"                                                                  
INFO     PlexTraktSync [0.25.14]                                                
ERROR    (401) unauthorized; http://192.168.11.120:32400/                       
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    (401) unauthorized; http://172.17.0.1:32400/                           
         <html><head><script>window.location =                                  
         window.location.href.match(/(^.+\/)[^\/]*$/)[1] +                      
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>4
         01 Unauthorized</h1></body></html>                                     
ERROR    No more methods to connect. Giving up.                                 

** Press ANY KEY to close this window **

**Comment by glensc** [comment]
_why your post looks so weird, edit and add [code fence](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) around pastes._

Your plex login credentials are missing or incorrect. run `plextraktsync plex-login` in the container and finish the setup. and edit your bugreport to fill version to issue body.

**Comment by bruno-briner** [comment]
Unraid Docker working fine for me except for not being able to check for updates.

**Comment by glensc** [comment]
Original reporter answer given, and user has disappeared. others. create your own bug reports with your details.
