### ISSUE TITLE
Missing option to sync watchlist only

### ISSUE THREAD

**Issue by pterisaur** [Taxel/PlexTraktSync#1399]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

After reading the posted docs, it appears I should be able to run 
```
plextraktsync sync --sync watchlist
```
or
```
plextraktsync sync --sync=watchlist
```

...however I get an error when I attempt this:
```
Error: Invalid value for '--sync': 'watchlist' is not one of 'all', 'movies', 'tv', 'shows'.
```
There's seemingly no difference between "shows" and "tv" when I try each of them. What happened to the watchlist sync command?

### Expected behavior

I should be able to run a watchlist sync command.

### Steps to reproduce the behavior

plextraktsync sync --sync watchlist

### Install method

pipx

### Version

0.25.15

### Python Version

3.10.5

### Operating System and Version

macOS 12.6.2

**Comment by glensc** [comment]
works for me, are you sure you are using 0.25.15 version?

```
~/Library/Preferences/PlexTraktSync ➜ plextraktsync sync --sync=watchlist
INFO     PlexTraktSync [0.25.15]
Processing Plex watchlist 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30/30  [ 0:00:04 < 0:00:00 , 9 it/s ]
INFO     Updated watchlist in 4.2 seconds
INFO     Completed full sync in 5.0 seconds
~/Library/Preferences/PlexTraktSync ➜ plextraktsync sync --sync watchlist

INFO     PlexTraktSync [0.25.15]
Processing Plex watchlist 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30/30  [ 0:00:04 < 0:00:00 , 8 it/s ]
INFO     Updated watchlist in 4.2 seconds
INFO     Completed full sync in 5.2 seconds
~/Library/Preferences/PlexTraktSync ➜ plextraktsync --version
PlexTraktSync 0.25.15
~/Library/Preferences/PlexTraktSync ➜
```
