### ISSUE TITLE
No such command 'self-update'

### ISSUE THREAD

**Issue by downey-lv** [Taxel/PlexTraktSync#1444]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

self-update missing from the package since 0.22.3. Doesn't show up in --help either

When downgraded to 0.22.3 the command exists but throws a permission error for me, _pipx upgrade PlexTraktSync_ works fine. Might be just an issue for me or I'm assuming that's the reason why the command was removed. Probably just an update to README.md to just contain pipx upgrade needed then?

### Error trace / logs

```text
C:\Users\user>plextraktsync self-update
Usage: plextraktsync [OPTIONS] COMMAND [ARGS]...
Try 'plextraktsync --help' for help.

Error: No such command 'self-update'.
```

### Expected behavior

Runs the pipx upgrade command

### Steps to reproduce the behavior

plextraktsync self-update

### Workarounds

plextraktsync 0.22.3 was the latest that the command existed

### Install method

pipx

### Version

0.25.16

### Python Version

3.9.7

### Operating System and Version

Windows 11

**Comment by glensc** [comment]
the command is enabled if detects it's pipx installed:
- https://github.com/Taxel/PlexTraktSync/blob/22ae1ec9aa0d1b17ff115145c327317ab45b4b7e/plextraktsync/cli.py#L339-L340

- https://github.com/Taxel/PlexTraktSync/blob/22ae1ec9aa0d1b17ff115145c327317ab45b4b7e/plextraktsync/util/Factory.py#L182-L188
- https://github.com/Taxel/PlexTraktSync/blob/22ae1ec9aa0d1b17ff115145c327317ab45b4b7e/plextraktsync/util/packaging.py#L62-L72
- https://github.com/Taxel/PlexTraktSync/blob/22ae1ec9aa0d1b17ff115145c327317ab45b4b7e/plextraktsync/util/packaging.py#L39-L59

could be that program_name is incorrect or your pipx output changed, what is your pipx version?

**Comment by glensc** [comment]
start with pipx list output:

```
➜ pipx list --json | jq '.venvs|keys'  
[
  "cdhist",
  "plextraktsync",
  "plextraktsync@1404",
  "wssh"
]
```

**Comment by glensc** [comment]
so, it's program_name probably incorrect, the only thing you didn't check

**Comment by glensc** [comment]
@downey-lv can you debug what's program_name in your system?

**Comment by glensc** [comment]
reported dis-appeared. closing
