### ISSUE TITLE
Log in to Plex failed

### ISSUE THREAD

**Issue by yoanndelattre** [Taxel/PlexTraktSync#1490]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

When I run the sync command from Docker and have to connect to my Plex account, I get an error.

### Error trace / logs

```text
INFO     PlexTraktSync [0.26.5]
WARNING  Added default server to /app/config/servers.yml
Please enter your Plex username or e-mail: yoanndelattre21@gmail.com
If you have 2 Factor Authentication enabled on Plex you can append the code to your password below (eg. passwordCODE)
Please enter your Plex password:
Log in to Plex failed: '(429) too_many_requests; https://plex.tv/users/sign_in.xml '
```

### Expected behavior

I expected the connection to Plex to be successful.

### Steps to reproduce the behavior

1. Run this command : ```docker run -it --rm -v plextraktsync-config:/app/config ghcr.io/taxel/plextraktsync:latest sync``` 

### Install method

docker-compose

### Version

0.26.5

### Python Version

3.11.3

### Operating System and Version

Alpine Linux v3.16

**Comment by twolaw** [comment]
Some clues that could help :
- https://github.com/Taxel/PlexTraktSync/pull/1030
- https://github.com/Taxel/PlexTraktSync/discussions/1028

**Comment by yoanndelattre** [comment]
@twolaw I hadn't seen it, thanks for your reply.
