### ISSUE TITLE
Extra option to not create collection in Trakt?

### ISSUE THREAD

**Issue by ArnoutVerbeken** [Taxel/PlexTraktSync#15]
Hello,

I found this hidden gem and I am testing it out.  I wanted to ask you if there is a way to not initially sync the whole Plex library to the Trakt Collection.  Is that possible to be excluded?  I could not find it in the json file.

I actually just want to create Plex collections out of Trakt Lists.  If possible even with specify what Trakt list.  I think that should be possible with this, but I can't get past the initial sync to Trakt Collection (does a lot of time-outs)

Thanks!

**Comment by twolaw** [comment]
For that, in json file you can toggle `collection` to `false`.
In this script, sync collection is only a _from-Plex-to-Trakt_ action.

Then, if you want to create Plex lists from Trakt, in json file you can use `liked_lists` : it will the fetch Trakt lists you like on Trakt and create Plex list accordingly.
The same with `watchlist` setting to fetch your Trakt watchlist and create (keep updated if changed) this list on Plex.
And if you want to fetch some of your Trakt personal lists, you just have to like them on Trakt (thumbs up icon), they will be included in the liked_lists sync.
