### ISSUE TITLE
Watched episode not adding to Trakt

### ISSUE THREAD

**Issue by blackwater17** [Taxel/PlexTraktSync#1520]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Scrobbling to trakt doesn't work. It also doesn't update my watched history when I finish an episode. I think it was scrobbling before because I was using some other plugins for this purpose. I think it was the other plugin that doing the scrobbling. Now I removed all the other plex plugins and only installed this repo, and it doesn't even scrobble now.

### Expected behavior

It should update my watched history on trakt. Also it should scrobble when I watch something.

### Steps to reproduce the behavior

I didn't do anything odd. Just basic installation.
I installed plextraktsync with the pip command. Its installed (python version 3.7)
It asked me for plex username and password, I entered them. Then it run the sync operation, it scanned all my movie and show library. its done. 
Then somewhere around the installation it asked me to create a trakt app there. So I created my app, copied the code pasted there. Just basic instructions, nothing weird happened.
Installation done. Just to be sure I run plextraktsync sync again. Then I watched a show from browser (tried both app.plex.tv and the localhost url), it didn't scrobble, didn't update the plextraktsync.log file neither. No changes. The only time I see plextraktsync.log file changing is when I run the plextraktsync sync command. Other than that this file never changes when I watch an episode/movie etc.

### Inspect of problematic items

Its not about the media item I watch. I tried with multiple movies and shows. Not sure what should I put here.

### Install method

pipx

### Config file contents

Here: https://pastebin.com/vxgCVfyE

### Version

PlexTraktSync 0.26.8

### Python Version

Python 3.7.9

### Operating System and Version

Windows 11

**Comment by twolaw** [comment]
Did you watch it at least 80% of its duration ?

You can check your episodes scrobble status  with : https://api.trakt.tv/sync/playback

- https://trakt.docs.apiary.io/#reference/sync/playback/get-playback-progress

**Comment by blackwater17** [comment]
> 

Yeah, I watch 100% of it. No skipping, no faulty video files, nothing. Issue happens with every tv show, so its not related to file as well.
Another issue: Now I just opened an episode and quitted it, but according to trakt I'm still playing it. Progress bar is also moving on trakt, even though Plex not open anywhere in home. Its so weird.
Also I just tried again the issue looked like fixed, but then its not working again.
Its just so random. I already tried re-installing 3 times.

Additional info, sometimes I watch episodes from LG Plex app, and sometimes from PC. When installing this I choose the PC server, not the TV option. Just wanted to say, maybe it will help.
What would you recommend to me? Its just so random I don't even know what is the issue anymore :/

**Comment by twolaw** [comment]
Enable debug mode and watch an episode, then pastebin the debug log so we can dig it.

**Comment by blackwater17** [comment]
> Enable debug mode and watch an episode, then pastebin the debug log so we can dig it.

Nothing logs in the log file. It only logs stuff when I run the sync command on terminal. But when I watch something from TV Plex app or from browser, its not updated at all.

**Comment by twolaw** [comment]
Chek that your `watch` command runs with the Plex server your play films on.
Run Plex setup process again to be sure (command `plex-login`).

**Comment by blackwater17** [comment]
They are both same URLs, just checked. When I run the plex-login command I'm getting the following errors, is that normal:
<img width="761" alt="error" src="https://github.com/Taxel/PlexTraktSync/assets/37250588/2a2461bd-3236-431d-a1d3-bd1c7f252d1d">

**Comment by twolaw** [comment]
Why *no response* in **Config file contents** ?

**Comment by blackwater17** [comment]
I don't know what does this mean. What should I do exactly?

**Comment by twolaw** [comment]
You should show the content of your config file.

**Comment by twolaw** [comment]
It should be in the appropriate section of your first post.

Also, your **Steps to reproduce the behavior** is almost empty.
I can't reproduce because you don't even tell how you scrobble...

Also, when you say "it works", show the logs.

And **Inspect of problematic item** is empty too, fulfill it please.

**Comment by blackwater17** [comment]
Rewritten the first post.

**Comment by twolaw** [comment]
You don't run the 
**watch**  command?
Read the readme again.

**Comment by blackwater17** [comment]
Ok now I got it to work, thanks a lot. But do I have to run this watch command every time I restart my PC? (server is hosted on this PC) If so is there anything I can do for this? The codes in the installation doc seems like for linux systems, but I use windows.

**Comment by twolaw** [comment]
Explain how you got it to work. Be specific.

**Comment by blackwater17** [comment]
I just run the watch command as stated in the docs, (I was not doing this before)
And now it works. But yeah do I have to run this code every time I restart my PC?

**Comment by twolaw** [comment]
Yes. The code needs to be running if you want the scrobble to work.
