### ISSUE TITLE
Script fails to finish .env in BSD jail 12.2

### ISSUE THREAD

**Issue by Remnence** [Taxel/PlexTraktSync#153]
I am stuck in a first run loop while running this script in my BSD 12.2 plex jail on TrueNas. It creates the .env file and .pytrakt.json but the .env is always empty and the script starts over after authorizing on Trakt.

**Comment by Remnence** [comment]
Seems to be 0.5.0/master only I downgraded to the 0.4.1 release and it generated just fine.

**Comment by glensc** [comment]
Can you test https://github.com/Taxel/PlexTraktSync/pull/155
