### ISSUE TITLE
Endless Config Loop

### ISSUE THREAD

**Issue by gorgarp** [Taxel/PlexTraktSync#154]
![image](https://user-images.githubusercontent.com/7957736/112685807-17e88700-8e43-11eb-989c-10fffcdc7ac8.png)

**Comment by gorgarp** [comment]
As of this commit: https://github.com/Taxel/PlexTraktSync/commit/825d1fc52f1dc58e1233e3ce32aeaf616104a5ed

Ubuntu 20.04.

**Comment by glensc** [comment]
Duplicate https://github.com/Taxel/PlexTraktSync/issues/153

**Comment by glensc** [comment]
@gorgarp it's a merge commit, are you sure it's even that commit that is really at fault?

**Comment by glensc** [comment]
@gorgarp I rather guess this one may have gone wrong: https://github.com/Taxel/PlexTraktSync/pull/139/files

**Comment by glensc** [comment]
Can you test https://github.com/Taxel/PlexTraktSync/pull/155?
