### ISSUE TITLE
Freezes right after start4

### ISSUE THREAD

**Issue by jonasprokopf** [Taxel/PlexTraktSync#1547]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Hello,
I have tried running PlexTraktSync via the provided .bat file on Windows and by using the "docker-compose run --rm plextraktsync sync" command. In both cases this is as far as I get:
```
Microsoft Windows [Version 10.0.19044.3086]
(c) Microsoft Corporation. All rights reserved.

C:\Users\b1€r\Downloads\PlexTraktSync-0.26.10\PlexTraktSync-0.26.10>docker-compose run --rm plextraktsync sync
INFO     PlexTraktSync [0.26.10]
Please enter your Plex username or e-mail (): pi2mp3
If you have 2 Factor Authentication enabled on Plex you can append the code to your password below (eg.
passwordCODE)
Please enter your Plex password:



```
As you can see, I'm supposed to enter my password here, but none of my keystrokes are registered and the whole program freezes up. Unfortunately, I don't think I get even far enough for logs to show anything interesting. Or is there some other way I could log this than pasting plextraktsync.log from the "config" folder?

### Expected behavior

I want to enter my password

### Steps to reproduce the behavior

1. run docker-compose run --rm plextraktsync sync

### Workarounds

I'm sorry, I'm code illiterate and I don't really know how to downgrade. I can just download the repo and run commands.

### Install method

docker-compose

### Version

0.26.10

### Python Version

3.11.4

### Operating System and Version

Windows 10

**Comment by twolaw** [comment]
duplicate of #1201

**Comment by jonasprokopf** [comment]
> duplicate of #1201

I feel very stupid. I suggest that you make some indication for people that they are typing, because there was at least one other guy as stupid as me.
