### ISSUE TITLE
Feature request: Emby support

### ISSUE THREAD

**Issue by sanicki** [Taxel/PlexTraktSync#1612]
### Feature description
This script works beautifully to sync Plex and Trakt. Can it be modified to support Emby and Trakt syncing? 

### Use case

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

I have a small Plex server set up at home, with limited media. A friend with a more extensive media collection shared their Emby server with me.

I would like to sync my watch history between Emby and Plex through Trakt.

The only way I can find to sync Emby and Trakt is a [server-side plugin](https://github.com/MediaBrowser/trakt) which doesn't appear to support a multi-user environment.

### Workarounds

_Is there an existing workaround to accomplish this?_

Not that I can find.

### Plan to implement

_Are you interested in submitting a PR to implement this?_

Unfortunately not.

**Comment by twolaw** [comment]
This feature is out of scope.
You can fork to create **EmbyTraktSync** project.
