### ISSUE TITLE
Taxel: Change default branch to be main

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#162]
Problem: Requirement to have 1 review, slows down project development.

Solution: Use a different branch than `master` for development.

- EDIT[2021-03-25]: Decided to switch to git-flow model, where changes go to `develop` and releases from `master` branch: https://github.com/Taxel/PlexTraktSync/pull/160
- EDIT[2021-04-04]: will go with simple `main` for now, as I'm doing changes alone here.
- EDIT[2021-04-12]: set default branch to `0.7.x`, `0.6.x` (aka `main`) should be merged here: https://github.com/Taxel/PlexTraktSync/pull/209
- EDIT[2021-04-17]: set default branch to be `main`

refs:
- https://github.com/Taxel/PlexTraktSync/pull/142#issuecomment-806587666
- https://github.com/Taxel/PlexTraktSync/pull/159#issuecomment-811482697
- https://github.com/Taxel/PlexTraktSync/pull/159#issuecomment-813071791

@Taxel please update project settings to reflect new changes.

**Comment by Taxel** [comment]
@glensc I disabled the branch protection for master and switched the default branch to 0.7.x. Would it make more sense to merge 0.7.x into `main` and using that as the default branch?

**Comment by glensc** [comment]
@Taxel hello! :)

I've made a mess here, so let me provide a plan on how to proceed.

**Comment by glensc** [comment]
I actually like the two branch mechanism here, provides some kind of stability and developer releases procedure.

so, right now:
1. merge `main` -> `master`: https://github.com/Taxel/PlexTraktSync/pull/209 this is named 0.6.x branch
1. merge `0.7.x` -> `master`: https://github.com/Taxel/PlexTraktSync/pull/248, this is named 0.7.x branch
1. create branches `0.5.x`, `0.6.x`, `0.7.x` from their last state. they will be left for bugfixes only
1. delete `main` branch.

altho I prefer merging to 0.8.x and one new version start merging to 0.9.x branch, but this procedure would require to update default branch from time to time. it's tedious and requires owner permission in the repository, which I don't have.

and for the future:
1. re-create branch `main` from `0.7.x`, set it as the default branch
1. create a branch from `main` for `0.8.x` development, make new developments go there.
1. delete `master` branch

time to time when development is complete, create merge up pull request (like #209, #248):
1. create a merge request to merge 0.8.x to `main`
2. create a new branch 0.9.x from `main`

**Comment by glensc** [comment]
@Taxel wdyt? is it clear? if no objections I will proceed with the "right now" items.

**Comment by glensc** [comment]
@Taxel I realized that the plan has a conflict with the current default branch (0.7.x), github may do something funny, for example close all pull requests.

so, I'll merge #209, and you set the default branch back to `main`, but not before `#209` is merged.

**Comment by glensc** [comment]
@Taxel merged #209, can you set the default branch to be `main` now, so could proceed with this plan:
- https://github.com/Taxel/PlexTraktSync/issues/162#issuecomment-821784403

sorry for the mess. I'm trying to figure out myself too how this should work :)

**Comment by glensc** [comment]
And as I guessed, GitHub still did something funny. when #209 was merged, all other PR's merging to `main` were closed as the `main` branch was deleted:
- https://github.com/Taxel/PlexTraktSync/pull/200

**Comment by Taxel** [comment]
@glensc default branch is now main.

**Comment by glensc** [comment]
All done!

I guess should update documentation, re-opened PR for that:
- https://github.com/Taxel/PlexTraktSync/pull/160
