### ISSUE TITLE
Dependabot updates have stopped?

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#1637]
The last dependabot pull request is from a month ago:
- https://github.com/Taxel/PlexTraktSync/pull/1622

Doesn't seem right.

**Comment by glensc** [comment]
I don't see any options to check project settings, @simonc56, do you?

@Taxel can you perhaps make me and @simonc56  (formerly @twolaw) admins here, so we can manage such problems?

**Comment by glensc** [comment]
Seems dependency updates are back:
- https://github.com/Taxel/PlexTraktSync/pulls?q=label%3Adependencies

i.e.:
- https://github.com/Taxel/PlexTraktSync/pull/1645
- ...

what changed?

**Comment by glensc** [comment]
74bca5a2: 3 more updates to go:

```
➜ pip list --outdated            
Package          Version Latest Type
---------------- ------- ------ -----
PlexAPI          4.15.4  4.15.6 wheel
requests-cache   1.1.0   1.1.1  wheel
websocket-client 1.6.4   1.7.0  wheel
```

- https://superuser.com/questions/259474/find-outdated-updatable-pip-packages/588422#588422

**Comment by glensc** [comment]
waiting for pytrakt update:
- https://github.com/glensc/python-pytrakt/pull/34
- https://github.com/glensc/python-pytrakt/releases/tag/3.4.25

it's been 2 days since the release...

**Comment by glensc** [comment]
@Taxel can you add more admins to the project?
- https://github.com/Taxel/PlexTraktSync/issues/1637#issuecomment-1830827759

**Comment by simonc56** [comment]
> I don't see any options to check project settings, @simonc56, do you?

No, I don't see the settings page.

**Comment by glensc** [comment]
Submitted github support ticket
- https://support.github.com/ticket/personal/0/2518454 (private, accessible only by me)

**Comment by glensc** [comment]
Updates have appeared now:
- https://github.com/Taxel/PlexTraktSync/pull/1711
- https://github.com/Taxel/PlexTraktSync/pull/1710

**Comment by glensc** [comment]
Support answered that dependabot runs only on weekdays. Doh!

> The daily schedule only runs on weekdays, so would not have run the last two days (documented [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)). For last Friday, it would probably come down to timing of when the release happened, when Dependabot ran, and if the API returns were updated immediately on release.

**Comment by glensc** [comment]
There's this view available:
- https://github.com/Taxel/PlexTraktSync/security
  - https://github.com/Taxel/PlexTraktSync/security/dependabot
