### ISSUE TITLE
Feature request: Option for clear-collections to only remove items not in Plex's library

### ISSUE THREAD

**Issue by kvl19** [Taxel/PlexTraktSync#1644]
### Feature description
Would be great if possible to have the option to remove items that are in Trakt's collection but not in Plex's library

### Use case

User has Movie A In Plex's library, and in Trakt's Collection.
User deletes Movie A from Plex's library
User run `Plextraktsync clear-collections --remove-items-not-in-library`
Expected Result: Movie A should be removed from Trakt's Collection.

**Comment by simonc56** [comment]
Duplicate of #374
