### ISSUE TITLE
Feature request: Watch_status priority

### ISSUE THREAD

**Issue by pashashocky** [Taxel/PlexTraktSync#1668]
### Feature description
I'd like to specify priority of `watched_status` between trakt and plex. With certain episodes in series you sometimes want to have a primary source of truth for which is watched. If both are marked watched and I unwatch it in Plex, I'd like to also update trakt to unwatched instead of syncing plex back to watched. 

### Use case
Falling asleep and then updating/reversing plex watch status.

### Workarounds
Having to unwatch in both trakt and plex. 

### Plan to implement
MMaybe..? Are there dates to when watch status updates on both plex/trakt?

**Comment by pashashocky** [comment]
@simonc56 thanks for pointing it out, I was unaware, I scrolled and read through #1080, but it's unclear if you have plans to work on the feature or are just unsure how to implement it from trakt -> plex?

imo plex -> trakt would satisfy most users. how do we get this in?

**Comment by glensc** [comment]
for the falling asleep cure, I visit my watch history:
- https://trakt.tv/users/me/history

remove items I didn't want to watch. and then do the same in Plex.

**Comment by simonc56** [comment]
duplicate -> closing
