### ISSUE TITLE
Synology NAS keep popping up "Container plextraktsync stopped unexpectedly. Go to Container Manager for more information." notifications

### ISSUE THREAD

**Issue by Shasoosh** [Taxel/PlexTraktSync#1701]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

I'm running the container using the docker compose shared and once sync is finished, my synology NAS is sending me a notification with "Container plextraktsync stopped unexpectedly. Go to Container Manager for more information."

There are no errors and the syncs completes successfully but it seems that container closes abruptly. 

### Expected behavior

Stop the container without getting a notification.

### Steps to reproduce the behavior

Docker compose on synology NAS will reproduce this.

### Install method

docker-compose

### Version

0.27.16

### Python Version

3.12.1

### Plex Server Version

v.1.32.8.7639-fb6452ebf

### Operating System and Version

DSM 7.2.1-69057 Update 3

**Comment by glensc** [comment]
Not reproducible. Provide logs and details from your system. How we're supposed to help if you provide no info other than just your word? Show your problem!

**Comment by Shasoosh** [comment]
Sorry, other than the warnings it seemed like everything is working as it should. 
I'm using a DS920+
DSM 7.2.1-69057 Update 3
Debug is turned on in the config.yml

Here's the log: (Please let me know if you need anything else.)

> 2024/01/07 21:47:48	stdout	INFO     Completed full sync in 14.1 seconds                                    
> 2024/01/07 21:47:48	stdout	INFO     Updated liked list in 0.0 seconds                                      
> 2024/01/07 21:47:48	stdout	Syncing show ratings 100% ━━━━━━━━━━━━ 42/42  [ 0:00:00 < 0:00:00 , 3,437 it/s ]
> 2024/01/07 21:47:47	stdout	INFO     סדרות ילדים processed in 3.0 seconds                                   
> 2024/01/07 21:47:47	stdout	Processing סדרות ילדים 100% ━━━━━━━━━━━━━━━━ 8/8  [ 0:00:03 < 0:00:00 , 2 it/s ]
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12523> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e52/Episode 52 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12522> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e51/Episode 51 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12521> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e50/Episode 50 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12520> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e49/Episode 49 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12519> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e48/Episode 48 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12518> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e47/Episode 47 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12517> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e46/Episode 46 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12516> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e45/Episode 45 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12515> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e44/Episode 44 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12514> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e43/Episode 43 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12513> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e42/Episode 42 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12512> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e41/Episode 41 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12511> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e40/Episode 40 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12510> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e39/Episode 39 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12509> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e38/Episode 38 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12508> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e37/Episode 37 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12507> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e36/Episode 36 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12506> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e35/Episode 35 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12505> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e34/Episode 34 (None): Skipping                      
> 2024/01/07 21:47:47	stdout	         <PlexGuid:local://12504> because provider local has no external Id     
> 2024/01/07 21:47:47	stdout	WARNING  הקוסם מארץ עוץ/s01e33/Episode 33 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12503> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e32/Episode 32 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12502> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e31/Episode 31 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12501> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e30/Episode 30 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12500> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e29/Episode 29 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12499> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e28/Episode 28 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12498> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e27/Episode 27 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12497> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e26/Episode 26 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12496> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e25/Episode 25 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12495> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e24/Episode 24 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12494> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e23/Episode 23 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12493> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e22/Episode 22 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12492> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e21/Episode 21 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12491> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e20/Episode 20 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12490> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e19/Episode 19 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12489> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e18/Episode 18 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12488> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e17/Episode 17 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12487> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e16/Episode 16 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12486> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e15/Episode 15 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12485> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e14/Episode 14 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12484> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e13/Episode 13 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12483> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e12/Episode 12 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12482> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e11/Episode 11 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12528> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e10/Episode 10 (None): Skipping                      
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12480> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e09/Episode 9 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12479> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e08/Episode 8 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12478> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e07/Episode 7 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12530> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e06/Episode 6 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12476> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e05/Episode 5 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12475> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e04/Episode 4 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12474> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e03/Episode 3 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12473> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e02/Episode 2 (None): Skipping                       
> 2024/01/07 21:47:46	stdout	         <PlexGuid:local://12472> because provider local has no external Id     
> 2024/01/07 21:47:46	stdout	WARNING  הקוסם מארץ עוץ/s01e01/Episode 1 (None): Skipping                       
> 2024/01/07 21:47:45	stdout	         found on Trakt                                                         
> 2024/01/07 21:47:45	stdout	WARNING  הדרדסים/s00e06/Intro (2021): Skipping <PlexGuid:tvdb://4571756> not    
> 2024/01/07 21:47:44	stdout	INFO     סדרות processed in 3.9 seconds                                         
> 2024/01/07 21:47:44	stdout	Processing סדרות 100% ━━━━━━━━━━━━━━━━━━━ 35/35  [ 0:00:03 < 0:00:00 , 13 it/s ]
> 2024/01/07 21:47:40	stdout	INFO     סרטים processed in 0.7 seconds                                         
> 2024/01/07 21:47:40	stdout	Processing סרטים 100% ━━━━━━━━━━━━━━━━━━ 64/64  [ 0:00:00 < 0:00:00 , 342 it/s ]
> 2024/01/07 21:47:40	stdout	INFO     סרטי ילדים processed in 4.2 seconds                                    
> 2024/01/07 21:47:40	stdout	Processing סרטי ילדים 100% ━━━━━━━━━━━ 199/199  [ 0:00:04 < 0:00:00 , 142 it/s ]
> 2024/01/07 21:47:34	stdout	INFO     Sync Show sections: ['סדרות', 'סדרות ילדים']                           
> 2024/01/07 21:47:34	stdout	INFO     Sync Movie sections: ['סרטי ילדים', 'סרטים']                           
> 2024/01/07 21:47:34	stdout	INFO     PlexTraktSync [0.27.15]       
> 
> 
>

**Comment by glensc** [comment]
unfortunately, that is still not useful. how are you invoking the command? how you obtained the logs? seems to be log of different runs? also you said you enabled debug, but not even shared debug logs.

**Comment by Shasoosh** [comment]
I'm not invoking a command, I just start the container using the Synology DSM UI or via SSH `docker-compose up -d`.
The logs are from inside the container via Portainer.
I've just realised that a log file is created with DEBUG. I'm uploaded it here: https://pastebin.com/FhUmX2MC

**Comment by glensc** [comment]
you can upload text files to github issue. drag, drop or select them. be sure to use supported extension like .txt
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by glensc** [comment]
where is that "Container plextraktsync stopped unexpectedly" appearing? your compose file is configured to run "sync" command. that will exit process once sync is complete.what does docker inspect say for the exited container?  run the command without `-d`, what happens then?

**Comment by Shasoosh** [comment]
@glensc In your first comment  you wrote "Not reproducible" so I was under the impression that you are also on Synology DSM. 
It could be an OS thing altough I had containrs that did short tasks and didn't produce that notification.

<img width="269" alt="image" src="https://github.com/Taxel/PlexTraktSync/assets/2679978/909f41fd-9d70-4f04-ab04-a65d942c71f6">

It shows up on the Synology OS, also sends an email about it. Unfortunately there's no way for me to disable these just for one container. Disabling these alerts would mean stop getting alerts about containers that stopped. 

Running the command without `-d` will put out `plextraktsync exited with code 0`

**Comment by Shasoosh** [comment]
`docker run  -d alpine sh -c "sleep 10"` doesn't produce the notification.

**Comment by glensc** [comment]
or adjust "sleep 10" with approximate time the plextraktsync container ran? I don't see why would it consider unexpected close if it exited with 0.

also show `docker inspect` of the container that pop up the notification. be sure not to run with `--rm`. should be in `docker ps -a` list.

**Comment by Shasoosh** [comment]
[docker inspect.txt](https://github.com/Taxel/PlexTraktSync/files/13865110/docker.inspect.txt)

It seems that for `docker-compose run --rm plextraktsync sync` I will not get the alert
but for `docker start -i plextraktsync` (an existing container) the alert will show. 
Does that make any sense to you?

**Comment by glensc** [comment]
Nothing suspicous in inspect output. I personally don't use `docker start`, so not sure what it does. but guessing, if you omit -i, does it behave differently?

if you don't want to re-create container for next run, you could keep the container "up" by having it run "sleep infinity" command, and then execute plextraktsync commands with `docker exec`.

**Comment by Shasoosh** [comment]
Thanks for the help. It behaves the same without the `-i`.
I'll try the `sleep infinity` solution.

**Comment by glensc** [comment]
Don't forget to close issue and post solution for other users.

**Comment by Shasoosh** [comment]
Couldn't figure out this beaviour. 

`docker-compose up -d` -> No alert
`docker start plextraktsync` -> No alert
run container from the UI -> Alert
Then again
`docker start plextraktsync` -> Alert (??)

I've recreated the container and now runs it only from the scheduler using `docker start plextraktsync` - No alerts so far.
If the alerts will return I'll use `docker-compose run --rm plextraktsync sync` which never showed me the alert.
