### ISSUE TITLE
Missing libbsd.so.0 on latest docker image

### ISSUE THREAD

**Issue by foux** [Taxel/PlexTraktSync#1726]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

On docker image v0.28.3 (or latest tag), the docker image is missing libbsd.so.0 resulting on a crash of the image with the following message : 
```
Error loading shared library libbsd.so.0
```

### Error trace / logs

```text
Error loading shared library libbsd.so.0
```

### Expected behavior

The docker image should launch

### Steps to reproduce the behavior

1. Pull `ghcr.io/taxel/plextraktsync:0.28.3`
2. Launch the docker container

### Inspect of problematic items

```text
N.A
```

### Workarounds

Go back to version 0.28.2

### Install method

docker-compose

### Config file contents

```yaml
N.A
```

### Version

0.28.3

### Python Version

N.A

### Plex Server Version

N.A

### Operating System and Version

Docker

**Comment by glensc** [comment]
Broken from https://github.com/Taxel/PlexTraktSync/pull/1712
