### ISSUE TITLE
Internal server error with 0.28.5

### ISSUE THREAD

**Issue by Njur** [Taxel/PlexTraktSync#1742]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Hi after running a new scan I get this error, it normally runs fine and works for movies, but crashes on shows.
Error message: Internal server error. Please open a support issue and  
         include your full API request and response, including all headers.     
ERROR    API didn't respond properly, script will abort now. Please try again   
         later.                                                                 
ERROR    Last call: plextraktsync.trakt.TraktApi.search_by_id(('3042827',),     
         {'id_type': 'tmdb', 'media_type': 'episode'})                       

### Expected behavior

It normally runs fine.

### Steps to reproduce the behavior

Tried running several times.

### Install method

docker-compose

### Version

0.28.7

### Python Version

3.12.1

### Plex Server Version

4.15.7

### Operating System and Version

Linux

**Comment by glensc** [comment]
Try downgrade, and give the exact version it got broken.

**Comment by glensc** [comment]
So, the error says it can't get response from trakt

```
ERROR API didn't respond properly, script will abort now. Please try again
later.
ERROR Last call: plextraktsync.trakt.TraktApi.search_by_id(('3042827',),
{'id_type': 'tmdb', 'media_type': 'episode'})
```

this should correspond to:
- https://trakt.tv/search/tmdb/3042827?id_type=episode

which shows result for two items, but they both link to:
  -  https://trakt.tv/shows/liaison/seasons/1/episodes/1 

<img width="398" alt="image" src="https://github.com/Taxel/PlexTraktSync/assets/199095/083e0521-1c5c-4b2b-b798-52163e3a2ebe">


also, the the api call indeed gives 500:

```
curl -sSf --header 'Content-Type: application/json' --header 'trakt-api-version: 2' --header 'trakt-api-key: xxx' --header 'Authorization: Bearer xxx' 'https://api.trakt.tv/search/tmdb/3042827?id_type=episode' -i
```

```
HTTP/2 500 
date: Mon, 15 Jan 2024 20:17:12 GMT
content-type: application/json
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
x-pagination-page: 1
x-pagination-limit: 10
expires: Tue, 16 Jan 2024 04:17:09 GMT
x-pagination-page-count: 1
x-pagination-item-count: 3
cache-control: public, max-age=28800
x-error-message: Internal server error. Please open a support issue and include your full API request and response, including all headers.
vary: Accept-Encoding
x-ratelimit: {"name":"AUTHED_API_GET_LIMIT","period":300,"limit":1000,"remaining":999,"until":"2024-01-15T20:20:00Z"}
x-request-id: e307d0d2-9809-4ae7-a6d4-255a44ce6ec3
x-runtime: 2.662518
cf-cache-status: MISS
server: cloudflare
cf-ray: 8460ccf0ff5e09b7-ARN
alt-svc: h3=":443"; ma=86400
```

as the error says, it should be reported to trakt support.

**Comment by glensc** [comment]
don't forget to post feedback you get from trakt support.

**Comment by glensc** [comment]
It will not get magically fixed if the problem is with trakt site. you need to report it there.

**Comment by G4Zz0L1** [comment]
Sorry, I didn't have much time this week.
I will try to report the error to Trakt and let you know.

**Comment by glensc** [comment]
And you can reopen the issue yourself if needed.

**Comment by lostb1t** [comment]
the sideeffect of this is that the whole script gets a aborted. Would be nice if it can log a warning/error and continue to the next item

**Comment by glensc** [comment]
You could remove match for the whole show in plex, then it would not attempt to update with trakt.

In fact, maybe fix match actually improves the situation?

**Comment by lostb1t** [comment]
yeah im currently fixing my matches to see if it resolves it

**Comment by G4Zz0L1** [comment]
It should be fixed here https://github.com/trakt/api-help/issues/435
It also suggests a fix for the url we call with this

**Comment by glensc** [comment]
you should had linked this discussion to that bug report, it was already determined here that there are duplicate results for same id. would had saved them some research time!
