### ISSUE TITLE
Trakt API Deprecate

### ISSUE THREAD

**Issue by keeper2k** [Taxel/PlexTraktSync#1793]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

https://twitter.com/traktapi/status/1753116197229670524

The API host name http://api-v2launch.trakt.tv will be removed on February 1. 

This has been deprecated since 2017. This will only affect very old apps and they need to use http://api.trakt.tv to continue working beyond February 1.

The old [http://api-v2launch.trakt.tv](https://t.co/9TYHCeYzjb) end point will be removed today. Please use [http://api.trakt.tv](https://t.co/0mENbHo7Uq) instead.

INFO     PlexTraktSync [0.26.9]
INFO     Sync Show sections: ['SERIES']
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f57b1050>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 1 seconds (try: 1/5)

### Steps to reproduce the behavior

docker-compose run --rm plextraktsync

### Error trace / logs

```text
INFO     PlexTraktSync [0.26.9]
INFO     Sync Show sections: ['SERIES']
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f57b1050>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 1 seconds (try: 1/5)
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f57b0910>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 2 seconds (try: 2/5)
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f57827d0>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 3 seconds (try: 3/5)
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f57f1490>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 4 seconds (try: 4/5)
WARNING  HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f5807e90>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)")) for
         plextraktsync.trakt.TraktApi.search_by_id(), retrying after 5 seconds (try: 5/5)
ERROR    Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url:
         /search/tmdb/114461?type=show (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object
         at 0x7f84f5816290>: Failed to resolve 'api-v2launch.trakt.tv' ([Errno -2] Name does not resolve)"))
ERROR    API didn't respond properly, script will abort now. Please try again later.
ERROR    Last call: plextraktsync.trakt.TraktApi.search_by_id(('114461',), {'id_type': 'tmdb', 'media_type':
         'show'})
```

### Expected behavior

Explain in X (Twitter)

### Install method

docker-compose

### Config file contents

```yaml
version: "3"
services:
  scheduler:
    image: mcuadros/ofelia:latest
    restart: always
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 1h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
```

### Version

0.26.9

### Python Version

3.11.4

### Plex Server Version

1.32.8.7639 

### Operating System and Version

DSM 7.2.1-69057 Update 3

**Comment by th12289** [comment]
Hello, 

i think this is already fixed. 

Just go into your folder with docker-compose.yml file.

Type: docker compose pull
Type docker compose up -d

Should work again. 
I had the same.

**Comment by glensc** [comment]
Duplicate: https://github.com/Taxel/PlexTraktSync/issues/1787

that issue is even pinned!

**Comment by glensc** [comment]
neither of these are actually true:

-  I have checked if identical issue already exists
- I have tried downgrading to find version that can be used as a workaround

and 0.26.9 is very old version.
