### ISSUE TITLE
Bad Request 401

### ISSUE THREAD

**Issue by xudonymous** [Taxel/PlexTraktSync#18]
Been getting the following error when it comes to syncing playlists: 

`BadRequest (401) unauthorized http://plex.mydomain.com/library; <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>`

For reference, I'm using Cloudbox install instance of Plex, etc. 

Is there a setting I need to tinker with in order to get this to work?

Thanks so much!

**Comment by desigi** [comment]
A late reply, for what it's worth, but I got it to work by disabling secured connections in plex. Settings -> Server -> Network and change to disabled
