### ISSUE TITLE
Existing Trakt ratings are set to the same value and with a new date if a rating with the same value exist in Plex

### ISSUE THREAD

**Issue by SebbeJohansson** [Taxel/PlexTraktSync#1805]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Running the script with the default config file causes all ratings in Trakt with the same value as in Plex to have a new date set as when it was first run. This is not ideal for historical references.
For me personally this means that all the dates for any ratings I've done for the last 10 years are now wrong.
![image](https://github.com/Taxel/PlexTraktSync/assets/5083273/387ae971-abe4-4bc5-8e25-158b158ab968)

This problem is probably only a thing if you have the same rating set in both applications either manually or by a different application/install of the same application.

### Steps to reproduce the behavior

1. Setup the script with docker.
2. Go through login and authentication against both trakt and plex.
3. Run the script with `docker-compose run --rm plextraktsync sync`
4. Check the ratings on trakt.
5. Profit.

### Expected behavior

I expect only new ratings to update the date. If the rating is set to the same rating as it is already in trakt it makes no sense to re-set it.

### Workarounds

The only option for me right now is to NOT sync ratings at all to trakt.

### Install method

docker-compose

### Config file contents

```yaml
Default config.
```

### Version

0.28.18

### Python Version

3.12.2

### Plex Server Version

1.32.8.7639-fb6452ebf,

### Operating System and Version

Ubuntu 20.04

**Comment by glensc** [comment]
didn't know you can submit date when adding rating... does trakt api support it?

**Comment by simonc56** [comment]
Indeed, Trakt API have `rated_at` value when adding a rating.
- https://trakt.docs.apiary.io/#reference/sync/add-ratings/add-new-ratings

```json
  "movies": [
    {
      "rated_at": "2014-09-01T09:10:11.000Z",
      "rating": 5,
      "title": "Batman Begins",
      "year": 2005,
      "ids": {
        "trakt": 1,
        "slug": "batman-begins-2005",
        "imdb": "tt0372784",
        "tmdb": 272
      }
    },
    {
      "rating": 10,
      "ids": {
        "imdb": "tt0000111"
      }
    }
  ]
```

**Comment by glensc** [comment]
this app doesn't send the date, trakt just assumes current date. i have not looked does trakt api support sending date.

**Comment by SebbeJohansson** [comment]
@glensc yes it does. @simonc56 included the whole body that you can send before and that includes "rated_at".

**Comment by glensc** [comment]
Now the second part needs to support it as well. Does plex offer date when rating was made?

**Comment by SebbeJohansson** [comment]
@glensc I have no idea. I took a quick look in PyTrakt and found this: https://github.com/moogar0880/PyTrakt/blob/8a6d4f168a858447014fb4c2c0efceb47b30ebb7/trakt/sync.py#L40-L55

For me its just down to trakt supporting it. Plex doesn't display the ratings in a chronological order, so its not a big deal (for me) if plex doesn't have the correct date.
Trakt:
![image](https://github.com/Taxel/PlexTraktSync/assets/5083273/0c7fe6ab-3187-4e5b-b4d0-5d0f8bc86f9c)
Plex:
![image](https://github.com/Taxel/PlexTraktSync/assets/5083273/e18801e9-5cfe-4ad2-85d0-d49cbee8819a)

**Comment by glensc** [comment]
@SebbeJohansson your response does not make any sense. what date would you send to trakt then if plex doesn't provide rating date? current date? but that's the existing behaviour already!

**Comment by SebbeJohansson** [comment]
@glensc Plex does have dates, it just doesn't display it anywhere. Sorry I wasn't clear.

**Comment by glensc** [comment]
You can try this PR at some point:
- https://github.com/Taxel/PlexTraktSync/pull/1821

I could not test myself as trakt.tv seems to have availability issues.

**Comment by glensc** [comment]
> Expected behavior
> 
> I expect only new ratings to update the date. If the rating is set to the same rating as it is already in trakt it makes no sense to re-set it.

In fact. this app does not update rating if rating is already in sync:
- https://github.com/Taxel/PlexTraktSync/blob/9d34003cd43d4b8c5770e9113b85b1a2093971b7/plextraktsync/sync.py#L125-L126

so, you could sync one way first: trakt to plex, then it will not overwrite the historic values.

**Comment by SebbeJohansson** [comment]
Could it be worth it to have a warning or something similar? I doubt I'm the only trakt user who cares about their dates and historical data.

**Comment by glensc** [comment]
Warning about what?

**Comment by glensc** [comment]
Um, why bother? or you are saying that the same can happen after the PR I created? Did you test it?

**Comment by glensc** [comment]
Um, why bother? or you are saying that the same can happen after the PR I created? Did you test it?

**Comment by glensc** [comment]
Um, why bother? or you are saying that the same can happen after the PR I created? Did you test it?

**Comment by glensc** [comment]
and again: this app does not overwrite ratings that are already there with same value (I linked you exact code that skips). so overwrite can only happen if your plex had different values. it's expected to overwrite as in default config plex has priority. if plex did not have ratings, there would not be any ratings present to sync to trakt.

are you saying something else happened?

**Comment by SebbeJohansson** [comment]
Haven't been able to test the PR. But if you think that it fixes the issue then I guess it's no need to add any docs about it. Just sounded like it might take a long time until the code is in the app, while a change to the Readme takes just 2 minutes. 

My plex had no rating at all when I synced with default settings, while trakt had thousands. This has happened twice for me with two different installs and plex accounts. So I'm not convinced that what you think is true. Sadly Im not gonna be able to test with fresh accounts again for some time.

**Comment by glensc** [comment]
I myself create backup with this tool:
- https://github.com/fuzeman/trakt-tools

luckily I never needed it to restore anything, so I'm not sure how to use the backup :)

**Comment by glensc** [comment]
@SebbeJohansson regarding warning, sure, send a pr if it can cause overwrite, and then can discuss how can it be fixed
