### ISSUE TITLE
Feature request: Config per library

### ISSUE THREAD

**Issue by SebbeJohansson** [Taxel/PlexTraktSync#1808]
### Feature description
A way to have different settings per library as to allow for syncing only specific things in specific libraries.

### Use case

I want to be able to only sync the collection status from plex to trakt in one specific library, but sync everything for all other libraries.

### Workarounds

I guess a way to do this is to have two separate docker-compose containers, but that's not ideal for me.

### Plan to implement

Not currently.

**Comment by glensc** [comment]
this is already there, just nobody wants to document anything:
- https://github.com/Taxel/PlexTraktSync/pull/1569

it has "docs needed" label

**Comment by glensc** [comment]
> I guess a way to do this is to have two separate docker-compose containers, but that's not ideal for me.

you could also have two different Servers in same servers config

**Comment by SebbeJohansson** [comment]
@glensc heh... I should have figured that it was already a thing. I will look into documenting it. Closing.

**Comment by glensc** [comment]
Use `--server=xxx` to set what server to use. No need to login or anything.

**Comment by SebbeJohansson** [comment]
Hmmm okay I'll give it a try. Thanks!

**Comment by SebbeJohansson** [comment]
I wasnt sure on how its recommended to use ofilia with this kind of a server, but I managed to get it to work atleast.
