### ISSUE TITLE
Ratings syncing is broken.

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#182]
In my opinion, the whole ratings syncing is broken.

- Plex has a float value, say `8.6`
- Trakt has an integer value (1 to 10), so `8.6` is synced as `8`
- In the next iteration, the rating is again synced even if it has not really changed.

And in fact, I don't know where Plex the rating is set, visually it's only 5 stars, but the value set by API does not change that.

# Plex UI

![image](https://user-images.githubusercontent.com/199095/113620331-de91f180-9662-11eb-92e7-0c74e47c96c4.png)

# Trakt UI

![image](https://user-images.githubusercontent.com/199095/113620418-f7020c00-9662-11eb-878d-8f8a887c5637.png)

_Originally posted by @glensc in https://github.com/Taxel/PlexTraktSync/issues/180#issuecomment-813617808_

**Comment by twolaw** [comment]
> And in fact, I don't know where Plex the rating is set, visually it's only 5 stars, but the value set by API does not change that.

This is the average audience rating fetched from scraping (TMDB, IMDB,...), not the user rating.

From Plex xml you can find 3 differents ratings for a movie :
`rating="8.0" audienceRating="9.5" userRating="6.0"`

**Comment by glensc** [comment]
What's even worse, is that I have not rated any Plex movies at all. But debugging with IDE shows I have Movie ratings in Plex and now it tries to sync that nonsense to Trakt.

Where the `userRating` can be set from Plex? only via API?

**Comment by twolaw** [comment]
`userRating` is related to the UI with 5 stars and multiplied by 2 to be a x/10 value.

**Comment by glensc** [comment]
@twolaw can you show the `userRating` related to the UI? You seem to be giving conflicting information. First, you said the stars are related to scraping, now you say it's related to user rating. what then?

**Comment by glensc** [comment]
@twolaw where is that multiplication by 2? I don't see it in the main.py:

https://github.com/Taxel/PlexTraktSync/blob/ad883a8a3885e5be468794b21192a3def5bc765f/plex_trakt_sync/main.py#L97-L130

**Comment by twolaw** [comment]
It seems to be like that :
- `userRating` = rating by Plex user, x/5 stars in UI multiplied by 2 (it means a 3 stars is stored as a 6.0 rating in Plex)
- `rating` = rating by scraped source, fetched from the `Ratings Source` you setup in your plex agent (Rotten Tomatoes, IMDB, TMDB,...)
- `audienceRating ` = rating by audience of the scraped source, fetched from the `Ratings Source` you setup in your plex agent (Rotten Tomatoes, IMDB, TMDB,...)

**Comment by glensc** [comment]
Oh, that `8.6` I was seeing was actually rotten tomatoes `86%`? :)

As I accessed `Movie.rating` property accidentally, the rest of the code seems to convert to `int()`:
- https://github.com/Taxel/PlexTraktSync/blob/ad883a8a3885e5be468794b21192a3def5bc765f/plex_trakt_sync/main.py#L103-L104

**Comment by glensc** [comment]
Closing as ratings are not broken. Code was broken when refactoring and got value in wrong type:

- https://github.com/Taxel/PlexTraktSync/pull/180#issuecomment-813632516

**Comment by glensc** [comment]
Doesn't seem there's a way to remove the rating from Plex. Or is there any special value to use?

**Comment by glensc** [comment]
Ok, Setting `userRating` to `0` for Plex removes it.

Un-setting rating is currently not synced, so just info for the future.

**Comment by glensc** [comment]
For Trakt rating remove need to POST:

```
Request URL: https://trakt.tv/movies/{movie.slug}/rate/remove
Request Method: POST

type: movie
trakt_id: {movie.trakt_d}
stars: {movie.rating}
```

But the pytrakt API method is missing for that.
