### ISSUE TITLE
Error 401 / Error running sync command: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by robinm0** [Taxel/PlexTraktSync#1836]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Fillms and Tv programmes are scanned; after ratings are read, fails with:

Updated liked list in 0.0 seconds                                            
ERROR    Error during [redacted] account access: (401) unauthorized; 

### Steps to reproduce the behavior

1. Updated to 0.29.2
2. ran plextraktsync sync
3. Exited with error 401

### Error trace / logs

```text
2024-02-25 17:03:08,059 ERROR[PlexTraktSync]:Error during [redacted] account access: (401) unauthorized; https://plex.tv/api/v2/user <?xml version="1.0" encoding="UTF-8"?> <errors>   <error code="1001" message="User could not be authenticated" status="401"/> </errors> 
2024-02-25 17:03:08,062 ERROR[PlexTraktSync]:object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/plex/.local/pipx/venvs/plextraktsync/lib/python3.11/site-packages/plextraktsync/cli.py", line 26, in wrap
    cmd(*args, **kwargs)
  File "/Users/plex/.local/pipx/venvs/plextraktsync/lib/python3.11/site-packages/plextraktsync/commands/sync.py", line 68, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "/Users/plex/.local/pipx/venvs/plextraktsync/lib/python3.11/site-packages/plextraktsync/sync/Sync.py", line 105, in sync
    if walker.config.walk_watchlist and self.sync_wl:
                                        ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/plex/.local/pipx/venvs/plextraktsync/lib/python3.11/site-packages/plextraktsync/sync/Sync.py", line 35, in sync_wl
    return self.config.sync_wl and len(self.plex_wl) > 0
                                   ^^^^^^^^^^^^^^^^^
  File "/Users/plex/.local/pipx/venvs/plextraktsync/lib/python3.11/site-packages/plextraktsync/plex/PlexWatchList.py", line 21, in __len__
    return len(self.watchlist)
           ^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

### Expected behavior

Normal end of run.

### Install method

pipx

### Config file contents

```yaml
cache:
  path: /Users/plex/Library/Caches/PlexTraktSync/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.29.2

### Python Version

3.11.3

### Plex Server Version

1.40.0.7998

### Operating System and Version

macOS-14.3.1

**Comment by glensc** [comment]
edit your post and put terminal output to code blocks
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by glensc** [comment]
Seems same error reported here:
- https://github.com/Taxel/PlexTraktSync/issues/1838

no info whether this appeared with upgrade (did you try downgrading) or is this new install? have you changed your config recently?

from trace I guess you are using managed account?

**Comment by glensc** [comment]
you need to test downgrade to see if it's code error or something at trakt.tv side has changed. i.e does the old downgraded version still work? try to pin point exact version what caused breakage if that's the case.

**Comment by glensc** [comment]
and managed account:
- https://www.google.com/search?q=plex+managed+account

**Comment by glensc** [comment]
this still needs edit (scroll your whole post):
- https://github.com/Taxel/PlexTraktSync/issues/1836#issuecomment-1968944483

**Comment by glensc** [comment]
you may try this pr:
- https://github.com/Taxel/PlexTraktSync/pull/1844

but in short, seems your plex account token is missing or expired or whatever reason plex.tv is rejecting it:
- https://github.com/Taxel/PlexTraktSync/blob/bdd88045fc6002597d6bf17ba185e3d261a3aebc/plextraktsync/plex/PlexApi.py#L186-L188

plex-login subcommand may help.

**Comment by glensc** [comment]
syncing watchlist requires plex account oken, if you can't have it, you can turn off and sync to playlist instead

```yml
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: true
```

**Comment by robinm0** [comment]
Right, now I see that 'managed' account refers to Plex. Thank you.

I have got it running to completion, but it took several attempts using the 'plex-login' option. Initially, all attempts to log-in using the pwd (which hadn't been changed) failed, with either the Plex username or Plex account e-mail address. Eventually, after changing the pwd for the username (me), and some https errors (apparently expected), it connected and wrote details to a  .yml file.. 

I see that you are implementing a friendlier error message for this problem.

Thanks again for your help.
