### ISSUE TITLE
ModuleNotFoundError: No module named 'plextraktsync'

### ISSUE THREAD

**Issue by tonybeatle** [Taxel/PlexTraktSync#1839]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Installed with pipx install PlexTraktSync. Tried to run sync and got error message. 
File "/root/.local/bin/plextraktsync", line 5, in <module>
    from plextraktsync.cli import cli
ModuleNotFoundError: No module named 'plextraktsync'

### Steps to reproduce the behavior

Installed with pipx install PlexTraktSync. Tried to run sync and got error message. 

### Error trace / logs

```text
File "/root/.local/bin/plextraktsync", line 5, in <module>
    from plextraktsync.cli import cli
ModuleNotFoundError: No module named 'plextraktsync'
```

### Expected behavior

syncing

### Install method

pipx

### Version

latest

### Python Version

3.10.0

### Plex Server Version

lastest

### Operating System and Version

6.9.14-1 (Shaitan)

**Comment by glensc** [comment]
> Version: latest

invalid version. try downgrade to find what version works.

you should also not run this program as root. it does not require any special permissions

**Comment by glensc** [comment]
0.29.2 works fine to me (macOS).

**Comment by glensc** [comment]
closing. reporter disssapeared

**Comment by random647** [comment]
exact same issue
