### ISSUE TITLE
Watched dates from episodes not correctly synced from Plex to trakt

### ISSUE THREAD

**Issue by engeld** [Taxel/PlexTraktSync#19]
Hi, so I've got this strange issue that episodes watch dates from Plex are not synced correctly when the script is run. Meaning, that when I watched an episode on Plex, I expect the episode on trakt to have the same watched timestamp. Instead it seems to have the timestamp from the sync.

Strangely enough, the issue doesn't arise with movies, there the timestamp sync works without issues and as expected.

**Comment by twolaw** [comment]
Movies timestamp date was corrected on [this PR](https://github.com/Taxel/PlexTraktSync/pull/11) but they forgot to do tvshows as well.
It's only 2 lines of code.

`seen_date = (episode.lastViewedAt if episode.lastViewedAt else datetime.now()) eps.instance.mark_as_seen(seen_date)`

**Comment by engeld** [comment]
Thanks for the solution, it works almost perfectly now, but it seems to have an offset of +2 hours?

In the last_update.log it's correctly recognized:
`2020-04-02 21:18:22,027 INFO:Show [A Black Lady Sketch Show (2019)]: Marked as watched on trakt: episode S01E05`

But on trakt it's logged as 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/944746/78292762-d53de880-7527-11ea-8e43-614df055ebb0.png">.

**Comment by twolaw** [comment]
I think the timezone of the OS you run PlexTraktSync on is wrong.
Check it in python with:
```
import time
time.tzname
time.strftime("%z")
```

PlexAPI converts a Unix time string ( example: `1585914417` which is not aware of timezone) into a Python datetime based on system timezone. If it is wrong, time sent to trakt will be wrong.

**Comment by twolaw** [comment]
I think the problem is the python [trakt module](https://pypi.org/project/trakt/).
It sends local timestamp whereas trakt API expects to receive UTC timestamp. That's why you have +2 hour offset.

My opinion is that this trakt module is not very good. Issue #20 is also due to this defective module.
@Taxel The more popular [trakt.py module](https://pypi.org/project/trakt.py/) would be a better choice I think.

**Comment by engeld** [comment]
Thanks, I've had a similar assumption as in the meantime I've also seen in the trakt API docs that they expect a UTC timestamp but didn't knew it was the trakt module who isn't timezone aware. So thanks!

I've used your workaround and now it works perfectly.
