### ISSUE TITLE
Feature request: Sync watched Anime shows & movies to Trakt also add them in list.

### ISSUE THREAD

**Issue by sonikun** [Taxel/PlexTraktSync#1902]
### Feature description
Self explanatory.

### Use case
As Trakt doesn't provide a separate section for Anime, this would help to track all Anime separately.

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

### Workarounds

_Is there an existing workaround to accomplish this?_

### Plan to implement

_Are you interested in submitting a PR to implement this?_

**Comment by glensc** [comment]
edit your report to remove placeholder texts. also: Please explain what do you mean. Not everybody knows the specifics of Anime that you assume here.

**Comment by glensc** [comment]
re-open if you fill find time to answer
