### ISSUE TITLE
Version 0.30.0 adds all TV series to Trakt collection, then removes them all in the next step. Downgrading to 0.29.14 corrects it.

### ISSUE THREAD

**Issue by SawkeeReemo** [Taxel/PlexTraktSync#1923]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

When PTS runs, it re-adds every TV series episode to Trakt Collection, but then immediately removes them all again int he next step.

### Steps to reproduce the behavior

Running PTS

### Expected behavior

To not remove every TV episode from collection.

### Workarounds

Downgrading to 0.29.14 corrects this.

### Install method

docker-compose

### Version

0.30.0

### Python Version

3.12.3

### Plex Server Version

1.40.2.8395

### Operating System and Version

Ubuntu LTS 22.04

**Comment by SawkeeReemo** [comment]
Correction: The first time it runs, it removes all TV episodes from the Trakt collection. Then on the next run it will add them all back, then immediately remove them all again.

**Comment by glensc** [comment]
Missing config contents from bugreport.

**Comment by SawkeeReemo** [comment]
> Missing config contents from bugreport.

Weird, not sure how I managed to skip the config, but here ya go:
https://hastebin.com/share/ahovibiqej.yaml

> 
> Also try to change sync settings to see if changing them as any workaround.

What settings should I change to test? These have been the same for a long time and this issue only started with 0.30.0. Reverting brings back a version makes it work again. Did something change between those two versions to affect this? My apologies if I missed something.

**Comment by glensc** [comment]
relevant config:

```yml
    # Clear collected state of items not present in Plex
    clear_collected: true
```

this was fixed with https://github.com/Taxel/PlexTraktSync/pull/1916
