### ISSUE TITLE
After update from 0.28.14 to 0.30.1,  addon times out tryinig to connect to plex

### ISSUE THREAD

**Issue by jonasprokopf** [Taxel/PlexTraktSync#1930]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Without having changed anything in the config, the addon stopped working after having updated it using pipx. When trying to log in again to Plex, I get a 401.

### Steps to reproduce the behavior

plextraktsync sync
or
plextraktsync plex-login

### Error trace / logs

```text
root@bierkasten2:/home/szwab# pipx upgrade plextraktsync
upgraded package plextraktsync from 0.28.14 to 0.30.1 (location: /root/.local/pipx/venvs/plextraktsync)
root@bierkasten2:/home/szwab# plextraktsync
WARNING  plextraktsync without command is deprecated. Executing "plextraktsync sync"
INFO     PlexTraktSync [0.30.1]
INFO     Connecting with url: https://192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPSConnectionPool(host='192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at
         0x7f628cd46a40>: Failed to resolve '192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct' ([Errno -5] No address associated with hostname)"))
WARNING  Adding rewritten http url to connect with: http://192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct:32400
INFO     Connecting with url: https://172-20-0-1.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    (401) unauthorized; https://172-20-0-1.4b58693a885a4c4bb5927261585de323.plex.direct:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] +
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
INFO     Connecting with url: https://172-18-0-1.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    (401) unauthorized; https://172-18-0-1.4b58693a885a4c4bb5927261585de323.plex.direct:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] +
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
INFO     Connecting with url: http://192.168.178.22:32400, timeout 30 seconds
ERROR    (401) unauthorized; http://192.168.178.22:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: http://172.20.0.1:32400, timeout 30 seconds
ERROR    (401) unauthorized; http://172.20.0.1:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: http://172.18.0.1:32400, timeout 30 seconds
ERROR    (401) unauthorized; http://172.18.0.1:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: https://93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPSConnectionPool(host='93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at
         0x7f628cdad6c0>, 'Connection to 93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct timed out. (connect timeout=30)'))
WARNING  Adding rewritten http url to connect with: http://93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct:32400
INFO     Connecting with url: http://93.132.9.69:32400, timeout 30 seconds
ERROR    HTTPConnectionPool(host='93.132.9.69', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f628cdae140>, 'Connection to 93.132.9.69 timed out.
         (connect timeout=30)'))
INFO     Connecting with url: https://139-162-175-123.4b58693a885a4c4bb5927261585de323.plex.direct:8443, timeout 30 seconds
ERROR    (401) unauthorized; https://139-162-175-123.4b58693a885a4c4bb5927261585de323.plex.direct:8443/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] +
         'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
INFO     Connecting with url: http://139.162.175.123:8443, timeout 30 seconds
ERROR    ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO     Connecting with url: http://localhost:32400, timeout 30 seconds
ERROR    (401) unauthorized; http://localhost:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: http://192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPConnectionPool(host='192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at
         0x7f628cdae200>: Failed to resolve '192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct' ([Errno -5] No address associated with hostname)"))
INFO     Connecting with url: http://93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPConnectionPool(host='93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f628cdaf790>,
         'Connection to 93-132-9-69.4b58693a885a4c4bb5927261585de323.plex.direct timed out. (connect timeout=30)'))
CRITICAL Error running sync command: No more methods to connect. Giving up
```

### Expected behavior

No timeouts or 401s

### Config file contents

```yaml
cache:
  path: /root/.cache/PlexTraktSync/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: null
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

pipx

### Version

0.30.1

### Python Version

3.10.13

### Plex Server Version

1.40.0.7998 

### Operating System and Version

Linux-5.15.0-100-generic-x86_64-with-glibc2.35

**Comment by glensc** [comment]
what is the addon?

**Comment by glensc** [comment]
> Workarounds
>
> No response

did you try downgrading? what version **exactly** breaks?

**Comment by glensc** [comment]
```
INFO     Connecting with url: https://192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct:32400/, timeout 30 seconds
ERROR    HTTPSConnectionPool(host='192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at
         0x7f628cd46a40>: Failed to resolve '192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct' ([Errno -5] No address associated with hostname)"))
```

your configuration is invalid, these are almost all the time problem without networking or using wrong address, NameResolutionError means your DNS is broken.

here it resolves correctly:

```
❯ host 192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct
192-168-178-22.4b58693a885a4c4bb5927261585de323.plex.direct has address 192.168.178.22
```

and so should in your environment

**Comment by glensc** [comment]
User disappeared. Closing.

**Comment by jonasprokopf** [comment]
> User disappeared. Closing.

I'm sorry for disappearing. If this is on my end, how do I troubleshoot it? I don't think my dns is broken, Injust ran the comman again and there's no NameResolutionError, just a bunch of 401s.

`INFO     PlexTraktSync [0.30.10]
INFO     Connecting with url:
         https://192-168-178-22.4b58693a885a4c4bb5927261
         585de323.plex.direct:32400, timeout 30 seconds
ERROR    (401) unauthorized;
         https://192-168-178-22.4b58693a885a4c4bb5927261
         585de323.plex.direct:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         https://172-20-0-1.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400, timeout 30 seconds
ERROR    (401) unauthorized;
         https://172-20-0-1.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         https://172-18-0-1.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400, timeout 30 seconds
ERROR    (401) unauthorized;
         https://172-18-0-1.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         http://192.168.178.22:32400, timeout 30 seconds
ERROR    (401) unauthorized;
         http://192.168.178.22:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: http://172.20.0.1:32400,
         timeout 30 seconds
ERROR    (401) unauthorized; http://172.20.0.1:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url: http://172.18.0.1:32400,
         timeout 30 seconds
ERROR    (401) unauthorized; http://172.18.0.1:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         https://93-132-9-69.4b58693a885a4c4bb5927261585
         de323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPSConnectionPool(host='93-132-9-69.4b58693a8
         85a4c4bb5927261585de323.plex.direct',
         port=32400): Max retries exceeded with url: /
         (Caused by
         ConnectTimeoutError(<urllib3.connection.HTTPSCo
         nnection object at 0x7effe19859f0>, 'Connection
         to
         93-132-9-69.4b58693a885a4c4bb5927261585de323.pl
         ex.direct timed out. (connect timeout=30)'))
WARNING  Adding rewritten http url to connect with:
         http://93-132-9-69.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400
INFO     Connecting with url: http://93.132.9.69:32400,
         timeout 30 seconds
ERROR    HTTPConnectionPool(host='93.132.9.69',
         port=32400): Max retries exceeded with url: /
         (Caused by
         ConnectTimeoutError(<urllib3.connection.HTTPCon
         nection object at 0x7effe1985210>, 'Connection
         to 93.132.9.69 timed out. (connect
         timeout=30)'))
INFO     Connecting with url:
         https://139-162-175-123.4b58693a885a4c4bb592726
         1585de323.plex.direct:8443, timeout 30 seconds
ERROR    (401) unauthorized;
         https://139-162-175-123.4b58693a885a4c4bb592726
         1585de323.plex.direct:8443/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         http://139.162.175.123:8443, timeout 30 seconds
ERROR    ('Connection aborted.',
         RemoteDisconnected('Remote end closed
         connection without response'))
INFO     Connecting with url: http://localhost:32400,
         timeout 30 seconds
ERROR    (401) unauthorized; http://localhost:32400/
         <html><head><script>window.location =
         window.location.href.match(/(^.+\/)[^\/]*$/)[1]
         +
         'web/index.html';</script><title>Unauthorized</
         title></head><body><h1>401
         Unauthorized</h1></body></html>
INFO     Connecting with url:
         http://93-132-9-69.4b58693a885a4c4bb5927261585d
         e323.plex.direct:32400, timeout 30 seconds
ERROR    HTTPConnectionPool(host='93-132-9-69.4b58693a88
         5a4c4bb5927261585de323.plex.direct',
         port=32400): Max retries exceeded with url: /
         (Caused by
         ConnectTimeoutError(<urllib3.connection.HTTPCon
         nection object at 0x7effe1987970>, 'Connection
         to
         93-132-9-69.4b58693a885a4c4bb5927261585de323.pl
         ex.direct timed out. (connect timeout=30)'))
CRITICAL Error running sync command: No more methods to
         connect. Giving up`
