### ISSUE TITLE
Trakt token not being refreshed after 3 months

### ISSUE THREAD

**Issue by twolaw** [Taxel/PlexTraktSync#20]
[Trakt API](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-code-for-access_token) says `access_token` is valid for 3 months only. So after this time, the script can't connect to trakt api anymore and fail.

Solution : as the api say, the script must store and use the `refresh_token` to [get a new token](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token) when `access_token` expiration date comes.

Could you fix this please ?

**Comment by cutzenfriend** [comment]
+1

**Comment by twolaw** [comment]
My PR moogar0880/PyTrakt#121 has been merged into pytrakt 2.14 👍 
Therefore, updating trakt module requirement to version 2.14 fixes this issue.
@glensc I'm not familiar with pipfile.lock content and I don't want to break anything. Can you help me?

**Comment by glensc** [comment]
@twolaw: https://github.com/Taxel/PlexTraktSync/pull/50

but I'm no heavy user of pipenv either, I just found it's useful in Python world as npm/yarn/composer lock in node/php worlds.

**Comment by twolaw** [comment]
This issue is back, after this PR being merged :
- https://github.com/Taxel/PlexTraktSync/pull/314

Because of bad implementation of Trakt Auth Token processing in PyTrakt:
- https://github.com/moogar0880/PyTrakt/issues/150

Many decorators use, which I'm not understanding very well.

**Comment by glensc** [comment]
Check that you don't have `.pytrakt.json` in the default location: `~/.pytrakt.json`. the freshness check may use that file instead of forced location of `.pytrakt.json`

**Comment by glensc** [comment]
should be fixed with https://github.com/Taxel/PlexTraktSync/pull/715

please open a new bug report if it re-occurs or have more details.
