### ISSUE TITLE
plextraktsync terminated by API didn't respond properly

### ISSUE THREAD

**Issue by leokklai** [Taxel/PlexTraktSync#2025]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

During sync, plextraktsync terminated by API didn't respond properly.  The error log is shown:

```
2024-08-19 12:19:29,502 WARNING[plextraktsync.decorators.retry]:Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 1 seconds (try: 1/5)
2024-08-19 12:19:30,780 WARNING[plextraktsync.decorators.retry]:Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 2 seconds (try: 2/5)
2024-08-19 12:19:33,066 WARNING[plextraktsync.decorators.retry]:Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 3 seconds (try: 3/5)
2024-08-19 12:19:36,335 WARNING[plextraktsync.decorators.retry]:Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 4 seconds (try: 4/5)
2024-08-19 12:19:40,627 WARNING[plextraktsync.decorators.retry]:Internal Server Error for plextraktsync.trakt.TraktApi.search_by_id(), retrying after 5 seconds (try: 5/5)
2024-08-19 12:19:46,563 ERROR[plextraktsync.decorators.retry]:Error: Internal Server Error
2024-08-19 12:19:46,566 ERROR[plextraktsync.decorators.retry]:Error message: Internal server error. Please open a support issue and include your full API request and response, including all headers.
2024-08-19 12:19:46,569 ERROR[plextraktsync.decorators.retry]:Last call: plextraktsync.trakt.TraktApi.search_by_id(('2207604', 'tmdb', 'episode'), {})
2024-08-19 12:19:46,587 CRITICAL[plextraktsync.cli]:Error running sync command: API didn't respond properly, script will abort now. Please try again later.
```

I think it is due to the TV show with tmdb ID 2207604 that plextraktsync may not be supported.  But how can I found which show with this ID?

### Steps to reproduce the behavior

execute plextraktsync sync, the progress will be stopped at this point.

### Expected behavior

plextraktsync terminated.

### Install method

docker-compose

### Version

0.31.7

### Python Version

3.12.4

### Plex Server Version

1.29.2.6364

### Operating System and Version

Synolgoy DSM 7.1

**Comment by glensc** [comment]
> I think it is due to the TV show with tmdb ID 2207604 that plextraktsync may not be supported. But how can I found which show with this ID?

did you enable debug logging and checking logs?

**Comment by WillPresley** [comment]
For what it's worth, I was also having this exact error for the last few days, but at some point in the last ~12 hours, it started working again on its own.

**Comment by glensc** [comment]
this is problem at trakt.tv api side, so they might have addressed problems.

you need to report problem to them

**Comment by glensc** [comment]
tmdb id 2207604  could be one of these:
- https://trakt.tv/search/tmdb?query=2207604
  - episode: https://trakt.tv/shows/crazy-over-his-fingers-just-the-two-of-us-in-a-salon-after-closing-2020-199249/seasons/1/episodes/3
  - person: https://trakt.tv/people/vasyl-yavtushenko

**Comment by glensc** [comment]
enable debug log and see what request it makes with 2207604, and then use trakt-api.sh script from project root to make same request.

**Comment by glensc** [comment]
might be this request:

```
❯ ./trakt-api.sh 'https://api.trakt.tv/search/tmdb/2207604?type=episode'
curl: (22) The requested URL returned error: 500
```

you need to report this to trakt support.

**Comment by Animosity022** [comment]
This seems to hard stop the sync, is there a flag / way / method to skip it and continue on? I reported the one I found as well.

**Comment by glensc** [comment]
This is trakt side problem. seems none of you reported this to them.

still 500 error:

```
$ ./trakt-api.sh 'https://api.trakt.tv/search/tmdb/2207604?type=episode'
curl: (22) The requested URL returned error: 500
[{"type":"episode","score":1000,"episode":{"season":1,"number":3,"title":"I am well aware of your hard work.","ids":{"trakt":4121230,"tvdb":7697618,"imdb":null,"tmdb":2207604,"tvrage":null}},"show":{"title":"Crazy Over His Fingers: Just the Two of Us in a Salon After Closing","year":2020,"ids":{"trakt":160313,"slug":"crazy-over-his-fingers-just-the-two-of-us-in-a-salon-after-closing","tvdb":379925,"imdb":"tt12044826","tmdb":100937,"tvrage":null}}}]zsh: unknown file attribute: 2
```

**Comment by glensc** [comment]
looks like i was mistakenly copying previous error message as well

so, that specific one is fixed

```
$ ./trakt-api.sh 'https://api.trakt.tv/search/tmdb/2207604?type=episode'
[{"type":"episode","score":1000,"episode":{"season":1,"number":3,"title":"I am well aware of your hard work.","ids":{"trakt":4121230,"tvdb":7697618,"imdb":null,"tmdb":2207604,"tvrage":null}},"show":{"title":"Crazy Over His Fingers: Just the Two of Us in a Salon After Closing","year":2020,"ids":{"trakt":160313,"slug":"crazy-over-his-fingers-just-the-two-of-us-in-a-salon-after-closing","tvdb":379925,"imdb":"tt12044826","tmdb":100937,"tvrage":null}}}]
```

**Comment by Animosity022** [comment]
> This is trakt side problem. seems none of you reported this to them.
> 

Seems like you didn't seem my response as the image is a response from Trakt Support.

Closing this out doesn't solve the error that it fails the sync and won't go paste it. If should log the error and progress as trakt srever problems should not blow up the sync.

**Comment by glensc** [comment]
There is pr:
- https://github.com/Taxel/PlexTraktSync/pull/1874

but since nobody who wanted it responded, it's abandoned (might not work)
