### ISSUE TITLE
Docker container in unraid keeps shutting down 

### ISSUE THREAD

**Issue by doobersn** [Taxel/PlexTraktSync#2044]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

The docker container is always automatically shutting down. 

### Steps to reproduce the behavior

It happens every time i restart it but im not sure when exactly it’s shutting down. I have always had to start the container before syncing. 

### Expected behavior

To stay on all the time and auto start when needed. 

### Install method

Unraid installation (not supported)

### Version

newest version 

### Python Version

don’t use python 

### Plex Server Version

newest version 

### Operating System and Version

unraid

**Comment by glensc** [comment]
not reproducible. with little details you've given can only say: "dunno". you haven't even shared your config or description how you set it up.
