### ISSUE TITLE
RuntimeError: Server with name 'PlexRD' is not defined

### ISSUE THREAD

**Issue by seedboxer** [Taxel/PlexTraktSync#2048]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Could someone tell me about the error below ? Ive tried a few thing to fix but nothing works, as thought maybe it was an access issue to the plex container.

ERROR    http://172.16.1.2:32400: HTTPConnectionPool(host='172.16.1.2', port=32400): Max retries exceeded with url: / (Caused by
         ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f775743c0e0>, 'Connection to 172.16.1.2 timed out. (connect
         timeout=30)'))
Connection to PlexRD established successfully!
Plex Media Server Authentication Token and base URL have been added to servers.yml
ERROR    Server with name 'PlexRD' is not defined
         ╭──────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────
         │ /app/plextraktsync/config/ServerConfigFactory.py:21 in get_server                                                                         │
         │                                                                                                                                           │
         │   18 │   def get_server(self, name: str):                                                                                                 │
         │   19 │   │   self.load()                                                                                                                  │
         │   20 │   │   try:                                                                                                                         │
         │ ❱ 21 │   │   │   return PlexServerConfig(name=name, **self.servers[name])                                                                 │
         │   22 │   │   except KeyError:                                                                                                             │
         │   23 │   │   │   raise RuntimeError(f"Server with name '{name}' is not defined")                                                          │
         │   24                                                                                                                                      │
         ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
         KeyError: 'PlexRD'

         During handling of the above exception, another exception occurred:

         ╭──────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────
         │ /app/plextraktsync/cli.py:28 in wrap                                                                                                      │
         │                                                                                                                                           │
         │    25 │   │   │   cmd = getattr(module, name)                                                                                             │
         │    26 │   │   │                                                                                                                           │
         │    27 │   │   │   try:                                                                                                                    │
         │ ❱  28 │   │   │   │   cmd(*args, **kwargs)                                                                                                │
         │    29 │   │   │   except EOFError as e:                                                                                                   │
         │    30 │   │   │   │   raise ClickException(f"Program requested terminal, No terminal is                                                   │
         │       connected: {e}")                                                                                                                    │
         │    31 │   │   │   except ClickException as e:                                                                                             │
         │                                                                                                                                           │
         │ /app/plextraktsync/commands/sync.py:52 in sync                                                                                            │
         │                                                                                                                                           │
         │   49 │                                                                                                                                    │
         │   50 │   ensure_login()                                                                                                                   │
         │   51 │   wc = factory.walk_config.update(movies=movies, shows=shows, watchlist=watchlist)                                                 │
         │ ❱ 52 │   w = factory.walker                                                                                                               │
         │   53 │                                                                                                                                    │
         │   54 │   if ids:                                                                                                                          │
         │   55 │   │   for id in ids:                                                                                                               │
         │                                                                                                                                           │
         │ /usr/local/lib/python3.12/functools.py:993 in __get__                                                                                     │
         │                                                                                                                                           │
         │    990 │   │   │   raise TypeError(msg) from None                                                                                         │
         │    991 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                                 │
         │    992 │   │   if val is _NOT_FOUND:                                                                                                      │
         │ ❱  993 │   │   │   val = self.func(instance)                                                                                              │
         │    994 │   │   │   try:                                                                                                                   │
         │    995 │   │   │   │   cache[self.attrname] = val                                                                                         │
         │    996 │   │   │   except TypeError:                                                                                                      │
         │                                                                                                                                           │
         │ /app/plextraktsync/util/Factory.py:191 in walker                                                                                          │
         │                                                                                                                                           │
         │   188 │   │   from plextraktsync.plan.Walker import Walker                                                                                │
         │   189 │   │                                                                                                                               │
         │   190 │   │   walk_config = self.walk_config                                                                                              │
         │ ❱ 191 │   │   plex = self.plex_api                                                                                                        │
         │   192 │   │   trakt = self.trakt_api                                                                                                      │
         │   193 │   │   mf = self.media_factory                                                                                                     │
         │   194 │   │   pb = self.progressbar                                                                                                       │
         │                                                                                                                                           │
         │ /usr/local/lib/python3.12/functools.py:993 in __get__                                                                                     │
         │                                                                                                                                           │
         │    990 │   │   │   raise TypeError(msg) from None                                                                                         │
         │    991 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                                 │
         │    992 │   │   if val is _NOT_FOUND:                                                                                                      │
         │ ❱  993 │   │   │   val = self.func(instance)                                                                                              │
         │    994 │   │   │   try:                                                                                                                   │
         │    995 │   │   │   │   cache[self.attrname] = val                                                                                         │
         │    996 │   │   │   except TypeError:                                                                                                      │
         │                                                                                                                                           │
         │ /app/plextraktsync/util/Factory.py:48 in plex_api                                                                                         │
         │                                                                                                                                           │
         │    45 │   │   from plextraktsync.plex.PlexApi import PlexApi                                                                              │
         │    46 │   │                                                                                                                               │
         │    47 │   │   return PlexApi(                                                                                                             │
         │ ❱  48 │   │   │   server=self.plex_server,                                                                                                │
         │    49 │   │   │   config=self.server_config,                                                                                              │
         │    50 │   │   )                                                                                                                           │
         │    51                                                                                                                                     │
         │                                                                                                                                           │
         │ /usr/local/lib/python3.12/functools.py:993 in __get__                                                                                     │
         │                                                                                                                                           │
         │    990 │   │   │   raise TypeError(msg) from None                                                                                         │
         │    991 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                                 │
         │    992 │   │   if val is _NOT_FOUND:                                                                                                      │
         │ ❱  993 │   │   │   val = self.func(instance)                                                                                              │
         │    994 │   │   │   try:                                                                                                                   │
         │    995 │   │   │   │   cache[self.attrname] = val                                                                                         │
         │    996 │   │   │   except TypeError:                                                                                                      │
         │                                                                                                                                           │
         │ /app/plextraktsync/util/Factory.py:83 in plex_server                                                                                      │
         │                                                                                                                                           │
         │    80 │   │   from plextraktsync.factory import factory                                                                                   │
         │    81 │   │   from plextraktsync.plex.PlexServerConnection import PlexServerConnection                                                    │
         │    82 │   │                                                                                                                               │
         │ ❱  83 │   │   server = self.server_config                                                                                                 │
         │    84 │   │                                                                                                                               │
         │    85 │   │   return PlexServerConnection(factory).connect(                                                                               │
         │    86 │   │   │   urls=server.urls,                                                                                                       │
         │                                                                                                                                           │
         │ /usr/local/lib/python3.12/functools.py:993 in __get__                                                                                     │
         │                                                                                                                                           │
         │    990 │   │   │   raise TypeError(msg) from None                                                                                         │
         │    991 │   │   val = cache.get(self.attrname, _NOT_FOUND)                                                                                 │
         │    992 │   │   if val is _NOT_FOUND:                                                                                                      │
         │ ❱  993 │   │   │   val = self.func(instance)                                                                                              │
         │    994 │   │   │   try:                                                                                                                   │
         │    995 │   │   │   │   cache[self.attrname] = val                                                                                         │
         │    996 │   │   │   except TypeError:                                                                                                      │
         │                                                                                                                                           │
         │ /app/plextraktsync/util/Factory.py:121 in server_config                                                                                   │
         │                                                                                                                                           │
         │   118 │   │   │   server_config.load()                                                                                                    │
         │   119 │   │   │   server_name = config["PLEX_SERVER"]                                                                                     │
         │   120 │   │                                                                                                                               │
         │ ❱ 121 │   │   return server_config.get_server(server_name)                                                                                │
         │   122 │                                                                                                                                   │
         │   123 │   @cached_property                                                                                                                │
         │   124 │   def urls_expire_after(self):                                                                                                    │
         │                                                                                                                                           │
         │ /app/plextraktsync/config/ServerConfigFactory.py:23 in get_server                                                                         │
         │                                                                                                                                           │
         │   20 │   │   try:                                                                                                                         │
         │   21 │   │   │   return PlexServerConfig(name=name, **self.servers[name])                                                                 │
         │   22 │   │   except KeyError:                                                                                                             │
         │ ❱ 23 │   │   │   raise RuntimeError(f"Server with name '{name}' is not defined")                                                          │
         │   24 │                                                                                                                                    │
         │   25 │   def server_by_id(self, id: str):                                                                                                 │
         │   26 │   │   self.load()                                                                                                                  │
         ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
         RuntimeError: Server with name 'PlexRD' is not defined

### Steps to reproduce the behavior

docker compose run --rm plextraktsync sync

### Expected behavior

to sync

### Install method

docker-compose

### Version

0.31.12

### Python Version

as container

### Plex Server Version

1.40.5.8921

### Operating System and Version

debian

**Comment by seedboxer** [comment]
Script seems to loop repeated few series with

'because provider 'local' has no external Id'

Would this be normal behviour ?
![Capture](https://github.com/user-attachments/assets/46b952b2-713f-42ac-be81-2047dba43fd2)

**Comment by glensc** [comment]
Seems you already solved original problem. Closing.

One problem, One issue

**Comment by seedboxer** [comment]
Hi i am constantly getting errors 

p```
lextraktsync  | ERROR    HTTPSConnectionPool(host='192-168-1-99.2c0bf7f51a72463081d637a56f718019
plextraktsync  |          .plex.direct', port=32400): Max retries exceeded with url: / (Caused by
plextraktsync  |          NameResolutionError("<urllib3.connection.HTTPSConnection object at     
plextraktsync  |          0x7f4ca5a5ff50>: Failed to resolve                                     
plextraktsync  |          '192-168-1-99.2c0bf7f51a72463081d637a56f718019.plex.direct' ([Errno -5]
plextraktsync  |          Name has no usable address)"))                                         
plextraktsync  | WARNING  Adding rewritten http url to connect with:                             
plextraktsync  |          http://192-168-1-99.2c0bf7f51a72463081d637a56f718019.plex.direct:32400 
plextraktsync  | INFO     Connecting with url:                                                   
plextraktsync  |          https://192-168-80-5.2c0bf7f51a72463081d637a56f718019.plex.direct:32400
plextraktsync  |          , timeout 30 seconds                 
```   
The container shuts down and restarts in a loop constantly.
