### ISSUE TITLE
Not making as watched in Trakt

### ISSUE THREAD

**Issue by tonybeatle** [Taxel/PlexTraktSync#2064]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Scrobble is working fine. If it currently watching something in Plex it will show in Trakt. But once the episode or movie finishes it’s not showing under history in Trakt. Its been working fine for a year but the past few days its not been keep track of history. 

### Steps to reproduce the behavior

Run sync. Checked settings for scrobble. Settings haven’t changed but not working. 

### Expected behavior

Watched shows in history on Trakt. 

### Install method

pipx

### Version

0.31.13

### Python Version

3.9.2

### Plex Server Version

1.41.0.8992

### Operating System and Version

Debian

**Comment by glensc** [comment]
> Error trace / logs
> 
> No response

Why? How should we help?

**Comment by glensc** [comment]
What are you saying? scrobble doesn't end up with a play? That works for me.

**Comment by tonybeatle** [comment]
I think scrobble is working. I'll play an episode on plex and it will show as watching now on Trakt. The progress bar will move while i'm watching the show. The show will end on plex but when I check Trakt the epiosde I just watched does not show in my history. Could this be more of an issue with Trakt or the sync app?

**Comment by glensc** [comment]
now you're saying show will end, but you played episode? do not mix terms. this app records plays of single movies and episodes, never shows or seasons. 

but if episode scrobble is working then it's trakt.tv side problem, as  they will mark episode played once scrobble ends and play threshold is above some percentage. 

is it re-watch of the episode? did you finish episode play at 100% or less?

**Comment by tonybeatle** [comment]
It’s simple. I watch an episode on Plex. On Trakt it will show on the homepage currently watching with a progress bar. I will watch the full episode so it’s passing the 80 or 90% threshold. But it will not show in my watched history on Trakt. This start happening about four or five days ago. This happens with new episodes I’m watching and also old episodes I am re-watching.

**Comment by glensc** [comment]
the flow you describe works perfectly for me. 

I think it's trakt.tv problem. contact their support.
you should enable debug logging and see if there's anything, maybe 409 error again.

**Comment by tonybeatle** [comment]
After a full clean reinstall of PlexTraktSync play history is working. Maybe an update bugged or Trakt was having issues.

**Comment by glensc** [comment]
there's no state when you uninstall and re-install with pipx. config and cache is still retained if you reinstall. see `plextraktsync info` for the paths.
