### ISSUE TITLE
Feature request: Specify which plex user to sync

### ISSUE THREAD

**Issue by stevezau** [Taxel/PlexTraktSync#2072]
### Feature description
Regarding https://github.com/Taxel/PlexTraktSync/discussions/2049

I have several Plex users I've invited to my server. I Want to provide better recommendations, so I need to sync their watch status to Trakt. To do this, I've created a trakt account for each user.

I now want to configure PlexTraktSync, where each user will have its own config/docker container.

However, it is unclear how to tell PlexTraktSync which user to sync. 

I can see the username_filter cofig option but it is true/false. 

I am now thinking this doe snot support my use case?

### Workarounds
None

### Plan to implement
Possibly.

**Comment by stevezau** [comment]
Reading each comment in https://github.com/Taxel/PlexTraktSync/discussions/997.. 

It seems to suggest in the past this script would allow you to select the external user but it does not anymore? So i guess, it is no longer support or i am misunderstanding?

**Comment by glensc** [comment]
The user comes with whatever is in the config and the token.

What you need to do is setup a separate config folder for each user and use `plextraktsync plex-login` to setup needed env/files.

**Comment by glensc** [comment]
What is "trust account"?

**Comment by stevezau** [comment]
Hey @glensc thanks for responding to this. 

RE "Trust". Sorry typo, i meant to say trakt account. 

Ok, so my users are invited/external friends. I cannot log in as them so how would i get this sync working for their account into their own trakt account?

**Comment by glensc** [comment]
You need their plex token. they can send it to you maybe.

there's plenty of pages how to find token, here's from quick find
- https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/

**Comment by stevezau** [comment]
@glensc thanks i figured it out. 

You can get each users token via https://plex.tv/api/servers/{PLEX_SERVER_ID}/shared_servers?X-Plex-Token={PLEX_SERVER_TOKEN}

```
import requests
import xml.etree.ElementTree as ET
import os
import yaml


PLEX_SERVER_URL = "http://x.x.x.x:32400"
PLEX_SERVER_ID = "xxxxxxx"
PLEX_SERVER_TOKEN = "xxxxx"

# Function to fetch and parse the XML
def fetch_xml(url):
    response = requests.get(url)
    if response.status_code == 200:
        return ET.fromstring(response.content)
    else:
        raise Exception(f"Failed to fetch XML from {url}, status code: {response.status_code}")


# Function to create or update the server.yml file
def create_or_update_file(username, access_token):
    base_dir = f"/config/traktsync/{username}"
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)

    file_path = os.path.join(base_dir, "server.yml")

    # Load existing YAML content if file exists, otherwise use a template
    if os.path.exists(file_path):
        with open(file_path, 'r') as file:
            config = yaml.safe_load(file)
    else:
        config = {"servers": {
            "SFlix": {"token": "", "urls": [PLEX_SERVER_URL], "id": PLEX_SERVER_ID, "config": None}}}

    # Update the access token in the config
    config['servers']['SFlix']['token'] = access_token

    # Write the YAML file back
    with open(file_path, 'w') as file:
        yaml.dump(config, file)


# Function to create or update the .env file
def create_or_update_env_file(username):
    base_dir = f"/config/traktsync/{username}"
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)

    env_file_path = os.path.join(base_dir, ".env")

    # Define the content of the .env file
    env_content = f"""# This is .env file for PlexTraktSync
PLEX_USERNAME={username}
TRAKT_USERNAME=stevezau+{username}
PLEX_SERVER=SFlix
PLEX_OWNER_TOKEN=
PLEX_ACCOUNT_TOKEN=
"""

    # Write or overwrite the .env file
    with open(env_file_path, 'w') as file:
        file.write(env_content)


def main():
    url = f"https://plex.tv/api/servers/{PLEX_SERVER_ID}/shared_servers?X-Plex-Token={PLEX_SERVER_TOKEN}"

    # Fetch and parse XML
    xml_root = fetch_xml(url)

    # Loop through each SharedServer element and process it
    for server in xml_root.findall('SharedServer'):
        username = server.attrib.get('username')
        access_token = server.attrib.get('accessToken')

        if username and access_token:
            # Create or update the YAML configuration file
            create_or_update_file(username, access_token)

            # Create or update the .env file
            create_or_update_env_file(username)
        else:
            print(f"Skipping invalid server entry with missing username or access token.")


if __name__ == "__main__":
    main()
```
