### ISSUE TITLE
Sync reviews from Trakt into Plex

### ISSUE THREAD

**Issue by rg9400** [Taxel/PlexTraktSync#2088]
### Feature description

Plex recently added reviews alongside their ratings (see below). It would be nice to be able to sync them from Trakt into Plex. For the sake of transparency, I do not currently use the tool (I am maintaining a fork of the Trakt plugin currently on its last legs), but this feature would get me to use it for sure.

![image](https://github.com/user-attachments/assets/1dcb7cac-b253-4385-b654-097aab90999b)
![image](https://github.com/user-attachments/assets/8e11c732-5645-414d-b612-f7aa1badb075)

### Use case

I write reviews on Trakt, but it would be nice to have them available on Plex so others can see them. I guess it can work vice versa as well.

### Workarounds

Manually copying, but this is cumbersome, especially for historical reviews.

### Plan to implement

I can try and help with testing, but writing the code might be a bit beyond me

**Comment by glensc** [comment]
First is needed that plexapi has support for the methods:
- https://github.com/pkkid/python-plexapi

**Comment by rg9400** [comment]
> First is needed that plexapi has support for the methods:
> 
> * https://github.com/pkkid/python-plexapi

Discussed with SwiftPanda, but it seems like these reviews do not show up alongside the other critic reviews in the XML (despite being in the same place on the UI). After some digging, seems like it is calling the GraphQL API endpoint used for community/Discover content which is not supported by plexapi, so I guess this isn't feasible at the moment.

**Comment by rg9400** [comment]
@glensc fwiw, I created a rough script to do this myself at https://github.com/rg9400/Plextrakt-Reviews . It's only one way sync and utilizes the GraphQL API on their community endpoint directly. Not sure if it's officially allowed, but it seems to work. Seems not all Plex Tokens can do this method. Mostly just FYI since it suits my purposes, but in case you ever did want to look into that portion of the Plex API.
