### ISSUE TITLE
Excluding a libray

### ISSUE THREAD

**Issue by AuchOnGit** [Taxel/PlexTraktSync#22]
Is there any way to exclude a library?

Also,  when adding to cron, couldn't it just be "0 */2 * * * python main.py"?
I'm not even sure what the rest does, but I've noticed "plex_trakt_sync.sh" seems to set some PATH variables before running main.py

**Comment by AuchOnGit** [comment]
I've sorted the cron part and left a comment on the PLEX forums.
Regarding the library filter, seems easy enough but I'm clueless about python or how this works.

allShows = s.all()   <- Can I add a filter here for libraries to exclude?

**Comment by MarcelCosta79** [comment]
That would be great !

**Comment by twolaw** [comment]
Try using `config.json` and `main.py` from [here](https://github.com/twolaw/PlexTraktSync/tree/exclude-library) and tell me if it works.

**Comment by AuchOnGit** [comment]
Hey, thanks for the update-
Doesn't seem to be working.

`Traceback (most recent call last):
  File "/home/pi/Downloads/PlexTraktSync-master/main.py", line 20, in <module>
    from config import CONFIG
  File "/home/pi/Downloads/PlexTraktSync-master/config.py", line 4, in <module>
    CONFIG = json.load(fp)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 16 column 21 (char 369)
`

I also seem to have an issue finding the correct path when called through cron.
Attempted path: /bin/sh: 1: /home/pi/Downloads/PlexTraktSync-master/**h**plex_trakt_sync.sh: not found
Real path: /bin/sh: 1: /home/pi/Downloads/PlexTraktSync-master/plex_trakt_sync.sh: not found

I'm not sure how the path is set but it seems to have an extra "h".

**Comment by twolaw** [comment]
Ok I updated config.json to fix the bug, please try again.

For the extra h i don't know where it comes from.

**Comment by AuchOnGit** [comment]
It ran. Hit something else:

/home/pi/Downloads/PlexTraktSync-master/plex_trakt_sync.sh
Traceback (most recent call last):
  File "/home/pi/Downloads/PlexTraktSync-master/main.py", line 332, in <module>
    main()
  File "/home/pi/Downloads/PlexTraktSync-master/main.py", line 276, in main
    trakt_watched_shows = pytrakt_extensions.allwatched()
AttributeError: module 'pytrakt_extensions' has no attribute 'allwatched'

**Comment by twolaw** [comment]
That's because you have an old version (you downloaded before 11-may-2020).
Redownload all files then.

**Comment by AuchOnGit** [comment]
Seems good, mate!
Yeah I was cherry picking those specific ones.

Will wait for the cronjob to run, but manually it went successfully, completely ignored the library I didn't want.
Thanks a ton!

**Comment by twolaw** [comment]
It was very few lines to add, took me 1 minute.
I will wait 2 or 3 days and if nothing wrong happen I will merge the code.

**Comment by MarcelCosta79** [comment]
I can confirm too.
It's working great !
