### ISSUE TITLE
Feature request -- allow user to determine log file name

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#231]
It would be nice to allow the user to differentiate log files for different types of scans.

For example, I do a TV scan every couple of hours. But I only do a movie scan once a day. Since the script erases the log file and starts over each time, it is difficult for me to look at the log file for the movies, since it is getting overwritten by the latest log file from a TV scan.

I think it would be helpful to include a command line argument to determine the name of the log file. Or some other way to separate the logs so this won't happen.

**Comment by glensc** [comment]
I was thinking of moving logging configuration to config.json:
1. append: bool
1. rotate: bool
2. filename: string

**Comment by glensc** [comment]
logging configuration docs:
- https://docs.python.org/3/library/logging.html#logging.basicConfig

**Comment by glensc** [comment]
there's also a module to load logging config from the file:
- https://docs.python.org/3/library/logging.config.html#module-logging.config

but not sure if it's a good idea to give full control of logging to end-users...

**Comment by BEisem** [comment]
Sorry, this is a bit over my head. But I think rotating the logs would be fine, otherwise giving users the ability to choose a log file name on the command line (overriding the default). But rotating seems to be a good idea as well.

**Comment by glensc** [comment]
I propose such schema:

```json5
{
	"logging": {
		"filename": "PlexTraktSync.log", // previously "last_update.log'
		"level": "debug" | "info", // previously: "log_debug_messages":bool
		"append": bool, // whether to truncate file on each run 
		"rotate": bool, // enable rotation based on some built in defaults
		"rotate": [ // advanced rotate config
			"max_bytes": 1024,
			"backup_count": 3,
		],
	}
}
```

for your scenario just need:
```json5
{
	"logging": {
		"append": bool, // whether to truncate file on each run 
	}
}
```

**Comment by glensc** [comment]
@BEisem: no answer.

**Comment by BEisem** [comment]
Sorry, yes I think this is a good plan...

**Comment by glensc** [comment]
Here's the implementation: https://github.com/Taxel/PlexTraktSync/pull/253.

Respond there if it works as expected for you.

**Comment by glensc** [comment]
0.7.22: #253: Add support to disable log truncation on each run
