### ISSUE TITLE
Trakt permissions

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#24]
The form at https://trakt.tv/oauth/applications/new has extra questions, not mentioned in README:

- Permissions:
  - [ ] [`/checkin`](https://trakt.docs.apiary.io/#reference/checkin)
  - [ ] [`/scrobble`](https://trakt.docs.apiary.io/#reference/scrobble)

Whether to check them or not needs to be documented, otherwise, users have to go over a hassle to make new token if the did choose the wrong one initially.

**Comment by twolaw** [comment]
I disagree.
README says to not check them : `You can leave Javascript origins and the checkboxes blank.`
So just let them blank, it's clear.
