### ISSUE TITLE
Movies are no longer being added to Trakt collections

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#256]
I just noticed something ... for the last 2 days, the scripts has stopped adding movies to my Trakt collection, even though I'm running it every night. I'm currently going back and testing each version of the script, to see where the problem started ... it will display for example:

```
Processing Movies  [#-----------------------------------]  372/11114  01:19:57
INFO: Add to Trakt Collection: <imdb:tt9562694:<Movie:379251:Alien-Warfare>>
```

But if I look at the Trakt website, that movie is not added to my collection. And if I run the script again, it displays the same thing.

I'm currently working my way back through the versions to see when this started. Right now I'm testing 0.7.17. If you have any idea when code was changed that could have caused this, let me know so I can test it... otherwise, I'll report back with the latest version that it worked and the first version where it was broken.

**Comment by BEisem** [comment]
Ok, found it. Something happened between 0.7.8 and 0.7.9. 

Using 0.7.8, `./plex_trakt_sync.sh sync --sync=movies` will report that a movie is being added to the Trakt collection, and it actually adds it (checked on the Trakt website). 

With 0.7.9 and higher, it reports that the movie has been added to the Trakt collection, but it doesn't actually add it. Also, repeated runs will say that it is adding the movie again.

I think we were working on TV collections when this version was created, so something must have been changed that broke the movie scan.

**Comment by glensc** [comment]
the diff:
- https://github.com/Taxel/PlexTraktSync/compare/0.7.8...0.7.9

this includes hs pr:
- https://github.com/Taxel/PlexTraktSync/pull/232

it added batching the requests. please show the end of the script, there should be line about batch submission

**Comment by BEisem** [comment]
I've actually been cancelling it after the first movie gets added. It would take an hour or so to run through the entire movie library. Which version do you want me to run it with? 0.7.9? I can run it and let the entire thing finish, I just need to know which version to use.

**Comment by BEisem** [comment]
It looks like the same thing might be happening for TV shows as well. I am getting some shows added to the Trakt collections, but I'm wondering if it's not actually being done by the script.

Running the TV library right now, and it is claiming some episodes have been added, but when I check in the Trakt website, they are not added.

I will let the script finish (for TV shows) and see what happens at the end.

**Comment by BEisem** [comment]
Ah, I understand what is happening ... I didn't realize the entire operation is being batched, so they aren't actually sent to Trakt until the end. I just let the TV sync complete, and it did in fact bring everything over to Trakt.

So, my issue is actually that the movie sync has been crashing midway through, so the changes never actually get sent to Trakt. I guess this is a problem with using the batch, because if the script crashes before completing, then the batch never gets sent.

Also, the logfile is a little misleading because it says "Add to Trakt collection" when in fact it's only storing it, to be sent at the end.

**Comment by BEisem** [comment]
Maybe the logfile should say something like "Adding to batch" ... or something like that. Also, maybe we can have an option in the config file to turn batch on or off?

Why was the batch processing added in the first place? I guess it was to reduce the number of API calls?

**Comment by glensc** [comment]
I linked the PR, you can read the WHY from there.

**Comment by BEisem** [comment]
Here's the reason my movie sync has been crashing ... I'm going to run it again to see if it happens again on the same movie, if so, I'll remove it and try again. But it might be a good idea to try and catch this error so it won't crash out the script.

```
Processing Movies  [#################-------------------]  5268/11117  00:48:45INFO: Add to Trakt Collection: <imdb:tt11908982:<Movie:198327:Jakob's-Wife>>
Processing Movies  [#################-------------------]  5275/11117  00:48:41INFO: Add to Trakt Collection: <imdb:tt0097613:<Movie:197966:The-January-Man>>
Processing Movies  [#################-------------------]  5404/11117  00:47:33INFO: Add to Trakt Collection: <imdb:tt0045943:<Movie:197979:Julius-Caesar>>
Processing Movies  [#################-------------------]  5422/11117  00:47:24INFO: Add to Trakt Collection: <imdb:tt6710826:<Movie:198267:The-Jurassic-Games>>
Processing Movies  [#################-------------------]  5453/11117  00:47:09
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    cli()
  File "/Library/Python/3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Python/3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 235, in sync
    sync_all(movies=movies, tv=tv, show=show)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 178, in sync_all
    for pm, tm in for_each_pair(plex.movie_sections, trakt):
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/commands/sync.py", line 116, in for_each_pair
    tm = trakt.find_by_media(pm)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/decorators/rate_limit.py", line 45, in wrapper
    return fn(*args, **kwargs)
  File "/Users/bink/scripts/PlexTraktSync/plex_trakt_sync/trakt_api.py", line 205, in find_by_media
    search = trakt.sync.search_by_id(media.id, id_type=media.provider, media_type=media.type)
  File "/Users/bink/Library/Python/3.7/lib/python/site-packages/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/Users/bink/Library/Python/3.7/lib/python/site-packages/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.TraktInternalException: Internal Server Error
```

**Comment by glensc** [comment]
@BEisem please, each problem separate issue!

**Comment by BEisem** [comment]
Ok sorry, I'll copy this over to a separate issue. I figured it was the same issue because ultimately this issue was being caused by the crash. I just didn't realize it at first.

**Comment by BEisem** [comment]
So should I close this issue? Or do you want to use it to try and sort out the logging and batch problems?
