### ISSUE TITLE
Feature request: Ability to scan a single movie using --movie=

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#260]
### Feature description

Similar to the previously added `--show=` option, it would be helpful to be able to sync a single movie with `--movie=`

### Use case

I am trying to get through an entire sync of my movie library, but it crashes near the end. It would be helpful to be able to sync one movie so I can test them out without having to go through the entire library.

**Comment by glensc** [comment]
Before it's reasonable to implement this feature request, filtering logic needs to be defined first:
- https://github.com/Taxel/PlexTraktSync/issues/291

**Comment by glensc** [comment]
Added via https://github.com/Taxel/PlexTraktSync/pull/299

**Comment by glensc** [comment]
However, noticed that `--movie` will sync movie that's outside my 'sync-libraries' configuration. same goes for the previous `--show` option, as they are implemented the same way.

we really need to describe the behavior how the options behave:
- https://github.com/Taxel/PlexTraktSync/issues/291
