### ISSUE TITLE
Feature request: Scan individual libraries

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#265]
### Feature description

Another idea, it would be useful to be able to scan individual libraries... similar to the `--sync=tv` and `--sync=movies` commands, to allow users with large libraries to split up the syncing operations.

### Use case

In a case like mine, where I have a very large library, the sync can take quite some time. It would be great for me to be able to break up the sync operations, and syncing individual libraries would allow me to do that.

### Workarounds

None

**Comment by glensc** [comment]
https://github.com/Taxel/PlexTraktSync/pull/267

**Comment by glensc** [comment]
Workaround exists, edit `config.json` before invoking a run :)

**Comment by glensc** [comment]
I'm not aware is it okay to run different versions concurrently, the SQLite engine used for requests_cache I think supports concurrency, so it might just work.

**Comment by BEisem** [comment]
Ah, you are right, I didn't think about that option. Still, I think an additional command line option would be useful.

**Comment by glensc** [comment]
@BEisem please read the comment above.

**Comment by BEisem** [comment]
I wasn't actually talking about running them concurrently. The use case I was thinking about would be to run different versions at different times in crontab. For example one hour I would sync Reality TV library, next hour I would sync Main TV library. The easiest way to do this would be to call different command line options in crontab.

**Comment by glensc** [comment]
I was referring to a comment where I pointed to a pull request adding the change. so arguing of necessity is pointless.

**Comment by glensc** [comment]
If you start them with cron, there's still possible their run overlaps. there's no locking in place to prevent other version to start up.

if you really want to ensure only one process runs at a time, you need to kill the other(s) first or set up some locking. altho easier is to just run multiple instances.

**Comment by glensc** [comment]
@BEisem the PR is okay?

**Comment by BEisem** [comment]
It reports `INFO: Syncing TV=True, Movies=True` which is technically not correct. But it does do the correct sync of only requested libraries.

```
bink@Plex-Server plex-trakt-sync-filter-library % ./plex_trakt_sync.sh sync --library="TV Shows"
INFO: Syncing with Plex BlaEis and Trakt binkatl
INFO: Syncing TV=True, Movies=True
INFO: Loaded Trakt lists in 4.8 seconds
INFO: Server version 1.22.2.4282-a97b03fad updated at: 2021-04-18 09:03:09
INFO: Recently added: [<Season:380942:Leonardo-s1>, <Movie:380934:Rocky-IV>, <Movie:380931:Right-in-Front-of-Me>, <Movie:380929:American-Dream>, <Season:380924:Godfather-of-Harlem-s2>]
Processing TV Shows  [------------------------------------]  10/1429  00:48:4
```

**Comment by glensc** [comment]
The UI glitch can be fixed after https://github.com/Taxel/PlexTraktSync/pull/254
