### ISSUE TITLE
multiuser

### ISSUE THREAD

**Issue by chocorem** [Taxel/PlexTraktSync#27]
Is there a way to sync multiple users from one linux machine ?

my server was previously on windows, and I simply copied the directory and run the get_env several time.

Now I have migrated on ubuntu, and one user is working fine, but the other one are giving an error message
`Traceback (most recent call last):
  File "main.py", line 322, in <module>
    main()
  File "main.py", line 263, in main
    map(lambda m: m.slug, trakt_user.watched_movies))
  File "/home/greg/.local/lib/python3.6/site-packages/trakt/core.py", line 472, in inner
    json_data = self._handle_request('get', url)
  File "/home/greg/.local/lib/python3.6/site-packages/trakt/core.py", line 449, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
`

**Comment by twolaw** [comment]
Did you download the script before 16 January 2020 ?
There has been [an update](https://github.com/Taxel/PlexTraktSync/commit/895594b3ca9d1eba03a600f02756cf79b31360e9) which moves credentials from /home/user to script folder. And therefore allow to have multiple users by copying folder script just like you do.

In `get_env_data.py`, do you have line 7 and 8 :
```
trakt.core.CONFIG_PATH = path.dirname(path.abspath(__file__)) + "/.pytrakt.json"
env_file = path.join(path.dirname(path.abspath(__file__)), ".env")
```

**Comment by berot3** [comment]
so it is possible to have multiple users on plex and each with there own trakt-sync (with own trakt-account)?
Could you please provide a short description in the Readme?

**Comment by twolaw** [comment]
Yes I think it is possible if you duplicate PlexTraktSync folder for each user.
Then you can execute each one and setup will have to be done with each user credentials (plex and trakt).

If you can try it and confirm that it works we will add it in the Readme.

**Comment by Djeloan** [comment]
So, not sure if enough related to this.
But i have just installed this App, and wanted to use it for my GF to sync with trakt, as she is not Plex Pass nor Trakt VIP member (i am both). So i installed it all, but when it started syncing, it first failed 2 times, then third time, it succeeded. 
Now, what the issue is, it have Synced all watched media from Plex, not only hers.. Now we both have identical Trakt watch history...
Is that how this program is supported to work?

**Comment by twolaw** [comment]
Sorry, I didn't clearly understand what you meant. Many users on the same Plex library.
For now it is not possible, but this feature [can be added](https://github.com/pkkid/python-plexapi/issues/65#issuecomment-424405702).
I'll take a look.

**Comment by twolaw** [comment]
> So, not sure if enough related to this.
> But i have just installed this App, and wanted to use it for my GF to sync with trakt, as she is not Plex Pass nor Trakt VIP member (i am both). So i installed it all, but when it started syncing, it first failed 2 times, then third time, it succeeded.
> Now, what the issue is, it have Synced all watched media from Plex, not only hers.. Now we both have identical Trakt watch history...
> Is that how this program is supported to work? just syncing all watched media, regardless of user?

What do you mean by "I installed it all" ?
Does your gf have a plex account or just a local managed user ?
Did you check that both plex token and trakt token are differents in .env and .pytrakt.json ?

**Comment by twolaw** [comment]
@chocorem @berot3 @Djeloan 
You can try [this branch](https://github.com/twolaw/PlexTraktSync/tree/invited-plex-user) and tell me if it works.
It now should work with managed users and shared libraries.

If it doesn't behave as you want, give details about how you set it up, explain what went wrong and give logs.
