### ISSUE TITLE
Network errors when syncing (TimeoutError, ReadTimeout)

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#279]
### The problem

I'm getting repeated crashes while trying to sync my movie library. It doesn't happen on the same item every time, so it's not a specific movie that is causing the problem.

Here's the Traceback (in a gist because it is quite long)

https://gist.github.com/BEisem/20d03e04bad91a32fa46c9142329b948

### Expected behavior

No crash

### Steps to reproduce the behavior

`% ./plex_trakt_sync.sh sync --sync=movies`

### Workarounds

None that I can find

### Environment

- Version: [`0.8.5`]
- Python version: [`3.7.3`]
- Platform: [`MacOS 10.15.6`]

**Comment by glensc** [comment]
@BEisem avoid issue titles that make no sense in the future, like "new". everything is at some point "new".
