### ISSUE TITLE
Episodes added to Trakt Collection even though they are already in Trakt Collection

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#281]
### The problem

Certain TV episodes report repeatedly "Updated to Trakt Collection" even though they are already part of the Trakt collection.

### Expected behavior

Episodes already in the Trakt collection should not be reporting they are being added each time a sync is run

### Steps to reproduce the behavior

`% ./plex_trakt_sync.sh sync --library="Reality / Talk / Documentary TV"`

### Workarounds

None that I'm aware of

### Environment

- Version: `0.8.5`
- Python version: `3.7.3`
- Platform: `MacOS 10.15.7`

Attaching a screenshot of the Trakt entry, showing all episodes are already in the collection, as well as a log showing PlexTraktSync adding them again, even though they are already in the collection.

<img width="1182" alt="Screen Shot 2021-04-19 at 3 14 08 PM" src="https://user-images.githubusercontent.com/34734248/115291182-6cb9ad80-a122-11eb-8010-22a21d8b0439.png">

[100 Day Dream Home.txt](https://github.com/Taxel/PlexTraktSync/files/6338488/100.Day.Dream.Home.txt)

**Comment by glensc** [comment]
@BEisem we discussed this, you approved to merge partial solution, you already forget?

**Comment by BEisem** [comment]
I don't remember the exact situation, all I know is that this isn't working ... I don't understand why the same show would repeatedly report "Updated to Trakt collection" when it is already in the Trakt collection. I don't think we covered this specific situation before.

**Comment by glensc** [comment]
@BEisem I explained why it's not working! look it up and link! bye!

**Comment by glensc** [comment]
0.7.27: #252: Fallback to single episode search for found form Trakt errors

**Comment by glensc** [comment]
Trakt needs to be contacted for those items that go to fallback mode (and later submitted to collection each time)

You can find the episodes query from linked #252

If you want to help, record down trakt show id's with the failing shows here. Use edit to keep it compact (as opposed to creating multiple posts) and create only one post.

**Comment by BEisem** [comment]
Shows that are currently exhibiting this problem:

100 Day Dream Home
https://trakt.tv/shows/100-day-dream-home

American Idol (last 4 seasons)
This is an interesting situation, because the last 4 seasons are actually considered a “reboot” on a different network. So TVDB show all 19 seasons in one series. But TMDB and Trakt have it split. The first 15 seasons (https://trakt.tv/shows/american-idol) and the last 4 seasons (https://trakt.tv/shows/american-idol-2018). I don’t know if there is a way to address this…

Ridiculousness Season 20
https://trakt.tv/shows/ridiculousness

Whose Line Is It Anyway?
Same issue as with American Idol, there is a discrepancy as to whether this is one series or a series and a reboot.
https://trakt.tv/shows/whose-line-is-it-anyway-1998

Frank of Ireland (I know you’re already aware of this one)
https://trakt.tv/shows/frank-of-ireland-2021

The Comedy Store
https://trakt.tv/shows/the-comedy-store

**Comment by glensc** [comment]
this is trakt.tv site problem. contact them.
