### ISSUE TITLE
Feature request: Make use of a lockfile

### ISSUE THREAD

**Issue by BEisem** [Taxel/PlexTraktSync#286]
### Feature description

Would it be possible to have the script use a lockfile? So if you are calling the script from cron, in case the previous instance isn't completed yet, it would stop the script from starting again and avoid having more than one instance running at a time.

### Use case

For use in calling the script from crontab.

**Comment by glensc** [comment]
@BEisem why can't add references to previous discussions on the exact same topic? like we've never talked about it. makes it look that if it as my idea then was discarded, but when you file it as your own it's the best?

**Comment by BEisem** [comment]
I searched the entire repository for "lockfile" and found nothing. I had to find it manually because you didn't use that term. Here's the reference: https://github.com/Taxel/PlexTraktSync/issues/265#issuecomment-822003256

Honestly I couldn't care less who gets credit for an idea. I wasn't trying to steal the glory.

**Comment by BEisem** [comment]
I've tried the following as a replacement for the `plex_trakt_sync.sh` file. It creates the lockfile, and if the lockfile exists, it refuses to start. But it doesn't delete the lockfile when the script completes. I'm guessing it's because of how the python script exits? Otherwise, this should work...

```
#!/bin/sh
set -eu

dir=$(dirname "$0")
LOCK_FILE="$dir/plextraktsync.lock"

if [ -e ${LOCK_FILE} ] && kill -0 `cat ${LOCK_FILE}`; then
  echo "PlexTraktSync is already running."
  exit
  
fi

trap "rm -f ${LOCK_FILE}; exit" INT TERM EXIT
echo $$ > ${LOCK_FILE}

exec python3 "$dir/main.py" "$@"

rm -f ${LOCK_FILE}
```

**Comment by glensc** [comment]
That's your conflict with me you that you don't respect of others efforts. And you create so many threads that you can't even follow on your own. I also said that the locking is maybe needed, because sqlite supports concurrency. But you don't refer that discusdion here like I've never written that to you.

**Comment by glensc** [comment]
There's better and simple external program to do the locking.

- https://linux.die.net/man/1/flock

There are examples on the manual page, on how to use. My recommendation is to use fd smaller than 10, unless you are using bash, for portability reasons. 

<! - - 

Handling locking is not this project concern. Supporting different lock style (whether to wait or abort, whether to use different lock name), only complicate this project and  drive away its main goal. 

-->
