### ISSUE TITLE
Filtering what to sync

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#291]
Users want to walk their library with different inputs:
1. all libraries of type movies or shows (default)
2. libraries of type movies (usually to split their runs)
1. libraries of type shows (usually to split their runs)
2. specific movie (usually to debug a problem)
3. specific tv (usually to debug a problem)

some of the settings come from config (excluded-libraries),
other options come from the command line, some of the options could be repeated (like --show and --movie).

also, there are options that conflict with each other, or override, need to put that logic in too. like if you specify --library, then --show and --movie options become irrelevant.

**we need to define how options behave, alone and combined, and then implement it so.**

_Originally posted by @glensc in https://github.com/Taxel/PlexTraktSync/issues/282#issuecomment-824185338_

**Comment by glensc** [comment]
Current commands:

1. sync all libraries: `./plex_trakt_sync.sh`
2. sync libraries of type movies: `./plex_trakt_sync.sh sync --sync=movies`, turns off shows syncing
3. sync libraries of type shows: `./plex_trakt_sync.sh sync --sync=tv`, turns off movies syncing
4. sync specific show: `./plex_trakt_sync.sh sync --show=Show_Title`, turns off movies syncing

now the large question is what commands options there should be and how they behave? all existing commands can be scratched. backward compatibility is not the goal. go!

**Comment by glensc** [comment]
"tv" should be renamed to "shows" for for consistency

**Comment by BEisem** [comment]
In an ideal world, it would be great to have everything you listed above, with the additional option of `./plex_trakt_sync.sh sync --movie=Movie_Title` because that would give you any number of options....

1. Full Plex library (consisting of all libraries in the Plex database)
2. All movies or all TV shows (using either `--sync=movies` or `--sync=tv`
3. Just a single library (using `--library=Library_Name` ... this already exists, although you didn't mention it in your comment above.
4. Indiviual shows or movies. We already have `--show=Show_Title` but we don't yet have `--movie=MovieTitle`.

Sorry for the long winded response, but my point is that almost all of these are already available. Single movie sync would pretty much get us all the necessary options.

**Comment by glensc** [comment]
The point of the issue was to define behavior. what options are wanted is already known.

**Comment by glensc** [comment]
Added printing contents of walk plan, this perhaps helps to figure out how they should apply:
- https://github.com/Taxel/PlexTraktSync/pull/300

**Comment by glensc** [comment]
From https://github.com/Taxel/PlexTraktSync/issues/260#issuecomment-827779993:

> For example `--movie` will sync a movie that's outside my 'sync-libraries' configuration. same goes for the previous `--show` option, as they are implemented the same way.

**Comment by twolaw** [comment]
As far as I'm concerned, if I can choose to sync category movies or category shows that's enough.
Syncing a specific library can be usefull too.
But going deeper is not something I need. When I want to sync a specific show or a specific movie, I just do it manually in Plex or on Trakt website.


Logically, excluded-libraries of config file should be applied only for a full sync or a category sync.

**Comment by glensc** [comment]
> What is the 'sync-libraries' configuration ?

'all libraries' minus 'excluded-libraries' config.

I think the current `--movie` and `--tv` behavior is just not what users would expect. They would expect  "excluded-libraries" from config to be respected and if `--library` is specified, that to be respected as well. reality it just searches movie or show from plex server from any library.

**Comment by twolaw** [comment]
> They would expect "excluded-libraries" from config to be respected and if --library is specified, that to be respected as well.

Yes you are right, excluded-libraries should be respected whatever the option.

**Comment by glensc** [comment]
And not only, I would also expect `--library` be respected too:

```
--library="4K movies" --title="The Day of the Triffids"
```
