### ISSUE TITLE
Getting "WARNING: Can't use the AlertListener without websocket"

### ISSUE THREAD

**Issue by vladola** [Taxel/PlexTraktSync#312]
### The problem

Getting WARNING: Can't use the AlertListener without websocket

### Expected behavior

It should listen for me watching stuff on plex

### Steps to reproduce the behavior

Simply run the script with "watch" argument

### Workarounds

no

### Environment

- Version: latest release
- Python version: 3.9
- Platform: e.g. `Ubuntu 20`

**Comment by glensc** [comment]
@vladola please complete the issue:
1. what app version
2. complete reproducer

**Comment by five2seven** [comment]
Same issue here. Using version 0.9.15. 
Input: `./plex_trakt_sync.sh watch`
Output: `WARNING: Can't use the AlertListener without websocket`

**Comment by glensc** [comment]
@five2seven does `pip3 inbstall websocket` help?

**Comment by xsnaruto** [comment]
> pip3 inbstall websocket

It helps to me. I didn’t realize that i dont have this module. 

But I don’t know why I can’t install websocket with pip, maybe because some issues of python versions. Anyway, at the end, I have installed it by `sudo apt install python3-websocket`.

Btw, my hardware is Raspberry 4B, Debian10.

**Comment by glensc** [comment]
> But I don’t know why I can’t install websocket with pip, maybe because some issues of python versions. (I don’t know really know python).

Without sharing your errors, nobody else will know either. and it's probably best to be reported to websocket package issue system.

**Comment by xsnaruto** [comment]
> > But I don’t know why I can’t install websocket with pip, maybe because some issues of python versions. (I don’t know really know python).
> 
> 
> 
> Without sharing your errors, nobody else will know either. and it's probably best to be reported to websocket package issue system.

I already finished install python-websocket with apt and I believe that's just because my own problems(python2 and python3). 

So, I didn't put my logs on. Just to confirm that why I had the same problem as this issue is I don't have python-websocket install on my machine.
