### ISSUE TITLE
Add scrobble user filter function

### ISSUE THREAD

**Issue by xsnaruto** [Taxel/PlexTraktSync#324]
Seems like for now, the `watch` function will scrobble all users status to my trakt account.
It would be great if we could filter users at the time of scrobble.

**Comment by glensc** [comment]
@xsnaruto could you explain it more widely, making examples, sharing links etc? as I'm not familiar with the concept.

**Comment by xsnaruto** [comment]
> @xsnaruto could you explain it more widely, making examples, sharing links etc? as I'm not familiar with the concept.

Sorry, English is not my native language, maybe my expression is not good enough.

Well, what I want to say is that I found that when I turn on the scrobble feature, all the playback records of plex users under my management, it will processes them. 

I have a few family members linked to my Plex, so even other users start playing, I will see my own trakt also got update. 

I hope scrobble feature could filter Plex user, to scrobble only my Plex user's status. 

I don't know how to explain it with share link or any other way, so, still in text, sorry. 

Cheers🤣

**Comment by glensc** [comment]
@xsnaruto yes, a longer explanation always better, I understand now.

Anyway, when you configured this app, did you chose managed user?

The current code acts on such message from websocket:

```py
{
    'type': 'playing',
    'size': 1,
    'PlaySessionStateNotification': [
        {
            'sessionKey': '8',
            'guid': '',
            'ratingKey': '10623',
            'url': '',
            'key': '/library/metadata/10623',
            'viewOffset': 5930000,
            'playQueueItemID': 22306,
            'state': 'playing',
            'transcodeSession': 'jef0tvnla5gt8c18ira1ddz7'
        }
    ]
}
```

so as you can see, no user context there, may need to dig into transcodeSession, or playQueueItemID, maybe there's some user context.

**Comment by keldian** [comment]
Having this issue as well. I don't quite understand @glensc's post but I'm assuming it doesn't contain a solution. 

For my part, I did not choose a managed user when configuring the app (none of the managed users is my main account).

**Comment by iamkroot** [comment]
@glensc take a look at the `/status/sessions` endpoint. It has the user info. You can take a look at 
https://github.com/iamkroot/trakt-scrobbler/blob/892877851fd82b23bd3d9bfe70d82ebfb73c994e/trakt_scrobbler/player_monitors/plex.py#L81 
to see how I parse it

**Comment by chrillep** [comment]
> @glensc take a look at the `/status/sessions` endpoint. It has the user info. You can take a look at 
> 
> https://github.com/iamkroot/trakt-scrobbler/blob/892877851fd82b23bd3d9bfe70d82ebfb73c994e/trakt_scrobbler/player_monitors/plex.py#L81 
> 
> to see how I parse it. I don't use webhooks, and the output of this endpoint is the source of truth for my app. You may have to add some logic to match the notification with the session. 

I'm not really sure what the equivalent would be in the used [PlexAPI package](https://python-plexapi.readthedocs.io/en/latest/index.html) any thoughts? 😊

**Comment by glensc** [comment]
Dunno, try some code search:
- https://github.com/pkkid/python-plexapi/search?q=%2Fstatus%2Fsessions

**Comment by iamkroot** [comment]
I guess this is the relevant method: https://python-plexapi.readthedocs.io/en/latest/modules/server.html#plexapi.server.PlexServer.sessions

**Comment by ImjuzCY** [comment]
Any updates on this? I did some research and indeed `plexapi.server.PlexServer.sessions` is the method to use. It returns a list of current playing media. For each media there will be a attribute `usernames` which is a list of usernames that is currently watching this media. So `plex.sessions()[0].usernames` will give a list of username strings for the first session. But I guess the devs already know this. My python-fu is not good enough to implement this but I'm also waiting for this feature.
