### ISSUE TITLE
WARNING: Internal Server Error for plex_trakt_sync.trakt_api.watchlist_movies(), retrying after 1 seconds (try: 1/5)

### ISSUE THREAD

**Issue by andrewvint** [Taxel/PlexTraktSync#333]
Getting this error when running the script

WARNING: Internal Server Error for plex_trakt_sync.trakt_api.watchlist_movies(), retrying after 1 seconds (try: 1/5)

**Comment by hokagemedia** [comment]
Same here

**Comment by andrewvint** [comment]
I changed the config file to set the following two items to false, this then enabled the file to run as expected

`
       
           "liked_lists": false,       
           "watchlist": false,

`

**Comment by twolaw** [comment]
Trakt Internal server error happen sometimes. We can't do anything about it.
What can be done is a https://github.com/Taxel/PlexTraktSync/pull/273 try/catch to be added here :
https://github.com/Taxel/PlexTraktSync/blob/14b28ccfdee87bb9bb23abd97179b3cfc50e7bc0/plex_trakt_sync/commands/sync.py#L63-L69
to avoid script crash.

**Comment by Davo1624** [comment]
As @andrewvint mentioned setting the config.json 'watchlist' option to 'false' allowed the script to complete.

Regarding the try/catch you mentioned, I found the relevant code in sync.py but I am not sure how to modify/implement. I looked at #273 you linked but could not see what changes were recommended

I am relatively new to all this, sorry for the novice questions

**Comment by hokagemedia** [comment]
> I changed the config file to set the following two items to false, this then enabled the file to run as expected
> 
> `
> 
> ```
>        "liked_lists": false,       
>        "watchlist": false,
> ```
> 
> `

This workaround was successful.

**Comment by glensc** [comment]
@twolaw then it needs to be decided for each option what would be the action, as for example if watchlist_movies fails, then syncing watchlist should be disabled or the script could nuke some data.

i.e if watchlist fetch failed, then script will see the trakt side list empty, and may delete some needed data. this is theoretical, I have not checked the code.

so the current behavior of aborting script seems the safest option for now.

**Comment by glensc** [comment]
`Internal Server Error` needs to be reported to trakt.tv support. PlexTraktSync must not build tons of workarounds for their data problems.

**Comment by twolaw** [comment]
> so the current behavior of aborting script seems the safest option for now.

You are right, it can be complicated to handle each scenario.

Then I suggest a single try/catch for all the 6 "Loaded Trakt lists" lines. The user would get a message about Trakt Error and the script would stop properly. Like this :

`Trakt Internal Server Error : Trakt didn't respond properly, script abort now. Please try again later.`

**Comment by twolaw** [comment]
@andrewvint @Davo1624 @hokagemedia
2 days later, did you try again ty sync playlists and do you still get `internal server error` from trakt ?

**Comment by Davo1624** [comment]
No issues now with all options set to true in config.json, everything synced properly.

**Comment by glensc** [comment]
Added trakt support label. This issue should be closed as we should not make workarounds here for trakt API issues.
