### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by jiegto** [Taxel/PlexTraktSync#34]
When I run synchronization, I get an error:

Traceback (most recent call last):
  File "./main.py", line 324, in <module>
    main()
  File "./main.py", line 309, in main
    process_show_section(section, trakt_watched_shows)
  File "./main.py", line 222, in process_show_section
    eps.instance.mark_as_seen(seen_date.astimezone(datetime.timezone.utc))
ValueError: astimezone() cannot be applied to a naive datetime

**Comment by twolaw** [comment]
Where do you live (your timezone) ?

Can you try in main.py to turn this line 222 :
`eps.instance.mark_as_seen(seen_date.astimezone(datetime.timezone.utc))`
into
`eps.instance.mark_as_seen(seen_date.astimezone().astimezone(datetime.timezone.utc))`
And do the same for movies on line 117.
Then check if it works.

**Comment by jiegto** [comment]
I updated python to 3.8.3 from 3.5.3.
It Already works.
Thank you!

**Comment by montizzl3** [comment]
OK, I am getting this same error with Python 3.5.4.  I will update and give it a try.  Thank you!
