### ISSUE TITLE
[QUERY] Collection 2 way sync

### ISSUE THREAD

**Issue by arbuilder** [Taxel/PlexTraktSync#362]
Could u tell me if the collection sync is 2 way, i.e. if i delete files on plex will they also removed from trakt collection and vice versa. Also if it is currently not possible will this feature be available in the future versions.

**Comment by glensc** [comment]
If you delete files on plex, nothing will happen to trakt as the application can't find any match, so nothing will be updated.

the application flow is this:
1. find all media from plex
2. find matching trakt media
3. update watched status
4. update collected status
5. ...

also, you should probably use "discussions" for questions:
- https://github.com/Taxel/PlexTraktSync/discussions

**Comment by glensc** [comment]
as for the future, there's no roadmap. a slight idea you may get from open issues and open pull requests.

if you want something, make a feature request, the better you describe the problem (and solution) the higher chance there is someone will develop it.

you can of course submit yourself as well a pull request implementing something.

**Comment by arbuilder** [comment]
>if you want something, make a feature request, the better you describe the problem (and solution) the higher chance there is someone will develop it.

thanks, i will create a detailed feature request later
