### ISSUE TITLE
Feature request: Sync per Plex User

### ISSUE THREAD

**Issue by rijsab** [Taxel/PlexTraktSync#365]
### Sync per Plex user

Sync per Plex user for shared libraries
### Use case

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

I have a Plex library sharing with family. I want to sync to Trakt and back to Plex per user. 

### Workarounds

_Is there an existing workaround to accomplish this?_
Currently only Trakt on Kodk
### Plan to implement

_Are you interested in submitting a PR to implement this?_

**Comment by glensc** [comment]
> ### Workarounds
> _Is there an existing workaround to accomplish this?_
> Currently only Trakt on Kodk

Yes, there is: you set up multiple instances of PlexTraktSync with different tokens.

**Comment by glensc** [comment]
@rijsab is the workaround what you want or you have something else in mind?
