### ISSUE TITLE
.pytrakt.json is created after running main.py

### ISSUE THREAD

**Issue by d3lac** [Taxel/PlexTraktSync#368]
### The problem

There is no `.pytrakt.json` file created. Also, `.env` has plex and trakt username as None (is this expected?)

### Expected behavior

Successfully setting up sync

### Steps to reproduce the behavior

https://github.com/Taxel/PlexTraktSync#setup

After setting up Trakt new API app and running `python3 main.py` there is no `.pytrakt.json` file created. Also, `.env` has plex and trakt username as None (is this expected?)

Screenshot of .env (PLEX_BASEURL, PLEX_FALLBACKURL and PLEX_TOKEN values have been redacted):

![](https://i.ibb.co/cvJtH79/df-AGTm-WNSW.png)

### Workarounds

None

### Environment

- Version: 0.12.18
- Python version: 3.7.3
- Platform: Debian 10

**Comment by twolaw** [comment]
Can you show the full console output of the script ?
Is config.json created? 
If yes, can you open it and set debug to true, then run script again and show the output?

**Comment by d3lac** [comment]
Very odd.

I enabled debugging on config.json and re-ran `main.py` and everything was all set.

**Comment by glensc** [comment]
what does it mean "everything was all set"? the bug no longer exists?

**Comment by glensc** [comment]
I'm unable to reproduce this.

with such setup:
1. removed `.pytrakt.json`
2. `.env` with `PLEX_USERNAME=None`, `TRAKT_USERNAME=None`
3. version `0.12.18`

running the app will ask for trakt credentials.

```
➔ python3 main.py
INFO: PlexTraktSync [8a7c0ef9: Merge pull request #311 from glensc/requests-cache==0.7.0.dev289 @2021-06-23 19:26:51]
Sign in to Trakt
If you do not have a client ID and secret. Please visit the following url to create them.
  https://trakt.tv/oauth/applications

Please enter your client id: ^C
```

**Comment by d3lac** [comment]
`.pytrakt.json` and `.env` files got created as expected, I fixed the trakt client id and secret. I ran `plex_trakt_sync.sh` and the sync was complete.
