### ISSUE TITLE
Feature request: Remove deleted items from Trakt collection

### ISSUE THREAD

**Issue by rfgamaral** [Taxel/PlexTraktSync#374]
### Feature description

I just deleted an entire TV Show from my Plex server, ran PlexTraktSync, and noticed that that show's episodes remain collected at Trakt.tv. I'd like to use the "Collection" feature on Trakt to keep track of the items I currently have on my Plex server. If any Movie or TV Show / Episode is deleted from the server, I'd like it to be deleted from Trakt collection as well.

### Use case

Explained above.

### Workarounds

_Is there an existing workaround to accomplish this?_

A workaround is to use the [clear collections](https://github.com/Taxel/PlexTraktSync/blob/main/plextraktsync/commands/clear_collections.py) command at regular intervals (eg. every month).
The next sync then recreates the Trakt collection up-to-date.

### Plan to implement

_Are you interested in submitting a PR to implement this?_

Python's not my thing.

**Comment by glensc** [comment]
This is not how this applocation works. I don't think this is not doable, there's no way to match `<nothing>` to `<trakt>`.

How the current sync logic works is:
1. take media items from plex
2. match with trakt
3. do sync actions

Perhaps it's doable to integrate to `watch` command and intercept "delete" event.

**Comment by rfgamaral** [comment]
I'm not sure if I understand what you're saying, but [Plex-Trakt-Scrobbler](https://github.com/trakt/Plex-Trakt-Scrobbler) does it. Like I said, Python is not my thing, so I don't really understand how they are doing it.

**Comment by mcdallas** [comment]
This can be done by querying trakt for all collected items and deleting those that are not present in the server.

But what about people that have split collection for example multiple servers or they have DVDs/Bluerays? I feel this should be behind a configuration option i.e sync_collections = ‘push’ vs ‘bidirectional’

**Comment by twolaw** [comment]
Keep in mind that a partial sync could remove trakt collected status of items not in the current synced Plex libraries.
So this removal operation should be processed only with a full sync.

**Comment by rfgamaral** [comment]
I just wanted to bump this feature request with another alternative approach on how this could be implemented.

A local collection cache could be kept with movies/episodes that are sent to the Trakt collection, and on the next run, compare the local collection cache with movies/episodes from Plex. Every movie/episode that comes from Plex, and is not found in the local collection cache, should be removed from Trakt collection.

For this approach to work in every scenario, the Trakt collection should probably be completely pruned in the first run (i.e., when there is no local collection cache).

@glensc @twolaw What do you think of this approach?

**Comment by twolaw** [comment]
> A local collection cache could be kept with movies/episodes that are sent to the Trakt collection, and on the next run, compare the local collection cache with movies/episodes from Plex. 

I don't think a local db is needed, Trakt API can provide the [collection](https://trakt.docs.apiary.io/#reference/sync/get-collection/get-collection) content directly.

**Comment by erikt311** [comment]
This is the one remaining piece to my Plex, Sonarr/Radarr, Trakt automation. 

I can control everything that gets added to Plex via Trakt now (and can also control automatic deleting of media if I remove it from the Trakt collection manually). 

However, for my use case (single user, don’t keep media after watching), I’d really like to automate that final step of deletion. 

I can have Plex delete the files automatically after watching, but this doesn’t get removed from the Trakt collection, which means my Trakt collection just continuously grows and is out of sync. 

https://github.com/trakt/Plex-Trakt-Scrobbler appears to be able to do that piece, but it hasn’t been updated in quite a while and reportedly has issues with the new media agents in Plex. 

Would it be possible to look into how they are doing that step and do that in this script somewhere? 

Or does anyone have any other strategies that work for automatically syncing deleted media?

**Comment by sanjeevneo** [comment]
I don't know python - but I have been able to pull records from trakt `https://api.trakt.tv/sync/collection/[movies, shows]` collection and do a bulk compare of IMDB IDs with Plex then remove anything that doesn't match `https://api.trakt.tv/sync/collection/remove`

**Comment by glensc** [comment]
> I don't know python

so, share whatever language you have the code, converting to a different language is piece of cake usually.

**Comment by sanjeevneo** [comment]
> > I don't know python
> 
> so, share whatever language you have the code, converting to a different language is piece of cake usually.

basic working code

```php #Get Trakt Collection
$collection = json_decode($response, true);

#Build Collection Array
for ($i=0; $i < count($collection); $i++) {
  $cMovies[] = array('imdb' => $collection[$i]['movie']['ids']['imdb'],
                    'payload' => $collection[$i]);
}

# Match and Build Payload
foreach ($cMovies as $traktMovie) {
  foreach ($plexIMDB as $pleMovie) {
    if (in_array($pleMovie, array($traktMovie['imdb']))) {
      $cleanPayload[] = $traktMovie['payload'];
    }
  }
}

send_to_remove($cleanPayload);`

**Comment by glensc** [comment]
Btw,there is a workaround. You can clear all your collections and let resync.

- https://github.com/Taxel/PlexTraktSync/blob/0.18.2/plextraktsync/commands/clear_collections.py

You may want to increase --batch-size while doing sync, to prevent rate limit being hit too soon.

**Comment by glensc** [comment]
Delete support was added to watch command:
- https://github.com/Taxel/PlexTraktSync/pull/703

Submit documentation update pr if you tested that it works.

**Comment by wraith1385** [comment]
@glensc I tried this but it never removed the item from my collection.  Below is the only output I received.  I never got the removed from collection message.  

rect:32400/:/websockets/notifications?X-Plex-Token=<hidden>
INFO: Deleted New Amsterdam (2018) S04 E11

This is the watch section of my config.json:
    "watch": {
        "scrobble_threshold": 100,
        "add_collection": false,
        "remove_collection": true,
        "username_filter": true
    },

**Comment by glensc** [comment]
@wraith1385 did you enable it in the config? as the second message "Removed from Collection" is missing. see the example output in https://github.com/Taxel/PlexTraktSync/pull/703

perhaps you edited wrong config file? `plextraktsync info` to find config location.

**Comment by wraith1385** [comment]
@glensc yeah that section at the bottom of my comment is directly from my config.  It's the correct file because I have some other libraries ignored for sync in that file and that works.

**Comment by glensc** [comment]
The other reason could be that plex already deleted item by the time watch agent polled it and the item was not found:
- https://github.com/Taxel/PlexTraktSync/blob/78c33c1737c27528d740543d7c02a5bdd0ec90fe/plextraktsync/commands/watch.py#L89-L98

Add some debug code a round this block:

```py
        m = self.find_by_key(event.item_id)
        if not m:
            print(f"Item not found: {event.item_id}")
            return
```

**Comment by doopsuiker** [comment]
I also experience this "problem".
I added some suggested code and this is the result while deleting a season.
The strange part is that the second episode is not even mentioned.

Code
`        m = self.find_by_key(event.item_id)
        if not m:
            self.logger.error(f"Could not delete {event.title}")
            return`

Log
`2022-01-25 08:57:56,432 INFO[PlexTraktSync.WatchStateUpdater]:Deleted The Crown S01 E01
2022-01-25 08:57:57,931 ERROR[PlexTraktSync.WatchStateUpdater]:Could not delete The Crown S01 E01
2022-01-25 08:57:58,594 INFO[PlexTraktSync.WatchStateUpdater]:Deleted 
2022-01-25 08:57:58,785 ERROR[PlexTraktSync.WatchStateUpdater]:Could not delete `

**Comment by glensc** [comment]
@doopsuiker please edit your post, put code between three backticks block (```) to preserve formatting. so someone else can copy your code fragment:
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by doopsuiker** [comment]
@glensc 
edited

**Comment by glensc** [comment]
I can conclude that then this approach doesn't work. the watch command calls the API too late, when it's already deleted from Plex. May need to pre-cache items locally.

**Comment by glensc** [comment]
@doopsuiker your code is wrongly indented, you always `return`. the `return` should be indented with the error case. see my original post again.

**Comment by doopsuiker** [comment]
@glensc 
it was only wrongly indented in the example not in watch.py, but thanks for noticing

**Comment by nicopz5** [comment]
How can I use the clear collections command to delete my entire collection? I do not know how it works.

**Comment by glensc** [comment]
Anyone to test if clear_collections batching now works:
- https://github.com/Taxel/PlexTraktSync/pull/1326

I don't have a test trakt account, so I will not test this.

**Comment by rfgamaral** [comment]
@glensc I'm not clear on what exactly that does, care to explain, please?

**Comment by glensc** [comment]
With 0.25.6 release clear collections uses batching. So it should be a lot faster now.

**Comment by rfgamaral** [comment]
@glensc So, the idea here is, to clear the collections before syncing them to Trakt, so that the collection on Trakt always match what's on Plex, is that it? Just trying to clarify, as I'm a bit confused if this issue can be considered/fixed/closed, or not.

**Comment by glensc** [comment]
yes, that's just the workaround, and it's been made faster.

if that's an acceptable workaround, then making code that does the same automatically shouldn't be that hard:
- `plextraktsync clear-collections --keep-plex`
- take trakt.movie_collection, trakt.show_collection, create set()
- take plex movie collection, plex show collection, create set()
- do intersect of trakt - plex
- remove items from trakt that are in the remaining set

**Comment by rfgamaral** [comment]
@glensc A few observations from my testing:

- There's no such thing as `--keep-plex` (I also can't find this documented anywhere)
- I had to use `--confirm` instead (or `--dry-run`)
- With the current implementation, I'm forced to run `clear-collections` **first**, and afterwards run `sync`, correct?
    - I was expecting the collections to be removed when the `sync` command was used. I have the `sync` command running periodically (with ofelia, as recommended in the README), and I was hoping to keep my collections always up-to-date with a single command.
        - I guess a workaround is to use this command in ofelia:
          `python -m plextraktsync clear-collections --confirm && python -m plextraktsync sync`
- By implementing this periodic mechanism of "clear collections, sync collections back to trakt", the `add_collection` and `remove_collection` options for the `watch` command feels a bit pointless (because everything in the collections will be cleared with `clear-collections` and synced again). I mean, one can always keep using them to have collections up-to-date in real time.
    - However, I believe I found a bug in the `remove_collection` option:
        ```
        2023-01-12 12:17:07,981 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'timeline', 'size': 1, 'TimelineEntry': [{'identifier': 'com.plexapp.plugins.library', 'sectionID': '3', 'itemID': '3455', 'parentItemID': '3450', 'rootItemID': '3449', 'type': 4, 'title': 'The Walking Dead S06 E05', 'state': 9, 'metadataState': 'deleted', 'updatedAt': 1673525827}]}
        2023-01-12 12:17:07,981 INFO[PlexTraktSync.WatchStateUpdater]:on_delete: Deleted on Plex: 3455: The Walking Dead S06 E05
        2023-01-12 12:17:07,984 DEBUG[plexapi]:GET https://10-0-1-25.[REDACTED]].plex.direct:32400/library
        2023-01-12 12:17:07,987 DEBUG[requests_cache.policy.actions]:Cache directives from request headers: {}
        2023-01-12 12:17:07,987 DEBUG[requests_cache.policy.actions]:URL https://10-0-1-25.[REDACTED]].plex.direct:32400/library matched pattern "*/library": 0
        2023-01-12 12:17:07,989 DEBUG[urllib3.connectionpool]:Resetting dropped connection: 10-0-1-25.[REDACTED]].plex.direct
        2023-01-12 12:17:08,026 DEBUG[urllib3.connectionpool]:https://10-0-1-25.[REDACTED]].plex.direct:32400 "GET /library HTTP/1.1" 200 289
        2023-01-12 12:17:08,028 DEBUG[requests_cache.session]:Pre-cache checks for response from https://10-0-1-25.[REDACTED]].plex.direct:32400/library: {'disabled cache': False, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': True}
        2023-01-12 12:17:08,028 DEBUG[requests_cache.session]:Skipping cache write for URL: https://10-0-1-25.[REDACTED]].plex.direct:32400/library
        2023-01-12 12:17:08,028 DEBUG[plexapi]:GET https://10-0-1-25.[REDACTED]].plex.direct:32400/library/metadata/3455
        2023-01-12 12:17:08,030 DEBUG[requests_cache.policy.actions]:Cache directives from request headers: {}
        2023-01-12 12:17:08,031 DEBUG[requests_cache.policy.actions]:URL https://10-0-1-25.[REDACTED]].plex.direct:32400/library/metadata/3455 matched pattern "*/library/metadata/*": 0
        2023-01-12 12:17:08,044 DEBUG[urllib3.connectionpool]:https://10-0-1-25.[REDACTED]].plex.direct:32400 "GET /library/metadata/3455 HTTP/1.1" 404 78
        2023-01-12 12:17:08,045 DEBUG[requests_cache.session]:Pre-cache checks for response from https://10-0-1-25.[REDACTED]].plex.direct:32400/library/metadata/3455: {'disabled cache': False, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': True}
        2023-01-12 12:17:08,045 DEBUG[requests_cache.session]:Skipping cache write for URL: https://10-0-1-25.[REDACTED]].plex.direct:32400/library/metadata/3455
        2023-01-12 12:17:08,045 ERROR[PlexTraktSync.EventDispatcher]:AttributeError was raised: 'NoneType' object has no attribute 'library'
        2023-01-12 12:17:08,143 DEBUG[PlexTraktSync.EventDispatcher]:['  File "/app/plextraktsync/listener.py", line 40, in dispatch\n    listener["listener"](event)\n', '  File "/app/plextraktsync/commands/watch.py", line 184, in on_delete\n    m = self.find_by_key(event.item_id)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n', '  File "/app/plextraktsync/commands/watch.py", line 143, in find_by_key\n    if pm.library is None:\n       ^^^^^^^^^^\n']
        ```

**Comment by glensc** [comment]
1. There's no such thing as --keep-plex, I [posted](https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1380076905) an idea for an implementation plan
2. Please report bugs as new issues. Separate logs for sync and watch commands to be understandable.
4. Unclear did your clear-collections  work properly or not
5. not sure what you mean collections to be removed, you mean plex collections? https://support.plex.tv/articles/201273953-collections/. clear collections command clears "collected" state in trakt only.

**Comment by rfgamaral** [comment]
This mechanism works, but I have to run 2 commands, and in a specific order:

- `plextraktsync clear-collections --confirm`
- `plextraktsync sync`

This doesn't bother me that much, but IMO it would make more sense if the sync command had an option to clear collections before sync them again.

> There's no such thing as --keep-plex, I https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1380076905 an idea for an implementation plan

Oh, I get it now, and I think it makes sense to implement this. 👍 I just think the `--keep-plex` name is a bit confusing, but I don't have a better suggestion right now.

**Comment by glensc** [comment]
Do you have info on how much faster `plextraktsync clear-collections --confirm` is now and before? for comparison include the approximate number, and how many items were to be deleted. It's to satisfy curiosity about how good the background queue submit code is.

or if you enable debug log, this grep should give timing and counts:
```
$ grep Submitted plextraktsync.log
```

**Comment by rfgamaral** [comment]
I have around 400+ movies, 8 TV Shows (around 100+ episodes), and syncing usually takes around ~1min for me, including adding everything to collections. Before syncing, I clear all collections (as mentioned above with the 2 commands that I run), and for me that takes around ~2-3seconds. I can't compare to before because I wasn't using this feature before.

I don't have a huge collection like other people might have, so I'm not the best person to benchmark this, but this looks acceptable to me, and seems pretty fast. Good job 👍

**Comment by glensc** [comment]
### It's not that easy seems it is

The original plan was to:
1. take trakt.movie_collection
2. find plex match
3. check if omit

but the problem is that plex doesn't offer a way to find by trakt id, so a search by title is performed:
- https://github.com/Taxel/PlexTraktSync/blob/90329c6575cfde7bc6d68615083403d29319c9a4/plextraktsync/media.py#L282

well, it alt east does check that guid matches:
- https://github.com/Taxel/PlexTraktSync/blob/90329c6575cfde7bc6d68615083403d29319c9a4/plextraktsync/media.py#L289-L295

but it may omit some titles that are totally different plex vs trakt:
- "The Vortex": https://trakt.tv/movies/the-vortex-2012
- "Big Bad Bugs": https://app.plex.tv/desktop/#!/provider/tv.plex.provider.vod/details?key=%2Flibrary%2Fmetadata%2F60185c5891c237002b37653d

that's for Plex Discover title, butsince it searches your media, you can have totally different titles (perhaps by filename.mkv) or even localized.

so need to do different (slower?) approach:
1. fetch all media from plex (like sync command does)
2. match against trakt.movie_collection
3. voila!

**Comment by glensc** [comment]
@rfgamaral seems you didn't report your NoneType bug as separate issue.

**Comment by glensc** [comment]
clear for movies:
- https://github.com/Taxel/PlexTraktSync/pull/1363

you can test this, currently enabled for movies only.

for shows the "clear_collections" used shows, but you can collect individual episodes, so the sync command should clear collection state for episodes, not shows. right?
