### ISSUE TITLE
Warnings not on separate line

### ISSUE THREAD

**Issue by hawkeone** [Taxel/PlexTraktSync#377]
### The problem
Some warnings are appended to the processing line rather than entered as a separate lien above.
![image](https://user-images.githubusercontent.com/87250193/125184368-64c06400-e260-11eb-9835-f0c938541a80.png)

### Expected behavior

Each warning displayed on a sperate line, with the processing lien beneath them.

### Steps to reproduce the behavior

Run sync as per normal.

### Workarounds

No

### Environment

- Version: 0.13.2
- Python version: 3.9.1
- Platform: Windows 10

**Comment by glensc** [comment]
won't fix, too complicated

however, the problem may go away if rendering library is replaced: https://github.com/Taxel/PlexTraktSync/pull/271

**Comment by hawkeone** [comment]
Thanks for the response and you work on this project. Rich looks like it has potential to add value, however it doesn't seem to fix this issue:
![image](https://user-images.githubusercontent.com/87250193/125256378-bd1a6300-e33f-11eb-8e74-2504f3b82af7.png)

**Comment by sirloinofbeef** [comment]
Interestingly this does not seem to happen since upgrading to Windows 11.

**Comment by glensc** [comment]
because it was solved in #386.
