### ISSUE TITLE
Certain movies "watched status" are being added multiple times to Plex history

### ISSUE THREAD

**Issue by rfgamaral** [Taxel/PlexTraktSync#384]
### The problem

Certain movies "watched status" are being added multiple times, here's an example:

```
amaral@HYPERCUBE:~/.local/scripts/PlexTraktSync$ pipenv run python main.py sync --sync movies
Loading .env environment variables...
INFO: PlexTraktSync [5dfc1801: Merge pull request #382 from glensc/Pipfile.lock-regenerate @2021-07-14 11:58:37]
INFO: Syncing with Plex redacted@domain.com and Trakt <redacted>
Sync Movies: True
Sync Shows: False
INFO: Loaded Trakt lists in 3.8 seconds
Plex Server version: 1.23.5.4801-bc4dd58bb, updated at: 2021-07-15 12:30:49
Server has 2 libraries: ['Movies', 'TV Shows']
Processing Movies  [###---------------------------------]  22/229  00:00:23INFO: Marking as watched in Plex: <tmdb:497698:<Movie:5121:Black-Widow>>
Processing Movies  [###############---------------------]  100/229  00:00:14INFO: Marking as watched in Plex: <tmdb:512200:<Movie:3118:Jumanji:-The-Next-Le>>
Processing Movies  [###################################-]  226/229  00:00:00INFO: Marking as watched in Plex: <tmdb:637649:<Movie:3249:Wrath-of-Man>>
Processing Movies  [####################################]  229/229
INFO: Movies processed in 30.2 seconds
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 34.1 seconds
amaral@HYPERCUBE:~/.local/scripts/PlexTraktSync$ pipenv run python main.py sync --sync movies
Loading .env environment variables...
INFO: PlexTraktSync [5dfc1801: Merge pull request #382 from glensc/Pipfile.lock-regenerate @2021-07-14 11:58:37]
INFO: Syncing with Plex <redacted@domain.com> and Trakt <redacted>
Sync Movies: True
Sync Shows: False
INFO: Loaded Trakt lists in 3.0 seconds
Plex Server version: 1.23.5.4801-bc4dd58bb, updated at: 2021-07-15 12:30:49
Server has 2 libraries: ['Movies', 'TV Shows']
Processing Movies  [###---------------------------------]  22/229  00:00:23INFO: Marking as watched in Plex: <tmdb:497698:<Movie:5121:Black-Widow>>
Processing Movies  [###############---------------------]  100/229  00:00:14INFO: Marking as watched in Plex: <tmdb:512200:<Movie:3118:Jumanji:-The-Next-Le>>
Processing Movies  [###################################-]  226/229  00:00:00INFO: Marking as watched in Plex: <tmdb:637649:<Movie:3249:Wrath-of-Man>>
Processing Movies  [####################################]  229/229
INFO: Movies processed in 30.4 seconds
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 33.4 seconds
```

What do these specific movies have in common, you might ask? I simply went to Trakt.tv website, and added something to my history, like this:

![image](https://user-images.githubusercontent.com/96476/125835534-ec0414bd-f432-43e2-83e5-7ed1b4174206.png)

So, **every time I run** `pipenv run python main.py sync --sync movies` (or just `pipenv run python main.py`), the movies that were added to my Trakt.tv history, are going to be added multiple times to my Plex history.

### Expected behavior

Movies/episodes should only be added **once** to the Plex watched history when syncing the history from the Trakt.tv website.

### Steps to reproduce the behavior

Not sure, I've only followed the instructions to install PlexTraktSync and configured my setup like this:

```json
{
  "log_debug_messages": false,
  "logging": {
    "append": false
  },
  "sync": {
    "liked_lists": false,
    "watchlist": false,
    "watched_status": true,
    "collection": false,
    "ratings": false
  },
  "xbmc-providers": {
    "movies": "imdb",
    "shows": "tvdb"
  },
  "excluded-libraries": [
    "Samples"
  ]
}
```

### Workarounds

Avoid running the script and mark "as played" manually on Plex.

### Environment

- Version: `main`
- Python version: `3.8.8`
- Platform: `synology_apollolake_918+`

**Comment by twolaw** [comment]
@glensc i'm not sure but maybe a plex request is cached and should not ?
https://github.com/Taxel/PlexTraktSync/pull/342#issuecomment-867019619

**Comment by flammable** [comment]
I'm seeing something very similar. Certain TV episodes are marked as 'watched' each time I run the script.

**Comment by glensc** [comment]
does deleting `trakt_cache.sqlite` help?

**Comment by glensc** [comment]
If it's cache related, the workaround is to use a version older than 0.13.0

**Comment by flammable** [comment]
Good idea, but deleting the cache does not prevent the problematic items from being marked with each sync.

**Comment by glensc** [comment]
@flammable what exactly is a good idea? the delete cache was a suggestion to better bisect the problem. did the problem go away with cache deletion? did the problem go away with an older version?

please be distinct and transparent.

**Comment by flammable** [comment]
Sorry, language barrier, I think. It was a good suggestion to delete the cache, but unfortunately, it does not work to fix this issue. After deleting the cache, the same items are still repeatedly synched as 'watched' in Trakt.

I have not tried downgrading, but I think I've had this issue for a while. The same shows have many, many 'watches' on Trakt for me, as I have the script running once per hour.

**Comment by mcdallas** [comment]
This has been bugging me for a while, as a temporary fix I nuke the cache everytime I run the sync as a part of my sync script.

**Comment by glensc** [comment]
rather deleting cache, why not confirm does the workaround apply:
- https://github.com/Taxel/PlexTraktSync/issues/384#issuecomment-882426483

**Comment by mcdallas** [comment]
I run git-bisect on it, 7ed55909e52b5ca0b046e56af4cff67c4be59e50 is where the issue begins, everything before it doesn't have the problem

**Comment by glensc** [comment]
You need to bisect with pull request granularity. as I usually make atomic commits, the actual change that is having the effect is committed before the commit that activates the change.

- https://www.freshconsulting.com/insights/blog/atomic-commits/
