### ISSUE TITLE
Cache Preventing TV Show Watched Sync

### ISSUE THREAD

**Issue by n810K** [Taxel/PlexTraktSync#387]
### The problem

I am currently working through a show. I have the sync set to run every night at 3:00AM. The sync does not appear to properly mark watched episodes on Trakt. Even after manually running the sync, the episodes do not get marked as "watched". The solution that I've found is to delete the cache file then run the sync again for the episodes to be properly marked.

### Expected behavior

Episodes within a show do not properly get marked as watched

### Steps to reproduce the behavior

1) Watch an episode
2) Run the script -> Notice that the episode does not get marked on Trakt
3) Delete cache file then run script again
4) Longer run time but the episode is now properly marked as watched.

### Workarounds

1) Delete cache file then run script again
2) Longer run time but the episode is now properly marked as watched.

### Environment

- Version: 0.13.3
- Python version: 3.8
- Platform: Windows

**Comment by rfgamaral** [comment]
I have a feeling this is somewhat related to #384.

**Comment by glensc** [comment]
Which agent are you using?

**Comment by flammable** [comment]
I'm seeing this with both movies and TV shows. In both cases, deleting the cache allows the sync to proceed.

I'm using the new movie and TV agents in Plex. I'm using version 0.13.3 of the script, Python version 3.9.6, and my platform is macOS 11.4.

Please let me know if I can provide more details to troubleshoot!

**Comment by glensc** [comment]
@flammable I'm sure then it's related to cached plex requests as @twolaw suggested:
- https://github.com/Taxel/PlexTraktSync/issues/384#issuecomment-881047027

seems, it affects only new agents (I tested with legacy agent myself).

(someone) needs to debug what (extra) requests plex makes for a new agent. as for legacy agents, all movie details were given with library feed, and that request is not cached.

as a workaround use any version that's older than 0.13.0

**Comment by flammable** [comment]
That sounds reasonable. I'm facing both issues, so it was hard to tell if they're part of the same problem: when I watch new movies and TV shows, they don't sync to Trakt unless I delete the cache (this issue), and every time I perform a sync, some TV shows are repeatedly marked as watched (#384).

Are there any logs I can provide to help solve this issue? Is there a way to enable debugging in the script to provide more detailed output? Thanks for all of your work on this.

**Comment by glensc** [comment]
I think it's best to mail down a commit that causes the breakage. you can try to use --show or --movie parameter to sync only a specific item. but beware that those options ignore configured libraries, and perform search and sync on all libraries (ignoring config.json)

I'm pretty sure it's the 0.13.0 release that breaks it as outlined earlier.

You can enable debug in config.json and analyze the last_update.log yourself, if you find something useful from there, then provide it.

**Comment by n810K** [comment]
I've enabled debugging and have produced the last_update.log for a show that I have been watching. I manually ran --show to select the specific item.

Is there anything specific that I should look for within the log file?

**Comment by glensc** [comment]
it was asked to downgrade to older than 0.13.0, have you done that and confirmed that it solves anything?

if you can't figure out what to share from debug log, don't bother with it and use the workaroundd.

**Comment by n810K** [comment]
Yep, downgrading to below 0.13.0 has fixed the problem.

**Comment by Scales82** [comment]
Below 0.13.0? or are you using 13. I've the same problem

**Comment by glensc** [comment]
anything below 0.13.0. 0.13.0 is affected by this bug.
