### ISSUE TITLE
Question: Syncing only main account

### ISSUE THREAD

**Issue by esticle** [Taxel/PlexTraktSync#388]
A silly question -

I'm keen on syncing my collections/watched items of my main account only - and not that of my other users.

When I answer 'N' to "Do you want to use managed user instead of main account?" - my trakt of course updates with what   everybody is watching.

When I answer 'Y' to "Do you want to use managed user instead of main account?" - my main account is not listed as a 'Managed user' (rightfully so).

Thanks!

**Comment by flammable** [comment]
That's strange. If you answer 'N', it's supposed to only track your main account (that's what it does for me). My Trakt history doesn't include what everyone else is watching.

**Comment by glensc** [comment]
my experience has been similar to @flammable, answering `N` syncs only main account (my account).

**Comment by esticle** [comment]
Thanks for confirming @flammable & @glensc - that is curious!

Does your .env file possibly have PLEX_USERNAME populated? (Presumably only answering 'Y' does that).

In the mean-time I've edited config.json to log debug messages to hopefully shed some light!

**Comment by flammable** [comment]
It does, but I honestly can't remember if I manually edited it in there. Probably worth a shot.

**Comment by glensc** [comment]
I have PLEX_USERNAME filled, initial configuration will always fill it with the main account or any managed user account.

what's the value there for you? (obfuscate it for privacy)

**Comment by esticle** [comment]
> I have PLEX_USERNAME filled, initial configuration will always fill it with the main account or any managed user account.
> 
> what's the value there for you? (obfuscate it for privacy)

Mine was a empty declaration - I filled it in - so will see if that helps, thanks!

**Comment by twolaw** [comment]
Plex username is stored only to help user to easily identify which account is used when reading logs or output. It is not needed for communication with Plex API.

**Comment by esticle** [comment]
Okay, so definitely happening for me - here is the last two plays on my server (Tautulli screenshot) - my main user being the 'SHIELD' user:

![image](https://user-images.githubusercontent.com/8289941/126394654-6fe37ff0-19af-4b7d-8663-68abe5cf5705.png)

Trakt shows both as played whilst I (the main user) only played one:

![image](https://user-images.githubusercontent.com/8289941/126394747-a5f2cb64-a28d-4365-bd6c-2b441c348db7.png)

The last_update.log created with debug mode on is quite verbose but I did not spot the content being mentioned.

**Comment by flammable** [comment]
Hmm, I'm not seeing the 'User' column in the screenshot. Are both of those entries for the same user?

**Comment by esticle** [comment]
> Hmm, I'm not seeing the 'User' column in the screenshot. Are both of those entries for the same user?

Yeah did not want to share the user column - but no, they are different users who played content - both being shown in the history of the main user's Trakt account.

**Comment by twolaw** [comment]
> Trakt shows both as played whilst I (the main user) only played one

Which one? You should give much more details.
Also give informations about users of your plex account. That's the point of this issue right?

You can copy full logs on a pastebin and give us the url.

**Comment by esticle** [comment]
Okay, so fresh install with 0.13.5 with main user only.

This is my trakt.tv history before running PlexTraktSync:

https://paste.pics/807e2466f92565f91b35ca21597eed05

This is my Tautilli history before running PlexTraktSync - I am 'fbxor' (the main) user and the only users content I wish to have in my trakt.tv history:

https://paste.pics/6db3719c42243c4e9498022241cedd1f

As I run plex_trakt_sync.sh I get all the last plays in my trakt.tv history

```
# ./plex_trakt_sync.sh 
INFO: Syncing with Plex None and Trakt estagaxorus
Sync Movies: True
Sync Shows: True
INFO: Loaded Trakt lists in 12.0 seconds
INFO: Downloaded List Trakt Watchlist
Plex Server version: 1.23.5.4841-549599676, updated at: 2021-07-21 05:13:29
Server has 3 libraries: ['Movies', 'TV Shows', 'Music']
<snip...>
Processing TV Shows: 100%|████████████████████████████████| 1831/1831 [06:58<00:00,  4.38it/s]
INFO: TV Shows processed in 7 min 0.9 seconds
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 9 min 57.5 seconds

```
The 24MB debug log file will not share on pastebin - let me know if particular fields would be helpful or otherwise which log level would be useful.

After running the above, my trakt.tv history looks like this:

https://paste.pics/382a37ec24177196afa1b777937bc98c

Here's something strange - when I look at my Plex server's history I see this:

https://paste.pics/685a01d168006f1f365ce6bf741ef8c6

Where you can see that PlexTraktSync "played" some content with the player being the hostname of the instance.

Thanks

**Comment by keldian** [comment]
I have this issue in scrobbling mode (but sync works as expected). Any way to tell the script not to scrobble what managed users are watching?

**Comment by twolaw** [comment]
@keldian about your issue in scrobbling mode, please go here :
- https://github.com/Taxel/PlexTraktSync/issues/324

**Comment by Generator** [comment]
Having the same issue
.env: 
```
# This is .env file for PlexTraktSync
PLEX_BASEURL=https://**********28530e62131acac.plex.direct:32400                  
PLEX_FALLBACKURL=http://localhost:32400
PLEX_TOKEN=****************
PLEX_USERNAME=American_Jesus
TRAKT_USERNAME=American_Jesus
```

Tested with Plex dummy account. Items are sync to main (Trakt) account when other accounts watch any item.

**Comment by glensc** [comment]
@Generator what is the "same"? it came to attention (if you follow the discussion), that problem appears with "watch" command, not "sync" command.

**Comment by Generator** [comment]
@glensc yes all items are scrobbled from all users when using ```main.py watch```

**Comment by glensc** [comment]
Scrobble syncing all users is already a known issue:
- https://github.com/Taxel/PlexTraktSync/issues/324

no point reporting it anymore as filtering by users is not implemented. you're welcome to send your implementation.

**Comment by twolaw** [comment]
> that problem appears with "watch" command, not "sync" command.

In https://github.com/Taxel/PlexTraktSync/issues/388#issuecomment-885582445 esticle says he runs this command :
`# ./plex_trakt_sync.sh `

In this issue, nobody (before you) talks about a bug with scrobble or watch command.

**Comment by agneevX** [comment]
@glensc its probably a good idea to restrict scrobbling to main user only, by default.

**Comment by glensc** [comment]
This issue is not about scribbling.

Closing as outdated.

Here's no version information, also multiple and different topics mixed up in a discussion.

Please create a new issue if the problem persists.

If you want to change the default, you send a pull request.
