### ISSUE TITLE
Feature request: Simplify / unify config

### ISSUE THREAD

**Issue by chrillep** [Taxel/PlexTraktSync#391]
### Feature description
as user i want to be able to just change settings in one precommented file to get things to work
### Use case

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

easier setup, copy of settings.

I wanted to try and get the sync working in a github workflow / action
As you can set cron on workflows....
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events

It be a lot easier with just having to add settings to one file eg. ".env"

### Workarounds

_Is there an existing workaround to accomplish this?_
not sure

### Plan to implement

_Are you interested in submitting a PR to implement this?_

maybe, proboably be best with just .env file with all settings.
If there isn't a good reason for multiple files.

**Comment by twolaw** [comment]
.env and .pytrakt.json are not supposed to be edited by user.
config.json is the only config file to be edited by user. That's why it is separated.

.pytrakt.json is written by trakt module so it cannot be merged with another file.

**Comment by chrillep** [comment]
aaah i c. then ui close the issue. I managed to get around it and run the app in the workflow by writing secrets ti .env and .pytrakt.json, not sure if this can be automated since running the main script requires human interaction.

maybe I'll create another feature Request  whete no human input/interaction is required. or is there any cli commands for no interaction?

**Comment by twolaw** [comment]
Human interaction is only needed to fetch trakt or plex tokens in a user-friendly way.
But you can get them by any other way without running the PlexTraktSync script.

https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
https://github.com/Taxel/PlexTraktSync/issues/75#issuecomment-705132268
https://trakt.docs.apiary.io/#reference/authentication-oauth
