### ISSUE TITLE
Publish Python package

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#414]
- [x] Create Python package: https://github.com/Taxel/PlexTraktSync/pull/263
- [x] Publish in pip: https://github.com/Taxel/PlexTraktSync/pull/510
  - https://pypi.org/project/PlexTraktSync/
- [ ] Document using it
  - [ ] `pip3 install plex-trakt-sync && plex-trakt-sync`
  - [ ] https://github.com/pypa/pipx

**Comment by chrillep** [comment]
just throwing it out here for reference

### Github actions
[Building and testing Python
](https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
)
[Publish Python Package
](https://github.com/actions/starter-workflows/blob/main/ci/python-publish.yml)Publish a Python Package to PyPI on release.

[Python package
](https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml)Create and test a Python package on multiple Python versions.

**Comment by glensc** [comment]
@chrillep there's some progress:
- https://github.com/Taxel/PlexTraktSync/pull/263

but I got stuck because the package created did not include source code.

**Comment by chrillep** [comment]
sorry but i'm no help here. Tried removing package_dir but then it only built files from plex_trakt_sync/ and sub directories :/ 

Really seems overly complicated :(

**Comment by glensc** [comment]
Github actions publish workflow works now:
- https://github.com/Taxel/PlexTraktSync/pull/510

however, @Taxel, to make things automatic,

1. please create yourself an account at https://pypi.org/
2. ensure your primary email is verified
1. optionally enable 2fa
2. create token: https://pypi.org/help/#apitoken
3. save token to secrets with name `PYPI_TOKEN`: https://github.com/Taxel/PlexTraktSync/settings/secrets/actions
4. let me know when done and I add you as a collaborator in pypi: https://pypi.org/manage/project/plextraktsync/collaboration/

**Comment by glensc** [comment]
@twolaw could you please repeat these steps:
- https://github.com/Taxel/PlexTraktSync/issues/414#issuecomment-927988277

and share to me your pypi.org account name, I'll add you as maintainer as well.

so you could publish pip package yourself by pushing git tag to your fork:

```
git tag 0.14.2
git push origin 0.14.2 # origin = your fork
```

**Comment by glensc** [comment]
Disabled the PyPI workflow for now:
- https://github.com/Taxel/PlexTraktSync/actions/workflows/pypi.yml

**Comment by Taxel** [comment]
@glensc I finally got around to creating the API token. It is a repo secret named PYPI_TOKEN. My account can be found [here](https://pypi.org/user/Taxel/)

**Comment by glensc** [comment]
@Taxel invite pending:
- https://pypi.org/manage/project/plextraktsync/collaboration/

**Comment by Taxel** [comment]
@glensc I have joined the project and recreated the API token so it is scoped to the project, not my entire account.

**Comment by glensc** [comment]
0.14.3 published with taxel token. so this can be closed. if twolaw wishes to be granted access, they can do this later.
