### ISSUE TITLE
Syncing Managed Users

### ISSUE THREAD

**Issue by tbkurtz** [Taxel/PlexTraktSync#42]
I am working on getting trakt and plex syncing again since the plugin stopped working.  I got the script working and it imported all the watches and collected to trakt that I've missed in the past few months - so thats great.  But, I have a separate library setup for Kids Movies, and the kids have a "managed user" that they watch their movies from.  Naturally, most of those movies remain unwatched on my normal plex account, and watched on the Kids managed user. 

I'd like to be able to sync the watch status from the managed user up to Trakt, so I can then sync down the watched status to my main account - so all the movies the kids have watched end up getting marked as watched on my normal account. 

Can the script support this scenario?

**Comment by twolaw** [comment]
No, but I added managed users handling in [this branch](https://github.com/twolaw/PlexTraktSync/tree/managed-users).
You can try it but be careful,  it's experimental.

You could try to copy 2 instances of PlexTraktSync in 2 distinct folders : one with your main plex account, the other one with your account but choose kids managed user during setup.
Then if you do the syncs alternatively, it could do the job. 🤞

**Comment by tbkurtz** [comment]
Excellent work, going to set it up tonight.  Will let you know.

**Comment by tbkurtz** [comment]
@twolaw Well, it worked, but re-running the main.py from the master branch took FOREVER, like over 8 hours.  And I cancelled one of the libraries because I thought it was hung.

**Comment by twolaw** [comment]
Can you give logs.
I tried at home with a managed user and it sucessfully synced.

**Comment by tbkurtz** [comment]
Where are the logs stored?

**Comment by twolaw** [comment]
When you face a problem like that, go read the logs to understand what's wrong.
If it happened only one time, it may have been a temporary connection issue.

Let it run some syncs a few days and then come back tell me if everything is ok. If yes I'll merge the code.

**Comment by tbkurtz** [comment]
I'm happy top dig through some logs, I just don't know where they are :)

**Comment by twolaw** [comment]
The file `last_update.log` in the script folder.

**Comment by tbkurtz** [comment]
I didn't see anything alarming in the last_update.log, and both the master and managed_user branches ran in an expect amount of time when I re-ran them today (~300 seconds)
