### ISSUE TITLE
Permission denied error when using  ./plex_trakt_sync.sh watch for windows Fixed by using py instead of python3

### ISSUE THREAD

**Issue by Chalanxe** [Taxel/PlexTraktSync#427]
# The problem

Getting permission denied in bash
```
/AppData/Local/Microsoft/WindowsApps/python3: Permission denied
```

# Expected behavior

```
./plex_trakt_sync.sh watch
Listening for events!
INFO: Starting AlertListener: 
```

# Steps to reproduce the behavior

Running
`./plex_trakt_sync.sh watch` command in powershell or bash

### Workarounds

_Is there an existing workaround for this issue?_

Using `py` instead of `python3` command in the `plex_trakt_sync.sh` file, ie

```
#!/bin/sh
set -eu

dir=$(dirname "$0")

exec py "$dir/main.py" "$@"
```

# Environment

- Version: 0.13.12
- Python version: 3.9
- Platform: Windows 10

**Comment by glensc** [comment]
show:

```
ls -l /AppData/Local/Microsoft/WindowsApps/python3
```

and 

```which
py
```

**Comment by Chalanxe** [comment]
Original  plex_trakt_sync.sh
#!/bin/sh
set -eu

dir=$(dirname "$0")

exec python3 "$dir/main.py" "$@"


Changed plex_trakt_sync.sh​
#!/bin/sh
set -eu

dir=$(dirname "$0")

exec py "$dir/main.py" "$@"


Script worked as expected after changing it

**Comment by glensc** [comment]
@Chalanxe can you please answer my questions:
- https://github.com/Taxel/PlexTraktSync/issues/427#issuecomment-894767244

changing `python3` -> `py` you already described in issue body, why repeat it as a command?

**Comment by Chalanxe** [comment]
ls -l /AppData/Local/Microsoft/WindowsApps/python3

AppData\Local\Microsoft\WindowsApps


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l         23/8/2020  10:22 PM              0 python3.exe



dont understand your 2nd question

**Comment by glensc** [comment]
Run the command `which py` or `type -p py` or `whereis py`

**Comment by glensc** [comment]
why is python3.exe 0 bytes, and what does the `l` mean? it's a symlink? of that's so can you look up where the link points to?

**Comment by Chalanxe** [comment]
> Run the command `which py` or `type -p py` or `whereis py`

the above commands return as error:which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ which py
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

i tried running the using py command
py
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>>
>>> print(sys.executable)
C:\Python39\python.exe

**Comment by twolaw** [comment]
You should write `which.exe py`

Those 0 bytes files are [aliases created by Microsoft](https://stackoverflow.com/questions/58754860/cmd-opens-window-store-when-i-type-python) so they can open Microsoft Store if software is not installed yet.

**Comment by glensc** [comment]
@Chalanxe you should format your code blocks:
- https://guides.github.com/features/mastering-markdown/

I've edited your previous posts, but seems you don't learn if you don't do that yourself personally.

**Comment by Chalanxe** [comment]
> @Chalanxe you should format your code blocks:
> 
> * https://guides.github.com/features/mastering-markdown/
> 
> I've edited your previous posts, but seems you don't learn if you don't do that yourself personally.

Noted sorry for the mess

**Comment by glensc** [comment]
Seem you got `python3` working...

**Comment by Chalanxe** [comment]
> Seem you got `python3` working...

Probably this
https://stackoverflow.com/questions/40914108/bash-python3-command-not-found-windows-discord-py

Only `py` manages to call the latest version of python on windows for my case.
I tried reinstalling python 3.9.6 and now only `py` works well. The installer also said to use `py` command for using python.
