### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Rickexe** [Taxel/PlexTraktSync#429]
Good day to you,

Everytime I run the sync script it gives me this error. 

`plexapi.exceptions.BadRequest: (500) internal_server_error; https://192-168-178-78.9b6e32b5292e44a0bd63d1e8dbd2aeb1.plex.direct:32400/library/metadata/21?checkFiles=1&includeAllConcerts=1&includeBandwidths=1&includeChapters=1&includeChildren=1&includeConcerts=1&includeExternalMedia=1&includeExtras=1&includeFields=thumbBlurHash%2CartBlurHash&includeGeolocation=1&includeLoudnessRamps=1&includeMarkers=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeRelated=1&includeRelatedCount=1&includeReviews=1&includeStations=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>`

I see that it's trying to access plex through my local ip address of the server. It should just be able to access it through that ip. I have correctly done the set up. 

Can anyone help me?

**Comment by twolaw** [comment]
Looks very similar to :
- https://github.com/Taxel/PlexTraktSync/issues/402

Can you tell which PlexTraktSync version you installed ?
You should use the [issue template](https://github.com/Taxel/PlexTraktSync/blob/main/.github/ISSUE_TEMPLATE/bug.md).

**Comment by Rickexe** [comment]
I just cloned the repo with the provided command. 

`git clone -b 0.7.19 --depth=1 https://github.com/Taxel/PlexTraktSync`

My python version is 3.7.3

**Comment by Rickexe** [comment]
It works.

**Comment by glensc** [comment]
I hope you realize that you copied an example, 0.7.19 is a very old version.

so your bug report still misses app version info.

**Comment by Rickexe** [comment]
I just followed the tutorial on your readme. It's outdated. I just cloned the repo. So it's the latest version I guess.

**Comment by glensc** [comment]
the version there is an example. nobody is going to update the number to be accurate with each release. the leading text describes how to obtain the latest version.

**Comment by Rickexe** [comment]
If you just type this command: `git clone https://github.com/Taxel/PlexTraktSync` you will always get the latest version. Not so difficult to update I would say.

**Comment by glensc** [comment]
@Rickexe no, with that clone, you get development version, not the latest release.

**Comment by Rickexe** [comment]
Ok lol. The default branch is main. Anyway doesn't matter. Thank you for your project. I only needed it once to sync my collection and it did.

**Comment by glensc** [comment]
yes, the default branch "main" is development, releases are tagged.
