### ISSUE TITLE
Sync non-local Plex

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#44]
I have access to friends' Plex where I'm just a user, not an admin.

Can I use this tool to sync with that plex instance? I can mark "Watched" in web UI, so, technically should be possible.

**Comment by glensc** [comment]
First I tried just inputting IP of that remote plex instance to config `base_url` key.

It was difficult to find the address, needed to monitor Network requests from Browser Console.
Maybe this tool can help with this, query plex API and show available remotes.

so, tried with:
- https://a-b-c-d.d5e0708d403467017d4dd217178112b5.plex.direct:32400
- http://a.b.c.d:32400

but they give error like:

```
plexapi.exceptions.BadRequest: (401) unauthorized; http://a.b.c.d:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
```

**Comment by twolaw** [comment]
You can get the baseurl from PlexServer with the `_baseurl` variable.
It returns the url as `https://a-b-c-d.d5e0708d403467017d4dd217178112b5.plex.direct:32400` format but I don"t know why you have an error.

**Comment by glensc** [comment]
seems to me your suggestion is the chicken-egg problem: obtaining _baseurl from the plex object, means I first need to provide in base_url to even connect, which in the end will be just base_url I provided... 

seems you did not understand what I'm even asking?

**Comment by twolaw** [comment]
No you don't need the baseurl to access the PlexServer. Read get_env_data.py line 15 :

```
account = MyPlexAccount(username, password)
plex = account.resource(servername).connect()  # returns a PlexServer instance
```
then plex._baseurl

**Comment by glensc** [comment]
Seems I had wrong token in .env file. now it works.

For the record, I was able to obtain URL and token from server name like this:

```python
    from pprint import pprint
    account = MyPlexAccount(username, password)
    pprint(account.resources()) # list available server names
    plex = account.resource(servername).connect()
    pprint(plex.url(''))
    pprint(plex._token)
```

**Comment by twolaw** [comment]
I think an update is needed to allow friends' Plex access.
base_url should be automatically written in `secret.json` file at first run, not by user in config.json.
