### ISSUE TITLE
ERROR: <Show:61408:xxxxxxx>: Unable to parse a valid provider from guid com.plexapp.agents.xbmcnfotv

### ISSUE THREAD

**Issue by Hebusing** [Taxel/PlexTraktSync#452]
### The problem

While Movies are synchronizing well, none of the shows are. I've got the following error message for all of them: 

```
ERROR: <Show:61408:24>: Unable to parse a valid provider from guid com.plexapp.agents.xbmcnfotv://76290?lang=xn
```

76290 is the TheTVDB Id of this show, you check it on their [website](https://www.thetvdb.com/series/24-show).

I didn't modify the config.json file:
```
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
```

I'm sure I've done something wrong but don't know what... :-(

### Expected behavior

Shows should synchronize without those errors.

### Steps to reproduce the behavior

I've entered the simple command to sync only the shows:

```
python3 -m plex_trakt_sync sync --sync tv
```

In Plex, I'm using the XBMCnfoTVImporter and XBMCnfoMoviesImporter agents.

I do recall that the synchro was working with a previous installation I had, but I've just tried with version 0.7.19 and have a similar error:

```
Processing TV Shows  [------------------------------------]  2/191  00:15:20
ERROR: <xbmcnfotv:76290:<Show:61408:24>>: Unable to parse a valid provider from guid:'com.plexapp.agents.xbmcnfotv://76290?lang=xn', guids:[]
```

### Workarounds

There is no workaround.

### Environment

- Version: 0.13.18
- Python version: 3.9.6
- Platform: Debian 11 (using the docker image python:latest)

**Comment by pgjensen** [comment]
@glensc I applied the 2 PRs and got the following issue on inspect:

`python3 -m plex_trakt_sync inspect 9383`

>PlexTraktSync inspect [Unknown version]
WARNING: No response from https://REDACTED:32400, fallback to http://REDACTED:32400
Inspecting 9383: <tvdb:281776:<Show:9383:You're-the-Worst>>
URL: https://app.plex.tv/desktop/#!/server/REDACTED/details?key=/library/metadata/9383
Media.Type: show
Media.Guid: 'com.plexapp.agents.xbmcnfotv://281776?lang=xn'
Guids:
  Guid: com.plexapp.agents.xbmcnfotv://281776?lang=xn, Id: 281776, Provider: tvdb
Metadata: {'collected_at': '2021-07-28:T14:17:53.000Z', 'media_type': 'digital'}
Trakt: https://trakt.tv/shows/60635
Watched on Plex: False
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/bleh/PlexTraktSync/plex_trakt_sync/__main__.py", line 16, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bleh/PlexTraktSync/plex_trakt_sync/commands/inspect.py", line 61, in inspect
    print(f"Warched on Trakt: {m.watched_on_trakt}")
  File "/home/bleh/PlexTraktSync/plex_trakt_sync/media.py", line 78, in watched_on_trakt
    return watched.get_completed(self.show_trakt_id, self.season_number, self.episode_number)
  File "/home/bleh/PlexTraktSync/plex_trakt_sync/media.py", line 46, in show_trakt_id
    raise RuntimeError(f"Unexpected call: episode without show property")
RuntimeError: Unexpected call: episode without show property


I'm sure it's user error, so apologies in advance :-D

**Comment by glensc** [comment]
It seems you did not apply changes fully from #456, but I'll merge it so it's only one PR to test at a time.

you should probably give details how you applied the changes, then can direct what you did wrong.

**Comment by glensc** [comment]
@pgjensen on the other hand, why are you doing `inspect 9383` you're not the original reporter, so don't even know what is your error? also 9383 seems to be show, not episode, so it's a different error.

**Comment by pgjensen** [comment]
Sorry about the confusion, stemming from original issue being about show, and then turning into episode issue as well.  I can log a separate bug regarding inspect for shows not working if you prefer.

`inspect 76971` for episode did work successfully with latest `main` and #453  applied

**Comment by glensc** [comment]
Ok. i'll merge #453 then

**Comment by Hebusing** [comment]
@glensc: it works, thank you!  :-)

**Comment by twolaw** [comment]
My bad, I misread.
Can you show the nfo file ? Maybe the xbmcnfotv agent didn't find the data.
Something strange in xbmcnfotv code is :
```
# if tv show id doesn't exist, create
# one based on hash of title
```
https://github.com/gboudreau/XBMCnfoTVImporter.bundle/blob/534e7737886135b2d0b43d8ae9ee394f1a116051/Contents/Code/__init__.py#L293-L302

But it doesn't explain the plex id being same number as provider id...
