### ISSUE TITLE
Feature request: Better documentation about other features like webhook

### ISSUE THREAD

**Issue by ImjuzCY** [Taxel/PlexTraktSync#475]
### Use case

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

I was using [Plaxt](https://github.com/XanderStrike/goplaxt/) to automate scrobbling from Plex to Trakt via webhook. It stopped working and it has been semi-abandoned. It seem like PlexTraktSync has a webhook function, but it's not documented(?), and it might be a replacement for Plaxt.

### Workarounds

_Is there an existing workaround to accomplish this?_

Documentation about webhook feature

### Plan to implement

_Are you interested in submitting a PR to implement this?_

If I know how it works, why not

**Comment by glensc** [comment]
it's not useful, `watch` command is much better.

therefore pull request was closed:
- https://github.com/Taxel/PlexTraktSync/pull/304

probably should delete the code as well.

**Comment by ImjuzCY** [comment]
Hmm, but `watch` doesn't filter by user, so does not fit my usage as I have a few users on my server. Is it hard to implement a user filter to watch?

**Comment by glensc** [comment]
There's an open issue about filter by user. Dig in.
