### ISSUE TITLE
Speed of sync (after initial sync)

### ISSUE THREAD

**Issue by Scales82** [Taxel/PlexTraktSync#483]
### The problem

Running Sync time takes an EXTREMELY long time, Initial sync and cache has been carried out. Initial sync was 1 item a sec, subsequent scans are around 2 items a sec. Very large library taking around 300mins for a full sync. Inital scan was about 5-6 hours.
Using docker-compose image as per the recent pull request and added comments.
Has something changed? or is this normal behavior? Its taking way too long for me to consider making a cronjob for it to run.

### Expected behavior

A speed of over 2 items a second. Previous versions were around 11 from memory

### Steps to reproduce the behavior

Unsure, its normal for me at this point

### Workarounds

_Is there an existing workaround for this issue?_

### Environment

- Version: Latest docker image 0.13.26
- Python version: as per docker image
- Platform: Linux mint - Docker

**Comment by twolaw** [comment]
- https://github.com/Taxel/PlexTraktSync/discussions/469
