### ISSUE TITLE
User TV episode rating not syncing from Plex to Trakt

### ISSUE THREAD

**Issue by tonitonae** [Taxel/PlexTraktSync#485]
### The problem

_Yesterday I watched a TV Show episode. I rated it after it finished. This morning a ran a sync and the watched status was synced but not the rating._

### Expected behavior

_Rating should be synced alongside the watched status._

### Steps to reproduce the behavior

_Watch a TV Show Episode, rate it on Plex app, sync._

### Workarounds

_None that I am aware of._

### Environment

- Version: 0.13.26
- Python version: 3.8.11
- Platform: Linux 4.4.59+ (on a Synology NAS)

Default config is being used:

```
{
    "log_debug_messages": false,
    "logging": {
        "append": false
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "liked_lists": true,
        "watchlist": true,
        "watched_status": true,
        "collection": true,
        "ratings": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays"
    ]
```

Thanks!

**Comment by tonitonae** [comment]
This PR solved the issue for me. Thanks! 

However, now I have noticed that I have a bunch of movies in Trakt that are watched and rated. The ratings are synced to Plex, but watched status is not. Watched status does sync for tv episodes, which makes things weirder. Is this supposed to be this way?

Thanks again for your help.

**Comment by twolaw** [comment]
This thread is about syncing TV episodes ratings.
Please find appropriate issue to talk about your other problem, or open a new one if you don't find.
