### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'trakt'

### ISSUE THREAD

**Issue by Frazzer951** [Taxel/PlexTraktSync#487]
### The problem

When running the script it gets through 2 libraries before failing in my library with Anime TV Shows
```
Traceback (most recent call last):
  File "C:\dev\Python\PlexTraktSync\main.py", line 6, in <module>
    cli()
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1646, in invoke
    super().invoke(ctx)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\cli.py", line 23, in cli
    sync()
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python\Python38\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\commands\sync.py", line 131, in sync
    sync_all(walker=w, trakt=trakt, plex=plex, dry_run=dry_run)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\commands\sync.py", line 40, in sync_all
    runner.sync(walker, listutil, dry_run=dry_run)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\sync.py", line 23, in sync
    self.sync_watched(episode, dry_run=dry_run)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\sync.py", line 64, in sync_watched
    m.mark_watched_trakt()
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\media.py", line 81, in mark_watched_trakt
    self.trakt_api.mark_watched(self.trakt, self.plex.seen_date)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\decorators\nocache.py", line 14, in inner
    return method(*args, **kwargs)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\decorators\rate_limit.py", line 23, in wrapper
    return fn(*args, **kwargs)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\decorators\time_limit.py", line 18, in wrapper
    return fn(*args, **kwargs)
  File "C:\dev\Python\PlexTraktSync\plex_trakt_sync\trakt_api.py", line 187, in mark_watched
    self.watched_shows.add(m.show.trakt, m.season, m.number)
AttributeError: 'dict' object has no attribute 'trakt'
```

### Expected behavior

To run through the script without errors

### Steps to reproduce the behavior

`pipenv install`
`pipenv run main.py`

### Workarounds

Switch to release 0.13.25 

### Environment

- Version: 0.13.27
- Python version: 3.8.9
- Platform: Windows

[last_update.log](https://github.com/Taxel/PlexTraktSync/files/7172384/last_update.log)

**Comment by twolaw** [comment]
The show `The Ancient Magus Bride` should be recognised in Plex with **tmdb** id **73833** (instead of **67800**). Then it will be correctly sync with trakt.

About the AttributeError : The show `Tokyo Ghoul` [doesn't have](https://www.themoviedb.org/tv/61374/seasons) any episode 13. Your file recognised with **tmdb** id **1581424** is in fact the episode 1 of season 4.
I think you did not properly separate episodes files in season folders and Plex can't associate files to tmdb ids following the exact show layout.

What is the Plex agent used to scan your files ?

Anyway this problem shouldn't crash the whole sync, a fix is needed.

**Comment by Frazzer951** [comment]
> The show `The Ancient Magus Bride` should be recognised in Plex with **tmdb** id **73833** (instead of **67800**). Then it will be correctly sync with trakt.
> 
> About the AttributeError : The show `Tokyo Ghoul` [doesn't have](https://www.themoviedb.org/tv/61374/seasons) any episode 13. Your file recognised with **tmdb** id **1581424** is in fact the episode 1 of season 4.
> I think you did not properly separate episodes files in season folders and Plex can't associate files to tmdb ids following the exact show layout.
> 
> What is the Plex agent used to scan your files ?
> 
> Anyway this problem shouldn't crash the whole sync, a fix is needed.

I can manually check `The Ancient Magus Bride` to make sure it is correct. I was following the TVDB for `Tokyo Ghoul` episode and season numbering, because that is what Sonarr is using, and Plex seems to do fine with it. 

For TV shows plex is using TVDB and TMDB agents, and it seems to see both the shows correctly

**Comment by twolaw** [comment]
To sync with trakt, you'll need to use TMDB layout because now [Trakt use TMDB as their data source](https://blog.trakt.tv/tmdb-transition-ef3d19a5cf24).
Trakt can't sync an episode 13 if it doesn't exist in its database.

You can check [here](https://trakt.tv/transition/tmdb/my/shows) how much difference are in your TVDB and TMDB shows layouts.

TVDB has recently moved to a paid model and many projects now switch to TMDB as data source.

**Comment by Frazzer951** [comment]
> To sync with trakt, you'll need to use TMDB layout because now [Trakt use TMDB as their data source](https://blog.trakt.tv/tmdb-transition-ef3d19a5cf24).
> Trakt can't sync an episode 13 if it doesn't exist in its database.
> 
> You can check [here](https://trakt.tv/transition/tmdb/my/shows) how much difference are in your TVDB and TMDB shows layouts.
> 
> TVDB has recently moved to a paid model and many projects now switch to TMDB as data source.

Ok, So I've been looking at the code and I think I've found the issue. 
On `line 187` of `trakt_api.py` that has `self.watched_shows.add(m.show.trakt, m.season, m.number)`
The error comes when getting the first parameter with `m.show.trakt` no all "episodes" have that value.
I tried changing it to `m.show["ids"]["trakt"]` and that worked with most episodes, but this is where the problem is. 
Not all "episodes" are the same. Some have the `trakt` value at `m.show.trakt`, `m.show["ids"]["trakt"]`, or `m.show.ids["ids"]["trakt"]` if this could be unified it could be fixed. 
It also resolves the issue with the different episode formats. For example where it fails when trying to mark S03E13, it has the correct season and episodes value with `season = 4` and `episode = 1` but the `trakt id` is in a different spot, so it fails. 

```
            try:
                trakt_id = m.show.trakt
            except:
                trakt_id = m.show["ids"]["trakt"]
            finally:
                self.watched_shows.add(trakt_id, m.season, m.number)
```
That seemed to fix the issue, but its feels more like a workaround

**Comment by twolaw** [comment]
I think there is a bug in PyTrakt : 
- https://github.com/moogar0880/PyTrakt/pull/157

**Comment by twolaw** [comment]
> I belive this is becuase the episode is S03E13 and so on, but it's able to math the Trakt ID fine.

Yes, there is a mismatch due to wrong episodes numbering.
To check that you can use the `inspect` command on this Plex S03e13 episode.

Season 4 of `Tokyo Ghoul` has trakt id `246149` and tmdb id `106990`.
