### ISSUE TITLE
Fails to retrive Trakt List, if it has Episodes Instead of Shows

### ISSUE THREAD

**Issue by Frazzer951** [Taxel/PlexTraktSync#489]
### The problem

During the step where Trakt Lists are downloaded, One list keeps failing, and I Belive it is because it has episodes instead of shows. This is the list in particular
https://trakt.tv/users/grendelcrusher/lists/doctor-who-universe-watching-order
`WARNING: Failed to get list Doctor Who Universe Watching Order by user grendelcrusher`

### Expected behavior

Download said list and add it to plex with available episodes

### Steps to reproduce the behavior

Have list likes on Trakt, and run PlexTraktSync

### Workarounds

No

### Environment

- Version: 0.13.27
- Python version: 3.9.7
- Platform: Windows

**Comment by twolaw** [comment]
Did you try this :
- https://github.com/Taxel/PlexTraktSync/issues/92#issuecomment-745903119
> Some time ago I "liked" a playlist but now the owner's profile is private and I can't see it anymore until I follow him.

**Comment by twolaw** [comment]
This list has 1032 items and Trakt API has a rate limit allowing no more than 1000 requests in 5 minutes.
Maybe @glensc can help.
Is rate_limit decorator in motion here ?
Ref:
- https://github.com/Taxel/PlexTraktSync/pull/177

**Comment by Frazzer951** [comment]
> @Frazzer951 can you try this :
> 
> * [Use LazyUserList to fetch Trakt Lists faster #493](https://github.com/Taxel/PlexTraktSync/pull/493)
> 
> Also can you confirm that you can sync a list with less than 1000 episodes with version 0.13.27 ? If so, you can edit the Problem in 1st post.

I tried it with a smaller list `https://trakt.tv/users/yasve/lists/doctor-who-order?sort=released,desc` and it still failed to get it. 

But both lists work with that pull request!
