### ISSUE TITLE
Re-watches on Plex are not being pushed to Trakt

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#506]
### The problem

An episode which is marked as watched on both Trakt and Plex doesn't push when it's rewatched on Plex again. 

### Expected behavior

The play would get pushed. 

### Steps to reproduce the behavior

Play a video that's marked as watched on both Plex and Trakt and run the plextraktsync script

### Workarounds

_Is there an existing workaround for this issue?_

### Environment

- Version: 0.13.18
- Python version: 3.8
- Platform: Ubuntu 20.04

**Comment by glensc** [comment]
Workaround: Use "watch" command

**Comment by agneevX** [comment]
I was under the assumption that watch simply scrobbles and doesn't actually mark as watched?

**Comment by glensc** [comment]
Trakt marks as watched when scrobble reaches 100% (in reality probably at 97%, have not paid detailed attention)

**Comment by HenryQW** [comment]
My watched episodes are not pushed, I used the `watch` command and the log shows:
```log
Listening for events!
INFO: Starting AlertListener: ws://86.8.106.185:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Msg Error: 'int' object is not subscriptable
ERROR: AlertListener Msg Error: 'int' object is not subscriptable
ERROR: AlertListener Msg Error: 'int' object is not subscriptable
.....
```

**Comment by glensc** [comment]
@HenryQW don't hijack issues, create your own bug report. when done the issue, hide your comment here as "off topic".

**Comment by glensc** [comment]
off topic posts hidden

**Comment by ImjuzCY** [comment]
Related to this: All plays should be synced. For example, if one movie is watched twice on separate occations (eg. two new entries in Plex's watch history) between syncs, both plays should be synced and Trakt should have two more play counts after the sync vs only one play count. 

I'm not sure if @agneevX is describing the exact same thing in OP, so I thought I should add this comment.

**Comment by ImjuzCY** [comment]
Related to this: All plays should be synced. For example, if one movie is watched twice on separate occations (eg. two entries in Plex's watch history) between syncs, both plays should be synced and Trakt should have two more play counts after the sync vs only one play count. 

I'm not sure if @agneevX  is describing the exact same thing in OP, just want to make it clear

**Comment by agneevX** [comment]
OK, while I'm using the `watch` command now, I'll try reproducing the issue again without an active `watch` daemon.

**Comment by glensc** [comment]
`sync` command doesn't understand re-watch (hence the open issue), `watch` command does.

technically `watch` command only does scrobble API calls, trakt.tv does the rest (https://github.com/Taxel/PlexTraktSync/pull/739 is not needed and needs to be reverted).

**Comment by agneevX** [comment]
Is this solved @twolaw?

**Comment by twolaw** [comment]
Sync only match the watched **status** between plex & trakt, not the number of watch.

The `watch` command scrobbles every watch from plex to trakt (in real-time only, not previous watches). Therefore re-watch are added in trakt as long as the `watch` command is up during the re-watch. 

Everythink works as expected, there is nothing to solve.

**Comment by agneevX** [comment]
> Everythink works as expected, there is nothing to solve.

What happens when you don't have an internet connection and cannot scrobble or you simply don't want to do so?

Closing this issue isn't right as the issue remains. CC @glensc

**Comment by ImjuzCY** [comment]
This is more like a feature request than a bug, honestly. As @twolaw has stated, `sync` only syncs watch status, which is the intended purpose, the goal of this issue is more like to request the feature that not just sync watch status, but also every watch history.
