### ISSUE TITLE
Give user indication what to do on error

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#51]
I've updated to recent master (39c89b9) and now I get error:

```
root@acai:~/scm/mediaserver/plex/Plugins/PlexTraktSync # ./plex_trakt_sync.sh
Loading .env environment variables…
Starting sync Plex None and Trakt *censored*
Trakt authentication error: Unauthorized - OAuth must be provided
```

I did ran `pip3 install -r requirements.txt` to grab latest packages, the error is still there

I really would not wish to dig through merged pull requests to see what changed and how to log in again. I think the error should give me instructions on what to do next.

**Comment by twolaw** [comment]
Remove all files and start over the setup process.

**Comment by glensc** [comment]
I mean the error is clear: Unauthorized, so tell user how to authenticate.

**Comment by twolaw** [comment]
No, it's not normal use case.
This is an already fixed bug, you used an old trakt oauth token which doesn't come with a refresh token.
Wipe everything as I said and restart over.

**Comment by glensc** [comment]
What do you mean everything? I don't remember how I started it. And creating new trakt app again does not seem neccessary.

Removing `.pytrakt.json` should be sufficient?

**Comment by glensc** [comment]
Seems still need to create new app??!

```
root@acai:~/scm/mediaserver/plex/Plugins/PlexTraktSync # mv .pytrakt.json .pytrakt.json.old
root@acai:~/scm/mediaserver/plex/Plugins/PlexTraktSync # ./plex_trakt_sync.sh
Loading .env environment variables…
Starting sync Plex None and Trakt **censored**
Traceback (most recent call last):
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/main.py", line 341, in <module>
    main()
  File "/home/glen/scm/mediaserver/plex/Plugins/PlexTraktSync/main.py", line 270, in main
    trakt_user = trakt.users.User(getenv('TRAKT_USERNAME'))
  File "/home/glen/.local/share/virtualenvs/PlexTraktSync-sKH3BWbK/lib/python3.7/site-packages/trakt/users.py", line 222, in __init__
    self._get()
  File "/home/glen/.local/share/virtualenvs/PlexTraktSync-sKH3BWbK/lib/python3.7/site-packages/trakt/core.py", line 472, in inner
    json_data = self._handle_request('get', url)
  File "/home/glen/.local/share/virtualenvs/PlexTraktSync-sKH3BWbK/lib/python3.7/site-packages/trakt/core.py", line 449, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app
root@acai:~/scm/mediaserver/plex/Plugins/PlexTraktSync #
```

**Comment by glensc** [comment]
I despise suggestion to delete everything, so instead did:
1. renamed .pytrakt.json to .pytrakt.json.old
2. edited get_env_data.py to skip overwriting plex related data (only trakt expired)
3. run get_env_data.py
4. copied CLIENT_ID and CLIENT_SECRET values from .pytrakt.json.old when get_env_data.py asked for them
5. visited https://trakt.tv/activate/authorize and input the token get_env_data.py printed

from these steps, I'd say it would be possible to recover from the error programmatically.

**Comment by twolaw** [comment]
Sorry, by everything I meant your files in script folder.
And when the next PR will be merged (the one moving plex baseurl from config.json to .env) you will need to do it again.
The easiest way is to remove files but doing like you did is correct too.

**Comment by glensc** [comment]
I don't want to re-authenticate, need to look up the password and log in. it's inconvenient to reset auth with each update. with switching to token auth, I understand the previous device auth just no longer works, so that's okay change.

**Comment by twolaw** [comment]
I understand.
Those updates are special, they are changing the way credentials are saved.

I think the average user will not perform such update. Once everything is setup and working good, they don't come on github everyday to look for updates. If they do so, the advice is simply to start over the setup process on client side, it's not that long.
