### ISSUE TITLE
Add multi arch support

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#522]
I've tried running the container on `arm64` but I get an exec error. 

It seems to be `amd64` only. Please add support for other architectures.

**Comment by grasuoare** [comment]
any news regarding this ? :)

**Comment by twolaw** [comment]
As a workaround you can still build it yourself. That's what I do.

**Comment by glensc** [comment]
should be an easy change if you go and read docs of docker/build-push-action

**Comment by glensc** [comment]
https://github.com/Taxel/PlexTraktSync/pull/523 does not work:

```
error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
Error: buildx failed with: error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

- https://github.com/Taxel/PlexTraktSync/runs/3781676525?check_suite_focus=true

**Comment by glensc** [comment]
Perhaps this helps:
- https://github.com/docker/build-push-action/issues/302
