### ISSUE TITLE
Sync not considering rank

### ISSUE THREAD

**Issue by s01ice** [Taxel/PlexTraktSync#54]
Hi, 

This script was exactly what I was looking for. Nevertheless it does not consider the rank position on the list e.g. when I reorder my watchlist and sync again, the playlist in Plex does not update accordingly. I'm I doing something wrong or can this be added?

**Comment by Taxel** [comment]
You're not doing anything wrong.
The order is currently not taken into account.
At the moment (as long as this hasn't been changed by the many changes I haven't been reviewing in the last time), the script first downloads the list from trakt, and then when looping through your Plex db it just checks if the movie should be added to a playlist. Adding this is probably not trivial, depending on the Plex API's capabilities.

**Comment by twolaw** [comment]
I managed to fix this.
I made it working for my watchlist with python 3.7.
Before submitting I would like to ask you @Taxel why did you use **sets** instead of **lists** for slugs in TraktList class ?

I turned set into list to be able to find rank of movies.

**Comment by twolaw** [comment]
@s01ice here is my solution : https://github.com/twolaw/PlexTraktSync/commit/f1bf39452dd2b0edb825383dee8e90a78689e4fa
If you can confirm it works, i'll merge the code.

**Comment by Taxel** [comment]
I used sets because they automatically deduplicate and lookup is O(1) instead of O(n) (which is significant for a big number of elements inside them).
See [this](https://stackoverflow.com/a/2831242/3083470) Stackoverflow answer as reference :)
