### ISSUE TITLE
Error first run Plexapi

### ISSUE THREAD

**Issue by XSplinter** [Taxel/PlexTraktSync#55]
I tried to follow the install instruction and on the first run I get this:

`~/PlexTraktSync$ python3 main.py`

> Traceback (most recent call last):
>   File "main.py", line 2, in <module>
>     import plexapi.server
> ImportError: No module named 'plexapi'

I already did `pip install plexapi` but I get the same error when I run `python3 main.py`

**Comment by llzzrrdd** [comment]
Just tried this script earlier today and it worked!
I also got errors during this step, moved to the next ones and it worked.
Make sure Trakt and Plex APIs/tokens/users/etc. are OK.
Also, my Plex server was not localhost so I defined that at the .env file.

**Comment by montizzl3** [comment]
I got that as well before I did pip3 install -r requirements.txt.  Once I did that it installed the plexapi as well as 21 other things.  Then the script continued to run but I ran into other errors after that on my first run.

**Comment by twolaw** [comment]
There may be a difference between **pip** and **pip3** if you have both python 2 and 3 on your system.
In this case, pip will install dependances only for python 2.
That's why `python 3 main.py` raises an error.
