### ISSUE TITLE
Feature request: Sync Watchlist from Plex to Plex directly (Multiuser selection possible?)

### ISSUE THREAD

**Issue by dominikheiss** [Taxel/PlexTraktSync#568]
### Feature description
Make it possible to sync two or more plex servers watched status and so on.

### Use case
Keep my primary and backup server in sync.

### Workarounds
Sure, you can deploy multiple instances of this tool, to sync from plex to trakt and in the next instance from trakt to the other plex server.
-> not really feasible if you want to sync multiple users though.

### Plan to implement
Not at the moment

First, I really like your tool. Very well done, thanks for that!!
But it would really enhance it capabilities if you could sync two plex servers without the need to use trakt as a middleman.
The cherry on the cake would be to sync only some users or multiple users between the two servers.

I totally understand if you don't want that, too :)

Regards
Dominik

**Comment by glensc** [comment]
1. issue title does not match feature request body
2. there is a workaround, just set up a separate git or docker installation

**Comment by dominikheiss** [comment]
1. Sorry for that, I had no ideas for the other topics.
2. Right. 1 docker: plex to trakt, 2 docker trakt to plex. But my request was more complex than that.

But like it said, it's okay, just would've been great if that worked that way.

**Comment by glensc** [comment]
1. so edit it. title should describe the feature you request, so it's clear from the issue listing

**Comment by dominikheiss** [comment]
I tried to describe it the best I could ;)

**Comment by glensc** [comment]
oh, I get it now.

there are already some projects to do that:
- https://github.com/jacobwgillespie/plex-sync
- https://github.com/speijnik/plex-watched-sync
