### ISSUE TITLE
Blindly trusts search-results

### ISSUE THREAD

**Issue by WereCatf** [Taxel/PlexTraktSync#576]
### The problem

If two different movies have the same name, but different year and you've watched only one of them, PlexTraktSync may end up marking the other one as watched because it doesn't check the year of the movie in question and just blindly trusts whatever the search-results return.

### Expected behavior

PlexTraktSync should actually verify that the results are for the correct movie/TV-show and only then sync.

### Steps to reproduce the behavior

Add e.g. the Dune 2021 or Dumbo 2019 to your Plex-library, mark the original from decades ago as watched in Trakt and POOF -- PlexTraktSync will mark the newer version as watched.

### Workarounds

None

### Install method

pip

### Version

0.15.10

### Python Version

3.9

### Operating System and Version

Ubuntu 21.10

**Comment by glensc** [comment]
PlexTraktSync doesn't do any title matching, it uses something called GUID from Plex. If Plex tags the media items with the same GUID, then they are the same thing.

Post `plextraktsync inspect ID` of the items you think overwrite each other.

**Comment by WereCatf** [comment]
There's a miscommunication here: Plex has no problem with handling e.g. Aladdin correctly: I can mark the cartoon from 1992 just fine as watched and Plex won't mark the live-action version from 2019 as watched -- it knows full well they are two different movies.

I have the cartoon from 1992 marked as watched on Trakt, though, and plextraktsync thinks it's the same thing as the 2019 live-action movie and proceeds to mark both of them as watched. plextraktsync also then proceeded to mark the 2019-version as watched on Trakt as well, whereas it wasn't that before I ran plextraktsync.

**Comment by WereCatf** [comment]
The 2019 Aladdin:
PlexTraktSync inspect [0.15.10]
Inspecting 9480: <tmdb:420817:<Movie:9480:Aladdin>>
URL: https://app.plex.tv/desktop/#!/server/0b573b3fa12f44c44aff14933f08ce79ab50fe4a/details?key=/library/metadata/9480
Media.Type: movie
Media.Guid: 'plex://movie/5d776c7ffb0d55001f5892da'
Media.Guids: [<Guid:imdb://tt6139732>, <Guid:tmdb://420817>, <Guid:tvdb://6792>]
Audio: '5.1', 'English (AAC 5.1)'
Video: 'hevc'
Guids:
  Guid: tmdb://420817, Id: 420817, Provider: tmdb
  Guid: tvdb://6792, Id: 6792, Provider: tvdb
  Guid: imdb://tt6139732, Id: tt6139732, Provider: imdb
Metadata: {'collected_at': '2019-09-04:T04:11:49.000Z', 'media_type': 'digital', 'resolution': 'hd_1080p', 'audio': 'aac', 'audio_channels': '5.1'}
Trakt: https://trakt.tv/movies/276911
Watched on Plex: False
Watched on Trakt: False

The 1992 Aladdin:
PlexTraktSync inspect [0.15.10]
Inspecting 18873: <tmdb:812:<Movie:18873:Aladdin>>
URL: https://app.plex.tv/desktop/#!/server/0b573b3fa12f44c44aff14933f08ce79ab50fe4a/details?key=/library/metadata/18873
Media.Type: movie
Media.Guid: 'plex://movie/5d776827eb5d26001f1ddab7'
Media.Guids: [<Guid:imdb://tt0103639>, <Guid:tmdb://812>, <Guid:tvdb://285>]
Audio: '5.1', 'English (AAC 5.1)'
Video: 'hevc'
Guids:
  Guid: tmdb://812, Id: 812, Provider: tmdb
  Guid: tvdb://285, Id: 285, Provider: tvdb
  Guid: imdb://tt0103639, Id: tt0103639, Provider: imdb
Metadata: {'collected_at': '2020-06-30:T18:25:13.000Z', 'media_type': 'digital', 'resolution': 'hd_720p', 'audio': 'aac', 'audio_channels': '5.1'}
Trakt: https://trakt.tv/movies/655
Watched on Plex: True
Watched on Trakt: True

The Trakt URL is clearly different, so I don't know what causes the issue.

**Comment by glensc** [comment]
PlexTraktSync doesn't do any title matching or searching. It's a fact. something else is going on.

**Comment by WereCatf** [comment]
Well, I am not able to reproduce the issue anymore for some reason and I have no idea why. I guess I'll have to close this for now and re-open, if I encounter the issue again.
