### ISSUE TITLE
Feature request: Customize configuration directory

### ISSUE THREAD

**Issue by cosmincc** [Taxel/PlexTraktSync#580]
### Use case

It could be useful to run multiple instances with different configurations. One configuration per user and server as example.

### Workarounds

I've tried to use environment variables to change the configuration directory.
```
PTS_CONFIG_DIR=.config/PlexTraktSync_%i
PTS_CACHE_DIR=.cache/PlexTraktSync_%i
```

With a parameterized systemd service one can run several instances with different configuration.
Unfortunately this doesn't work if the application is installed and running `./plextraktsync version` just shows the same default paths.

### Plan to implement

Allow overwrite for system installed applications as well.
Example (in `path.py`):
```
def config_dir(self):
    default = self.app_dir.user_config_dir if self.installed else self.app_path
    return getenv("PTS_CONFIG_DIR", default)
```

Alternatively a new configuration flag could be added to allow this overwrite.

The first option is simple and should be easy to implement. I could create a pull request for it.

**Comment by glensc** [comment]
The appdirs package has something called version isolation:
- https://github.com/ActiveState/appdirs#per-version-isolation

not sure if that should be used/abused for this?

aside from that, how would you specify the `%i` to the app? via command line argument?

**Comment by glensc** [comment]
The other problem is probably that PTS_CACHE_DIR works only in non-system install mode, i.e if not installed from pip/pipx. should change that the env variables take precedence regardless of operation mode.

**Comment by glensc** [comment]
@cosmincc why don't you send the PR with the "plan to implement" change, seems exactly what you want?

**Comment by cosmincc** [comment]
> The appdirs package has something called version isolation:
> 
> * https://github.com/ActiveState/appdirs#per-version-isolation
> 
> not sure if that should be used/abused for this?

This could be (ab)used but we would need to pass a user-defined version for the configuration as a cli flag.
 
> aside from that, how would you specify the `%i` to the app? via command line argument?

The example above was from systemd service template:
```
$ cat /etc/systemd/system/plextraktsync@.service
[Unit]
Description=PlexTraktSync watch daemon %i
After=network-online.target
After=plexmediaserver.service
Wants=plexmediaserver.service

[Service]
Type=oneshot
Environment=PTS_CONFIG_DIR=/path/to/config/PlexTraktSync/%i
Environment=PTS_CACHE_DIR=/path/to/config/PlexTraktSync/%i
Environment=PTS_LOG_DIR=/path/to/config/PlexTraktSync/%i
ExecStart=/var/lib/plexmediaserver/.local/pipx/venvs/plextraktsync/bin/plextraktsync watch

Restart=on-failure
RestartSec=10
User=user
Group=user

[Install]
WantedBy=multi-user.target
```
Then you can instantiate this with the parameter: `systemctl status plextraktsync@config_v1`.
