### ISSUE TITLE
Feature request: set a custom scrobble threshold for `watch`

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#603]
### Feature description

Trakt marks anything above 80% as a play, this isn't desirable because when playback is resumed, after being stopped at or above the threshold, it creates duplicate plays. This was originally reported as a bug in #530.

The 80% threshold is also problematic when playing back movies that are long in duration.

Trakt docs (https://trakt.docs.apiary.io/#reference/scrobble/stop) mention:

> Note: If you prefer to use a threshold higher than 80%, you should use /scrobble/pause yourself so it doesn't create duplicate scrobbles.

I'd like to request the ability to use `/scrobble/pause` till it reaches a custom threshold.

### Use case

Non-duplicate plays, useful for long run time media

### Workarounds

Not that I'm aware of.

### Plan to implement

Sorry but no.

**Comment by glensc** [comment]
Are you sure this is happening with `watch` not `sync`?

I've been using only "watch" and I've seen 99% is still reported as "Playing". I run "sync" only manually, when I'm not watching something, i.e update collection.

If you open trakt.tv site it displays red ribbon "you are watching bla bla".

**Comment by glensc** [comment]
If this is happening with "sync", you could probably as a workaround to turn off "sync to trakt for watches" in config.json, as "watch" command doesn't even update trakt watch status, it's done by trakt.

"watch" command only updates "scrobble" status, and it does "pause" and "stop" if you pause or stop media play in plex:
- https://github.com/Taxel/PlexTraktSync/blob/3c3444c100ca6832e5a6fce2ec31a2a41c6948d8/plextraktsync/commands/watch.py#L102-L111

**Comment by glensc** [comment]
Also, if it does happen with "watch" perhaps easier hack is to fake "percent" not to go over 80% until it reaches 99%, i.e cap the value:
- https://github.com/Taxel/PlexTraktSync/blob/3c3444c100ca6832e5a6fce2ec31a2a41c6948d8/plextraktsync/commands/watch.py#L103

```py
  # hack: cap the value to 80
  if percent > 80 and percent < 99:
    percent = 80
  return self.scrobblers[tm].update(percent) 
```

**Comment by glensc** [comment]
I read the infot at this url again:
- https://trakt.docs.apiary.io/#reference/scrobble/stop

and made me think, considering "watch" understands "pause", what you need to do is change your behavior:

if you want it not to be scrobbled over 80%, you press "pause", then "stop" instead of just doing "stop", so no code change is needed here.

**Comment by glensc** [comment]
If you confirm that it's doable with plex pause, then implementing the same here is not that difficult either.

**Comment by agneevX** [comment]
> Are you sure this is happening with `watch` not `sync`?

It's a combination of both, initiated first by Trakt. 

Happens in this order: 

Watch till 85% (for e.g.) and stop. Trakt marks it as a play while Plex does not. Sync happens that pulls the play to Plex and it's subsequently marked as watched. This is the main issue.

Not too sure about faking the percent playing or the pause -> stop workaround (won't probably remember.)

All in all, I agree that Trakt has made this complicated with definitions of `pause` or `stop` and the 80% threshold makes absolutely no sense.

**Comment by glensc** [comment]
Asked you to give feedback does the pause/stop behavior works or not, please do that!

**Comment by agneevX** [comment]
It does not

**Comment by glensc** [comment]
So your proposed workaround won't work, no point in writing it into code.

Aside, did you monitor watch output that it did get the pause event, and looked trakt.tv site that it updated scrobble state?

**Comment by agneevX** [comment]
It seems that I misunderstood what you meant by "pause/stop"... I thought you meant pausing the video while playing.

Per the docs, I think `/scrobble/pause` should be used when it reaches x custom threshold (or above) instead of `/scrobble/stop` that's used currently?

> Aside, did you monitor watch output that it did get the pause event, and looked trakt.tv site that it updated scrobble state?

No, I haven't. I don't think there's any fault in the code and it probably sends events to Trakt servers correctly.

I just think some sort of accommodation should be made for the 80% threshold:

> Note: If you prefer to use a threshold higher than 80%, you should use /scrobble/pause yourself so it doesn't create duplicate scrobbles.

**Comment by glensc** [comment]
You may have to look at the logic and then test:
- https://github.com/Taxel/PlexTraktSync/pull/605

I usually mess up with logic expressions, so may need to swap if-else parts ;)

**Comment by glensc** [comment]
@agneevX when are you going to test the implementation?

**Comment by agneevX** [comment]
Sorry I've been busy this week, I'll make sure to test this out ASAP. 

Is there a Docker image for this somewhere?

**Comment by glensc** [comment]
Shall I close the issue since you're not interested in it anymore?

**Comment by agneevX** [comment]
No, I'm working on it.

**Comment by agneevX** [comment]
Ok, I built a docker image off of your branch, and I deployed it in a container. I'll provide an update when I'm able to play and test this fully.

**Comment by agneevX** [comment]
I set `scrobble_threshold` in config.json to `94` and watched an episode to `88%`, and it ended up being marked as watched in Plex by a sync job.

```
# plextraktsync - watch
today at 10:02:12 PM INFO: <Episode:81066:Yellowjackets-s01e02>: 86.785026% Watched: False, LastViewed: None
today at 10:02:38 PM INFO: <Episode:81066:Yellowjackets-s01e02>: 86.785026% Watched: False, LastViewed: None

# sync - ran at 10:10PM
2021-11-22 22:22:50,063 INFO[PlexTraktSync]:Marking as watched in Plex: <tmdb:3283029:<Episode:81066:Yellowjackets-s01e02>>
```

<details><summary>Full config.json</summary>

```json
{
    "log_debug_messages": false,
    "logging": {
        "append": false
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": false,
            "watchlist": false
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": true,
            "collection": true
        }
    },
    "watch": {
        "username_filter": true,
        "scrobble_threshold": 94
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    }
}
```

</details>

**Comment by agneevX** [comment]
So I just discovered that there was an old cron job that ran with the ghcr.io image right before this (I moved PTS to another machine, and forgot to delete this).

I was wrong, this does in fact work, and can be merged. 

I watched till `84.9%`, set the threshold to `94%`, and it did not push the play to Plex as it should.

```
INFO: <Episode:58905:Chuck-s02e13>: 84.968150% Watched: False, LastViewed: 2021-12-05 23:04:30
```

```sh
# PTS sync

ubuntu@oc-hyd1 ~> ./scripts/trakt_run.sh
INFO: PlexTraktSync [unknown]
WARNING: No response from http://10.0.0.11:32400, fallback to http://falcon.tailnet-d10c.ts.net:32400
Sync Movie sections: [<PlexLibrarySection:movie:Movies>, <PlexLibrarySection:movie:Movies (4K)>]
Sync Show sections: [<PlexLibrarySection:show:TV Shows>]
Processing Movies 100% ━━━━━━━━━━━╸ 1,253/1,257  [ 0:00:38 < 0:00:01 , 38 it/s ]
INFO: Movies processed in 38.7 seconds
Processing Movies (4K) 100% ━━━━━━━━━━━━━ 95/95  [ 0:00:02 < 0:00:00 , 54 it/s ]
INFO: Movies (4K) processed in 2.4 seconds
WARNING: <Episode:63913:The-Hunt-s00e02>: Skipping guid local://63913 because provider local has no external Id
Processing TV Shows 100% ━━━━━━━━━━━━━━━ 156/156  [ 0:09:26 < 0:00:00 , 0 it/s ]
INFO: TV Shows processed in 9 min 26.3 seconds
INFO: Updated plex watchlist in 0.0 seconds
INFO: Completed full sync in 10 min 7.4 seconds
```
