### ISSUE TITLE
ERROR[plexapi]:AlertListener Error: Handshake status 400 Bad Request

### ISSUE THREAD

**Issue by keldian** [Taxel/PlexTraktSync#609]
### The problem

I noticed Plex related errors on syncing. Not a bother since everything seems to sync as intended regardless, but I thought I'd report it anyway.

### Error trace

```text
2021-11-15 02:55:13,371 INFO[PlexTraktSync]:PlexTraktSync [0.16.x: ae19550e: Merge pull request #598 from glensc/id-search @2021-11-08 20:16:31]
2021-11-15 02:55:58,867 INFO[PlexTraktSync]:Films VO processed in 8.8 seconds
2021-11-15 02:55:59,696 INFO[PlexTraktSync]:Films VOAlt processed in 0.8 seconds
2021-11-15 02:56:12,817 WARNING[PlexTraktSync]:<Episode:4970:Dexter:-New-Blood-s09e01>: Skipping guid local://4970 because provider local has no external Id
2021-11-15 02:56:53,398 INFO[PlexTraktSync]:Séries VO processed in 53.7 seconds
2021-11-15 02:56:53,399 INFO[PlexTraktSync]:Updated plex watchlist in 0.0 seconds
2021-11-15 02:56:53,400 INFO[PlexTraktSync]:Completed full sync in 1 min 3.4 seconds
2021-11-15 01:55:14,421 ERROR[PlexTraktSync.WatchStateUpdater]:Server closed connection
2021-11-15 01:55:14,421 ERROR[PlexTraktSync.WebSocketListener]:Listener finished. Restarting in 15 seconds
2021-11-15 01:55:29,441 INFO[plexapi]:Starting AlertListener: ws://plex.domain.tld:80/:/websockets/notifications?X-Plex-Token=<hidden>
2021-11-15 01:55:29,555 ERROR[plexapi]:AlertListener Error: Handshake status 502 Bad Gateway
2021-11-15 01:55:34,446 ERROR[PlexTraktSync.WatchStateUpdater]:Server closed connection
2021-11-15 01:55:34,447 ERROR[PlexTraktSync.WebSocketListener]:Listener finished. Restarting in 15 seconds
```

Also:
```
/opt/PlexTraktSync $ systemctl status plextraktsync.service
● plextraktsync.service - PlexTraktSync watch daemon
   Loaded: loaded (/lib/systemd/system/plextraktsync.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-11-15 02:48:04 CET; 29min ago
 Main PID: 19741 (python3)
    Tasks: 1 (limit: 3720)
   CGroup: /system.slice/plextraktsync.service
           └─19741 python3 -m plextraktsync watch

Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Server closed connection
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Listener finished. Restarting in 15 seconds
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: INFO: Starting AlertListener: ws://plex.domain.tld:80/:/websockets/notifications?X-Plex-Token=<hidden>
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: AlertListener Error: Handshake status 400 Bad Request
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Server closed connection
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Listener finished. Restarting in 15 seconds
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: INFO: Starting AlertListener: ws://plex.domain.tld:80/:/websockets/notifications?X-Plex-Token=<hidden>
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: AlertListener Error: Handshake status 400 Bad Request
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Server closed connection
Nov 15 03:09:50 rpi plextraktsync.sh[19741]: ERROR: Listener finished. Restarting in 15 seconds
```

### Expected behavior

Absence of errors in `last_update.log`

### Steps to reproduce the behavior

```
/opt/PlexTraktSync $ python3 -m plextraktsync
/opt/PlexTraktSync $ cat last_update.log
```

### Install method

git clone

### Version

0.16.4

### Python Version

3.7.3

### Operating System and Version

Raspbian GNU/Linux 10 (buster)

```
/opt/PlexTraktSync $ python3 -m plextraktsync info
PlexTraktSync Version: 0.16.x: ae19550e: Merge pull request #598 from glensc/id-search @2021-11-08 20:16:31
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
Plex API Version: 4.7.2
Trakt API Version: 3.2.1
Cache Dir: /opt/PlexTraktSync
Config Dir: /opt/PlexTraktSync
Log Dir: /opt/PlexTraktSync
Plex username: plexuser
Trakt username: traktuser
Plex Server version: 1.24.5.5173-8dcc73a59, updated at: 2021-11-14 06:39:16
```

**Comment by glensc** [comment]
1. one bug report a time, `python3 -m plextraktsync` invokes `sync` command
2. your plex server was down, nothing plextraktsync can do better. as it recovered without a crash, here's no bug?

**Comment by keldian** [comment]
What do you mean "one bug report a time"? It's the same 'bug', just logged in different places. And I know it involves the sync command–I don't see where I implied it does not. 

I never said my Plex server was down. It was most definitely not. This error gets logged on every sync, and continuously on _watch_ , regardless of my Plex server's up state.

**Comment by glensc** [comment]
so, remove logs from sync command, do not mix different things. also your log entries are not in time order.

**Comment by glensc** [comment]
your logs (redacted to include highlights) include that plex server was down. so, I'm saying it was not available. not plextraktsync fault. and plextraktsync recovered, so nothing to do here.

```
2021-11-15 01:55:14,421 ERROR[PlexTraktSync.WatchStateUpdater]:Server closed connection
2021-11-15 01:55:29,555 ERROR[plexapi]:AlertListener Error: Handshake status 502 Bad Gateway
2021-11-15 01:55:34,446 ERROR[PlexTraktSync.WatchStateUpdater]:Server closed connection
```

**Comment by glensc** [comment]
so make two reports, one for errors from sync, other for errors from watch. they are never invoked from the same process. in other words errors from sync do not affect watch command, and you have repotted errors from watch (AlertListener exists only in watch) but also messages from sync.

**Comment by keldian** [comment]
Bro, you don't know how your own code works apparently. From your readme:
## You can view sync progress in the last_update.log file which will be created.
## You can view sync progress
## view sync progress
## sync sync sync sync sync sync sync sync sync sync sync sync sync sync sync


The first trace is copied AS IS from `last_update.log`, my only edit being the replacement of my actual domain with _domain.tld_. I didn't pull it out of my ass. There is an AlertListener event logged in that file. It's not my fault your code creates files that amalgamate _sync_ and _watch_ and you didn't know about it.

The time discrepancy was because I happened to reset the server time at that moment for DST. This shouldn't matter, but I'll put the timestamps an hour forward just to appease you.

And I get you're saying my Plex server was not available. I'm saying you're wrong–I know for a fact my Plex server was available. My Plex server is available NOW and your code still throws these errors, continuously. Maybe avoid making assumptions about a server that's not yours and you have no access to, instead of trying to work out where your code is failing.

**Comment by glensc** [comment]
going to close this now.

**Comment by twolaw** [comment]
Does your script communicate to Plex through a reverse proxy (like nginx) with/without SSL ?
It looks like a websocket problem.
In your Plex server settings, check if secure connections is set to "Preferred".
