### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by sebastianarena** [Taxel/PlexTraktSync#628]
### The problem

I'm trying to sync a very large library, and I've managed to make it work slowly by excluding libraries and only allow to run using just one library at a time. The last one, the tv shows, has 10k+ tv shows, and it just can finish to make a single run due to the amount of ram it consumes. I basically see the ram go up about 200kb every second of usage. I can leave it hours running, and it will eventually collapse. The container will just simply stop, no errors.

There's no resume feature, so I cannot ever finish syncing everything.

### Expected behavior

Not leak memory and purge regularly to keep the script using minimum ram to allow it to finish

### Install method

docker-compose

### Version

0.17.0

### Python Version

Using docker

### Operating System and Version

Linux on a Synology NAS

**Comment by glensc** [comment]
duplicate https://github.com/Taxel/PlexTraktSync/issues/431
