### ISSUE TITLE
Feature request: Multi-User Support

### ISSUE THREAD

**Issue by JonzaUK** [Taxel/PlexTraktSync#629]
### Use case

Ability to have multiple plex users to sync there watched status etc to trakt accounts... e.g:

Plex User 1 -> Sync to Trakt User 1
Plex User 2 -> Sync to Trakt User 2

I'm sure you get the idea.

### Workarounds

Not that I'm aware... (currently using the old Trakt4Plex plugin within Plex - but been looking for an alternative since Plugins were deprecated (even though they still work for now)

**Comment by glensc** [comment]
Not sure if i understand correctly, but workaround is very simple: you setup multiple installations of plextraktsync.

**Comment by glensc** [comment]
@JonzaUK please clarify!

**Comment by rfgamaral** [comment]
> Not sure if i understand correctly, but workaround is very simple: you setup multiple installations of plextraktsync.

I believe they are asking for PlexTraktSync to support multiple user authentications (both on Trakt and Plex), and, perhaps, have different sync settings for each one of them.

**Comment by glensc** [comment]
But then workaround exists: run multiple PlexTraktSync installations (instances) with different configs

**Comment by rfgamaral** [comment]
> But then workaround exists: run multiple PlexTraktSync installations (instances) with different configs

Yes, I know. And it's easier to set it up with Docker. But for people not using Docker, it would be much easier if PlexTraktSync supported this out-of-the-box. I'm just saying, I don't need multi-user support myself.

**Comment by glensc** [comment]
It's not about knowing or not, but feedback to the issue body "Workarounds: Not that I'm aware... " that's why I wanted to clarify with the issue author.

**Comment by rfgamaral** [comment]
I think it's safe to assume that they aren't aware that they could just set up multiple instances of PlexTraktSync.

**Comment by JonzaUK** [comment]
Hi Everyone,

Apologies, didn't even think about multiple instances... yes this would work for multiple users... not practical for my use, I have around x12 family members around 10x of which all have Trakt accounts... so setting up 10x instances is a bit of a pain though would work... I think just having Multiple user support built in is a more elegant solution, at the moment using the Plugin I just configure everyone user and trakt account in the one plugin... I would assume having multi-user support would be more resource friendly then running 10x docker instances.

**Comment by glensc** [comment]
Please explain the "pain", to me it's "pain" to maintain extra code to support extra functionality that can be easily be done outside this project.

**Comment by glensc** [comment]
Closing and locking due to unwanted attitude.

**Comment by twolaw** [comment]
- https://github.com/Taxel/PlexTraktSync/issues/580
- https://github.com/Taxel/PlexTraktSync/pull/594

You can use the environment variable **[PTS_CONFIG_DIR](https://github.com/Taxel/PlexTraktSync/blob/24badc1f9c165cc7246e2912476bdac12664c35a/plextraktsync/path.py#L26-L28)** and change it before each run to use a specific folder for each user.
