### ISSUE TITLE
Playlists I no longer like getting synced

### ISSUE THREAD

**Issue by abb0r** [Taxel/PlexTraktSync#636]
### The problem

I'm using PlexTraktSync on Unraid. A few days ago, I removed some liked lists in Trakt that I do no longer need, but PlexTraktSync keeps on syncing them. I thought that was a caching thing, so I removed the trakt_cache.sqlite file. But with the next sync all the lists, that are no longer in my Trakt profile getting synced again. Is there a way to fix this on my end?

### Expected behavior

Lists I do no longer like on Trakt shouldn't get synced.

### Install method

docker-compose

### Version

0.17.0

### Python Version

3.7 (?)

### Operating System and Version

Unraid 6.9.2

**Comment by twolaw** [comment]
Did you remove the lists in Plex too ?
How do you know the lists are synced ?
Can you update to last version 0.18.x and show logs please.
