### ISSUE TITLE
can't open file 'main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Bboy486** [Taxel/PlexTraktSync#65]
User@----- MINGW64 ~
$ pipenv run python main.py
Creating a virtualenv for this projectΓÇª
Pipfile: C:\Users\User\Pipfile
Using C:/Users/User/AppData/Local/Programs/Python/Python38/python.exe (3.8.1) to create virtualenvΓÇª
[=== ] Creating virtual environment...created virtual environment CPython3.8.1.final.0-64 in 15448ms
  creator CPython3Windows(dest=C:\Users\User\.virtualenvs\User-jBUq-HwN, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\User\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\User\.virtualenvs\User-jBUq-HwN
Creating a Pipfile for this projectΓÇª
C:\Users\User\.virtualenvs\User-jBUq-HwN\Scripts\python.exe: can't open file 'main.py': [Errno 2] No such file or directory

User@----- MINGW64 ~
$ python3 main.py
bash: python3: command not found

User@----- MINGW64 ~
$ sudo python3 main.py
bash: sudo: command not found

User@---- MINGW64 ~
$ pipenv run python main.py

C:\Users\User\.virtualenvs\User-jBUq-HwN\Scripts\python.exe: can't open file 'main.py': [Errno 2] No such file or directory

User@---- MINGW64 ~

**Comment by twolaw** [comment]
MINGW64 : You are mixing linux (bash) and windows (python.exe) environments.
Can't you just run it natively in your default OS command prompt ?

**Comment by Bboy486** [comment]
Sure. I will try windows.

**Comment by Bboy486** [comment]
This is what happens when it runs

Traceback (most recent call last):
  File "C:\Users\User\Downloads\# PLEX\PlexTraktSync-master\main.py", line 2, in <module>
    import plexapi.server
ImportError: No module named plexapi.server

**Comment by twolaw** [comment]
Did you install the required Python packages as [ReadMe](https://github.com/Taxel/PlexTraktSync#setup) says ?

**Comment by Bboy486** [comment]
yes I did

**Comment by twolaw** [comment]
If you have many python versions on your system (I don't know how you installed python on your Windows) the problem could be that you installed dependances on a version and run the script with another one.
Example: I have python 3.7.3 (called with `python` command) and python 3.7.9 (called with `python3` command) on my Windows system and installed dependances are different between them.

```
where.exe python3
C:\Users\me\AppData\Local\Microsoft\WindowsApps\python3.exe

where.exe python
C:\Python37\python.exe
```

**Comment by Bboy486** [comment]
Understood. Is there a way to have your python script do to the required python?

**Comment by twolaw** [comment]
Try both:
```
pip3 install -r requirements.txt
```
and
```
pipenv run python3 main.py
```
