### ISSUE TITLE
config.json, adds to collection when setting to false.

### ISSUE THREAD

**Issue by DesertRec** [Taxel/PlexTraktSync#673]
### The problem

I started fresh today using pipx and version 0.18.1.

My config.json looks like this and always has.

```json
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": false,
            "liked_lists": false,
            "watchlist": false
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": false,
            "collection": false
        }
```

but movies still get added to trakt collection which I don't need.

### Expected behavior

Not to add to trakt collection.

### Install method

pipx (Recommended)

### Version

0.18.1

### Python Version

3.9.9

### Operating System and Version

macOS 12.0.1

**Comment by glensc** [comment]
> 
> ### Workarounds
> 
> _No response_

Workaround typically exists using an older version. Try it!

**Comment by DesertRec** [comment]
thanks, a older plextraktsync version?

**Comment by glensc** [comment]
> thanks, an older plextraktsync version?

YES

**Comment by glensc** [comment]
Unable to reproduce. Are you sure your bug-report is complete? for example, your shared config is partial. also, are you sure you modified the correct config file? make an error to it deliberately and then the application should exit with an error unable to parse config. or use `plextraktsync info` command and find config path. also if you said it has always worked, to which version downgrade the problem goes away?

**Comment by DesertRec** [comment]
You are completely right, thanks to `plextraktsync info` I saw it was indeed the wrong config.json I had edited the install location have changed since before pipx.

Wrong location: /Users/user/.local/pipx/venvs/plextraktsync/config.json

Correct location:/Users/user/Library/Application Support/PlexTraktSync/config.json

It's running now on 0.18.2 as expected, many thanks.
