### ISSUE TITLE
Credentials accepted and then errors out

### ISSUE THREAD

**Issue by bullmoose20** [Taxel/PlexTraktSync#677]
### The problem

I cannot complete the initial configuration of PlexTraktSync because it crashes after I enter my email and password successfully.

### Error trace

```text
Please enter your Plex username or e-mail [n****.z******i@h*****l.com]: 
If you have 2 Factor Authentication enabled on Plex you can append the code to your password below (eg. passwordCODE)
Please enter your Plex password: 
Login to MyPlex was successful!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1637, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/plextraktsync/cli.py", line 23, in cli
    sync()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/plextraktsync/commands/sync.py", line 76, in sync
    ensure_login()
  File "/app/plextraktsync/commands/login.py", line 12, in ensure_login
    plex_login_autoconfig()
  File "/app/plextraktsync/commands/plex_login.py", line 140, in plex_login_autoconfig
    login(username, password)
  File "/app/plextraktsync/commands/plex_login.py", line 162, in login
    [server, plex] = choose_server(account)
  File "/app/plextraktsync/commands/plex_login.py", line 121, in choose_server
    click.echo(title(f"Attempting to connect to {server.name}. This may take time and print some errors."))
AttributeError: 'NoneType' object has no attribute 'name'
```

### Expected behavior

not sure... but thinking that the script will need to continue running

### Steps to reproduce the behavior

```
python3 -m plextraktsync
```

1. enter my email
1. enter my password
1. then it crashes

### Inspect of problematic items

```text
/app # python3 -m plextraktsync info
PlexTraktSync Version: 0.18.1
Python Version: 3.10.0 (default, Nov 13 2021, 03:43:50) [GCC 10.2.1 20201203]
Plex API Version: 4.8.0
Trakt API Version: 3.2.2
Cache Dir: /app/config
Config Dir: /app/config
Log Dir: /app/config
Plex username: None
Trakt username: None
```

### Install method

docker-compose

### Version

```
/app # python3 -m plextraktsync info
PlexTraktSync Version: 0.18.1
Python Version: 3.10.0 (default, Nov 13 2021, 03:43:50) [GCC 10.2.1 20201203]
Plex API Version: 4.8.0
Trakt API Version: 3.2.2
Cache Dir: /app/config
Config Dir: /app/config
Log Dir: /app/config
Plex username: None
Trakt username: None
```

### Python Version

Python 3.10.0

### Operating System and Version

Unraid 6.9.2

**Comment by glensc** [comment]
The problem here is that `server = pick_server(account)` returns `None`:
- https://github.com/Taxel/PlexTraktSync/blob/0.18.2/plextraktsync/commands/plex_login.py#L119

now which of these code branches fails?
- https://github.com/Taxel/PlexTraktSync/blob/6f8200447b89405433d5b5e600a7c02efe053270/plextraktsync/commands/plex_login.py#L98-L113

since you didn't indicate you got a prompt to choose server, I would guess `account.resources()` returns `None`.

```py
     servers = account.resources() 
```

is the token you authentication somehow limited? describe the account you're logging in, is it guest or owner?

perhaps youou can edit the code add some `print(f"servers: {servers}")` there and then invoke plex login command only:

```
python -m plextraktsync plex-login
```

**Comment by glensc** [comment]
From https://github.com/pkkid/python-plexapi/blob/4.8.0/plexapi/myplex.py#L199-L202
```py
    def resources(self):
        """ Returns a list of all :class:`~plexapi.myplex.MyPlexResource` objects connected to the server. """
        data = self.query(MyPlexResource.key)
        return [MyPlexResource(self, elem) for elem in data]
```

I would say you have no servers related to the given account you logged in.

**Comment by bullmoose20** [comment]
> From https://github.com/pkkid/python-plexapi/blob/4.8.0/plexapi/myplex.py#L199-L202
> 
> ```python
>     def resources(self):
>         """ Returns a list of all :class:`~plexapi.myplex.MyPlexResource` objects connected to the server. """
>         data = self.query(MyPlexResource.key)
>         return [MyPlexResource(self, elem) for elem in data]
> ```
> 
> I would say you have no servers related to the given account you logged in.

Hello and thanks for your help thus far. What I can tell you is that I have two plex.tv accounts. One that works with plextraktsync  is my hotmail account. When I try to use my gmail account, and password, plextraktsync does not accept the authentication. On all my plexpass machines in my home, I always log into those with my gmail account. Maybe this is related to the issue?

**Comment by bullmoose20** [comment]
So when I login to plex and go to account settings, I see that I do not have a server defined. But when I go to my gmail account, I see that I have my plex pass premium and my plex server is found.

So this makes sense with your presumption that there are no servers defined. the question then remains on why my gmail account won't get authenticated with plextraktsync

**Comment by bullmoose20** [comment]
![image](https://user-images.githubusercontent.com/12549033/147588539-15e3aa05-6072-411b-8580-a28ef17f7f33.png)
![image](https://user-images.githubusercontent.com/12549033/147588712-9b125223-0aff-43c2-9ae0-cfb10cc70f1c.png)

**Comment by glensc** [comment]
Fixed bug that plextraktsync crashes if no servers linked to account.

Everything else is Plex support forums, not here.
