### ISSUE TITLE
Doc Feature request: add details about the 'inspect' command to [README.md]

### ISSUE THREAD

**Issue by jrogers512** [Taxel/PlexTraktSync#681]
### Feature description
When submitting an issue/bug, one of the textarea's is asking for 'plextraktsync inspect ID', however it doesn't appear to be documented in README.md

### Use case

Documentation helps users help themselves

### Workarounds

It is partially documented in contextual help (cli `--help`), and I was able to figure it out.

### Plan to implement

I can do a PR for this, and I might add some more details about using the command line --help for clarity.  Probably as an appendix at the end to keep the current README nice and concise?

**Comment by glensc** [comment]
send a pr, docs and pr always welcome! developers like to write code and docs ain't that :) this is perfect place for community to step in :) and it would be even better as its then second pair of eyes and an extra brain to make changes.

I'm thinking maybe add docs needed labels to pull requests that make changes that need documenting but the docs are only in PR body.

**Comment by glensc** [comment]
created the label:
- https://github.com/Taxel/PlexTraktSync/issues?q=is%3Aissue+is%3Aopen+label%3A%22docs+needed%22+sort%3Aupdated-desc+

that link itself should added to readme

**Comment by glensc** [comment]
Marked more issues/pr's with that label.

Also: are you planning to submit the PR for this particular issue you created?

**Comment by glensc** [comment]
The reporter has dissapeared. Closing the issue.
