### ISSUE TITLE
Log file being stored at incorrect location

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#713]
### The problem

I'm upgrading from v0.18.1 to v0.18.4.

It seems that the log file name has changed from `last_update.log` to `plextraktsync.log`

This file is usually stored in the `PTS_LOG_DIR` folder. That defaults to `/app/config`, but it's being stored in `/app` instead.

Specifying a custom folder for `PTS_LOG_DIR` makes no difference as it saves to the same location.

Since the container is not running as root, it cannot create new files in its sandboxed filesystem, so I'm getting permission denied errors.

### Expected behavior

- Log file to be stored in `PTS_LOG_DIR` folder

### Install method

docker-compose

### Version

0.18.4

### Python Version

3.10.0

### Operating System and Version

Ubuntu 20.04

**EDIT**: correct version numbers.

**Comment by glensc** [comment]
> It seems that the log file name has changed from last_update.log to plextraktsync.log

Not a bug:
- https://github.com/Taxel/PlexTraktSync/pull/664

> I'm upgrading from v1.18.1 to v1.18.4.

we're still at 0.x, correct your bug report

> This file is usually stored in the PTS_LOG_DIR folder. That defaults to /app/config, but it's being stored in /app instead.

indeed, it's a regression from:
- https://github.com/Taxel/PlexTraktSync/pull/664/files

**Comment by glensc** [comment]
> > Workarounds
> No response

workaround exists: Use version before #644, i.e 0.18.1

![image](https://user-images.githubusercontent.com/199095/149127715-02eccfa2-3b8e-488a-8ee4-39a03302a385.png)

**Comment by glensc** [comment]
> Since the container is not running as root, it cannot create new files in its sandboxed filesystem, so I'm getting permission denied errors.

this must be your own doing, as docker image provided by this project runs as root.

**Comment by agneevX** [comment]
> workaround exists: Use version before #644, i.e 0.18.1

> this must be your own doing

> correct your bug report

Could you possibly be any less rude in your replies? 

> as docker image provided by this project runs as root

Yes, I specify the `id` of the user it should run as, as the container should't run with privileges.

**Comment by agneevX** [comment]
Appreciate the prompt fix nonetheless.
