### ISSUE TITLE
Feature request: Please do not expose Api-Keys in meta.log (which needs to be linked in postings)

### ISSUE THREAD

**Issue by gitttt54** [Taxel/PlexTraktSync#743]
### Feature description
When creating a Bugreport, we are informed, to add the full meta.log, which is fine.

Unfortunately, the log is not easy to read because of its format but I encountered 8 entries with my plain api-keys. (Those where for tautulli, which [I just create a bug report ](https://github.com/meisnate12/Plex-Meta-Manager/issues/635)for)

Search for "myapikey" (which was my api-key) finds, i.e.: 
`
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.178.240', port=8183): Max retries exceeded with url: /api/v2?apikey=myapikey&cmd=get_library_names (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x145b446a5e50>: Failed to establish a new connection: [Errno 113] No route to host'))
`

It would be nice, if the log would not store any api-keys at all.

### Workarounds

Remove the secrets by hand via search&replace in your favorite texteditor.

**Comment by glensc** [comment]
reported to wrong project?

**Comment by gitttt54** [comment]
You are correct and I am sorry! My Bad. 
Remove or ignore. Have a good day :-)

**Comment by glensc** [comment]
you as reporter can close your own ssues
