### ISSUE TITLE
watch doesn't add to history anymore

### ISSUE THREAD

**Issue by player8472** [Taxel/PlexTraktSync#758]
### The problem

When watching something on plex, it scobbles progress fine - but at the end it doesn't mark it as completed in Trakt-History

### Expected behavior

Watched Episodes/Movies should be marked as watched in Trakt-History.

### Steps to reproduce the behavior

Watch something on connected PLEX-instance

### Workarounds

Using Sync, but that only works if Item hasn't been watched before.

### Install method

docker-compose

### Version

0.18.15

### Python Version

3.10.0 (according to docker inspect)

### Operating System and Version

Fedora 35 (Containers Host)

**Comment by glensc** [comment]
anymore? what is the last version this worked then? what's the output of watch command? have you tried enabling debugging and see debug log of when play has stopped what appears to log?

**Comment by player8472** [comment]
It just stopped working - not even sure if there was an update.

I used version 0.8.14 before when the issue appeared. Updated to latest (0.18.15) to see if it might be fixed already
I can't really find any possibly configuration related errors in the debug-log.

I created one that only has the timeframe I basically skipped through an Item.
It scobbles progress fine and then it just sends a stop command.

The Play doesn't appear in Trakt history

[plextraktsync.bak.log](https://github.com/Taxel/PlexTraktSync/files/7965449/plextraktsync.bak.log)

**Comment by glensc** [comment]
@player8472 revoke your trakt token. you have shared it publicly with debug log (`Authorization': 'Bearer xxx'`)

**Comment by player8472** [comment]
> @player8472 revoke your trakt token. you have shared it publicly with debug log (`Authorization': 'Bearer xxx'`)

hmpf, overlooked that one - thx
Why are they in the log in the first place?

**Comment by glensc** [comment]
as you described scrobble stop is sent:
```

2022-01-30 06:47:20,567 INFO[PlexTraktSync.WatchStateUpdater]:<Episode:49384:The-Americans-(2013)-s03e01>: 99.823599% W
atched: True, LastViewed: 2022-01-29 18:50:42
2022-01-30 06:47:20,760 DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "POST /scrobble/stop HTTP/1.1" 201 None
```

after that trakt.tv site should mark item as played. perhaps the trakt.tv sit was slow and it needed to update cache>


there's also tons of json errors
```
2022-01-30 06:47:20,565 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
```

but unclear, were those retried and then recovered? i've already submitted PR to trakt library to improve logging there:
- https://github.com/moogar0880/PyTrakt/pull/181

**Comment by player8472** [comment]
> after that trakt.tv site should mark item as played. perhaps the trakt.tv sit was slow and it needed to update cache>

I can assure you it is not just slowness.
I have entire seasons (rewatch) missing from my history.

It would be helpful to have the actual historyID the scobble sends back in the log, so I can check it.

**Comment by glensc** [comment]
what is historyID? link? or perhaps send yourself PR with adding logger.debug? and describe how you would check it?

**Comment by glensc** [comment]
> > @player8472 revoke your trakt token. you have shared it publicly with debug log (`Authorization': 'Bearer xxx'`)
> 
> hmpf, overlooked that one - thx Why are they in the log in the first place?

that's logs from different project:

```
DEBUG[trakt.core]:headers:
```

you could git blame there, maybe there's reasonable commit message explaining :D but I guess it's just debugging what headers are sent. I would drop it from there. or obfuscate.

**Comment by player8472** [comment]
> what is historyID? link? or perhaps send yourself PR with adding logger.debug? and describe how you would check it?

https://trakt.docs.apiary.io/#reference/scrobble/stop

According to the API the scobble-stop should return the 64Bit historyID it saved the scobble as in the trakt-db.

**Comment by florianehmke** [comment]
I'm experiencing the same issue. I only installed 10 days ago and watch never worked whereas sync works just fine.

**Comment by player8472** [comment]
> I'm experiencing the same issue. I only installed 10 days ago and watch never worked whereas sync works just fine.

Maybe instead of sending scobble->stop, sending scobble-pause + sync->add to history?
https://trakt.docs.apiary.io/#reference/sync/add-to-history

Could be a workaround and should be more stable

The call for add to history could also be used for #506  (although this bug wouldn't be half as bad if #506 was already implemented :) )

**Comment by glensc** [comment]
History Id is added to debug log if you take changes of this branch and apply changes to trakt library (linked in the pr):
- https://github.com/Taxel/PlexTraktSync/pull/761

**Comment by glensc** [comment]
Encountering this myself too now.

So far no errors. looks like trakt.tv side something changed?

```
DEBUG    {'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '86',
         'clientIdentifier': 'x', 'guid': '', 'ratingKey': '13204', 'url': '',
         'key': '/library/metadata/13204', 'viewOffset': 3041000, 'playQueueItemID': 38389,
         'playQueueID': 1598, 'state': 'playing', 'transcodeSession': 'x'}]}
INFO     on_play: <Episode:13204:s02e06>: 99.972714% Watched: False, LastViewed:  
         2022-02-02 22:54:13
DEBUG    {'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '86', 
         'clientIdentifier': 'x', 'guid': '', 'ratingKey': '13204', 'url': '',    
         'key': '/library/metadata/13204', 'viewOffset': 3041000, 'playQueueItemID': 38389,   
         'playQueueID': 1598, 'state': 'stopped', 'transcodeSession': 'x'}]}   
INFO     on_play: <Episode:13204:s02e06>: 99.972714% Watched: False, LastViewed:    
         2022-02-02 22:54:13                                                           
DEBUG    Sleeping for 0.576 seconds
```

I don't read anything new from docs:
- https://trakt.docs.apiary.io/#reference/scrobble/stop

**Comment by glensc** [comment]
managed to capture response (details on how: https://github.com/Taxel/PlexTraktSync/issues/758#issuecomment-1025245372):

```
INFO     on_play: <Episode:13205:s02e07>: 99.989809% Watched: False, LastViewed: None
DEBUG    post: https://api-v2launch.trakt.tv/scrobble/stop
DEBUG    RESPONSE [post] (https://api-v2launch.trakt.tv/scrobble/stop): <Response [201]>
DEBUG    Scrobbled: {'id': 0, 'action': 'pause', 'progress': 0.0, 'sharing': {'facebook': False,
         'twitter': False, 'tumblr': False}, 'episode': {'season': 2, 'number': 7, 'title': 'x', 'ids': {'trakt': x, 'tvdb': x, 'imdb': 'x', 'tmdb':
         x, 'tvrage': None}}, 'show': {'title': 'x', 'year': 2015, 'ids': {'trakt':
         x, 'slug': 'x', 'tvdb': x, 'imdb': 'x', 'tmdb': x, 'tvrage':
         x}}}
```

so, somewhy action=pause and progress=0.0 in response. that's not expected.

**Comment by glensc** [comment]
got message where it worked, with this branch applied:
- https://github.com/Taxel/PlexTraktSync/pull/761/commits

```
INFO     on_play: <Episode:13207:s02e09>: 99.967202% Watched: False, LastViewed: None
DEBUG    stop(<TVEpisode>: S2E9 None): 99.9672017720029
DEBUG    post: https://api-v2launch.trakt.tv/scrobble/stop
DEBUG    https://api-v2launch.trakt.tv:443 "POST /scrobble/stop HTTP/1.1" 201 None
DEBUG    RESPONSE [post] (https://api-v2launch.trakt.tv/scrobble/stop): <Response [201]>
DEBUG    Scrobbled: {'id': 8138889017, 'action': 'scrobble', 'progress': 99.9672017720029, 'sharing':
         {'facebook': False, 'twitter': False, 'tumblr': False}, 'episode': {'season': 2, 'number': 9,
         'title': 'x', 'ids': {'trakt': x, 'tvdb': x, 'imdb': 'x',
         'tmdb': x, 'tvrage': None}}, 'show': {'title': 'x', 'year': 2015, 'ids':
         {'trakt': x, 'slug': 'x', 'tvdb': x, 'imdb': 'x', 'tmdb': x,
         'tvrage': x}}}
```

**Comment by simonk83** [comment]
Hi, this still doesn't appear to work unfortunately. Nothing shows up in Trakt at all:

> 2022-02-04 12:09:29,620 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-04 12:09:29,620 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-04 12:09:29,621 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/39852?type=show): request: GET https://api-v2launch.trakt.tv/search/tmdb/39852?type=show, response: 200 (175 bytes), created: 2022-02-01 11:05:2>
> 2022-02-04 12:09:29,621 INFO[PlexTraktSync.WatchStateUpdater]:on_play: <Episode:52702:The-Sinner-s04e07>: 80.231707% Watched: False, LastViewed: None
> 2022-02-04 12:09:29,621 DEBUG[PlexTraktSync.ScrobblerProxy]:update(<TVEpisode>: The Sinner S4E7 Part VII): 80.23170701702588
> 2022-02-04 12:09:29,621 DEBUG[trakt.core]:post: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-04 12:09:29,621 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-04 12:09:29,621 DEBUG[trakt.core]:method, url :: post, https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-04 12:09:29,622 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-04 12:09:30,151 DEBUG[urllib3.connectionpool]:https://api-v2launch.trakt.tv:443 "POST /scrobble/start HTTP/1.1" 201 None
> 2022-02-04 12:09:30,153 DEBUG[requests_cache.session]:Pre-cache checks for response from https://api-v2launch.trakt.tv/scrobble/start: {'disabled cache': True, 'disabled method': True, 'disabled status': True, 'disabled by filter': False, 'disa>
> 2022-02-04 12:09:30,153 DEBUG[requests_cache.session]:Skipping cache write for URL: https://api-v2launch.trakt.tv/scrobble/start
> 2022-02-04 12:09:30,153 DEBUG[trakt.core]:RESPONSE [post] (https://api-v2launch.trakt.tv/scrobble/start): <Response [201]>
> 2022-02-04 12:09:30,154 DEBUG[PlexTraktSync.WatchStateUpdater]:Scrobbled: {'id': 0, 'action': 'start', 'progress': 80.23170701702588, 'sharing': {'facebook': False, 'twitter': False, 'tumblr': False}, 'episode': {'season': 4, 'number': 7, 'titl>
> 2022-02-04 12:09:30,737 DEBUG[plexapi]:Alert: type size TranscodeSession
> 2022-02-04 12:09:30,737 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'transcodeSession.update', 'size': 1, 'TranscodeSession': [{'key': '/transcode/sessions/glscm5zxnq6ck2k64rrh3lnt', 'throttled': True, 'complete': False, 'progress': 22.200000>
> 2022-02-04 12:09:32,697 DEBUG[plexapi]:Alert: type size TranscodeSession
> 2022-02-04 12:09:32,697 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'transcodeSession.update', 'size': 1, 'TranscodeSession': [{'key': '/transcode/sessions/wu5o3grqtmlyywhyujb2ua9v', 'throttled': True, 'complete': False, 'progress': 38.799999>
> 2022-02-04 12:09:35,765 DEBUG[plexapi]:Alert: type size TranscodeSession
> 2022-02-04 12:09:35,765 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'transcodeSession.update', 'size': 1, 'TranscodeSession': [{'key': '/transcode/sessions/glscm5zxnq6ck2k64rrh3lnt', 'throttled': True, 'complete': False, 'progress': 22.200000>
> 2022-02-04 12:09:38,307 DEBUG[plexapi]:Alert: type size TranscodeSession
> 2022-02-04 12:09:38,308 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'transcodeSession.update', 'size': 1, 'TranscodeSession': [{'key': '/transcode/sessions/wu5o3grqtmlyywhyujb2ua9v', 'throttled': True, 'complete': False, 'progress': 38.799999>
> 2022-02-04 12:09:39,238 DEBUG[plexapi]:Alert: type size PlaySessionStateNotification
> 2022-02-04 12:09:39,239 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '192', 'clientIdentifier': 'xxx', 'guid': '', 'ratingKey': '24874', 'url': '', 'key>
> 2022-02-04 12:09:39,611 DEBUG[plexapi]:Alert: type size PlaySessionStateNotification
> 2022-02-04 12:09:39,611 DEBUG[PlexTraktSync.EventDispatcher]:{'type': 'playing', 'size': 1, 'PlaySessionStateNotification': [{'sessionKey': '193', 'clientIdentifier': 'xxx', 'guid': '', 'ratingKey': '52702', 'url': '', 'key>
> 2022-02-04 12:09:39,611 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/3281684?type=episode
> 2022-02-04 12:09:39,611 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-04 12:09:39,611 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/3281684?type=episode
> 2022-02-04 12:09:39,612 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/requests_cache/cache_keys.py", line 165, in normalize_json_body
>     body = json.loads(decode(original_body))
>   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 2022-02-04 12:09:39,612 DEBUG[requests_cache.cache_control]:Cache directives from request headers: {}
> 2022-02-04 12:09:39,612 DEBUG[trakt.core]:RESPONSE [get] (https://api-v2launch.trakt.tv/search/tmdb/3281684?type=episode): request: GET https://api-v2launch.trakt.tv/search/tmdb/3281684?type=episode, response: 200 (319 bytes), created: 2022-02->
> 2022-02-04 12:09:39,612 DEBUG[trakt.core]:get: https://api-v2launch.trakt.tv/search/tmdb/39852?type=show
> 2022-02-04 12:09:39,613 DEBUG[trakt.core]:headers: {'Content-Type': 'application/json', 'trakt-api-version': '2', 'trakt-api-key': 'xxx', 'Authorization': 'Bearer xxx>
> 2022-02-04 12:09:39,613 DEBUG[trakt.core]:method, url :: get, https://api-v2launch.trakt.tv/search/tmdb/39852?type=show
> 2022-02-04 12:09:39,613 DEBUG[requests_cache.cache_keys]:Invalid JSON body:
>
