### ISSUE TITLE
Is it possible to use PlexTraktSync when Plex is in a docker container?

### ISSUE THREAD

**Issue by CraftyClown** [Taxel/PlexTraktSync#77]
Hi there,

I'm really interested in using PlexTraktSync but I'm not sure if I can make it work with my setup.

I have two Plex servers in two locations, one that is in a docker container and the other that is my Shield TV Pro, connected to a Raspberry Pi with an rclone mount.

Is there any for me to use PlexTraktSync, or am I out of luck?

**Comment by CraftyClown** [comment]
Would a symlink work? If PlexTraktSync is expecting to find Plex databases in a particular place, could I cheat the location this way?

**Comment by CraftyClown** [comment]
I tried with the symlink, but the script is throwing an error

```
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    main()
  File "main.py", line 260, in main
    import get_env_data
  File "/opt/PlexTraktSync/get_env_data.py", line 16, in <module>
    account = MyPlexAccount(username, password)
  File "/home/craftyclown/.local/lib/python3.8/site-packages/plexapi/myplex.py", line 82, in __init__
    self._session = session or requests.Session()
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/core.py", line 205, in __init__
    super(_ConfiguredCachedSession, self).__init__(
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/backends/__init__.py", line 63,                                                                    in create_backend
    return registry[backend_name](cache_name, **options)
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/backends/sqlite.py", line 28, i                                                                   n __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/backends/storage/dbdict.py", li                                                                   ne 62, in __init__
    with self.connection() as con:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/craftyclown/.local/lib/python3.8/site-packages/requests_cache/backends/storage/dbdict.py", li                                                                   ne 74, in connection
    con = sqlite.connect(self.filename)
sqlite3.OperationalError: unable to open database file
```

**Comment by CraftyClown** [comment]
I don't seem to be having much luck :(

I tried using one of the docker containers by @twolaw but that seems to be throwing an error for me as well

```
craftyclown@KingKong:~/.config/Docker$ sudo docker start -ia plextraktsync
First run, please follow those configuration instructions.
-- Plex --
Are you logged into this server with a Plex account? (y/n): Traceback (most recent call last):
  File "./main.py", line 354, in <module>
    main()
  File "./main.py", line 260, in main
    import get_env_data
  File "/usr/src/app/get_env_data.py", line 11, in <module>
    plex_needed = utils.input_yesno("-- Plex --\nAre you logged into this server with a Plex account?")
  File "/usr/src/app/utils.py", line 4, in input_yesno
    answer = str(input(msg + ' (y/n): ')).lower()
EOFError: EOF when reading a line
```

**Comment by twolaw** [comment]
The script does work with a dockerised Plex (I personally use plex in docker). It communicates with http, it doesn't read plex files directly.

Why didn't you use the script in the normal way?
What is your symlink? Where did you write it?

**Comment by CraftyClown** [comment]
Morning twolaw

Ok, so maybe I was confusing things by symlinking my Plex directory, but I was already getting the errors that said unable to find database, so I presumed it couldn't find Plex and that was the issue.

So if the symlink clearly doesn't matter and isn't doing anything, what is the error I'm getting related to?

**Comment by twolaw** [comment]
Answer this please : `Why didn't you use the script in the normal way?`

**Comment by CraftyClown** [comment]
> Answer this please : `Why didn't you use the script in the normal way?` I mean why do you use the docker version of script ?
> 
> > what is the error I'm getting related to?
> 
> I don't know, I'll take a look.

I only tried the docker container as the initial script was giving me errors, which at the time I presumed related to the location of my Plex databases (I now realise this was wrong)

I'm happy to go either way, but I seem to be having issues with both as per the errors above

**Comment by twolaw** [comment]
Ok, so you have the `sqlite3.OperationalError: unable to open database file`.
Do you use the version 3.2 of PlexAPI ? Did you install python requirements as stated in readme file ?

**Comment by CraftyClown** [comment]
> Ok, so you have the `sqlite3.OperationalError: unable to open database file`.
> ~Do you use the version 3.2 of PlexAPI ?~ I seems that you do.
> Did you install python requirements as stated in readme file ?
> Do you run script with enough read/write permissions ?
> What is your python version, on which OS ?

So here is my exact process...

```
1. craftyclown@KingKong:/opt$ sudo git clone https://github.com/Taxel/PlexTraktSync.git
[sudo] password for craftyclown:
Cloning into 'PlexTraktSync'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 329 (delta 36), reused 46 (delta 21), pack-reused 258
Receiving objects: 100% (329/329), 79.61 KiB | 141.00 KiB/s, done.
Resolving deltas: 100% (187/187), done.
```
```
2. craftyclown@KingKong:/opt$ cd PlexTraktSync
craftyclown@KingKong:/opt/PlexTraktSync$ pip3 install -r requirements.txt
Requirement already satisfied: astroid==2.3.2 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.3.2)
Requirement already satisfied: certifi==2019.9.11 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2019.9.11)
Requirement already satisfied: chardet==3.0.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: idna==2.8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.8)
Requirement already satisfied: isort==4.3.21 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (4.3.21)
Requirement already satisfied: lazy-object-proxy==1.4.2 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.4.2)
Requirement already satisfied: mccabe==0.6.1 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (0.6.1)
Requirement already satisfied: oauthlib==3.1.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (3.1.0)
Requirement already satisfied: PlexAPI==3.2.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (3.2.0)
Requirement already satisfied: pylint==2.4.3 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.4.3)
Requirement already satisfied: python-dotenv==0.10.3 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (0.10.3)
Requirement already satisfied: requests==2.22.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 12)) (2.22.0)
Requirement already satisfied: requests-cache==0.5.2 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (0.5.2)
Requirement already satisfied: requests-oauthlib==1.2.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (1.2.0)
Requirement already satisfied: six==1.12.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.12.0)
Requirement already satisfied: tqdm==4.36.1 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (4.36.1)
Requirement already satisfied: trakt==2.14.1 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (2.14.1)
Requirement already satisfied: typed-ast==1.4.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (1.4.0)
Requirement already satisfied: urllib3==1.25.6 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (1.25.6)
Requirement already satisfied: websocket-client==0.56.0 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (0.56.0)
Requirement already satisfied: wrapt==1.11.2 in /home/craftyclown/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (1.11.2)
```
```
3. craftyclown@KingKong:/opt/PlexTraktSync$ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import plexapi.server
ModuleNotFoundError: No module named 'plexapi'
```

I have chowned to my user and chmodded 777 on the entire directory to remove permissions as an issue

My OS is Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-48-generic x86_64)
My Python version is  2.7.18

**Comment by twolaw** [comment]
I'm not linux expert but maybe you should sudo the pip3 command too.
The best way is to use pipenv I think (instructions in readme file). It properly creates the environment needed.

**Comment by CraftyClown** [comment]
aaaaand, I answered my own question didn't I!

I forgot to run as pip3

**Comment by CraftyClown** [comment]
You beat me to it @twolaw 

I was running the dependancies for the wrong version of Python. Doh!

Thanks for the help. Just going through the process with you helped highlight what I'd done

**Comment by twolaw** [comment]
what you did with the symlink remains a mystery for me ;)

**Comment by CraftyClown** [comment]
ha ha, the symlink was me misunderstanding how the software was going to work. I presumed it would need local access to the databases. I didn't realise it would log into your Plex account. I was just trying to expose the databases as I thought it was searching for them on my server :)

**Comment by CraftyClown** [comment]
So if I want to run this on my other Plex server, can I do them both from the same machine? Or is it far less complicated to have separate installs of PlexTraktSync on each server? I'm presuming the later

**Comment by twolaw** [comment]
Yes, you have 2 ways to do it :

* duplicate the script folder and do the setup again in the new folder (remove config files .env and .pytrakt.json, setup will write them)
This allows to link to another Trakt acoount.

* use this version https://github.com/Taxel/PlexTraktSync/pull/70 which allows to run a custom .env file (.env file stores plex credentials)
This will use the same Trakt acoount.

**Comment by CraftyClown** [comment]
So just to get some clarification, why would I need to use a different Trakt account? Would that not defeat the purpose if I aim to keep the two servers and Trakt in sync?

I was just getting ready to run the script on my other server. Can I not use the same api details I generated the first time and have all three synced this way?

**Comment by twolaw** [comment]
A trakt account for you, one for your girlfriend, one for your dad, your dog,...
Keep in mind the script can run from any computer, as long as it has internet to reach plex and trakt.

> I was just getting ready to run the script on my other server. Can I not use the same api details I generated the first time and have all three synced this way?

Other plex server means other resource. So it means other credentials (base_url).

**Comment by CraftyClown** [comment]
Sorry, maybe I'm not explaining myself properly, or more likely not understanding your instructions :D 

I have two plex servers with identical content, one called King Kong and one called Donkey Kong. I want the watched status to match across both servers and I was hoping that PlexTraktSync could help me to achieve that.

At present I have run the software on King Kong and all of my content has been synced with my Trakt account, what I now want to do is use the same api details with PlexTraktSync on Donkey Kong to ensure both servers are synchronised.

Would that work? or is this what you are talking about when you refer to the credentials?

**Comment by CraftyClown** [comment]
Sorry if I'm being dense

**Comment by twolaw** [comment]
You can do that.
And it is what I talked about, it cannot be the same api details otherwise it would connect the same server. :smile:
Api details for plex are user token and url.

**Comment by twolaw** [comment]
> Plex api details being added to Trakt

lol that means nothing

**Comment by glensc** [comment]
@twolaw if you have Dockerfile, why not publish it to this repo?

**Comment by twolaw** [comment]
@glensc _Taxel_ is [working](https://github.com/Taxel/PlexTraktSync/issues/62#issuecomment-679920100) on a better version.
