### ISSUE TITLE
Feature Request: Exclude library "livetv"

### ISSUE THREAD

**Issue by theChad6** [Taxel/PlexTraktSync#770]
### Discussed in https://github.com/Taxel/PlexTraktSync/discussions/768

<div type='discussions-op-text'>

<sup>Originally posted by **theChad6** February  1, 2022</sup>
PlexTraktSync [0.18.15]
Plex Version 1.24.4.5081 (Windows 10)
Synology NAS : DSM7 : Docker

Ignore Live TV from sync.  

While playing LiveTV, these errors get pumped out every 10 seconds.
Adding this snipit to config.json doesn't seem to work.
` "excluded-libraries": [
        "Private",
        "Family Holidays",
                "Home Movies",
                "livetv"
    ]`

theChad@synnas:/volume1/docker/appdata$ sudo docker-compose run --rm plextraktsync
Creating trash-guides_plextraktsync_run ... done
Listening for events!
INFO: Starting AlertListener: wss://192-168-0-16.af24ef612f1342c19cb45edd07a8fd14.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: <Episode:/livetv/sessions/a1870327-dd48-491c-a54c-478a986e0325:FOX-10-Arizona-Morni-s2022eNone>: Unable to parse a valid provider from guid tv.plex.xmltv://episode/FOX%2010%20Arizona%20Morning/1900-01-01%2000%3A00%3A00
ERROR: <Episode:/livetv/sessions/a1870327-dd48-491c-a54c-478a986e0325:FOX-10-Arizona-Morni-s2022eNone>: Unable to parse a valid provider from guid tv.plex.xmltv://episode/FOX%2010%20Arizona%20Morning/1900-01-01%2000%3A00%3A00
</div>

**Comment by glensc** [comment]
I can't seem to get anything playing with https://app.plex.tv/desktop/ in browser, stuck with a spinner.

Any docs what platforms or countries the live tv is supported?

so, enable debug logging and share a few lines with:
```
DEBUG[PlexTraktSync.EventDispatcher]
```

**Comment by glensc** [comment]
Oh, this issue is back. Something funny happened to it, it disappeared totally at some point. Likely database crash at github, and they recovered it now.

**Comment by glensc** [comment]
So, the guid is `tv.plex.xmltv://episode/Daytime%20Jeopardy/38/47` is it resolvable to something that trakt knows? or just needs to be excluded?

**Comment by glensc** [comment]
You could try this branch. it should just ignore them:
- https://github.com/Taxel/PlexTraktSync/pull/777

**Comment by theChad6** [comment]
> 

I'm not sure how to pull a specific branch into docker. I updated today to 0.18.16, but it still seems to be erroring.

**Comment by glensc** [comment]
did you try googling? 0.18.16 of course does not contain https://github.com/Taxel/PlexTraktSync/pull/777 because it's not even merged.

**Comment by theChad6** [comment]
Yes... I'm doing my best since I'm neither a software developer nor a git or docker expert. I just learned how to spell CI/CD. I'm on the uphill of a learning curve, so please be patient with me.  
Are you waiting for my test results before merging?  It might take me a few days to figure all this out.

**Comment by glensc** [comment]
Instructions on how to install from PR is in README file.
