### ISSUE TITLE
New device notification

### ISSUE THREAD

**Issue by gitthangbaby** [Taxel/PlexTraktSync#774]
### The problem

the script triggers "New device" Plex notification on every run:

```
New Device

_User_ used a new device to access _Server_: _Server_ (PlexTraktSync)

```
### Error trace

```text
-
```

### Expected behavior

Identify as the same client each time

### Steps to reproduce the behavior

Run the configured script

### Workarounds

add `plexapi.BASE_HEADERS['X-Plex-Client-Identifier'] = "PlexTraktSync"` recommended by Plex employee - that made the notification diseappear 

### Install method

pip

### Version

0.18

### Python Version

3.7

### Operating System and Version

Linux

**Comment by gitthangbaby** [comment]
#168, #200

**Comment by glensc** [comment]
> the script triggers "New device" Plex notification on every run:

where is that? screenshot?  version of plex?

**Comment by gitthangbaby** [comment]
The notification arrives on the users' mobile phone from Plex company whenever new client identifier is used for any access with the same token.

Re mentions: it looks like headers could impact history or cause duplicit processing. 706 is from plexapi (edited above).
Couldn't figure out why all of these header changes exist, especially 168, but seems important to the project so i mention it in case there's a will to change this header as well. This X-Plex-Client-Identifier header record stabilization stops sending endless notification to Plex users on all Plex projects using python-plexapi. As i look at 620 (edited above), it might be python-plexapi issue in the end.

**Comment by glensc** [comment]
706 is still unclear what, use urls to be crystal clear. and if you out URLs to own line with preceding dash (list item), github includes title for them.

The only change this project does is to use an identifiable device:
- https://github.com/Taxel/PlexTraktSync/pull/168

so, in the future (still nothing implemented) are able to determine that the watch record was filled b this app, not the actual player.

if anything, it should have made changes better, not worse.

ps: maybe you want to link to commits or code lines instead of the tickets?

**Comment by glensc** [comment]
Can you send pull request with a fix?

**Comment by gitthangbaby** [comment]
this should be fixed in plexapi i think, [plexapi/__init__.py](https://github.com/pkkid/python-plexapi/blob/b8cef9dc1225c491f086b6dd1eecaf52314ff2af/plexapi/__init__.py) uses randomizer per session:
`X_PLEX_IDENTIFIER = CONFIG.get('header.identifier', str(hex(getnode())))`

_[here](https://stackoverflow.com/questions/36235807/fixed-identifier-for-a-machine-uuid-getnode) : uuid.getnode will return the same value for every call wthinin a single run of your app. If it has to defer to the random algorithm, then you will get a different value when you start a new instance of your app._

**Comment by glensc** [comment]
You can get link to specificv line if you click on the line number:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/199095/152702414-2ae20d98-4d2b-4a34-896a-12eb70619b50.png">

and holding down shift when clicking, you can select range of lines.

**Comment by glensc** [comment]
Send a pull request for improvement if this is an issue.
