### ISSUE TITLE
How does the synchronisation of lists, watch lists and collections work?

### ISSUE THREAD

**Issue by CraftyClown** [Taxel/PlexTraktSync#78]
So I have PlexTraktSync set up now and it works a charm to keep my two servers in sync. Thanks @twolaw  for the help yesterday

I'm a little confused by the list syncing however as I'm not sure what the expected behaviour should be. Should lists I create in Trakt register as Collections in Plex and vice versa? Or is it something else?

I have collections already set up in Plex and I have lists and a watch list in Trakt, but they don't seem to be syncing anywhere.

Any suggestions?

**Comment by twolaw** [comment]
* Collection sync = a movie or tv episode you have in plex is marked as "collected" in trakt (one way sync plex->trakt)

* List sync = lists you like in trakt are created in plex with the same content, **if content is available in plex library** (one way sync trakt->plex)

* Watchlist sync =  your trakt watchlist is created **and updated** in plex with the same content, **if content is available in plex library** (one way sync trakt->plex)

**Comment by CraftyClown** [comment]
Great, thank you, that is much clearer.

One final question if you don't mind; is there a way to sync any other Trakt lists that you create yourself, other than the trakt watchlist? I'm presuming you can't like your own lists, so this isn't covered by list sync.

If not, would it be something simple to implement?

**Comment by twolaw** [comment]
Yes, you can like your own lists. This way you can choose which one you want to sync.

**Comment by CraftyClown** [comment]
Ahhh, really? I couldn't find the option to like my lists. I'll take another look

**Comment by CraftyClown** [comment]
So it's still not working quite right for me.

At the very end of the process when it gets to playlists I get an error:

```
Starting sync Plex CraftyClown and Trakt CraftyClown
Processing section Commercials (local)
Processing section Demos
Processing section Film 
Processing section Film Making 
Processing section Films 4k
Processing section Football
Processing section Music Videos (local)
Processing section Screen calibration 
Processing section Tutorials
Processing section TV 
Processing section TV 4k
Processing section Work
Traceback (most recent call last):
  File "./main.py", line 354, in <module>
    main()
  File "./main.py", line 345, in main
    listutil.updatePlexLists(plex)
  File "/opt/PlexTraktSync/trakt_list_util.py", line 61, in updatePlexLists
    l.updatePlexList(plex)
  File "/opt/PlexTraktSync/trakt_list_util.py", line 36, in updatePlexList
    _, plex_movies_sorted = zip(*sorted(self.plex_movies))
TypeError: '<' not supported between instances of 'Movie' and 'Movie'
```
My Playlists in Trakt are liked and named identically in Plex, however nothing happens. What is the above error referring to?

**Comment by CraftyClown** [comment]
Am I right in thinking it's because I have duplicate content in different libraries (Movies and Movies 4K)

I'm going to try ignoring the 'Movies 4k' in the config.json as a short term fix

Is this something that could be worked around, without me having to ignore libraries?

**Comment by twolaw** [comment]
> Am I right in thinking it's because I have duplicate content in different libraries (Movies and Movies 4K)

You are right.
But I fixed this #74 bug yesterday with PR #76 😄

**Comment by CraftyClown** [comment]
Ha, great timing! :D 

Do I need to backup any config files before updating, or can I just clone the repo again?

**Comment by twolaw** [comment]
Just backup the config.json

Otherwise you can redownload main.py and trakt_list_util.py.
