### ISSUE TITLE
Change the default behavior of the executable

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#780]
By default, `plextraktsync` runs `sync`. 

This should not happen because:
1. `sync` is already a subcommand
2. `sync` is needed to use further arguments, e.g. `plextraktsync --sync movies` doesn't work, `plextraktsync sync --sync movies` does
3. It could be unintentional (destructive) as the user could be exploring available commands

It should simply show `plextraktsync --help` options and exit. This way when a command is specified, it is explicit and intentional by the user.

**Comment by glensc** [comment]
It might be too early morning, but what is the suggestion here?

**Comment by agneevX** [comment]
> It should simply show plextraktsync --help options and exit.

Basically a subcommand should always be specified for it to work.

**Comment by glensc** [comment]
Probably should first add a warning message that the default command is going away.

**Comment by trex005** [comment]
> Probably should first add a warning message that the default command is going away.

I agree requiring an argument is drastically better behavior, but this is a breaking change that no matter how much warning time is given, people will not notice until failure.  The question becomes, what is the cost/benefit?

I am not suggesting this, but an alternate idea would be to make  ```plextraktsync``` be an alias of ```newcommand sync```.

My initial instinct would be to make the new command ```plextrakt``` but as that is not the name of the project, it is a very poor naming convention, so it likely is not any better than the current behavior.

**Comment by glensc** [comment]
Adding warning:
- https://github.com/Taxel/PlexTraktSync/pull/1265

add your 👍🏿 or review submission
