### ISSUE TITLE
pipx install not installing

### ISSUE THREAD

**Issue by Norin-Radd** [Taxel/PlexTraktSync#782]
### The problem

pipx install not installing

### Error trace

```text
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Could not find a version that satisfies the requirement plextraktsync (f$
ERROR: No matching distribution found for plextraktsync
```

```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Could not find a version that satisfies the requirement plextraktsync==0$
ERROR: No matching distribution found for plextraktsync==0.18.17
```

### Expected behavior

should have installed

### Steps to reproduce the behavior

pipx install PlexTraxtSync

plex install  ==0.something --force

neither installed on this ubuntu version

### Install method

pipx (Recommended)

### Version

latest

### Python Version

3

### Operating System and Version

ubuntu 18.0.4

**Comment by glensc** [comment]
what is your `pipx` version? `pipx --version`

**Comment by Norin-Radd** [comment]
hi it is 
1.0.0

**Comment by glensc** [comment]
python2 is not supported
