### ISSUE TITLE
Plex connection errors in log

### ISSUE THREAD

**Issue by CraftyClown** [Taxel/PlexTraktSync#79]
I'm getting the below error in my last_update.log

```
2020-10-10 20:00:02,075 INFO:Starting sync Plex CraftyClown and Trakt CraftyClown
2020-10-10 20:00:05,489 INFO:Downloaded List Trakt Watchlist
2020-10-10 20:00:05,737 INFO:Downloaded List Steven Spielberg
2020-10-10 20:00:05,947 INFO:Downloaded List Oscar Winners
2020-10-10 20:00:05,972 INFO:Downloaded List Christopher Nolan
2020-10-10 20:00:05,972 INFO:Loaded Trakt lists.
2020-10-10 20:00:06,011 INFO:Plex connection error: HTTPSConnectionPool(host='redacted.plex.direct', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f87f4b2f2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Any idea what this error relates to?

**Comment by twolaw** [comment]
In Plex, try to disable ipv6 support and change preferred network interface to the network interface you actually use.

![image](https://user-images.githubusercontent.com/10365746/95665143-c6c33000-0b4d-11eb-99ff-aff132fd8d6b.png)

**Comment by CraftyClown** [comment]
I made the above changes but the error persists.
For clarity it was working fine up until yesterday and I have another Plex server also using PlexTraktSync on another machine that is having no problems at all. There was a PMS update on the affected machine yesterday. Is it possible they've broken something?

**Comment by twolaw** [comment]
> I made the above changes but the error persists.

What changes?
Can you give your plex preferred network interface? the base_url used? the secure connection setting? the plex version?
Do you run PlexTraktSync on same machine? local network? If you can give even more details, just do it.

**Comment by CraftyClown** [comment]
> > I made the above changes but the error persists.
> 
> What changes?
> Can you give your plex preferred network interface? the base_url used? the secure connection setting? the plex version? (for each, before and after)
> Do you run PlexTraktSync on same machine? local network? If you can give even more details, just do it.

**_What changes?_** I disabled IPV6 support and I set my preferred network interface to eth0 (the only interface available)
**_Base URL_** richflix.ddns.net
**_secure connection setting_** Preferred
**_Plex Version_** 1.20.3.3421 (I'm not sure what the version I upgraded from was, but I keep things updated, so it would have been the previous beta release)
**_Do you run PlexTraktSync on same machine?_** Yes they are both on the same remote server. Plex is in a docker container and PlexTraktSync is run on the host

Happy to supply any further info you need

**Comment by twolaw** [comment]
> **_Base URL_** richflix.ddns.net

I think that's your problem. You are using a custom domain name with a secured connection.
Plex delivers a SSL certificate for *.xxxx.plex.direct but not for richflix.ddns.net.
The easiest way to fix this is to disable SSL in your settings.json file : remove the s of https.

**Comment by twolaw** [comment]
> **_Base URL_** richflix.ddns.net

Copy/paste the full **base_url** found in your `config.json` please (just hide some middle numbers for privacy).

> HTTPSConnectionPool(host='redacted.plex.direct', port=32400)

On first post you had a **base_url** like `https://xxxx.plex.direct:32400` that's what i 'm asking. 😉

**Comment by CraftyClown** [comment]
> > **_Base URL_** richflix.ddns.net
> 
> What port? What protocol? Copy/paste the full base_url please.
> I think that your problem is that you are using a custom domain name with a secured connection.
> Plex delivers a SSL certificate for *.xxxx.plex.direct but not for richflix.ddns.net.
> 
> > HTTPSConnectionPool(host='redacted.plex.direct', port=32400)
> 
> On first post you had a different base_url, did you change it?
> 
> The easiest way to fix this is to disable SSL in your settings.json file : remove the s of https.
> And of course make sure your NAT router forwards connection properly.

**_What port? What protocol? Copy/paste the full base_url please_** http://richflix.ddns.net:32400/
**_On first post you had a different base_url, did you change it?_** Sorry, no I redacted it, as it showed my actual IP address plus a long string that I wasn't sure if should be shared publicly
**_And of course make sure your NAT router forwards connection properly_** Yes everything is working fine with all other forwards

**Comment by twolaw** [comment]
Ok, what is the error output when you use http://richflix.ddns.net:32400 ?

**Comment by CraftyClown** [comment]
**_Copy/paste the full base_url found in your config.json please (just hide some middle numbers for privacy)_** There is no base url in my config.json
```
{
    "log_debug_messages": false,
    "sync": {
        "liked_lists": true,
        "watchlist": true,
        "watched_status": true,
        "collection": true,
        "ratings": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays"
    ]
}
**_Ok, what is the error output when you use http://richflix.ddns.net:32400 ?_** Where can I set PTS to use this address?
```

**Comment by twolaw** [comment]
Sorry, I meant in `.env` file.

**Comment by CraftyClown** [comment]
Ah, ok  `PLEX_BASEURL=https://172-18-0-19.20dbeb992441bbaf3523d07cbb11d.plex.direct:32400`

**Comment by twolaw** [comment]
Ok, 172.18.0.19 is the internal docker ip address found when you setup the PlexTraktSync at first run.
Maybe restarting docker changes this ip address, that's why an update could have break it.
I suggest you to replace it with `PLEX_BASEURL=http://localhost:32400`

You can also see all resources addresses by browsing `https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=<your-plex-token-here>` 
Read here https://github.com/Taxel/PlexTraktSync/issues/75#issuecomment-705132268 someone had a similar problem.

**Comment by CraftyClown** [comment]
You are spot on and I was just typing to say the same thing. It appears the Docker IP is slightly wrong, so I guess it must be dynamic.

**Comment by twolaw** [comment]
Personnaly I have Plex in a docker container with some 172.xx.0.1 addresses too, and my **base_url** was correctly found by the script : "https://192-168-1-14.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxb4c0490.plex.direct:32400".
In Plex I changed preferred network interface to eth0 (docker interfaces 172.xx show up here too).

**Comment by CraftyClown** [comment]
Ok so as expected changing to localhost:32400 fixed the issue. The scan even noted there had been a Plex server update, so the problem must have occurred as the container was updated

`2020-10-11 15:00:39,638 INFO:Server version 1.20.3.3421-54b6523bd updated at: 2020-10-11 13:16:35`

**Comment by twolaw** [comment]
Yes, docker ip addresses are not reliable.
For my information, could you give the output of `https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=<your-plex-token-here>` ?

(you can put xxx for privacy concerns like i did [here](https://github.com/Taxel/PlexTraktSync/issues/75#issuecomment-705132268))

**Comment by CraftyClown** [comment]
Yes of course
```
<MediaContainer size="10">
<Device name="Donkey Kong" product="Plex Media Server" productVersion="1.20.1.3252-a78fef9a9" platform="Android" platformVersion="9" device="SHIELD Android TV" clientIdentifier="85d85d885d9b513bfa883a75fd0bb489ea9abc06" createdAt="1596902710" lastSeenAt="1602383822" provides="server" owned="1" accessToken="B-zJrs9PWz7zs9HCEQ1f" publicAddress="77.103.9.42" httpsRequired="0" synced="0" relay="1" dnsRebindingProtection="0" natLoopbackSupported="1" publicAddressMatches="1" presence="1">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
<Device name="King Kong" product="Plex Media Server" productVersion="1.20.3.3421-54b6523bd" platform="Linux" platformVersion="5.4.0-48-generic" device="Docker Container (LinuxServer.io)" clientIdentifier="933d23a73b21ebae6372648f62324f158e453eb2" createdAt="1545698996" lastSeenAt="1602411921" provides="server" owned="1" accessToken="B-zJrs9PWz7zs9HCEQ1f" publicAddress="148.251.191.194" httpsRequired="0" synced="0" relay="1" dnsRebindingProtection="0" natLoopbackSupported="1" publicAddressMatches="0" presence="1">
<Connection protocol="https" address="172.17.0.3" port="32400" uri="https://172-17-0-xxxxxxxxxxxxxxxxxxxxxxxbaf3523d07cbb11d.plex.direct:32400" local="1"/>
<Connection protocol="https" address="148.251.191.194" port="32400" uri="https://148-251-191-xxxxxxxxxxxxxxxxxxxxxxxbaf3523d07cbb11d.plex.direct:32400" local="0"/>
</Device>
<Device name="Galaxy S10+" product="Plex for Android (Mobile)" productVersion="8.8.0.21074" platform="Android" platformVersion="10" device="SM-G975F" clientIdentifier="1e062cf2ec5296e6-com-plexapp-android" createdAt="1557345580" lastSeenAt="1602408578" provides="player,pubsub-player,controller,sync-target" owned="1" publicAddress="34.244.193.204" publicAddressMatches="0" presence="0">
<Connection protocol="http" address="192.168.20.20" port="32500" uri="http://192.168.20.20:32500" local="1"/>
</Device>
<Device name="Galaxy Tab S6" product="Plex for Android (Mobile)" productVersion="8.8.0.21038" platform="Android" platformVersion="10" device="SM-T860" clientIdentifier="a83d57f25e4681df-com-plexapp-android" createdAt="1579483033" lastSeenAt="1602352225" provides="player,pubsub-player,controller,sync-target" owned="1" publicAddress="54.194.150.72" publicAddressMatches="0" presence="0">
<Connection protocol="http" address="192.168.10.107" port="32500" uri="http://192.168.10.107:32500" local="1"/>
</Device>
<Device name="Microsoft Edge" product="Plex Web" productVersion="4.34.4" platform="Microsoft Edge" platformVersion="86.0" device="Windows" clientIdentifier="o6ho6dswona1f9l2k0nuyzjz" createdAt="1593030274" lastSeenAt="1602415943" provides="client,player,pubsub-player" owned="1" publicAddress="77.103.9.42" publicAddressMatches="1" presence="1" accessToken="B-zJrs9PWz7zs9HCEQ1f">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxxb5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
<Device name="Microsoft Edge" product="Plex Web" productVersion="4.34.4" platform="Microsoft Edge" platformVersion="85.0" device="Windows" clientIdentifier="5vwse3yi97j1fub7og4mfgzy" createdAt="1595954337" lastSeenAt="1602409230" provides="client,player,pubsub-player" owned="1" publicAddress="185.247.200.174" publicAddressMatches="0" presence="1" accessToken="B-zJrs9PWz7zs9HCEQ1f">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
<Device name="SHIELD Android TV" product="Plex for Android (TV)" productVersion="8.8.0.21074" platform="Android" platformVersion="9" device="SHIELD Android TV" clientIdentifier="757beb2db3a18cc3-com-plexapp-android" createdAt="1596742047" lastSeenAt="1602290231" provides="player,pubsub-player,controller" owned="1" publicAddress="77.103.9.42" publicAddressMatches="1" presence="0">
<Connection protocol="http" address="192.168.20.30" port="32500" uri="http://192.168.20.30:32500" local="1"/>
</Device>
<Device name="Microsoft Edge" product="Plex Web" productVersion="4.44.1" platform="Microsoft Edge" platformVersion="0" device="Android" clientIdentifier="0ea9pb5lhhc2mcqerr0i02hl" createdAt="1597460263" lastSeenAt="1602368688" provides="client,player,pubsub-player" owned="1" publicAddress="77.103.9.42" publicAddressMatches="1" presence="0" accessToken="B-zJrs9PWz7zs9HCEQ1f">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
<Device name="Microsoft Edge" product="Plex Web" productVersion="4.44.1" platform="Microsoft Edge" platformVersion="86.0" device="Windows" clientIdentifier="up5kaoa8o5jo2me3152ytngq" createdAt="1597490855" lastSeenAt="1602420859" provides="client,player,pubsub-player" owned="1" publicAddress="77.103.9.42" publicAddressMatches="1" presence="0" accessToken="B-zJrs9PWz7zs9HCEQ1f">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
<Device name="Microsoft Edge" product="Plex Web" productVersion="4.34.4" platform="Microsoft Edge" platformVersion="85.0" device="Windows" clientIdentifier="rvbfdq9e6qosjzsrmlirldmu" createdAt="1602067977" lastSeenAt="1602341997" provides="client,player,pubsub-player" owned="1" publicAddress="185.247.200.174" publicAddressMatches="0" presence="0" accessToken="B-zJrs9PWz7zs9HCEQ1f">
<Connection protocol="https" address="192.168.20.30" port="32400" uri="https://192-168-20-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="1"/>
<Connection protocol="https" address="77.103.9.42" port="32400" uri="https://77-103-9-xxxxxxxxxxxxxxxxxxxxxxx5ad8baa8101.plex.direct:32400" local="0"/>
</Device>
</MediaContainer>
```

**Comment by twolaw** [comment]
Thank you, you should remove your last post because your token is visible.
I will add a fallback mechanism to 127.0.0.1, it can be usefull for people having this kind of problems.
