### ISSUE TITLE
Scrobble/watch not working

### ISSUE THREAD

**Issue by beeeeswax** [Taxel/PlexTraktSync#797]
### Discussed in https://github.com/Taxel/PlexTraktSync/discussions/796

<div type='discussions-op-text'>

<sup>Originally posted by **beeeeswax** February  9, 2022</sup>
I've installed PTS on a Windows 10 machine using the zip download, Plex Media Server is running on the same machine.

Synchronizing watched status is working fine but when I start PTS with the watch switch, it seems to be listening correctly but it doesn't seem to like any of the events and doesn't scrobble anything.  When shows/movies are played and hit the watched threshold, all I see is this:

> Listening for events!
INFO: Starting AlertListener: wss://192-168-0-3.xxxxxxxxxxxxxxxxxxx.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<hidden>
ERROR: AlertListener Msg Error: 'Tag' object has no attribute 'ratingKey'
ERROR: AlertListener Msg Error: 'Tag' object has no attribute 'ratingKey'
ERROR: AlertListener Msg Error: 'Tag' object has no attribute 'ratingKey'
ERROR: AlertListener Msg Error: 'Tag' object has no attribute 'ratingKey'

My Info output:

> PlexTraktSync Version: 0.18.x
Python Version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Plex API Version: 4.9.1
Trakt API Version: 3.4.0
Cache Dir: C:\Plex\PlexTraktSync
Config Dir: C:\Plex\PlexTraktSync
Log Dir: C:\Plex\PlexTraktSync
Plex username: xxxxxxxxxxxxxxx
Trakt username: xxxxxxxxxxx
Plex Server version: 1.25.5.5492-12f6b8c83, updated at: 2022-02-09 13:11:49
Enabled 2 libraries in Plex Server: ['Movies', 'TV']
</div>

**Comment by keldian** [comment]
Is your `Plex username` by any chance set to an email address? If so that would explain why it's not scrobbling–you have to use the actual username.

**Comment by beeeeswax** [comment]
My Plex Username as it appears in .env is:

PLEX_USERNAME=Name's Plex Server

Where "Name" is my name.  Other than the ['s] part there are no special characters in my name.  No idea on the Plex URL, I was never prompted for it, the setup wizard detected it and set it like that.  PMS is indeed on the same server as PTS.

**Comment by beeeeswax** [comment]
Thanks, your probing about the username gave me the clue I needed, I think it is the apostrophe in my Plex username.  I remembered seeing it represented as "Name&#39;s Plex Server" in some areas of the Plex web interface so I've used that notation in the .env for PTS and I'm now seeing lines like this which I wasn't getting before:

INFO: on_play: <Episode:120374:Snowpiercer-s03e04>: 49.212748% Watched: False, LastViewed: 2022-02-16 23:03:50

I assume that means it's working?

**Comment by keldian** [comment]
"[Name]'s Plex Server"? I didn't even know apostrophes or spaces were valid characters for the username, but hey if it works it works. Keep in mind you can easily change your username in your Plex account settings too.

Don't forget to close the issue if you deem it resolved.

**Comment by beeeeswax** [comment]
Replaced apostrophe in Plex username with `&#39;`

Assume other special characters require this kind of conversion too.

**Comment by glensc** [comment]
Replaced where? be concise and specific!

**Comment by beeeeswax** [comment]
I replaced the PLEX_USERNAME value in my .env file.

So initially my .env read:

PLEX_BASEURL=https://192-168-0-3.1f23806d61dd4a568d2c8b96f46d0890.plex.direct:32400/
PLEX_FALLBACKURL=http://localhost:32400/
PLEX_TOKEN=xxxxxxxxxxxxxxxxxxx
PLEX_USERNAME=Name's Plex Server
TRAKT_USERNAME=myname

and couldn't scrobble.  I changed it to look like this:

PLEX_BASEURL=https://192-168-0-3.1f23806d61dd4a568d2c8b96f46d0890.plex.direct:32400/
PLEX_FALLBACKURL=http://localhost:32400/
PLEX_TOKEN=xxxxxxxxxxxxxxxxxxx
PLEX_USERNAME=Name&#39;s Plex Server
TRAKT_USERNAME=myname

and now it works.

**Comment by glensc** [comment]
perhaps edit your post and put code block to markdown code fence. as they both look the same here :D

also, this is bug in https://github.com/pkkid/python-plexapi of not escaping properly, should be reported there somehow
