### ISSUE TITLE
Error when processing a TV show

### ISSUE THREAD

**Issue by Dukko** [Taxel/PlexTraktSync#8]
Hi, unsure what's going on here, but I think the show "The Bold Type" is making this script freak out.

This is what I get as an error in the console: 

`Traceback (most recent call last):
  File "main.py", line 247, in <module>
    main()
  File "main.py", line 233, in main
    process_show_section(section)
  File "main.py", line 125, in process_show_section
    logging.error("Show [{} ({})]: Unrecognized GUID {}".format(show.title, show                .year))
IndexError: tuple index out of range
`

**Comment by Taxel** [comment]
Are you on the latest version of the script? This is probably already fixed and the line in the traceback is different from what is in main.py, line 125
Please either pull the latest commit or redownload the zip file, extract it into the folder where the script is and overwrite all files. You may have to reconfigure the config.json, all other settings should persist.

**Comment by Dukko** [comment]
And that's why you check your source before asking for help :) Thanks, working as intended
