### ISSUE TITLE
Feature request: Switch off visual progress logging on console by default

### ISSUE THREAD

**Issue by mattpull** [Taxel/PlexTraktSync#807]
### Feature description
The console progress bars are pretty to look at but functionally unrepresentative of any useful data in terms of logging progress and just fill the screen with junk. On large libraries that take a long time to scan with an ssh client with logging to file turned on, I also noted it can lock up the ssh client.

### Use case

Default progress bars set to off, and a switch to flip on pretty progress bars if desired. More compact progress bar options also could be useful.

### Workarounds

n/a

### Plan to implement

n/a

**Comment by glensc** [comment]
Use ` --no-progress-bar`, default won't be changed.

```
➜ plextraktsync sync --help
Usage: plextraktsync sync [OPTIONS]

  Perform sync between Plex and Trakt

Options:
...
  --no-progress-bar             Don't output progress bars
```
