### ISSUE TITLE
When manually marking episode as watched in overview, sync takes wrong episode number

### ISSUE THREAD

**Issue by onexp** [Taxel/PlexTraktSync#812]
**The problem**

I am running plextraktsync in watch mode in a docker container. So far everything is working fine, but when I go in Plex in my browser to a season of a tv-series and press the three dots on an episode and select "Mark as watched", plextraktsync always thinks this is episode 1 of the season. I can select any episode, but in plextraktsync I can see, that always SXXE01 is taken.

Only, when I open the episode and click on the hook (which also means "Mark as watch", plextraktsync takes the right episode, e.g. SXXE05.

**Expected behavior**

When I manually mark an episode as watched in a season overview, plextraktsync should take the right episode to sync

**Workarounds**

Open the episode and mark it as watched in the episode overview and not season overview.

**Version**

latest

**Python Version**

3.7

**Operating System and Version**

ubuntu 18.0.4

**Comment by glensc** [comment]
post output of the watch command

**Comment by onexp** [comment]
Ok, I open Plex in my browser, go to season 6 and click the three dots on episode 15. Then I click "Mark as played".
In this moment I get following output from watch command:

`root@Plex:/opt/PlexTraktSync# docker-compose run --rm plextraktsync watch`
`Listening for events!`
`INFO: Starting AlertListener: wss://192-168-0-80.948hfireng9oht943zhtzheotj03.plex.direct:32400/:/websockets/notifications?X-Plex-Token=<hidden>`
`INFO: on_activity: <tmdb:37181:<Episode:62750:Raumschiff-Enterpris-s06e01>>: Collected: True, Watched: [Plex: True, Trakt: True]`

![Marked](https://user-images.githubusercontent.com/43592402/154802789-a2355d17-b924-465f-9094-159e3fb5033d.jpg)

**Comment by twolaw** [comment]
feature removed :
- https://github.com/Taxel/PlexTraktSync/issues/865#issuecomment-1202079926
