### ISSUE TITLE
Ratings do not sync from Plex to Trakt

### ISSUE THREAD

**Issue by mattdale77** [Taxel/PlexTraktSync#815]
### The problem

I have set some ratings in Plex but they do not sync to Trakt either under the watch command or a full sync. Ratings from Trakt to Plex work fine.

### Expected behavior

Under a full sync I would expect ratings in Plex to be applied to Trakt but this does not appear to happen.

Under the watch command I would expect ratings to be applied to Trakt but this does not happen. However I'm not sure if this is even possible at the moment so might end up being a feature request

### Steps to reproduce the behavior

Rate something in Plex.
Run a full sync.
Check rating for the episode in Trakt.

### Workarounds

Workaround is rating in Trakt directly but this is what I'm trying to avoid.

### Install method

docker-compose

### Version

0.18.20

### Python Version

3.10.0

### Operating System and Version

Ubuntu 21.04

**Comment by glensc** [comment]
> Workarounds
>
> Workaround is rating in Trakt directly but this is what I'm trying to avoid.

_Again bug report attempting to downgrade missing (https://github.com/Taxel/PlexTraktSync/pull/1237)._

**Comment by glensc** [comment]
Probably broken after this PR:
- https://github.com/Taxel/PlexTraktSync/pull/668 (0.18.1)

The `find_with_rating` seems to return nothing for `Shows` library:
- https://github.com/Taxel/PlexTraktSync/blob/7ec6b59a1dad647103b243f68acdb6c6bb9e1f54/plextraktsync/plex_api.py#L415-L422

but works okay with `Movies` library

**Comment by glensc** [comment]
Rating sync works fine for Movies from Plex to Trakt, at least with version `0.24.3` using  `sync` with `--id` param. `watch` doesn't support ratings sync anyway.

So what this issue is about? shows?
