### ISSUE TITLE
PlexTraktSync won't connect server with new dynamic IP

### ISSUE THREAD

**Issue by fqx** [Taxel/PlexTraktSync#816]
### The problem

When Plex server is on a dynamic IP, PlexTraktSync won't connect server with latest IP/URL.

### Error trace

```text
INFO: PlexTraktSync [0.18.20-6-g781fe5c_main]
ERROR: Plex connection error: HTTPSConnectionPool(host='116-21-1-66.9686607bf3264d53ac73839a66e89920.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe9e8ea1db0>, 'Connection to 116-21-1-66.9686607bf3264d53ac73839a66e89920.plex.direct timed out. (connect timeout=30)')), fallback url http://172.17.0.1:32400 didn't respond either.
Plex connection error: HTTPSConnectionPool(host='116-21-1-66.9686607bf3264d53ac73839a66e89920.plex.direct', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe9e8ea1db0>, 'Connection to 116-21-1-66.9686607bf3264d53ac73839a66e89920.plex.direct timed out. (connect timeout=30)')), fallback url http://172.17.0.1:32400 didn't respond either.
```

### Expected behavior

Connect to 113-111-63-251.9686607bf3264d53ac73839a66e89920.plex.direct:32400

### Workarounds

Maybe loose secure connection requirements could work, but I won't try, it is not safe.

### Install method

docker-compose

### Version

0.18.20-6-g781fe5c_main

### Python Version

3.10.0

### Operating System and Version

Docker

**Comment by glensc** [comment]
FYI: we don't support issues using installation from branch: 0.18.20-6-g781fe5c_main, use released versions. and whoever instructed you to use branch main, complain to them as well.

**Comment by glensc** [comment]
> Workarounds
>
> Maybe loose secure connection requirements could work, but I won't try, it is not safe.

you can use `plex-login` subcommand to find new IP each time it changes to find the new ip

**Comment by glensc** [comment]
Probably alternative would be to use MyPlex account and retrieve server address dynamically each time. Slower, but should catch the updates of changing server addresses.

**Comment by fqx** [comment]
> Probably alternative would be to use MyPlex account and retrieve server address dynamically each time. Slower, but should catch the updates of changing server addresses.

how do you do that?

**Comment by fqx** [comment]
@glensc for the fixes you suggested, I think it's not easy to make it an unmanned process, is that right?

**Comment by glensc** [comment]
Yes, it's indeed making changes to code:
- https://python-plexapi.readthedocs.io/en/latest/modules/myplex.html

basically what plex-login command is doing, but do that every time using server name and myplex password (not token)

**Comment by glensc** [comment]
but why is your server address changing dynamically so often that this is an issue? typically people run things in their plan. maybe you need to use some dyndns services to make name more permanent?

**Comment by fqx** [comment]
@glensc some ISP just won't give home users permanent IP. Indeed I can use some DDNS services, however, I also have to deal with SSL certificate etc.

**Comment by twolaw** [comment]
In .env file, change the ip 172.17.0.1 to 192.168.x.x (the local ip of you server) and if you run the script on the same network it will connect successfully.

**Comment by fqx** [comment]
> In .env file, change THE PLEX_FALLBACKURL ip address from 172.17.0.1 to 192.168.x.x (the local ip of you server) and if you run the script on the same network it will connect successfully.

what if I have set secure connections to required?

**Comment by glensc** [comment]
> what if I have set secure connections to required?

then you use plexdirect URL:
- https://github.com/Taxel/PlexTraktSync/discussions/775#discussioncomment-2215499

**Comment by fqx** [comment]
> > what if I have set secure connections to required?
> 
> then you use plexdirect URL:
> 
> * [Plex connection error: Max retries exceeded with plex.direct.url - PTR uses old IP-Address #775 (reply in thread)](https://github.com/Taxel/PlexTraktSync/discussions/775#discussioncomment-2215499)

That works, thanks.

**Comment by glensc** [comment]
Added "docs needed" label, for community to document this in readme
