### ISSUE TITLE
Unraid Docker Keeps Stopping

### ISSUE THREAD

**Issue by pokeponz** [Taxel/PlexTraktSync#819]
### The problem

The Unraid Docker stops itself after sync. Have to restart the docker image each time to manually sync

### Expected behavior

To not stop

### Steps to reproduce the behavior

Unraid 6.9.2, just install and run. It will stop

### Workarounds

Manually start docker container and run plextraktsync command

### Install method

docker-compose

### Version

0.18.0

### Python Version

3

### Operating System and Version

Unraid 6.9.2

**Comment by twolaw** [comment]
Why do you expect it to not stop ? To do what ?

**Comment by pokeponz** [comment]
The container itself stops. I figured the container would stay running at idle and just run a cron every X hours to re-sync.
I take it that's not the case..

**Comment by pokeponz** [comment]
Ok, I think I stumbled upon what I was missing. running `plextraktsync watch` appears to keep the container at idle/watching for events, which is what I was hoping for. 
Apologies!

**Comment by twolaw** [comment]
The cron has to be made manually outside of container.
The watch command is the only one keeping the script up. But it is very specific: only plex to trakt.

**Comment by glensc** [comment]
Adding docs needed label. As apparently this needs to be explained better.

**Comment by pokeponz** [comment]
@twolaw thank you! That worked nicely. I was able to use the User Scripts plugin in Unraid to setup a cron to call the container start. Unsure if necessary, but I also created a cron from within the container to run plextraktsync on startup. 
@glensc - would be happy to assist in writing something up specific to Unraid

**Comment by glensc** [comment]
@pokeponz as written in readme:
> Looking for a way to contribute? Please find issues with the [help-wanted](https://github.com/Taxel/PlexTraktSync/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+sort%3Aupdated-desc) label or to improve documentation [docs-needed](https://github.com/Taxel/PlexTraktSync/issues?q=label%3A%22docs+needed%22+sort%3Aupdated-desc), thank you.

**Comment by HStep20** [comment]
I came to check this out as well, so I was curious if adding the 'schedule' library would be an option, or if it's a philosophically different direction than the project aims to go. 

Plex-Meta-Manager uses it to handle running the 'meat' of the script on a cron schedule meaning the container is self-sufficient, and doesn't need to utilize an outside service to run consistently. With an internal schedule managed by container variables, it would just be a 'set it and forget it' model.
