### ISSUE TITLE
Everything is syncing as 2 plays

### ISSUE THREAD

**Issue by xiongster** [Taxel/PlexTraktSync#820]
### The problem

Everything is syncing as 2 plays but only played once. Screenshot https://prnt.sc/3SVZVNnI9tS1
Using on UNRID docker.

### Expected behavior

It should only sync once

### Install method

docker-compose

### Version

0.18.20

### Python Version

3.7

### Operating System and Version

UNRID

**Comment by zeroquinc** [comment]
How did you fix this? I have the same issue

**Comment by xiongster** [comment]
> How did you fix this? I have the same issue

@zeroquinc Are you getting this on UNRAID?

**Comment by zeroquinc** [comment]
@xiongster nope, on Windows 10. It happens in like 30% of the time, even when I let Plex continuously play a season without pauses.

**Comment by vpatel9202** [comment]
I have this issue also. I have two instances of PlexTraktSync running in docker containers, one which is continuously running `plextraktsync watch` and the other running `plextraktsync sync`. My thought behind doing it this way is that I want playlists and ratings to always be synced but I also want to scrobble. However, doing it this way has the downside that when an episode is watched, both commands separately report it to Trakt making it look like it was watched twice.

**Comment by twolaw** [comment]
@vpatel9202 your problem is identified in #865 
As a workaround I suggest to disable the 2 _"watched_status"_ in your config file.

**Comment by twolaw** [comment]
@zeroquinc @xiongster we don't even know what command you used, how can you expect some help ?
Please check if #865 is the issue you have.
If not, fill the issue template with all details.

**Comment by vpatel9202** [comment]
That's good to know @twolaw . That should work 95% of the time but that creates an issue in some cases where if I am browsing on Trakt and want to mark something as watched without having seen it on my Plex server, it will not sync across. Similarly, if I am browsing Plex and mark something as played without actually watching it, it will not sync across to Trakt. 

Like I said, this is an outside case so it is what it is.
