### ISSUE TITLE
During syncing it keeps crashing/ shutting down the container on docker. 

### ISSUE THREAD

**Issue by kenkwok83** [Taxel/PlexTraktSync#843]
### The problem

During syncing it keeps crashing/ shutting down the container on docker. 

### Expected behavior

During syncing it keeps crashing/ shutting down the container on docker after a few minutes. 

### Install method

docker-compose

### Version

0.18.21

### Python Version

3.10.0

### Operating System and Version

DSM 7.0.1-42218 Update 3

**Comment by twolaw** [comment]
If you let `No response` in the template questions you will receive this kind of help too : No response.

**Comment by kenkwok83** [comment]
Sorry I'm new to github. I'm not sure what I'm supposed to do =(

**Comment by twolaw** [comment]
Just answer the questions in your first post (3 dots menu > edit).

Show the [log](https://github.com/Taxel/PlexTraktSync#logging) file content below **Error trace** and describe precisely the steps to reproduce. Write as much details as you can.

**Comment by kenkwok83** [comment]
the log window doesn't show anything, they're empty

**Comment by twolaw** [comment]
read my previous comment again
copy/paste the logs in the first post

**Comment by M1kep** [comment]
@twolaw I'm also experiencing similar behavior. The log file does not provide much in this case though:

```
2022-03-29 21:09:31,129 INFO[PlexTraktSync]:TV Shows processed in 12 min 36.2 seconds
2022-03-29 21:09:31,345 INFO[PlexTraktSync]:Updated plex watchlist in 0.1 seconds
2022-03-29 21:09:32,266 INFO[PlexTraktSync]:Completed full sync in 12 min 57.9 seconds
```

I may be able to enable debug logging, but that is going to add quite a large number of logs

**Comment by twolaw** [comment]
I don't see any crash here. `Completed full sync` message is clear enough, no ?

**Comment by glensc** [comment]
Looks like both users don't make difference with "sync" and "watch" operation and expect something they aren't able to describe.

adding "docs needed" label

**Comment by M1kep** [comment]
@glensc I expect the docker container to not close after I run `plextraktsync` within the container launched with the -it flag.

**Comment by M1kep** [comment]
@twolaw Correct, it does sync, but the container then exits for some reason instead of returning to the terminal prompt

**Comment by M1kep** [comment]
Took a further look into this. It looks like the container is exiting because when it is launched in unraid, even with the `-it` flag, a sync is ran. Once that sync finishes, the containers is shutdown

**Comment by glensc** [comment]
"plextraktsync" is one shot command, it runs sync and finishes. to start new sync you need to start it again. documented as cron activation in readme.

"docs needed" label already present, submit improvement to documentation.

**Comment by M1kep** [comment]
@twolaw I don't find those documentation changes relevant to the issue describe here.

The issue here, is that there is not currently a way to get a never exiting interactive session given the current unraid instructions. Due to this, troubleshooting via `plextraktsync inspect` and running the commands interactively on unraid is much more cumbersome. I can only imagine how bad this would be for smaller libraries.

The easiest fix I can think of would be adding a `plextraksync prompt`(Or docker-interactive, or something) command which would simply trigger a prompt asking something like "Press any key to exit" as this would ensure PID 1 never exits, thus allowing users to `docker exec` into the container

**Comment by glensc** [comment]
so create a container that does basically `docker run <image> sleep infinity`:

```
 ➜ docker run --rm --entrypoint sleep ghcr.io/taxel/plextraktsync infinity
```
