### ISSUE TITLE
Movies not syincing only TV show does

### ISSUE THREAD

**Issue by xiongster** [Taxel/PlexTraktSync#851]
### The problem

Only TV shows are syncing Movies are not.
Agents currently selected are 'Plex Movies' and 'Plex TV Series'

### Expected behavior

Movies shoud sync too

### Install method

docker-compose

### Version

0.18.22

### Python Version

3.7

### Operating System and Version

UNRID

**Comment by twolaw** [comment]
No response

**Comment by twolaw** [comment]
@xiongster can you add details ?

command used, output of logfile, config file, steps to reproduce,...
