### ISSUE TITLE
Feature request: Batch Collection Requests

### ISSUE THREAD

**Issue by M1kep** [Taxel/PlexTraktSync#855]
### Feature description
I'd like to suggest updating the Sync to utilize the APIs ability to add multiple items to the "Collected" list per call. The API documentation indicates that the api accepts and array of movies and TV shows which in theory would allow collection syncs to happen in a matter of seconds instead 10s of minutes/hours

https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection

### Use case

Allow full syncs to happen much quicker.

### Workarounds

Wait for over an hour to sync large libraries at the 1 call per second rate

### Plan to implement

I may take a look, by python is far from my strong suite

**Comment by M1kep** [comment]
Looking further into this, it looks like the the `--batch-size` flag already exists. I'm mostly wondering now why this is defaulted to 1?

**Comment by M1kep** [comment]
Commit that set the value to 1 is here, but not sure what is meant by "Most compatible" size:
https://github.com/Taxel/PlexTraktSync/commit/55a2c7945a87c235490a963d515cd76e02c7abe2

**Comment by glensc** [comment]
You can read the discussion of the PR the commit belongs to:
- https://github.com/Taxel/PlexTraktSync/pull/259

**Comment by glensc** [comment]
Added "docs needed" label, so you can submit PR documenting it in readme.

**Comment by M1kep** [comment]
Are there any known issues or risks with this flag, or is it set to 1 for finer grained logging? From the discussion I'm not sure I was able to determine what is lost by using the flag

**Comment by glensc** [comment]
The risk is that if plextraktsync crashes prematurely then batch content may not be sent to trakt api.

**Comment by M1kep** [comment]
> The risk is that if plextraktsync crashes prematurely then batch content may not be sent to trakt api.

In the event a crash, whats the state of the unsent content I'm the cache? In other terms, would those unsent batched items be marked in the cache as already "uploaded" and thus skipped in the future?

**Comment by glensc** [comment]
no, there is no cache for unsent content. as said the risk is only that items are not sent in the event of crash.

**Comment by twolaw** [comment]
I think when `--batch-size` is set to `0` it does not use batch and just send all collected item in one request to trakt at the end of the sync. Sort of workaround to get the previous script logic.


I'd rename this feature request to : **Improve batch collection logic (use time basis)** 
Like we said last year :
- https://github.com/Taxel/PlexTraktSync/pull/232#issuecomment-821870284
- https://github.com/Taxel/PlexTraktSync/pull/259#issuecomment-821942363

It's easy to say, not easy to do. I know.

**Comment by glensc** [comment]
I don't see anyone implementing that smarter batch logic. Mostly because there's no real need for it.

Larger batch is needed if you submit all your collection, this could be solved by just documenting it for those users.

**Comment by twolaw** [comment]
It would be smarter if done automatically without needing the user to adjust the batch size for a "_big collection_" sync.
There is a need, hence this issue opened.

**Comment by M1kep** [comment]
My 2-cents here is that seeing as playlists currently process with the same, if not worse, risk of missing data/requiring re-syncs after a crash that theirs practically no real risk with enabling a default batch of something other than 1. This setting can drastically speed up initial syncs or large diff syncs

**Comment by glensc** [comment]
Since @twolaw sent the pr already, there's zero point in discussing the option that is going to be removed:
- https://github.com/Taxel/PlexTraktSync/pull/869

ps: @twolaw you should cross-link issue/pr to make things better visible for people not following all changes in the repository
