### ISSUE TITLE
Movies watched in Trakt are unwatched in Plex

### ISSUE THREAD

**Issue by auanasgheps** [Taxel/PlexTraktSync#860]
### The problem

Hello, when I mark movies as watched in Trakt before I collect them, they show up as "not watched" in Plex when later I add them to the collection.
As an example, when I watch a movie at the cinema, I mark it as watched in Trakt (via SeriesGuide app). 
When the BluRay/Digital release is later available and I add it to Plex, it is not marked as watched.

I can tell this is not happening for all titles.

The title is correctly matched by PlexTraktSync.

Here's my config

```json
{
    "logging": {
        "debug": false,
        "filename": "plextraktsync.log",
        "append": true
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": true,
            "watchlist": true
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": true,
            "collection": true
        }
    },
    "watch": {
        "scrobble_threshold": 80,
        "add_collection": false,
        "remove_collection": false,
        "username_filter": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays"
    ]
}
```

### Error trace

```text
Example (not error) from logs if I open a movie with the issue:

INFO: on_activity: <tmdb:634649:<Movie:6682:Spider-Man---No-Way->>: Collected: False, Watched: [Plex: False, Trakt: True]

This is actually incorrect, since is actually collected in Plex and first marked as watched in Trakt.

Another movie does not show the problem:

INFO: on_activity: <tmdb:624860:<Movie:6595:Matrix-Resurrections>>: Collected: True, Watched: [Plex: True, Trakt: True]
```

### Expected behavior

I expect that Trakt watched status overrides Plex status.

### Steps to reproduce the behavior

1- Pick a movie not in the collection and mark it as watched
2- Add the movie to the collection
3- Plex will not mark the movie as watched

### Inspect of problematic items

```text
/app # plextraktsync inspect 6682
PlexTraktSync [0.18.24]

Inspecting 6682: <tmdb:634649:<Movie:6682:Spider-Man---No-Way->>
URL: https://app.plex.tv/desktop/#!/server/b6006e511903d00ab752083f9b9a293f5719dcbb/details?key=/library/metadata/6682
Media.Type: movie
Media.Guid: 'plex://movie/5e16138ce0d3ae001ed11b39'
Media.Guids: [<Guid:imdb://tt10872600>, <Guid:tmdb://634649>, <Guid:tvdb://132448>]
Audio: '5.1(side)', 'Italiano (AC3 5.1)'
Video: 'hevc'
Parts:
  Part 1: <redacted>.mkv
Guids:
  Guid: tmdb://634649, Id: 634649, Provider: tmdb
  Guid: tvdb://132448, Id: 132448, Provider: tvdb
  Guid: imdb://tt10872600, Id: tt10872600, Provider: imdb
Metadata: {'collected_at': '2022-03-24:T19:10:52.000Z', 'media_type': 'digital', 'resolution': 'hd_1080p', 'hdr': 'hdr10', 'audio': 'dolby_digital', 'audio_channels': '5.1'}
Trakt: https://trakt.tv/movies/474180
Plex Rating: None
Trakt Rating: None
Watched on Plex: False
Watched on Trakt: True
```

### Install method

docker-compose

### Version

0.18.24

### Python Version

3.10

### Operating System and Version

Debian 10 / OpenMediaVault 5

**Comment by twolaw** [comment]
> 1- Pick a movie not in the collection and mark it as watched
> 2- Add the movie to the collection
> 3- Plex will not mark the movie as watched

I don't see any sync run between steps 2 and 3. Do you run it only with the `watch` command in step 0 ?
Please add more details.

**Comment by twolaw** [comment]
The watch command is only one direction : Plex -> Trakt
See the 'watch' part in your config file.
It's not supposed to do what you expect.
I suggest you run the script without 'watch' command. It will then process a full two way sync ('sync' part of the config file).

**Comment by auanasgheps** [comment]
Ok, but I don't want to run it manually - that's why I use watch. Am I missing something?

**Comment by twolaw** [comment]
The readme says to run it automatically with a cron job.
Also search 'cron' in old issues, we already talked about it.

I personally start my plextraktsync container every 6 hours with cron. :blush:

**Comment by auanasgheps** [comment]
I think the docs need more explanation, which I'll be happy to provide when I better understand the product.

I thought that `watch` was an alternative to the manual execution.

Can I still run the container as watch and run the normal sync with a cron configured there?

**Comment by twolaw** [comment]
Readme clearly states :

> You can use the **watch** command to listen to events from Plex Media Server and scrobble plays.

You can submit a pull request if you think it can be improved.

> Can I still run the container as watch and run the normal sync with a cron configured there?

Yes you can do both. One container for each command. I never tried myself but I think I've read some people doing that.

**Comment by glensc** [comment]
you don't need multiple container definitions, you can just pass args:

1. `docker-compose run --rm plextraktsync` - run default, which is sync
2. `docker-compose run --rm plextraktsync sync` - more implicit to run sync
3. `docker-compose run --rm plextraktsync watch` - run watch command

**Comment by auanasgheps** [comment]
@glensc why are you suggesting the `--rm` command? My goal is to have a set and forget sync. I don't want to mess with manual executions and runs.

I've done some testing: while the container is running with the watch command, I can simply run `plextraktsync` in the container itself and will trigger a full sync.

This means it could be built in the cron's container and have best of both worlds at the same time. I'll have a better look later today.

**Comment by glensc** [comment]
> @glensc why are you suggesting the --rm command? My goal is to have a set and forget sync. I don't want to mess with manual executions and runs.

perhaps first read documentation what the `--rm` option does? without `--rm` the container will linger around in `docker ps`. and one more container for each run invocation.

**Comment by twolaw** [comment]
A cronjob _inside_ the container with interval setup at first run would be great.

Already talked about it here :
- https://github.com/Taxel/PlexTraktSync/pull/89

Until someone submit a PR, we have to deal with a cronjob _outside_ of container.

**Comment by auanasgheps** [comment]
> > @glensc why are you suggesting the --rm command? My goal is to have a set and forget sync. I don't want to mess with manual executions and runs.
> 
> perhaps first read documentation what the `--rm` option does? without `--rm` the finished container will linger around in `docker ps`. and one more container for each run invocation.

Now I understand your point. I have no intention to create a container every time for a sync. I deploy mine via compose with the `watch` command and I want to add the full sync via cron to the same container.

@twolaw I will take a look and see if I can contribute.

Adding a cronjob inside the container is fairly easy, but I don't think is customizable, so we'll probably have to settle on a value that fits everyone.

**Comment by twolaw** [comment]
> I have no intention to create a container every time for a sync. I deploy mine via compose with the `watch` command and I want to add the full sync via cron to the same container.

As I said :
- one container for watch command.
- one container for sync command (using the same docker image) that you [start](https://docs.docker.com/engine/reference/commandline/start/) at set intervals with cron. It just starts and stops repeatedly.
