### ISSUE TITLE
Container unexpectedly exits in Unraid

### ISSUE THREAD

**Issue by M1kep** [Taxel/PlexTraktSync#864]
### Agreement

- [X] I have read the README.md on the project homepage.
- [X] I have checked if identical issue already exists.

### The problem

There is not currently a way to get a never exiting interactive session. Due to this, troubleshooting via `plextraktsync inspect`, for example, and running the tool interactively on Unraid is much more cumbersome. I can only imagine how bad this would be for smaller libraries.

The easiest fix I can think of would be adding a `plextraksync prompt`(Or docker-interactive, or something) command which would simply trigger a prompt asking something like "Press any key to exit" as this would ensure PID 1 never exits, thus allowing users to `docker exec` into the container

### Expected behavior

Given the nature of this CLI tool, to properly support Unraid, I'd expect a method allowing the container to run indefinitely until it is shutdown.

A possible suggestion for this would be a command or flag that simply outputs a text prompt requesting the user to press any key to exit. By having a prompt, PID 1 (`python -m plextraktsync`) should never exit until the container is manually shut down. This would allow users to properly connect to the container to be able to run commands for troubleshooting or reconfiguration.

### Steps to reproduce the behavior

1. Setup Unraid as per
- https://github.com/Taxel/PlexTraktSync/blob/d64aac68233fbf505aa93bdbb5ec226342cc672f/README.md?plain=1#L137-L151
2. Shut the container down
3. Start the container again
4. Enter into a shell session in the container
   - Unraid GUI: Click container icon, then select Consol
![CleanShot 2022-04-01 at 12 12 03@2x](https://user-images.githubusercontent.com/2661819/161327003-07f98c00-4621-4274-af9b-d64acb257c2a.png)
   - SSH'ed into Unraid: `docker exec -it <container-name> sh`
5. Depending on your library size, the session will eventually terminate once the background sync finishes

### Workarounds

Assuming everything is configured properly, the watch command may be able to be used. But if it is not authenticated properly I'm not sure if this command would keep the docker process running indefinitely.

### Install method

pipx (Recommended)

### Version

0.18.4

### Python Version

Whatever ships with the 0.18.4 Docker Image

### Operating System and Version

Unraid

**Comment by twolaw** [comment]
I understand this is specific to the Unraid OS which doesn't give full access to docker command.

> There is not currently a way to get a never exiting interactive session.

Yes there is. You can use the `plex-login` command with `-it` option, it will prompt asking if you want to log again or not. And this container will never stop until you answer the question.
This way you have time to ssh into it with `docker exec -it <container-name> sh` and do what you want inside the container.

**Comment by glensc** [comment]
Repost of:
- https://github.com/Taxel/PlexTraktSync/issues/843#issuecomment-1086818597

> 
> So create a container that does basically `docker run <image> sleep infinity`:
> 
> ```
> ➜ docker run --rm -d --entrypoint sleep ghcr.io/taxel/plextraktsync infinity
> 397c3b104f93ec912f04ae3c8eb642796f77271aa9a1e3a8113311c84a1bce1a
> ➜ docker exec -it 397c3b10 sh
> /app # ps axwuf
> PID   USER     TIME  COMMAND
>     1 root      0:00 sleep infinity
>     8 root      0:00 sh
>    17 root      0:00 ps axwuf
> /app #
> ```

**Comment by M1kep** [comment]
@glensc the referenced issue and associate d changes are put related to this as those target the watch command as well as docker #compose rather than Unraid.

@twolaw i think the provided workarounds here will be good enough
