### ISSUE TITLE
Feature request: Allow library filtering for watch command

### ISSUE THREAD

**Issue by myrison** [Taxel/PlexTraktSync#877]
### Feature description
Allow for the config.json file to be used to exclude libraries from the watch command like it is used now for the sync use case.  

### Use case

Currently the watch command will continuously attempt to find a metadata match for items in libraries that will never be matched.  The most common use cases I can think of are libraries containing personal home movies, music, or audiobooks.

### Workarounds

To be clear, this is more an efficiency change with an easy workaround (you simply live with the additional log-spam and attempted match attempts), but [as suggested](https://github.com/Taxel/PlexTraktSync/discussions/874#discussioncomment-2506517) by @glensc, I am adding it here to track the idea for the future.

### Plan to implement

Unfortunately I don't have the skills to do this one on my own, but if I can provide more detail to detail the work required, please let me know.

**Comment by glensc** [comment]
This should do it:
- https://github.com/Taxel/PlexTraktSync/pull/1286
