### ISSUE TITLE
Slow TV Sync

### ISSUE THREAD

**Issue by launchm** [Taxel/PlexTraktSync#879]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

all my TV shows seems to take ages compared to the movies. This is after my 1st initial scan, the 

Processing Movies 100% -----------------------------------------------  16,269/16,273  [ 0:02:04 < 0:00:01 , 136 it/s ]
Processing 4K Movies  98% ----------------------------------------------  1,072/1,090  [ 0:00:08 < 0:00:01 , 145 it/s ]

Processing Kids TV 100% -------------------------------------------------------------------------------- 748/748  [ 0:49:44 < 0:00:00 , 0 it/s ]

Processing TV Shows   4% --- ------------------------------------------------------------------------- 228/5,752  [ 0:12:43 < 6:32:56 , 0 it/s ]

Config:

{
    "logging": {
        "debug": false,
        "filename": "plextraktsync.log",
        "append": true
    },
    "config": {
        "dotenv_override": true
    },
    "cache": {
        "path": "$PTS_CACHE_DIR/trakt_cache"
    },
    "sync": {
        "trakt_to_plex": {
            "watched_status": true,
            "ratings": true,
            "liked_lists": false,
            "watchlist": false
        },
        "plex_to_trakt": {
            "watched_status": true,
            "ratings": true,
            "collection": false
        }
    },
    "watch": {
        "scrobble_threshold": 80,
        "add_collection": false,
        "remove_collection": false,
        "username_filter": true
    },
    "xbmc-providers": {
        "movies": "imdb",
        "shows": "tvdb"
    },
    "excluded-libraries": [
        "Private",
        "Family Holidays",
	"Anime"
    ]
}

### Error trace / logs

```text
2022-04-05 18:15:36,465 WARNING[PlexTraktSync]:Retry using search for specific Plex Episode
```

### Expected behavior

Should the scanner now be quicker once the initial scan is done

### Steps to reproduce the behavior

Start Scan

### Install method

zip download

### Version

0.18.25

### Python Version

3.10

### Operating System and Version

Windows 10 AWS

**Comment by glensc** [comment]
Show sync is naturaly slower because each show has N seasons and seasons have M episodes in it.

adding "docs needed" label if you want to send a PR to document it in readme

**Comment by launchm** [comment]
[plextraktsync.log](https://github.com/Taxel/PlexTraktSync/files/8424142/plextraktsync.log)
I am not sure if you can see anything for here which may lead you to figure out if there is an issue or not

**Comment by twolaw** [comment]
You have lots of matching problems in Plex. Those famous movies should have an external id :
```
2022-04-05 08:24:36,764 WARNING[PlexTraktSync]:<Movie:519283:Wonder-Woman-Bloodli>: Skipping guid local://519283 because provider local has no external Id
2022-04-05 08:24:36,779 WARNING[PlexTraktSync]:<Movie:519209:X-Men>: Skipping guid local://519209 because provider local has no external Id
2022-04-05 08:24:36,795 WARNING[PlexTraktSync]:<Movie:519208:X-Men-Days-of-Future>: Skipping guid local://519208 because provider local has no external Id
2022-04-05 08:24:36,795 WARNING[PlexTraktSync]:<Movie:519320:X-Men-the-Last-Stand>: Skipping guid local://519320 because provider local has no external Id
2022-04-05 08:24:36,826 WARNING[PlexTraktSync]:<Movie:519319:Zero-Dark-Thirty>: Skipping guid local://519319 because provider local has no external Id
2022-04-05 08:24:36,826 WARNING[PlexTraktSync]:<Movie:519288:Zola>: Skipping guid local://519288 because provider local has no external Id
2022-04-05 08:24:36,842 WARNING[PlexTraktSync]:<Movie:519141:Zombieland-Double-Ta>: Skipping guid local://519141 because provider local has no external Id
```
Are you sure Plex correctly identified those movies ?
What are your Plex agents ?

**Comment by dannymichel** [comment]
i mean can't it just skip the missing stuff for the next sync? this thing takes 15 minutes minimum every time

**Comment by twolaw** [comment]
Who are you ?
When it says 'skipping' you must understand the word 'skipping'.

**Comment by dannymichel** [comment]
> Who are you ? When it says 'skipping' you must understand the word 'skipping'.

im danny, i like long walks on the beach. you?

**Comment by dannymichel** [comment]
what i mean by 'skip' is if an initial scan is slow because the scan has to check for matches every time, can't those unmatched be logged and skipped for faster subsequent syncing

**Comment by twolaw** [comment]
It doesn't check for match every time, it skips if there is no external guid.
The slowness is not because of those missing match.

**Comment by dannymichel** [comment]
> It doesn't check for match every time, it skips if there is no external guid. The slowness is not because of those missing match.

are there any plans to look into speeding it up?

**Comment by twolaw** [comment]
Not that I know of
- https://github.com/Taxel/PlexTraktSync/discussions/469
