### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Taxel** [Taxel/PlexTraktSync#88]
As you might have seen, I have pushed the _work in progress_ docker branch. I am currently testing the built image in my home setup (with this image as well as Plex running in Kubernetes administered via Rancher) but I have made some changes to how the script works, files have been reorganized etc. so I wanted to discuss them here first before even submitting a pull request:

- I rebased the branch on my changes in #87, if we wait for the official python-plexapi package to get updated this will have to be redone
- I changed the file structure: With configuration, cache, logs, and source code in one directory the project felt unorganized, so I should have probably done this before even making the project open source.
- The docker image is based on @twolaw 's Dockerfile. The main differences are, that I am using a multistep build (unnecessarily I might add, this does not really make the resulting image much smaller, but it was fun to play around with) and that the script does not run once by default but on a cronjob, so the container can be configured and then left running forever. One can, however, pass the environment variable "RUN_ONCE" with a non-empty value and the script will only be run once, after which the container shuts down. Changing the cron schedule is also done via an environment var: CRON_SCHEDULE
- Running this in Docker also means that via volume mounts and multiple containers, one can use different configs for multiple users and/or Plex servers, solving #70 indirectly (only in Docker, of course. Not when running this with Python. Since I extracted all the filepaths to config.py this should be trivial to implement, though)

What might be the most controversial change, is that I am rerouting the log outputs to stdout if the terminal is non-interactive. I use it to detect if the script is running in a container since Docker containers should output to stdout/stderr and let Docker take care of the logging. Do you agree the script should no longer write to `lastRun.log` if it is running in a container and is the `sys.isatty(0)` check okay or should I add an argument like `python3 main.py --log-to-stdout` so this is easier to control?

Since the file structure changes alone constitute some manual work when upgrading from an older version of PlexTraktSync, I also propose we create a release 0.9.0 before merging the pull request for this once the feature is complete and then release 1.0.0 along with the docker image (I'd like to try Github Packages as the image registry and create a Github action that automatically builds, tags and pushes each new release in the future)

@glensc @twolaw what do you think about these changes? If you want to test them out locally it should suffice to `docker-compose up --build` after pulling the branch. Are there other things I should add to the image prior to release (for example atm the container always runs as root. I didn't deem it necessary to make it possible to change this since the container just mounts the config directory and is not accessible from the outside because it does not listen for incoming connections)

Greez
Taxel

**Comment by glensc** [comment]
You should create PR anyway, even if it does not get merged (or why be afraid of PR in the first place?), otherwise can't see or comment on the code. if I comment in the commit, then the comments are spread around and no overview of feedback.

**Comment by Taxel** [comment]
I mainly did not submit a PR earlier because this is not a completed feature and there are some things that should be discussed before even considering merging this (the points I mentioned above). Also, after watching the first couple of minutes of GitHub Universe, I realized this should not be an issue but a discussion, a feature I didn't know GitHub has. To try this out, I am converting this to a discussion right after writing this.
