### ISSUE TITLE
HTTPSConnectionPool

### ISSUE THREAD

**Issue by TCarneiro91** [Taxel/PlexTraktSync#90]
After i tried diferent branches, i am getting this error

![image](https://user-images.githubusercontent.com/17798233/101527811-65211580-3986-11eb-8d3d-c42b119a53e4.png)

**Comment by twolaw** [comment]
Do PlexTraktSync and Plex run on same server ? If not, does ping 192.168.1.65 respond ?

You can check your Plex available servers by browsing to this url :
`https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=<your-plex-token-here>`
then look for `192-168-1-65.f4915435xxxxx.plex.direct:32400` (same url as `.env` file content)

**Comment by TCarneiro91** [comment]
They are running on the same machine, I tried to disable Secure Connections but I get the same error

**Comment by twolaw** [comment]
Can you visit the url I told you and tell me if uri is matching ?
I know how to solve your problem but I'd like to understand everything.

**Comment by TCarneiro91** [comment]
Well, i can found the content you told me on the xml file. I don't know where the error is

![image](https://user-images.githubusercontent.com/17798233/101671088-f0181380-3a4b-11eb-9776-4aeb79c5c967.png)

**Comment by twolaw** [comment]
That's the address, what is the uri?

**Comment by TCarneiro91** [comment]
uri="https://192-168-1-65.f4915435d6ca4c86b46b4505b1340a3a.plex.direct:32400" local="1"/>

**Comment by twolaw** [comment]
In **.env** file change this line :
`PLEX_BASEURL=https://192-168-1-65.f4915435d6ca4c86b46b4505b1340a3a.plex.direct:32400`
into
`PLEX_BASEURL=http://192.168.1.65:32400`
then try script sync.
If it's still not working change line to :
`PLEX_BASEURL=http://localhost:32400`

**Comment by TCarneiro91** [comment]
I tried the 3 ways, none of them worked

![image](https://user-images.githubusercontent.com/17798233/101677880-155d4f80-3a55-11eb-8393-37590a36465c.png)

**Comment by glensc** [comment]
Seems like a firewall or networking issue, can you:
1. `ping 192.168.1.65`?
2. `tracert 192.168.1.65`?
3. `telnet 192.168.1.65 32400`?

**Comment by TCarneiro91** [comment]
Well, I fell dumb...
I recently installed docked which changed me some firewall settings. Disabled the firewall and it started to sync, but gave me another error.
![IMG_20201210_093027.jpg](https://user-images.githubusercontent.com/17798233/101753489-9a368080-3aca-11eb-9ae1-9978163cf969.jpg)

**Comment by glensc** [comment]
guids error is probably because you use a development branch and you ignored installation instructions described in the pull request.

switch to master branch and use the legacy agent:
- https://github.com/Taxel/PlexTraktSync/issues/56
