### ISSUE TITLE
If you pause a movie / serie, it gets synced twice to Trakt

### ISSUE THREAD

**Issue by zeroquinc** [Taxel/PlexTraktSync#905]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I watch alot of movies but sometimes I don't have the time to watch it in 1 sitting, so I pause the video and continue on a later time. This can be a hour later or sometimes even a day.

When I pause the video for longer then 30mins I feel like, it gets tracked twice to trakt.

I only use plextraktsync watch and not the manual sync

It are always around 4 minutes inbetween the 2 plays.
![pGC0urc](https://user-images.githubusercontent.com/39315068/166693964-8fdfb57b-6602-46f6-98e7-7ddc2dcc2a1d.png)

### Error trace / logs

```text
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 98.037572% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 98.503309% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 98.969045% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 98.969045% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 99.434782% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 99.558978% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_delete: Deleted on Plex: 1181:
ERROR    on_delete: Not found: 1181
INFO     on_delete: Deleted on Plex: 1182:
ERROR    <Clip:1182:X-Men:-First-Class>: Unable to parse a valid provider from guid
         <PlexGuid:iva://api.internetvideoarchive.com/2.0/DataService/VideoAssets(244133)>
ERROR    on_delete: Not found: 1182
INFO     on_delete: Deleted on Plex: 1706:
ERROR    on_delete: Not found: 1706
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 99.714224% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 99.869470% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_play: <Movie:1221:X-Men-Origins:-Wolve>: 99.947092% Watched: False, LastViewed: 2022-05-04 14:10:40
INFO     on_activity: <tmdb:2080:Movie:1221:X-Men-Origins:-Wolve>: Collected: True, Watched: [Plex: True, Trakt:
         False]
INFO     on_activity: Marking /library/metadata/1221 as watched in Trakt: <tmdb:2080:Movie:1221:X-Men-Origins:-Wolve>
INFO     on_delete: Deleted on Plex: 1321:
ERROR    on_delete: Not found: 1321
INFO     on_delete: Deleted on Plex: 153:
ERROR    on_delete: Not found: 153
INFO     on_delete: Deleted on Plex: 2075:
ERROR    on_delete: Not found: 2075
INFO     on_delete: Deleted on Plex: 1208:
```

I also continuesly get these errors?

on_delete: Not found: 153
INFO     on_delete: Deleted on Plex: 2075:
ERROR    on_delete: Not found: 2075
INFO     on_delete: Deleted on Plex: 1208:

### Expected behavior

I expect that it just syncs as 1 play when it reaches 90%, I don't pause it after the 90% completion mark.

### Steps to reproduce the behavior

1. Watch a movie
2. Pause it for a hour
3. Finish it and its synced twice

### Workarounds

In another issue [https://github.com/Taxel/PlexTraktSync/issues/820](url) there is a recommendation to put the 2 "watched_status" on false, I already tried this and makes no diference.

### Install method

pipx

### Version

0.19.2

### Python Version

3.10.2

### Operating System and Version

Windows 10 21H2

**Comment by zeroquinc** [comment]
> Without looking deeply into the problem, I'm guessing you're hitting catch threshold, which is 80%. You can try playing around with the watch threshold, make it 99 or even 100:
> 
> * [Add config to configure trakt auto watch threshold #605](https://github.com/Taxel/PlexTraktSync/pull/605)
> 
> it's not documented in readme because nobody stepped up and I'm annoyed documenting things. that's why in readme there's call for help:
> 
> > or to improve documentation [docs-needed](https://github.com/Taxel/PlexTraktSync/issues?q=label%3A%22docs+needed%22+sort%3Aupdated-desc), thank you.

Thank you, ill try that and update the thread. Do you maybe have any clue on where those errors come from in my log? It keeps going like this.

**Comment by glensc** [comment]
What errors? please be specific (show them along the question). also you should create one issue per one problem, unless you are absolutely sure they are from the same cause.

**Comment by zeroquinc** [comment]
> > I expect that it just syncs as 1 play when it reaches 90%, I don't pause it after the 90% completion mark.
> 
> where does the 90% come from? you're omitting some info!

90% comes from "scrobble_threshold", i already had this set to 90.

With the errors I mean this that continuesly pops up.

ERROR    on_delete: Not found: 1182
INFO     on_delete: Deleted on Plex: 1706:
ERROR    on_delete: Not found: 1706


I think these errors are related to my issue.

**Comment by glensc** [comment]
> INFO on_delete: Deleted on Plex: 1706:
> ERROR on_delete: Not found: 1706

nothing can be done here. plextraktsync gets event "item deleted", and when plextraktsync tries to fetch info about the item, it's already deleted by plex. this was already discussed in some other issue/discussion.

and this should have been reported as a separate issue to have better visibility if searching for that problem only. this error is no way related to "syncing twice" problem.

searching "on_delete: Not found" I found:
- https://github.com/Taxel/PlexTraktSync/discussions/872

**Comment by glensc** [comment]
Please follow the project conduct and explain why closed the issue

<img width="867" alt="image" src="https://user-images.githubusercontent.com/199095/167269667-7c4bb42a-d7cd-4385-97d6-4fd30318d8af.png">
