### ISSUE TITLE
Pipx can't find versions to install

### ISSUE THREAD

**Issue by Ricas13** [Taxel/PlexTraktSync#916]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Using pipx as recommended method, keeps failing installation.

[A similar problem was raised here but they were using python2.7. I made sure I'm using python3 
](https://github.com/Taxel/PlexTraktSync/issues/782)

Edit: Updated to python 3.10 and added the link to the older issue.

### Error trace / logs

```text
Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement plextraktsync (from versions: none)
    ERROR: No matching distribution found for plextraktsync
```

### Expected behavior

To install

### Steps to reproduce the behavior

1 - Install python3
2 - Set python3.9 as default python
3 - Install pipx - version 1.0.0
4 - Type pipx install PlexTraktSync
5 - The error appears

### Inspect of problematic items

```text
Not possible to do this
```

### Workarounds

Nothing I could find.

### Install method

pipx (Recommended)

### Version

0.19.2

### Python Version

3.9

### Operating System and Version

Ubuntu 18.04

**Comment by glensc** [comment]
This project requires python >= 3.7, so origin al bugreport with 3.6 indeed will not find the package.

But you edited your bugreport, changed to 3.9, and I can't reproduce with 3.9 your problem.

```
➜ docker run --rm -it python:3.9-alpine sh
/ # which pip
/usr/local/bin/pip
/ # pip install pipx
/ # which pipx
/usr/local/bin/pipx
/ # pipx install PlexTraktSync
⢿ creating shared libraries
⣯ upgrading shared libraries
⣾ installing plextraktsync
⡿ installing plextraktsync
  installed package plextraktsync 0.19.2, installed using Python 3.9.12
  These apps are now globally available
    - plextraktsync
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible
    until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your
    shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
/ #
```

also, you found some existing issue, edit the issue body and fill it's link.

**Comment by glensc** [comment]
what I'm guessing is your pipx is still installed with python 3.6, so remove the wrapper or re-install pipx with python 3.9. you can verify this with `which pipx` and look it's first line:

```
➜ head -n1 `which pipx`
#!/usr/local/Cellar/pipx/1.0.0/libexec/bin/python3.10
```

**Comment by Ricas13** [comment]
Brilliant!

Removing pip and reinstalling it did the trick.

I had to use this: https://stackoverflow.com/questions/65644782/how-to-install-pip-for-python-3-9-on-ubuntu-20-04 to be able to install pip on python3.9 but all works now.

Cheers
