### ISSUE TITLE
Feature request: Select Movies or Shows for clear-collections

### ISSUE THREAD

**Issue by b0ssem** [Taxel/PlexTraktSync#930]
Would be great if possible to have the option to select what type of media to clear from collections. 

Or even better if it would be possible on a library level. Just like when running sync command.

Example: 
I want to remove the library "Kids Movies" from my collection. 
`Plextraktsync clear-collections --library "Kids Movies"`
Or all TV-shows.
`Plextraktsync clear-collections TV`
Or all movies
`Plextraktsync clear-collections Movie`

**Comment by glensc** [comment]
Seems rather trivial to implement

**Comment by glensc** [comment]
Correction, adding `--shows`, `--movies` is trivial, just add condition for them:
- https://github.com/Taxel/PlexTraktSync/blob/2270cabf01f2cf557bc08750d2688f7be886134d/plextraktsync/commands/clear_collections.py#L15-L23


adding `--library` requires different approach, as it means walking plex libraries:
- https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1382865737

so this will be implemented differently:
- https://github.com/Taxel/PlexTraktSync/pull/1363

**Comment by glensc** [comment]
First part implemented:
- https://github.com/Taxel/PlexTraktSync/pull/1369

**Comment by glensc** [comment]
The reporter is gone (inactive in github), unlikely they will be testing this, so merging as is:
- https://github.com/Taxel/PlexTraktSync/pull/1369
