### ISSUE TITLE
Missing package in setup.cfg (plextraktsync.util)

### ISSUE THREAD

**Issue by mvanbaak** [Taxel/PlexTraktSync#933]
https://github.com/Taxel/PlexTraktSync/blob/89c0ef43f0de777a29aa232c47135e37ed4da7ab/setup.cfg#L30

`plextraktsync.util` is missing here, resulting in errors with at least the `inspect` command

version: 0.20.0
Install method: pipx install plextraktsync
System: Darwin MvB14m1pro01.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64 arm
pipx version: 1.1.0 (installed using homebrew)

**Comment by mvanbaak** [comment]
I quickly created this issue to not forget about it by using `Reference in a new issue` in the source browser ui of gihtub. Sorry about that.

**Comment by glensc** [comment]
version and installation method missing, please fill them to issue body
