### ISSUE TITLE
Can't sync liked playlists : unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by steffenbb** [Taxel/PlexTraktSync#941]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

Hello, I'm trying to set up the python script, I've succesfully got it working with another trakt account (different computer) with my liked lists and everything. Now I've freshly installed python and the script on a different computer, but whenever I try to sync (with having liked playlists on trakt) the following happens. If I unlike them on trakt and run the script again, it succeeds. 

### Error trace / logs

```text
console log: 
INFO     PlexTraktSync [0.20.x]
Sync Movie sections: [<PlexLibrarySection:movie:Concerts>, <PlexLibrarySection:movie:Documentarys>, <PlexLibrarySection:movie:Movies>]
Traceback (most recent call last):
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\PlexTraktSync\Lulu\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\PlexTraktSync\Lulu\plextraktsync\cli.py", line 46, in cli
    sync()
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\PlexTraktSync\Lulu\plextraktsync\cli.py", line 28, in wrap
    cmd(*args, **kwargs)
  File "C:\PlexTraktSync\Lulu\plextraktsync\commands\sync.py", line 60, in sync
    runner.sync(walker=w, dry_run=config.dry_run)
  File "C:\PlexTraktSync\Lulu\plextraktsync\sync.py", line 64, in sync
    listutil.addList(lst["username"], lst["listname"])
  File "C:\PlexTraktSync\Lulu\plextraktsync\trakt_list_util.py", line 88, in addList
    self.lists.append(TraktList(username, listname))
  File "C:\PlexTraktSync\Lulu\plextraktsync\trakt_list_util.py", line 47, in __init__
    for elem in LazyUserList._get(listname, username)._items
  File "C:\Users\lulu\AppData\Local\Programs\Python\Python37\lib\site-packages\trakt\core.py", line 554, in inner
    return generator.send(json_data)
  File "C:\PlexTraktSync\Lulu\plextraktsync\trakt_list_util.py", line 35, in _get
    ulist = LazyUserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'type'

plextraktsync.log:
2022-06-16 15:12:58,091 INFO[PlexTraktSync]:PlexTraktSync [0.20.x]
```

### Expected behavior

Expect the script to go through even if there's liked scripts on trakt

### Steps to reproduce the behavior

Like a list on trakt
Run sync command

### Workarounds

Not having liked lists on trakt

### Install method

zip download

### Version

0.20.1

### Python Version

3.10.5

### Operating System and Version

Windows 11

**Comment by steffenbb** [comment]
Just updated python hence the edit, still same issue

**Comment by twolaw** [comment]
The fix for this issue :
- https://github.com/moogar0880/PyTrakt/pull/206

**Comment by twolaw** [comment]
We have to wait until [PyTrakt](https://github.com/moogar0880/PyTrakt) maintainer get back and update its trakt module.
You can go there and upvote the Maintenance [issue](https://github.com/moogar0880/PyTrakt/issues/).

**Comment by ashepp** [comment]
Apologies for not checking for dupe / following template. Will track this thread. 
I'm not clear on if there's a short term fix or whether we have to wait for the PyTraky fix?
Whenever I try and run the container I'm getting the following error in the console (I reinstalled and still get the same). 

Error response from daemon: Container 86b194fdf69e42e5b0fc69e1a416e037e4748d133b6591148f220e441467d416 is not running.



Log shows the same as reported previously regarding missing type. 

Any suggestions?

**Comment by twolaw** [comment]
For now you can disable playlists sync in config file.

**Comment by ashepp** [comment]
I set the parameter to  'playlist_sync_to_user : false'  from
 'playlist_sync_to_user : all'.

The container starts and then immediately stops with the log details below.
Is there another parameter I'm missing?

Thanks

O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'
O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'
O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'
O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'
O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'
O [0m PlexTraktSync [ [1;36m0.20 [0m. [1;36m4 [0m]
ie sections: [<PlexLibrarySection:movie:Movies>,
<PlexLibrarySection:movie:Movies - 4K>, <PlexLibrarySection:movie:Movies -
4K DV>, <PlexLibrarySection:movie:Movies - Anime>,
<PlexLibrarySection:movie:Movies - Int>, <PlexLibrarySection:movie:Movies
3D>, <PlexLibrarySection:movie:Sports Movies>]
w sections: [<PlexLibrarySection:show:Courses>,
<PlexLibrarySection:show:Fitness>, <PlexLibrarySection:show:Sports>,
<PlexLibrarySection:show:TV Shows>, <PlexLibrarySection:show:TV Shows -
4K>, <PlexLibrarySection:show:TV Shows - 4K DV>,
<PlexLibrarySection:show:TV Shows - Anime>, <PlexLibrarySection:show:TV
Shows - Anime dub>, <PlexLibrarySection:show:TV Shows - Int>]
k (most recent call last):
sr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
run_code(code, main_globals, None,
sr/local/lib/python3.10/runpy.py", line 86, in _run_code
e, run_globals)
pp/plextraktsync/__main__.py", line 18, in <module>

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
er().invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in
new_func
(get_current_context(), *args, **kwargs)
pp/plextraktsync/cli.py", line 46, in cli

sr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
elf.main(*args, **kwargs)
sr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
f.invoke(ctx)
sr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
tx.invoke(self.callback, **ctx.params)
sr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
_callback(*args, **kwargs)
pp/plextraktsync/cli.py", line 28, in wrap
s, **kwargs)
pp/plextraktsync/commands/sync.py", line 60, in sync
ync(walker=w, dry_run=config.dry_run)
pp/plextraktsync/sync.py", line 64, in sync
.addList(lst["username"], lst["listname"])
pp/plextraktsync/trakt_list_util.py", line 88, in addList
ts.append(TraktList(username, listname))
pp/plextraktsync/trakt_list_util.py", line 47, in __init__
in LazyUserList._get(listname, username)._items
sr/local/lib/python3.10/site-packages/trakt/core.py", line 554, in inner
enerator.send(json_data)
pp/plextraktsync/trakt_list_util.py", line 35, in _get
LazyUserList(creator=creator, **data)
r: UserList.__new__() got an unexpected keyword argument 'type'

**Comment by twolaw** [comment]
This is off-topic, you should ask the developer of your Unraid CA container.

**Comment by marksie1988** [comment]
I updated pytrakt locally as per the PR, I assume additional changes are also needed to plextraktsync for it to work?

**Comment by YDeltagon** [comment]
any news ?

**Comment by abb0r** [comment]
> For now you can disable liked_lists and watchlist sync in config file.

I disabled it, but still get the error.

**Comment by glensc** [comment]
Anyone can try https://github.com/Taxel/PlexTraktSync/pull/1100?

**Comment by racincason** [comment]
Latest Error 

`Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\__main__.py", line 18, in <module>
    cli()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\cli.py", line 53, in cli
    sync()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\cli.py", line 24, in wrap
    module = importlib.import_module(f".commands.{name}", package=__package__)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\commands\sync.py", line 5, in <module>
    from plextraktsync.commands.login import ensure_login
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\commands\login.py", line 5, in <module>
    from plextraktsync.commands.trakt_login import (has_trakt_token,
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\commands\trakt_login.py", line 10, in <module>
    from plextraktsync.trakt_api import TraktApi
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\trakt_api.py", line 21, in <module>
    from plextraktsync.decorators.retry import retry
  File "C:\Users\USER\Downloads\PlexTraktSync-0.23.1\PlexTraktSync-0.23.1\plextraktsync\decorators\retry.py", line 9, in <module>
    from pytrakt.trakt.errors import BadResponseException
ModuleNotFoundError: No module named 'pytrakt'`
