### ISSUE TITLE
Feature request: Multiple Users

### ISSUE THREAD

**Issue by callumgourlay** [Taxel/PlexTraktSync#967]
### Feature description

Allow for adding multiple trakt users and syncing multiple plex users to ultiple trakt accounts

### Use case

Multiple people using one plex server wanting to use trakt

_Is there a specific goal that this would help you accomplish, or can you
provide any other context about how you would like to use this feature?_

### Workarounds

_Is there an existing workaround to accomplish this?_

### Plan to implement

_Are you interested in submitting a PR to implement this?_

**Comment by Anon0511** [comment]
I've created you this docker-compose.yml over here: https://github.com/Taxel/PlexTraktSync/discussions/997

And I let all Plex accounts except my own one sync to a single secondary trakt.tv user. It would be hilarious to create 20 Trakt users lol. IMO this should work. At least the stats on the Trakt profile look fine.

**Comment by twolaw** [comment]
See:
- https://github.com/Taxel/PlexTraktSync/discussions/997

Information is now in Readme file so I close this issue.
