### ISSUE TITLE
Watch Delete - Not Found

### ISSUE THREAD

**Issue by MrBamse** [Taxel/PlexTraktSync#972]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I'm unable to get "watch" to remove deleted file from Trakt collection.
The log says:
```
2022-07-05 19:01:09,249 INFO[PlexTraktSync.WatchStateUpdater]:on_delete: Deleted on Plex: 248716: Mulholland Drive
2022-07-05 19:01:09,260 ERROR[PlexTraktSync.WatchStateUpdater]:on_delete: Not found: 248716
```

Any ideas what might be wrong? 
I've tried with numerous different files under a variation of circumstances with no success, and I didn't find any issue open/closed on the anything that seems to match :/

Greatly appreciate any help on the issue :)

### Error trace / logs

```text
2022-07-05 19:01:09,249 INFO[PlexTraktSync.WatchStateUpdater]:on_delete: Deleted on Plex: 248716: Mulholland Drive
2022-07-05 19:01:09,260 ERROR[PlexTraktSync.WatchStateUpdater]:on_delete: Not found: 248716
```

### Expected behavior

For item to be removed from Trakt collection.

### Steps to reproduce the behavior

1. Install using pipx install PlexTraktSync
2. Configure and do initial sync.
3. Set log to debug and tail / or investigate after
4. Delete file from Plex Library

### Install method

pipx (Recommended)

### Version

0.20.4

### Python Version

3.9.2

### Operating System and Version

Debian 11 (Bullseye)

**Comment by twolaw** [comment]
> I didn't find any issue open/closed on the anything that seems to match :/

Duplicate #374 and #872

**Comment by glensc** [comment]
More specifically this comment:
- https://github.com/Taxel/PlexTraktSync/issues/374#issuecomment-1022017960
