### ISSUE TITLE
Feature request: Change processing rate calculation for shows sections

### ISSUE THREAD

**Issue by simonc56** [Taxel/PlexTraktSync#976]
### Feature description

Show sections : IMHO items/s should be calculated with episodes/s not with shows/s.

### Use case

When processing **movies** sections, the rate of processed items per second is simple: 1 item = 1 movie.
But for **shows** sections, the rate of processed items per second is (according to me) not correct because it is calculated based on 1 item = 1 show. Shows don't have same quantity of episodes, some have ~10 episodes and some have hundreds so **the actual calculation is not a good measure of script speed**. It should be 1 item = 1 episode.

![image](https://user-images.githubusercontent.com/10365746/178788212-239d1418-9d14-4837-9869-f4ab233793ab.png)

On my personal library, I have about 163 items/s for movies and 1 item/s for shows.

I know that movies sections and shows sections are not processed the same way, but I expect the items/s rate to be more or less consistent between sections to be a usefull value.

### Workarounds

Not that I know

### Plan to implement

I don't know how to implement this.
I'm not skilled at `yield` python things and will need help if i want to try to implement myself.

**Comment by glensc** [comment]
Changing the increment to emit episodes, is doable, but then the percentage will be unknown.

**Comment by glensc** [comment]
other option is to use multiple or sub-progressbars:
- https://github.com/Textualize/rich#rich-library

**Comment by Jopo-JP** [comment]
Maybe two progress bars?
One for all the show and one for that specifiy show and their epiosdes?

Example:
Processing Shows 80%   ━━━━━━━━━━━━━━━━━━━━━━━━━   80/100[ 0:03:00 < 0:00:00 , 1 it/s ]
Processing Big Bang Theory 100%  ━━━━━━━━━━━━━━━━━━━━   20/100 [ 0:00:05 < 0:00:00 , 20 it/s ]

**Comment by glensc** [comment]
@Jopo-JP that's precisely what I said:
- https://github.com/Taxel/PlexTraktSync/issues/976#issuecomment-1184811444

**Comment by Jopo-JP** [comment]
> @Jopo-JP that's precisely what I said:
> - https://github.com/Taxel/PlexTraktSync/issues/976#issuecomment-1184811444

Well this is at least the best way to handle it.

Otherwise pre scanning all episodes or counting it before scanning could take a while to start the initial scan.

I don't know if there is a API which will print all episode not just the shows.

I just started scanning today again and sometimes I think it's frozen in place but it's actually just scanning my large shows with many episodes. Pokemon at top with 1000+.

Would be awesome to have a greater feedback for tv show.

**Comment by glensc** [comment]
> I don't know if there is a API which will print all episode not just the shows.

If you (or anyone else) want to help, you could try finding an answer to that. need episode count in a library, etc

**Comment by JonnyWong16** [comment]
`LibrarySection.totalViewSize(libtype='episode')` will return the total number of episodes.

**Comment by glensc** [comment]
Implemented: https://github.com/Taxel/PlexTraktSync/pull/1578
