### ISSUE TITLE
Applying PyTrakt fixes

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#994]
So, we have a problem that the only maintainer of PyTrakt has decided to Ghost everything from GitHub:
- https://github.com/moogar0880/PyTrakt/issues/199

How do we solve this?

One idea was to just use git branch, without pip publishing:
- https://github.com/Taxel/PlexTraktSync/pull/984

will this work? or do we need to publish to pip using some new name?

The alternative is to ditch the package, and use something new? altho I submitted quite a bunch of fixes and refactoring to PyTrakt repository in January 2022.

**Comment by glensc** [comment]
@twolaw you have no opinion?

**Comment by twolaw** [comment]
> One idea was to just use git branch, without pip publishing

I think it's a good idea.
> will this work?

A test could answer the question.


> The alternative is to ditch the package, and use something new?

I talked about it 2 years ago (https://github.com/Taxel/PlexTraktSync/issues/19#issuecomment-608427315) but it's a difficult choice and we're not sure it solves the problem. IMHO it's not worth it.

**Comment by glensc** [comment]
The other module is not active either.

last release 4.4.0 was on Mar 19 2021, 174 days ago:
- https://pypi.org/project/trakt.py/#history

project has 3 open PRs, around the same time:
- https://github.com/fuzeman/trakt.py/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

project owner account is even inactive longer than pytrakt owner, last activity Apr 10 2021:
- https://github.com/fuzeman
